### ISSUE TITLE
Add indent style for normal text

### ISSUE THREAD

**Issue by immae** [xwiki-labs/cryptpad#101]
Currently the indentation is only possible for item lists. Maybe it would be easy to add indent for normal text?

**Comment by immae** [comment]
I think the missing plugin is http://ckeditor.com/addon/indentblock

**Comment by ansuz** [comment]
Since it's a default plugin, and it doesn't seem to interfere with anything, I've gone ahead and enabled `indentblock` in our staging branch.

It will be merged to master for our next release, to be deployed on April 11th.

**Comment by immae** [comment]
Thanks!
