### ISSUE TITLE
Do not use the Ctrl+L keyboard shortcut, as it is used by the browser to focus on the address bar

### ISSUE THREAD

**Issue by Nyco** [xwiki-labs/cryptpad#107]
My pain is, each time I want to copy-paste the URL of a pad (it happens a lot), I have this "Link" dialog box/popover I need to dismiss by hand, then move the pointer manually to the address bar...

It hurts, but I can live with it.

Is it hurting anyone else?

**Comment by ansuz** [comment]
I've heard of this from one other person. I didn't actually know about ctrl-L before that, but now I use it too.

I'm not sure what keys I'd bind the _create-link_ dialog to, though. I prefer not to have to use CKEditor's buttons if I don't have to.

**Comment by ansuz** [comment]
As it turns out, this was an easy fix. We've changed our production server to use `ctrl-shift-L` for the link dialog, with ctrl-L once again having its default behaviour.

You may have to hard reload for it to take effect.

**Comment by ansuz** [comment]
This will be the new default in our next release, on April 25th.
