### ISSUE TITLE
authentication with express and passport

### ISSUE THREAD

**Issue by suziesirena** [xwiki-labs/cryptpad#116]
Hi @ansuz ,

I'm very impressed by the cryptpad project. Since a few days, I study the code  and I'm wondering how to integrate your editor in an app using [express](http://expressjs.com/fr/) and [passport](http://passportjs.org/) to handle authentication.

How can I use my authentication process with cryptpad authentication ?

**Comment by ansuz** [comment]
CryptPad's login strategy is to use your username and password to derive a secret which is used to access and encrypt/decrypt the realtime object which contains all of the information you see in your drive.

This derivation is done locally using scrypt, so the server never learns either username or password. As long as you don't try to reuse that information in your authenticator, any one of Passport's strategies should work.

That's if you want to just take CryptPad _as is_ and put it behind another layer of authentication. If you wish to embed one of the editors into another app, that will probably be more work. We have a [matrix channel](https://riot.im/app/#/room/!cryptpad:matrix.org) that you can visit if chat is an easier venue for discussion.

**Comment by ansuz** [comment]
I'm going to close this issue for the same reason as [this other one](https://github.com/xwiki-labs/cryptpad/issues/174). We have no plans to implement different authentication methods for CryptPad.fr, and in the absence of external funding for this feature it just isn't going to happen.
