### ISSUE TITLE
Markdown side-by-side resource usage

### ISSUE THREAD

**Issue by lgierth** [xwiki-labs/cryptpad#117]
I got a ~600 lines markdown document which is my private notes file. In side-by-side mode, typing is very laggy and spikes the CPU. I imagine some kind of timeout would help, similar to how auto-complete fields do it.

(I love the side-by-side view! <3)

**Comment by ansuz** [comment]
I think this should be fixed as of today. I noticed the same thing and threw it in a timeout.

the relevant commit is [here](https://github.com/xwiki-labs/cryptpad/commit/dc80b6b11f102611cb48d6d792ee551f24bba165).

I deployed it to the server in a bit of a hotfix. Reloading might fix it for you.

**Comment by lgierth** [comment]
Still eats a bit CPU, but yes that's a lot better, thanks :)

Btw, I noticed the same issue when the side-pane is hidden.

**Comment by ansuz** [comment]
panel hidden but still in markdown mode? I didn't do anything about that case, but i can do so now.

**Comment by lgierth** [comment]
Yeah it just seems like it keeps rendering even if the preview pane is hidden. Lag there improved consistently with the fix you deployed.

**Comment by ansuz** [comment]
[fixed](https://github.com/xwiki-labs/cryptpad/commit/3803f6a20f789603c2707c48094f815ac0dc0eee)

**Comment by ansuz** [comment]
(in staging)

**Comment by ansuz** [comment]
This fix has been merged to master and deployed.
