### ISSUE TITLE
Remember preview toggle state

### ISSUE THREAD

**Issue by lgierth** [xwiki-labs/cryptpad#118]
Now that we have this beautiful side-by-side preview, it'd be great to reliably toggle its visibility, ideally on a per-document basis. Once I reload a document, the preview pane is visible by default, no matter if I've previously set it to hidden.

**Comment by ansuz** [comment]
and always show it to start?

**Comment by lgierth** [comment]
Yeah show it by default, but remember if I chose to hide it

**Comment by ansuz** [comment]
Implemented in [this commit](https://github.com/xwiki-labs/cryptpad/commit/b32c3292690067d2ae81ff58ef0a0dd1e6769d80). To be deployed for our next release, on June 6th, 2017.
