### ISSUE TITLE
command line tool to get the content of a document

### ISSUE THREAD

**Issue by monperrus** [xwiki-labs/cryptpad#12]
Is there a command line tool to get the content of a document (outside a browser)?

**Comment by ansuz** [comment]
There is not, but I've also thought about how useful that would be. If nobody gets to it first I'll probably write one soon.

**Comment by monperrus** [comment]
> If nobody gets to it first I'll probably write one soon. 
excellent!

**Comment by pojebunny** [comment]
I can suggest adding an option to Pad (CKeditor) that would "Commit" changes.
You can set a local (or remote) directory where the file would be decrypted and saved.

That kind of breaks the basic idea behind CryptPad, but if disabled by default could come in very handy for many new users.

**Comment by gustavohmsilva** [comment]
Allow me to jump in... Wouldn't Lynx meet this need perfectly?

**Comment by ansuz** [comment]
Unfortunately not, as all the document content is accessed via a websocket.

Chainpad works equally well in a nodejs environment, it would just be a matter of porting our on-wire protocol.

**Comment by wizzard0** [comment]
Better yet, a node module similar to media-tag in 1.14, which can resolve an URL into the snapshot of the document object :)

**Comment by ansuz** [comment]
There's a tool for downloading the content of a pad available [here](https://github.com/xwiki-labs/cryptpad-tools#downloadjs)

**Comment by monperrus** [comment]
Thanks @ansuz FYI, I'm unable to backup my pads with cryptpad-tools

I hit a crash, see https://github.com/xwiki-labs/cryptpad-tools/issues/3

Any idea on how to fix this?
