### ISSUE TITLE
Mail on pad changes

### ISSUE THREAD

**Issue by sachaz** [xwiki-labs/cryptpad#120]
To enhance the workflow : it could be interesting to receive an email when the followed cryptpad is modified on a selected range of time.

**Comment by kpcyrd** [comment]
@GammaNu The server already knows when a pad is modified. It can send out notifications _that_ the pad changed, but it can't send _what_ has been changed.

**Comment by cjdelisle** [comment]
This seems like potentially a good idea but it implies quite a bit of work. We need to communicate to the server that a *real* change has been made to the document (more than just adding/removing users in the document's editor list). We would also need to of course include an SMTP speaker in the server infrastructure.

Could you tell me what problem you are currently using CryptPad to solve and how this feature plays a role in this ?  I'm reachable also via the CryptPad community chat  https://riot.im/app/#/room/#cryptpad:matrix.org

**Comment by ansuz** [comment]
Closing this issue since it's been nearly three years and we still have no plans to integrate email into our infrastructure.

**Comment by 1000i100** [comment]
My usage is :
Use the pad as a collaborative document for a remote team.
If i use 10 or 30 pad for this, have email notification help me to know were i shoold get a look to what's new.

I've seen this feature as a plugin for etherpad and i love it : https://github.com/JohnMcLear/ep_email_notifications (it in use there : https://pad.tetaneutral.net/ )

**Comment by MarionMoseby** [comment]
This is essential IMHO. Email is already the most efficient form of collaboration, no matter what slack says
