### ISSUE TITLE
serving robots.txt

### ISSUE THREAD

**Issue by persianphilosopher** [xwiki-labs/cryptpad#132]
First of all, what an incredible repo. It's absolutely amazing.

Second: this is either a question or a suggestion. Unless I am mistaken, placing a robots.txt file in the "customize" folder does not seem to work. I thought it would because of this [line in server.js](https://github.com/xwiki-labs/cryptpad/blob/master/server.js#L88). If I am not mistaken, would you consider enabling this directly or via any of the npm robots modules? 

Thank you in advance.

**Comment by ansuz** [comment]
You can place it in `./www/robots.txt` and it will be served without any further changes. We haven't made any plans to serve robots.txt, so it's unlikely that pulling will cause collisions.

**Comment by persianphilosopher** [comment]
Thanks so much. I was not sure whether placing something outside of the customize folder would get in the way of any future pulls.
