### ISSUE TITLE
garbage collection in storage

### ISSUE THREAD

**Issue by ansuz** [xwiki-labs/cryptpad#14]
[Cryptpad.fr](https://cryptpad.fr/ "Unity is Strength - Collaboration is Key") states:

> **NOTE** Pads and spreadsheets will be removed after 30 days of inactivity

In actuality, once messages are stored in a channel, they remain until someone manually removes that part of the database. It's only the link to the pad which exists in a browser's localStorage which is cleaned up after 30 days.

It might be nice to add a 'deleteChannel' method to the storage API, such that after some amount of time the channel would get removed. Of course, this would have to be configurable.

_WDYT?_

**Comment by kpcyrd** [comment]
A definition of "inactivity" would be nice as well. 30 days after last modification or 30 days after last access? The later would require logging last access. I know some people who document their work in pads and expect them to be there forever, deletion would cause data loss.

**Comment by ansuz** [comment]
I started thinking about it after playing with my `amnesiadb`, which is just a channel's datastores kept in memory. If you're using it for development, then it doesn't matter, as you're probably going to restart somewhat regularly. Restarts destroy all pads, hence amnesia.

I can imagine a forgetful pad being useful for some people's interests, but amnesia's model is a memory leak if you intend to leave the server running.

I could embed the logic for cleaning up into the module itself, and make it a more viable option for people with an interest in this use case. Of course then it would definitely be a good idea to let users know.

In case of restarts during sessions, I'd like to develop a mechanism for restoring a pad's history from a client's localStorage, but if no one cares about this use case then I won't think too much about it.

On the issue of data loss, I should probably put up a notice that my instances of cryptpad shouldn't be considered reliable :stuck_out_tongue:

**Comment by clacke** [comment]
I came here to say that data should be kept in localStorage, so that any user can reseed the pad if it gets collected.

Turns out from this discussion that I misunderstood what that "removed after 30 days" message means, but as this was still mentioned here, I'll chime in and say that recovering from localStorage would be a great idea. :-)

The whole pad getting destroyed because the server was restarted is a pretty scary proposition.

**Comment by ansuz** [comment]
Hi clacke,

We're investigating the possibility of making Cryptpad peer to peer, with all patches distributed amongst clients, this should make it possible for every client to keep a complete copy of the pad, should they choose to do so.

Restarting the server definitely does not destroy information, I only meant to get an understanding of whether users would be interested in having this as an option in the API (for self-hosted pads, not necessarily [Cryptpad.fr](https://cryptpad.fr/).

Thanks for the feedback!

**Comment by clacke** [comment]
Ah, sorry, I misread your message. Amnesiadb was just something you were playing with for development. Gotcha. :-)

Fully P2P pad storage would be awesome, the server reduced to just code delivery, client brokerage and maybe optionally a backup store.
