### ISSUE TITLE
Feature Request: comments at the right of the screen

### ISSUE THREAD

**Issue by MaiaDereva** [xwiki-labs/cryptpad#143]
What a wonderful tool, thank you guys!
I wonder if it would be difficult to add the possibility of adding comments (bubbles at the right of the text) when you select a word?

**Comment by ansuz** [comment]
I'm told Microsoft Word has this feature. Is that the kind of workflow you're expecting?

If so, it's possible, but I can't say at the moment when we might get around to adding this.

**Comment by tessgadwa** [comment]
I agree, the ability to add comments while keeping the main document text read-only would be an extremely useful feature!

**Comment by funkycram** [comment]
+1, like Framapad : https://framapad.org/
![image](https://user-images.githubusercontent.com/23310825/34227285-ecefd78c-e5cc-11e7-96ab-2aa0d6eb5efa.png)

**Comment by MaiaDereva** [comment]
Yes, Google Doc Comments are also very practical because there are outside the text and you can see all the comments at a glance.
![comments](https://user-images.githubusercontent.com/17183356/40913289-6b3350d4-67f4-11e8-95db-6a52bcd8430e.png)

**Comment by JashanChittesh** [comment]
A decent comments workflow, like Google Docs and Microsoft Word has it, makes collaborating on texts significantly easier. In fact, without it, I find collaboratively working on a document quite cumbersome. So up until now, I always went back to Google Docs, even though I'd really prefer using something else.

**Comment by virtualcharlotte** [comment]
Would also love this feature - my organization currently uses cryptpad as we don't want big tech companies to casually have access to everything we do - would be really nice to get comments into the workflow as then we could finally cut the umbilical cord with google docs.

**Comment by unam12** [comment]
Still missing. https://cryptpad.piratenpartei.de/ has a word-document-Beta which includes this feature.
couldn't you easily adapt it?!
Thanks!

**Comment by ansuz** [comment]
A first version of this was implemented as a part of our [3.17.0](https://github.com/xwiki-labs/cryptpad/releases/3.17.0) release.
