### ISSUE TITLE
Problem with some pages

### ISSUE THREAD

**Issue by phineas0fog** [xwiki-labs/cryptpad#146]
Hello :)
In first, thanks for your work :)
I have install my own cryptpad instance, but here is some pages who doesn't work... In fact, the pages "drive", "whitebord", and "file" are working, there is a display etc. But with the text editor and code editor pages, nothing is displayed execpt the favicon... I follow the installation guide on this github page, but I not modified the config file because is just an instance for me to edit my courses...
I use antergos and all the needed packages are up to date.
Thanks a lot for your help and have a nice day :)
----
Sorry for my poor english im french...

**Comment by ansuz** [comment]
Salut,

sorry about that. It looks like maybe one of our clientside dependencies got dropped from `bower.json` when we were merging branches. I've pushed the fix to the master branch.

If you pull from the master branch, and run `bower install`, it should fetch the missing diff-dom package which is used for all the apps that stopped working.

Thanks for noticing.

**Comment by phineas0fog** [comment]
So, now the drive (when I am loged in) doesn't work.
Anonymously, text and code doens't work, but there is the loading page.
Poll and whiteboard are working.
If you want, i can give you the url of my instance for test.
