### ISSUE TITLE
Problem when I try to open other pages than the main page.

### ISSUE THREAD

**Issue by frju365** [xwiki-labs/cryptpad#147]
Hello,
I've a problem... I tested the app but it doesn't work. 
1° error : When I tried to open /code, I saw only a blank page. I opened my firefox console to see what was wrong and I saw a 404 on diffDOM.js. So, I installed DiffDOM by "bower install diff-dom#1.1". The error was fixed.
2° error : After fixing the previous error, for the /code page, I had another error : 
```
TypeError: DiffDOM is not a constructor[Learn More]  diffMarked.js:117:14
	<anonymous> https://mydomain.com/common/diffMarked.js:117:14
	execCb https://mydomain.com/bower_components/requirejs/require.js:1658:24
	check https://mydomain.com/bower_components/requirejs/require.js:874:43
	enable/</< https://mydomain.com/bower_components/requirejs/require.js:1121:29
	bind/< https://mydomain.com/bower_components/requirejs/require.js:132:20
	emit/< https://mydomain.com/bower_components/requirejs/require.js:1164:21
	each https://mydomain.com/bower_components/requirejs/require.js:57:31
	emit https://mydomain.com/bower_components/requirejs/require.js:1163:17
	check https://mydomain.com/bower_components/requirejs/require.js:925:25
	enable https://mydomain.com/bower_components/requirejs/require.js:1151:17
	init https://mydomain.com/bower_components/requirejs/require.js:782:21
	callGetModule https://mydomain.com/bower_components/requirejs/require.js:1178:17
	completeLoad https://mydomain.com/bower_components/requirejs/require.js:1552:21
	onScriptLoad https://mydomain.com/bower_components/requirejs/require.js:1679:21
```
3° error : on the main page, I've this error : 
```
TypeError: asm.js type error: Disabled by debugger  chainpad.dist.js
```

I really don't know how to fix the 2d and 3d error.

For Information : 
I'm using Debian Jessie 8 - npm 5.0.3 - node v8.1.3

PS : I'm packaging the app for an open-source software and an organization called Yunohost. My work is here : https://github.com/YunoHost-Apps/cryptpad_ynh , so, the conf is on this repos. Of course if you need logs or more info about this repos, don't hesitate to ask questions ;) . For instance I'm using Cryptpad.fr and your work is awesome, but I want really to integrate cryptpad to Yunohost.

Sorry for my bad english, I'm french.

Thanks and help me please,
frju365

**Comment by JimboJoe** [comment]
Hello,
Maybe @ansuz could you please explain why you're closing this issue...? :wink:

Thanks!

**Comment by ansuz** [comment]
There was a mismatch between the api we were using and the specified version in one of our dependencies.

You hit the same issue as in [this issue](https://github.com/xwiki-labs/cryptpad/issues/146), which we fixed. I was closing this as a duplicate.

To fix your installation, remove the `diff-dom` dependency from `www/bower_components`, pull the latest master version, and rerun `bower install`.
