### ISSUE TITLE
Problem with links in read-only views of text pads (since 1.10.0)

### ISSUE THREAD

**Issue by thedod** [xwiki-labs/cryptpad#149]
Links on read-only views of text pads could never be left-clicked[*], but had a right-click context-menu with an option to open the link in a new tab. Since 1.10.0, right-click does nothing, and the only way to follow a link is via the middle-button (which isn't very obvious, and even impossible on some devices).

----
[*] This makes sense while editing a pad (where you might want to place the cursor inside linked text), but in read-only views I don't see a reason why clicking a link shouldn't work "as expected".

**Comment by ansuz** [comment]
Thanks. We'll try to get this fixed by 1.11.0
