### ISSUE TITLE
Characters being deleted/reverted as I type them

### ISSUE THREAD

**Issue by elimisteve** [xwiki-labs/cryptpad#150]
Thank you for creating CryptPad; I use it almost every day

My JS console says things like:

```
shjson2 !== shjson
realtimeOptions.onRemote @ /pad/main.js?ver=1.10.2:393
/bower_components/textpatcher/TextPatcher.js?ver=1.10.2:95 Objectinsert: "type":"pad",""remove: ""__proto__: Object
/pad/main.js?ver=1.10.2:414 Encountered a known browser disagreement: available at `REALTIME_MODULE.fights[0]`
```

I would describe this bug as urgent, because if I type faster than ~30wpm, I have to keep retyping the characters that get deleted as I type them.

Thanks!

**Comment by ansuz** [comment]
This should only happen if you're typing with another user, and your browsers disagree about what the content should be.

The error you're seeing is from our code that's meant to catch these situations, and keep them from turning into an endless loop. This isn't a perfect solution, as you've noticed, but it's difficult to perfectly resolve all browser quirks (new quirks are constantly being introduced as well).

If you can tell us what browsers were involved in the session, and what types of elements (tables, lists, images) were included in the pad, that might help us reproduce the specific browser fight that you're seeing.

**Comment by elimisteve** [comment]
There was just 1 browser involved -- I was the only person editing -- and
I'm using Chromium.

It's possible that I had another tab opened in the same browser on that
same pad... I'll check

**Comment by ansuz** [comment]
We typically have at least one thing break every time chrome/chromium update to a new version, so I wouldn't be surprised. This is Chromium 59?

**Comment by elimisteve** [comment]
Chromium 57

**Comment by ansuz** [comment]
We believe we have a fix for this bug, which will be included in our next release.
