### ISSUE TITLE
Feature Request: RTP pdf export & image upload

### ISSUE THREAD

**Issue by skupfer** [xwiki-labs/cryptpad#155]
Came across cryptpad while looking for an alternative to etherpad (dev slow/stopped, plugins outofdate/dev stopped) ... 

So far I am happy with what I can see but I would like to request two things, maybe we will see them in the future!

As far as I have seen slides can be exported to pdf (even though I wasn't able to find the feature, just md by default)... It would be great if this could be available for other types, too.

1. PDF export for Rich Text Pads
2. Image import/upload - not only via link to a website

best regards

EDIT: As far as I know creditor 4.7 (which is your dependency) supports file upload per se and there is an pdf export plugin

**Comment by ansuz** [comment]
This is now possible for logged in users:

Drag and drop to upload your image...

![screenshot from 2018-01-31 12-24-09](https://user-images.githubusercontent.com/1264398/35620748-56874178-0682-11e8-892e-77b01c5e0441.png)

Use the export button in the CKEditor toolbar...

![screenshot from 2018-01-31 12-25-55](https://user-images.githubusercontent.com/1264398/35620812-8acf4548-0682-11e8-9571-5f0ecebf90b3.png)

Export to file and open your new PDF

![screenshot from 2018-01-31 12-26-36](https://user-images.githubusercontent.com/1264398/35620836-9ebd564e-0682-11e8-8780-cd8ccdeae743.png)
