### ISSUE TITLE
Add ability to set default indentation for code pads.

### ISSUE THREAD

**Issue by ryanpcmcquen** [xwiki-labs/cryptpad#165]
Should be a matter of exposing the `indentUnit` property from CodeMirror (https://codemirror.net/doc/manual.html).

**Comment by ryanpcmcquen** [comment]
There may be some other properties as well. I would (for instance) like to set default indentation to _4 spaces_ for all code. Others may prefer tabs and some other unit, so if both those were settable that would be 💯 .

**Comment by ansuz** [comment]
Would a new field on https://cryptpad.fr/settings/ be appropriate? We're trying to keep the UI as simple as possible, and this doesn't seem like something you'd like to change often. I also use 4 spaces.

**Comment by ryanpcmcquen** [comment]
Yes, that would be perfect!

**Comment by ryanpcmcquen** [comment]
It looks like we should expose these three settings:
```
indentUnit: integer
How many spaces a block (whatever that means in the edited language) should be indented. The default is 2.
```
```
tabSize: integer
The width of a tab character. Defaults to 4.
```
```
indentWithTabs: boolean
Whether, when indenting, the first N*tabSize spaces should be replaced by N tabs. Default is false.
```

As far as I'm concerned, `tabSize` and `indentUnit` could be set by the same field. Most editors just have one setting for indentation (unless we are talking about Emacs 🙃 ). Do you currently have a UI element for checkboxes or toggling?

**Comment by ansuz** [comment]
I'm part of the way through adding an input (with `type="number"`) to the settings page.

**Comment by ansuz** [comment]
This has been implemented and deployed.

**Comment by ryanpcmcquen** [comment]
Thank you!

**Comment by ryanpcmcquen** [comment]
Is there supposed to be a checkbox next to the `tab` setting?

![screenshot 2017-08-16 at 06 07 45](https://user-images.githubusercontent.com/772937/29364732-5318e770-8249-11e7-8c72-69ae23d3e73b.png)

**Comment by ansuz** [comment]
Yes, it's supposed to be below. It's working in Firefox, but I guess you're using chrome/chromium?

I see the same thing as you in Chromium. We should have it fixed shortly.

**Comment by ryanpcmcquen** [comment]
Yes, thank you!

**Comment by ansuz** [comment]
Should be fixed now.

**Comment by ryanpcmcquen** [comment]
Looks great! I also like how it is its own category on the sidebar. Bravo!

**Comment by ryanpcmcquen** [comment]
@ansuz, is the field setting `tabSize` and `indentUnit`?

**Comment by ansuz** [comment]
Yes, they're set [here](https://github.com/xwiki-labs/cryptpad/blob/master/www/code/main.js#L64-L69).

**Comment by ryanpcmcquen** [comment]
That looks good. I'm noticing some weird behavior, perhaps there is another setting (or this is a CodeMirror bug).

Enter some code such as this:
```py
print(map(lambda x: x + 1, [1, 2, 3]))
```
Hit enter after `print(`, and the `map(...` portion gets pushed to the next line with a `2` space indentation, rather than `4` (which is the `indentUnit` & `tabSize` currently set).

Are you seeing this as well?

![aug 24 2017 6-57 am - edited](https://user-images.githubusercontent.com/772937/29669888-c93495ca-8899-11e7-9390-04a6a4708bff.gif)

**Comment by ansuz** [comment]
Apparently the indentation values need to be set after changing the syntax highlighting mode, otherwise it reverts to two spaces.

**Comment by ryanpcmcquen** [comment]
Wow, nice find! Is that fix ported over?

**Comment by ansuz** [comment]
It should be better now.

**Comment by ryanpcmcquen** [comment]
It's perfect! Thank you so much for the quick fix.

**Comment by ansuz** [comment]
Thanks for noticing. I didn't think to test whether it continued to work after switching languages, but that's a pretty common use case.
