### ISSUE TITLE
Feature Request: Add support for Org-mode syntax highlighting

### ISSUE THREAD

**Issue by structur** [xwiki-labs/cryptpad#168]
For all the children of Stallman!

http://orgmode.org/

**Comment by ryanpcmcquen** [comment]
Here's some libraries that may help:
https://github.com/daitangio/org-mode-parser
https://github.com/mooz/org-js

**Comment by ryanpcmcquen** [comment]
You could even add presentation mode for Org mode (if you wanted to get really adventurous:
https://github.com/relevance/org-html-slideshow

**Comment by ryanpcmcquen** [comment]
This app uses CodeMirror and has an Org mode with Emacs keybindings:
https://github.com/mickael-kerjean/nuage

**Comment by ryanpcmcquen** [comment]
This seems to be the important file for CodeMirror support:
https://github.com/mickael-kerjean/nuage/blob/master/client/pages/viewerpage/editor/orgmode.js

**Comment by ryanpcmcquen** [comment]
@ansuz, what would this take to integrate?

**Comment by ryanpcmcquen** [comment]
Looks like we would need an addition here:
https://github.com/xwiki-labs/cryptpad/blob/master/www/common/modes.js

Where could we plop this file to be picked up by CodeMirror?
https://github.com/mickael-kerjean/nuage/blob/master/client/pages/viewerpage/editor/orgmode.js

**Comment by ansuz** [comment]
I don't remember getting a notification about this thread. Sorry to leave you hanging.

This should be implemented in the next release, on January 30th.

**Comment by ryanpcmcquen** [comment]
@ansuz, did you get folding working? I built an extension for Standard Notes using that library and have had no end of trouble getting folding to work in it:
https://github.com/ryanpcmcquen/standardnotes_org_mode_editor

**Comment by ansuz** [comment]
It was my colleague that did the integration, but I don't think there were any problems with folding.

**Comment by ryanpcmcquen** [comment]
@yflory, any ideas on my extension? https://github.com/ryanpcmcquen/standardnotes_org_mode_editor

**Comment by ansuz** [comment]
This was deployed yesterday, and will be tagged later today in our `1.25.0` release.

**Comment by ryanpcmcquen** [comment]
A bit off topic, but the fix for me was adding gutters:
https://github.com/ryanpcmcquen/standardnotes_org_mode_editor/commit/346dcf6fa9bc34c29e448a06cb393671eb16e8d6#diff-9a9569e9d73f33740eada95275da7f30R104
Thanks to @yflory for the help!

**Comment by ryanpcmcquen** [comment]
@ansuz, can you update this using:
https://github.com/mickael-kerjean/codemirror-orgmode
