### ISSUE TITLE
Anchors should output... anchors (or IDs)

### ISSUE THREAD

**Issue by polx** [xwiki-labs/cryptpad#169]
The feature with the "flag" icon seems just right: I can input an anchor name and I can potentially link to that. The problem is the potentially: What is the way for me to link to that?

Neither HTML exports, nor the read-only view display this anchor as an <a name="..."> or id attribute.

I must have overlooked something.

**Comment by ansuz** [comment]
I've gone ahead and removed the anchor button as it doesn't seem especially useful.

**Comment by polx** [comment]
Mmmh. I don't think that this is a good idea, except as a temporary idea.
If you tell me where I can hunt, I am happy to hunt.

For me this feature is part of a bigger set of features where CryptPad documents are the editing side of the world and the HTML export is used to produce, say, a website with a generator, e.g. Jekyll.

paul

**Comment by ansuz** [comment]
This looks like a broken feature buried somewhere in CKEditor. It's possible to create a link to the anchor with the link button, however, the anchors don't seem to produce anything usable by browsers.

We could open an issue on CKEditor's issue tracker, however, I think they're putting all of their effort into CKEditor 5, so this would probably be fruitless.

**Comment by polx** [comment]
Isn't it a matter exchanging the output of CKEditor?
Saving the html that CKEditor manipulates clearly is not a way to expect CKEditor to deliver an HTML that is for the world outside.

The following Regexp seems to work for me:
`            html = html.replace(/<img[^>]*class="cke_anchor"[^>]*data-cke-realelement="([^"]*)"[^>]*>/, function(match,realElt){ return unescape(realElt); }); `

But, of course, this bases on a way CKEditor encodes its things.
It wouldn't be very sustainable if this is not counter-checked by some testing.

paul

**Comment by polx** [comment]
Hello Aaron and all,
following this discussion, I created the pull request #245 where the Anchor function is restored, the export indeed yields an <a id='...'> element and a test corresponds to this.

Note however, that this requires the tested /pad/ documents to contain at least an anchor, as I have found no way in the current test systems to predefine the documents being tested or to press on buttons to do so. Maybe I have missed something...

This manual anchor function should follow the work done for the issue https://github.com/xwiki-labs/cryptpad/issues/243 .

paul

**Comment by polx** [comment]
I believe that my last commit (0dc1500784051226a6bf464b08035ade66958a8d) solves this issue and I propose to merge this.
thanks
paul

**Comment by polx** [comment]
@ansuz, are you willing to review that?
thanks
paul
