### ISSUE TITLE
drop user-agent requirement

### ISSUE THREAD

**Issue by ilf** [xwiki-labs/cryptpad#172]
When trying to access any cryptpad with HTTP User-Agent set to "Mozilla/5.0", the cryptpad fails to load. Since privacy is not only about content confidentiality but also (pseudo|ano)nymity, such a peace of identifying metadata should not be mandatory, IMHO.

**Comment by cjdelisle** [comment]
We're not checking UserAgent anywhere, please check if you might have some extensions in the browser which could be interfering with it loading. Browser localStorage is required in order for it to function.

**Comment by ilf** [comment]
Running `chromium --user-agent='Mozilla/5.0' https://cryptpad.fr/pad/` results in a pahge saying "Loading..." - and nothing else.
Running `chromium https://cryptpad.fr/pad/` works fine.

**Comment by cjdelisle** [comment]
Reproduced on /pad/ but not on /code/ it looks like the issue is with CKEditor which checks your user agent in order to setup correctly. Please open an issue on https://github.com/ckeditor/ckeditor-dev
Thanks.
