### ISSUE TITLE
Fatal error: Failed to read the 'localStorage' property from 'Window'

### ISSUE THREAD

**Issue by elimisteve** [xwiki-labs/cryptpad#173]
> Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.    LessLoader.js:13

Currently running into this on https://beta.cryptpad.fr/pad and on every document.

**Comment by ansuz** [comment]
What browser is this? Do you have any extensions running?

**Comment by elimisteve** [comment]
Chromium.  Same problem in Incognito Mode with no extensions enabled.

...but the pads are now loading despite this error!  So this is less urgent than it was earlier -- after the SSL error was fixed, but before pads were loading for me.
