### ISSUE TITLE
Cannot get  what-is-cryptpad.html 

### ISSUE THREAD

**Issue by xshadow** [xwiki-labs/cryptpad#175]
On the latest cryptpad version (CryptPad v1.14.0 (Ouroboros)) the access of  /what-is-cryptpad.html results in an error. 

Error message:
`Cannot GET /what-is-cryptpad.html/ `

Example URL:  https://cryptpad.systemli.org/what-is-cryptpad.html/

The other pages are working fine.

**Comment by ansuz** [comment]
I suspect your config.js file is missing [this line](https://github.com/xwiki-labs/cryptpad/blob/master/config.example.js#L117)

**Comment by xshadow** [comment]
My bad, had a spelling issue.
