### ISSUE TITLE
CryptPad RichText should be printable

### ISSUE THREAD

**Issue by polx** [xwiki-labs/cryptpad#178]
It should be possible for CryptPad rich-text-pads to print without all the toolbars and collaboration display.

**Comment by polx** [comment]
Patch attached: [non-printed-toolbars.txt](https://github.com/xwiki-labs/cryptpad/files/1277960/non-printed-toolbars.txt)

Apply with git apply (--check|--stat|--signoff).
paul

**Comment by ansuz** [comment]
I had to adapt it a bit for our latest code on the staging branch, but the patch is here now: https://github.com/xwiki-labs/cryptpad/commit/6a735b441fff85d73e3cff643836d64e2c2b3988

**Comment by ansuz** [comment]
thanks
