### ISSUE TITLE
media tag shown as a vertical line in presentations

### ISSUE THREAD

**Issue by silviolorusso** [xwiki-labs/cryptpad#182]
Hi, when I upload an image to a presentation, the image is shown as a tiny vertical line (see attachment). I'm using Firefox.
![screenshot from 2017-10-08 13 53 23](https://user-images.githubusercontent.com/1828267/31316561-28f1bba0-ac30-11e7-81ec-0c1c0accc72a.png)

**Comment by ansuz** [comment]
Thanks for the report.

Could you share a link to a pad where this is occurring? A read-only link should be sufficient.

**Comment by silviolorusso** [comment]
Here you go: https://cryptpad.fr/slide/#/1/view/ntHGUuRUx321WAPKH4hU4g/CHlQn+zt4m4oJE2A02e7W03MvNwVQU-1kfP-dmQwTOk/

(Thanks! Cryptpad is great)

**Comment by ansuz** [comment]
Thanks (for the link and the compliment).

We've looked at the link in every browser we have available for testing, but we're not seeing what you're seeing.

Which browser and version are you using? Could you provide a list of extensions that you have installed (if any)?

**Comment by silviolorusso** [comment]
I'm using Firefox ESR 45.2.0 on Linux debian 3.16.0-4-amd64. Browsers add-ons are:

- AdBlock
- Email This!
- Paper
- Wikictionary and Google Translate
- Zotero

**Comment by silviolorusso** [comment]
Just tested on Firefox 56.0.1 and works fine

**Comment by ansuz** [comment]
We just deployed a patch that ought to fix it. Try reloading.

**Comment by silviolorusso** [comment]
Works fine now!
