### ISSUE TITLE
Uncaught Error: Bootstrap tooltips require Tether (http://tether.io/) at bootstrap.min.js?ver=1.17.0:7

### ISSUE THREAD

**Issue by dohlin** [xwiki-labs/cryptpad#187]
I'm getting this error when I first visit the main cryptpad homepage - anything I can to do resolve it and get it to go away?  I've followed through all the steps 2 or 3 times thinking I missed something, and it's still happening...fresh install of Ubuntu 16.04, nodejs 6.x, etc.

Any advice?  Thank you!

EDIT: So I'm definitely not a programmer, but I can't help but wondering if it's relate to the version of bower that Ubuntu 16.04 installed (v1.8.2 I believe)?  The reason I say this is because for kicks and giggles I renamed the "bootstrap.min.js" file that's located in cryptpad/www/bower_components/bootstrap/dist/js to "bootstrap.min.js.bak" and then copied the "bootstrap.min.js" file located in /cryptpad/www/common/pdfjs/js over into cryptpad/www/bower_components/bootstrap/dist/js.  It definitely got rid of the error although I haven't done a ton of further testing to make sure it didn't break anything else.  Did I do something funky with my install or is anyone else seeing this on the latest version of Cryptpad?  Thanks!

**Comment by dohlin** [comment]
Is no one else seeing this issue other than me?

**Comment by ansuz** [comment]
We're aware of the console warning, but since it didn't actually break anything, we were focusing on some other issues for this release. We're hoping to have it fixed before deployment tomorrow.

**Comment by dohlin** [comment]
Ok, thanks!  Just was mainly wanting to make sure I didn't manage to screw something up in setup!
