### ISSUE TITLE
Cryptpad is not detecting connectivity issues in browsers with SOCKS proxy

### ISSUE THREAD

**Issue by anadahz** [xwiki-labs/cryptpad#191]
`Description`:
I occasionally observe random non stated disconnections in rich text pad version hosted under `cryptpad.fr` that leads to text not being uploaded/updated in the pad.
Connectivity issues are not always detected and users assume that the changes have been propagated since the pad is in `Saved` status mode (although they are not).

This behavior was observed in:
- Tor Browser 7.0.8 (based on Mozilla Firefox 52.4.1) (64-bit) on Security level: High
- Firefox ESR 52.4.0 (64-bit) with plugins: HTTPS everywhere, Privacy Badger, Self-Destructing Cookies

`Impact`: Pad users may lose content
`Workaround (backup)`: Use the export function to save the pad document locally
`Possible resolution`: Upon connectivity issues users should be in 'Disconnected' (or similar) status mode

I cannot stably reproduce this, but I already had missing text from pads assuming that my changes have been propagated to the server (status 'Saved').

**Comment by ansuz** [comment]
I believe this should have been fixed. If you notice this behaviour again please reopen this issue.
