### ISSUE TITLE
design: the "title toolbar" is arguably consuming too much horizontal space

### ISSUE THREAD

**Issue by quite** [xwiki-labs/cryptpad#192]
The font is large, and the bar twice as tall as would seem reasonable.

140926 <@pbondoer[m]>  quite: it did end up bigger than initially designed, but im sure this can be tweaked. it would probably be nice to have it become smaller with smaller viewports/as an option/by default but that might make it more cluttered :/

**Comment by pbondoer** [comment]
I was referring mostly to the actions in `/pad/` where CKEditor's toolbar ends up taking more space than what the design accounted for at first (for context, I proposed the current design and it was adapted to fit technological constraints).

I don't think there is a right answer for any of this but it'd certainly be interesting to see if there's any way to make it more compact as an option sometime in the future 😄
