### ISSUE TITLE
Deleted files in Cryptdrive are still available

### ISSUE THREAD

**Issue by anadahz** [xwiki-labs/cryptpad#193]
`Cryptpad version`: What is currently running in https://cryptpad.fr
`Cryptpad user`: none

**Description**: Deleted files in CryptDrive are still available visible and editable with the full content reachable on the cryptpad links.

**Expected behavior**: The cryptpad(s) should be deleted

**Actual behavior**: CryptDrive doesn't display the cryptpad files, thought the content can be accessed/edited by calling the cryptpad URLs

**Comment by cjdelisle** [comment]
The problem here is that the pads currently do not have a clear owner. So once you share a pad with other people they might have added it to their drive too and we don't really know when it should go away.

We have a solution to this but it is more long term, the solution is to have "owned pads" so therefore you  as the creator can actually delete them and they will become unavailable to other people and disappear from their CryptDrive. However it is non-trivial to be able to properly remove a pad from another person's CryptDrive so this is something which needs a bit of development.

**Comment by anadahz** [comment]
Perhaps it makes sense to remove this option until it's ready for use, otherwise people may faulty believe that their pads have been removed although they are still around.

**Comment by ansuz** [comment]
I don't think we can get by without having the functionality as it currently exists. However, it should say _move to trash_, and not _delete_.

**Comment by cjdelisle** [comment]
I can understand the desire to have something be gone from the server and so we can try to prioritize the simple ability to get rid of a document, even without the full granting and revoking of permissions for other people.

**Comment by anadahz** [comment]
Up to know pads (whichever implementations) were not meant to be deleted and (hopefully) users assumed the information will stay there forever or until the pad expires (if and when that happens).
Having a feature named as `move to trash` or `delete` in Cryptpad may potentially "trick" users to believe that they can delete (or move to trash) a pad and the text within it accordingly. I guess we don't need to go through the potential risks users may face when they think that a pad has been deleted when it's technically not feasible.

I guess this should be clearly communicated to the user or at least show a type of warning/notification similar to:
`Hey, your pad may not be deleted/disappear for various reasons: You are not logged in CryptDrive,  open instances of the pad may not allow deletion of the pad, other reasons here...
Please don't rely on the deletion/move to trash function of the CryptDrive (you have been warned).`

**Comment by gamaanderson** [comment]
I'm a new used and I just had the problem that my link was compromised. This is a big security risk, please prioritize this.

Also, thank you for the service.

**Comment by ansuz** [comment]
Our next release will feature a pad creation screen which will allow users to set themselves as the _owner_ of a pad. Owners will have special privileges for administrating their pads, including fully deleting them from the server.
