### ISSUE TITLE
Feature Request: Tweak mobile UI layout for code editor

### ISSUE THREAD

**Issue by wizzard0** [xwiki-labs/cryptpad#196]
While adapting editors for mobile is a complex task, it seems that there's one low-hanging fruit here, the code editor.

It looks almost usable with a small CSS change or a button that minimizes the toolbar into something narrow.

![p4opo_20171109_16_27_43](https://user-images.githubusercontent.com/424619/32610320-19a642f2-c56b-11e7-80f1-a6f8df003eb2.jpg)

**Comment by pbondoer** [comment]
I'll try to see if I can write a patch and do a PR as this seems to be a trivial fix ✨

**Comment by ansuz** [comment]
Thanks for the report.

PRs are always welcome, but if that doesn't happen first, we'll be putting some time into mobile improvements soon.

**Comment by yflory** [comment]
This issue should be fixed. The patch will be deployed with tomorrow's release (November 21st).
