### ISSUE TITLE
Bug: Right click - Open Readonly gives wrong link

### ISSUE THREAD

**Issue by wizzard0** [xwiki-labs/cryptpad#197]
Expected link: https://cryptpad.fr/pad/#/1/view/_TOKEN_/
Result: https://cryptpad.frhttps//cryptpad.fr/pad/#/1/view/_TOKEN_/

**Comment by yflory** [comment]
Thanks for the report.
We have a patch that should fixed the issue. It will be deployed for our next release, on November 21st, 2017.
