### ISSUE TITLE
Not able to scroll Rich text pads on iOS

### ISSUE THREAD

**Issue by solebared** [xwiki-labs/cryptpad#199]
Rich Text pads open fine and i'm able to type into the editable area, but can't scroll to content below anything that initially fits in the viewport.

Both `/edit` and `/preview` links are broken, but Code pads seems to work fine.

iPhone 6, iOS 10.3.3
Tried on Chrome (v62.0.3202.70) and Safari 10 (AppleWebKit/603.3.8 Safari/602.1)

**Comment by ansuz** [comment]
Thanks for the report. We'll see what can be done about this ASAP.

**Comment by pbeckmann** [comment]
I just want to notice that the problem does persist on the iPad Pro(2018) with iOS 12.1

**Comment by mthld** [comment]
Fixed, probably a while ago, closing!
