### ISSUE TITLE
Feature Request: Spreadsheet

### ISSUE THREAD

**Issue by teslasmoustache** [xwiki-labs/cryptpad#201]
An organization I work with wants to use this, but we need a spreadsheet function.

**Comment by marykatefain** [comment]
My entire activist group wants to use cryptpad for everything - but we really, really need spread sheets! I would be willing to donate to a crowdsourced campaign to support this feature. Many others probably would, too!

**Comment by MineRobber9000** [comment]
I really would use CryptPad more often if spreadsheets were included!

**Comment by ansuz** [comment]
Spreadsheets are included in our newly published [roadmap](https://blog.cryptpad.fr/2018/07/13/CryptPad-Roadmap/). Spreadsheets are a very complex feature, however, so we're looking for donations to help fund the investment of our time to get them working.

**Comment by ansuz** [comment]
We plan to deploy a spreadsheet editor in tomorrow's release.

**Comment by ansuz** [comment]
encrypted spreadsheets were included in this morning's release: https://github.com/xwiki-labs/cryptpad/releases/tag/2.16.0

Registered users can give it a try on https://cryptpad.fr
