### ISSUE TITLE
CryptoPad Slides enhancements 

### ISSUE THREAD

**Issue by koulaxizis** [xwiki-labs/cryptpad#202]
I 've been using Slides.com (a front-end of reveal.js project) for my presentations, but I think that CryptoPad slides could be equally awesome if you could add some enhancements.

- Option to add an image background, not just a solid color. This is a "must-have".
- Option to export the presentation to PDF and HTML for offline usage. Important!
- Option to choose animations for elements and slides. Not really essential, but nice! ;)

**Comment by funkycram** [comment]
@koulaxizis : There is all ready the possibility to show the document without the editor (but no slides) :
1. Get the embed code :
![image](https://user-images.githubusercontent.com/23310825/34154027-5d874c1a-e4b4-11e7-9ca8-e307f745ff6c.png)
2. Copy the link inside the commas.

It would be great to an element in this sharing menu to have directly this URL !

**Comment by ansuz** [comment]
As of CryptPad 1.24.0, it is possible to add an image as a background.

Presentations can be exported to PDF via the print submenu in the slide application.

At the moment we have no plans to implement animations for elements within slides.
