### ISSUE TITLE
Clients / API

### ISSUE THREAD

**Issue by ghost** [xwiki-labs/cryptpad#203]
Using clients would ensure encryption (because JS can be changed at any moment without the user noticing).

Putting less trust in the provider for the service (whoever that may be) is essential in my opinion.

Are there any plans for this?

**Comment by meme-lord** [comment]
Adding an API first would be good, then it would be a lot easier for people to make clients (or text editor plugins).

**Comment by mthld** [comment]
Hello,

Thanks for your interest in CryptPad! We rely on funding to develop more features, and we currently cannot plan for what you are proposing. As pull requests are always welcome, I'll be closing this issue for now. :)
