### ISSUE TITLE
Feature Request: add undo for whiteboard

### ISSUE THREAD

**Issue by GergelySzekely** [xwiki-labs/cryptpad#204]
The whiteboard is great!
What I really miss is an easy way to undo mistakenly drawn things (with `ctrl-z` or with a button).

**Comment by ansuz** [comment]
I'm marking this issue as a duplicate of https://github.com/xwiki-labs/cryptpad/issues/195, since we'll need to come up with a general solution for managing undo stacks before we add the feature to the whiteboard app.
