### ISSUE TITLE
Avatar upload suggestion 

### ISSUE THREAD

**Issue by kanellia** [xwiki-labs/cryptpad#205]
During the upload of the avatar in the profile section, the image couldn't be uploaded if it wasn't a perfect square. 

A nice implementation would be a build-in editor to crop the image properly and maybe a resizer/ size optimizer to automatically adjust the image to the right size and format, so there is no need for an external editor.

Thank you. :)

**Comment by ansuz** [comment]
Give it another try now. Our latest release is live on CryptPad.fr

**Comment by kanellia** [comment]
Hello. Thank you very much for the attention to my "problem". :)

The server of https://pads.sonsofpiracy.org will be updated tomorrow night (greek time) to the latest version and I'll give it a try then.
