### ISSUE TITLE
Single Sign On

### ISSUE THREAD

**Issue by funkycram** [xwiki-labs/cryptpad#206]
Thanks a lot for this great great app !

Is there a possibility to connect to the account with Google, Facebook or other OpenId Connect Identity provider such as [Keycloak](http://www.keycloak.org/) ?

**Comment by ansuz** [comment]
Thanks!

There was a bit of discussion about alternative means of authentication in [this issue](https://github.com/xwiki-labs/cryptpad/issues/174).

In particular:

> This type of thing is definitely possible but because the password is used to derive the root encryption keys, it is non-trivial to do it without effectively sharing all decryption keys with the LDAP server. However, if you are able to sponsor some development time, we could prioritize this on our roadmap. We're available for a discussion at sales@cryptpad.fr

**Comment by funkycram** [comment]
Thanks @ansuz !

**Comment by ansuz** [comment]
I'm on a mission to close some duplicate issues before the holidays, and this is my latest victim.
