### ISSUE TITLE
Assign different storage limit

### ISSUE THREAD

**Issue by koulaxizis** [xwiki-labs/cryptpad#207]
Hello!

Is it possible (on self-hosted) to assign different storage limit for a certain group of people (the admins, for example), without affecting all accounts?

**Comment by ansuz** [comment]
This feature didn't quite make it into the last tagged version (v1.21.0), but it is available on the master branch.

Given a user's public signing key (found near the top of their settings page), the admin of an instance should be able to give a user any limit they want via the [customLimits](https://github.com/xwiki-labs/cryptpad/blob/master/config.example.js#L170-L178) section of config.js. Changed limits will take effect after restarting your server.
