### ISSUE TITLE
Use more responsive design to support mobile devices

### ISSUE THREAD

**Issue by audreytoskin** [xwiki-labs/cryptpad#208]
I have this issue with both Firefox and Chrome on Android. The document title and formatting buttons are *always* in view, wasting a lot of precious screen space when trying to use Cryptpad on a smartphone. Combined with the space necessarily used by soft keyboards means I can only see a couple of lines of text at a time while trying to edit a notepad on the go.

**Comment by nobicycle** [comment]
Cryptpad is a fantastic project.
Unfortunately on android 4.4, firefox browser, the system hangs forever:
 ![cryptpad](https://user-images.githubusercontent.com/1372447/55286952-2f681300-53d5-11e9-9787-615e0f57358d.png)

**Comment by nobicycle** [comment]
On Android 6, I find Cryptpad for ToDO lists, perfectly fine
