### ISSUE TITLE
Design: wide rich-text pad makes reading very hard

### ISSUE THREAD

**Issue by bvhme** [xwiki-labs/cryptpad#209]
Love CryptPad!

I find it incredibly hard to read paragraphs that are as wide as my widescreen-screen. In moving my eyes back to the beginning of the line I often lose what line I was on and this makes it tiring to read longer paragraphs and texts.

I would love to see a smaller width to either be a standard, or alternatively a configurable option.

In my personal opinion something around 30em is a good width for text, however this issue has been widely documented on the internet and more information can be found over there.

**Comment by ansuz** [comment]
Thanks for the feedback! We'll probably add this as a configurable feature so that old pads will continue to appear as they currently do.

**Comment by ansuz** [comment]
If you check your account settings at https://cryptpad.fr/settings/ (also accessible via the dropdown in the top-right), you'll now see a section on the left for _Rich text_. You can choose to _Reduce the editor's width_, and the next time you load a rich text pad it will use a narrow layout.

**Comment by bvhme** [comment]
Very awesome folks!

I love it! Keep up the great work.
