### ISSUE TITLE
Pas clair, trop Geek

### ISSUE THREAD

**Issue by Franciscogva** [xwiki-labs/cryptpad#212]
Bonjour,
J ai découvert par hazard hier cryptpad.
Je ne suis pas un specialiste IT. 
Je pense avois saisi l essence de ce permet de faire cryptpad mais tout n est pas clair.

Le projet semble communiquer de specialistes à specialistes. Vous parlez de concepts techniques, qui vous semblent evidents, mais qui ne le sont pas pour ceux qui ne font pas partie de votre sphère. C est le gros point faible.

Voic mes questions, remarques:
- J edite un texte: si j ai bien compris , seules les personnes qui possèdent le lien peuvent accéder au texte ? est ce cela le principe de cryptpad ? ou peut on retrouver mon texte avec une recherche google ?
- 1ere page du site: C est quoi "Markdown" ?
- Page d'inscription: A quoi sert de cocher "Importer l'historique (Recommandé)" et l historique de quoi ?
- Apres avoir saisi un nouveau nom d utilisateur et mot the passe, le message " cet utilisateur existe deja, ..": comment cela est ce possible vu que je viens de m inscrire ? ca prete a confusion. De plus si je vais ensuite dans la page de login et je met le nom d utilisateur et le mot de passe que je viens de créer, cela ne fonctionne pas, et la page de Login connexion se réinitialise. 
- Je ne suis donc pas enregistré, je clique cependant dans "Pad riche de texte" (l editeur de texte). Je peux y accéder. Or je ne suis pas inscrit. Comment est ce possible ? que signifie cela ? que deviennent les données que je saisi ?
- dans l editeur de texte, ou se trouve "le bouton partager" pour "obtenir le lien en lecture seule " ?

Cordialement
Francisco

**Comment by frju365** [comment]
Bonjour,

1°/ Cryptpad ne s'adresse pas à des spécialistes mais il est vrai que déjà le concept de "pad"(document/traitement de texte sur internet) n'est pas compris par tout le monde. Le pad a plusieurs objectifs comme la possibilité d'écrire en ligne directement sans posséder le document sur son ordinateur. L'objectif principal est aussi la possibilité de partager ce document avec plusieurs personnes. Pour cela il existe 2 possibilités à choisir : la première est de créer un lien public que vous envoyez à votre collaborateur (il pourra éditer cela en tant qu'Anonyme ou en se connectant/s'enregistrant) ou bien vous ajoutez un utilisateur spécifique à votre "pad". 

De plus vous avez la possibilité de protéger votre document en écriture. Pour cela vous pouvez créer un lien public avec droit de lecture uniquement.

L'avantage de cryptpad, c'est que tous ces document en ligne peuvent être socker dans un drive (endroit où l'utilisateur pourra de nouveau les retrouver), sont chiffrés à travers le navigateur (cad. que l'administrateur du site ou d'autres personne ne pourront pas accéder à ce document sans votre autorisation et consentement), et 

Cryptpad permet d'avoir une interface agréable à utiliser reproduisant le design des suite offices communément utilisé sur les ordinateurs (libreoffice, Microsoft® office...) avec la puissance du stockage dit "en nuage" (cad. accessible depuis n'importe quel ordinateur possédant internet).

2°/ Markdown : La syntaxe markdown est à l'origine un langage (ou plutôt syntaxe) permettant de coutourner la syntaxe un peu barbare de HTML et du XHTML utilisé par les dévéloppeurs web.
cf : https://fr.wikipedia.org/wiki/Markdown

3°/ Importer l'historique : Qand vous n'êtes pas connecté vous avez peut-être modifié des pad anonymement, ou vous avez peut-être créer des pads. Cette option permet de fait d'importer tous ces pads dans votre compte utilisateur.

4°/ Sur une instance publique comme le site de cryptpad, il est possible qu'une autre personne ait déjà pris le nom d'utilisateur que vous avez choisi. C'est la même chose pour tous les autres sites d'inscrption. On ne peut pas enregistrer deux fois le même nom d'utilisateur.

5°/ Vous pouvez créer un "pad" anonymement sans vous connecter. Les données saisi sont enregistrées mais vous êtes considéré comme anonyme. Il vous faudra garder le lien du pad (l'URL) pour y accéder de nouveau.

6°/ Déjà expliqué en 1°/

J'espère avoir pu vous aider et n'avoir rien oublier,
N'hésitez pas à poser des questions,

Cordialement,
frju365

**Comment by Franciscogva** [comment]
Bonsoir,
Merci pour votre réponse très rapide.
L explication que vous donnez en 1) et beaucoup plus parlante . C est une exellent résummé.

2) ok. merci
3) ok, c est plus clair. (le mot historique prete à confusion. ca serait plutot "importer un ficher cryptpad html."
4) j ai bien compris. j avais bien une erreur. (J avais bien saisi 2 nom d utilisateur qui n avait jamais éte pris. c est impossible) C est peut etre parceque j utilisais internet explorer. aujourd hui j ai pu creer un compte sans erreur avec microsoft edge. ok 
5) noté.
toutefois, si google scanne le web, peut il découvrir la page ?
6) ok.  j ai trouvé le signe qui représente le bouton partager.

Merci c est exactement le logiciel que je recherchais. j espère que vous avancerez vite dans votre projet car je souhaite vraiment me "libérer" de google drive.

Etes vous la personne qui a fait la présentation que l on peut voir sur youtube ?

Cordialement
Francisco D

**Comment by frju365** [comment]
Bonjour,
4. C'est possible. Mircosoft Edge et (encore plus) Internet Explorer ne sont pas de très bon navigateurs, de mon point de vue. Je conseille plutôt d'utiliser Mozilla Firefox, Brave ou Google Chrome.
5. Google ne peut pas scanner le pad, ni le lien public si jamais vous voulez le partager avec d'autres utilisateurs non connectés. Les pads/documents Cryptpad restent dans Cryptpad et ne sont accessibles que si et quand vous le souhaitez. Il faut tout de même faire attention si vous mettez l'url public du pad sur une page web qui, elle, peut être scannée par Google ; l'url pourra alors peut-être apparaître dans une recherche approfondie.

J'espère avoir répondu à toutes vos questions.
Non, je ne suis pas celui qui a fait cette présentation. Je suis mainteneur du paquet cryptpad_ynh chez Yunohost (https://yunohost.org).

**Comment by ansuz** [comment]
It seems as though @frju365 answered your question. If you have any more issues feel free to raise them.
