### ISSUE TITLE
Add support for github flavoured markdown

### ISSUE THREAD

**Issue by telegnom** [xwiki-labs/cryptpad#220]
It would be great to have support for github flavoured markdown. It adds a bunch of features to markdown like tables.

**Comment by ansuz** [comment]
Hi,

I believe our code editor already supports github flavoured markdown.

![screenshot from 2018-01-16 09-55-34](https://user-images.githubusercontent.com/1264398/34980031-731fb9e0-faa3-11e7-8bc6-75da46a8fa79.png)

Are there features other than tables and task lists which are absent?

**Comment by telegnom** [comment]
Uhh my fault. I tried it without a header and with only two rows. Therefore I didn't notice the data being formated as a table.
