### ISSUE TITLE
mainPages cannot be disabled ? 

### ISSUE THREAD

**Issue by nicolass67** [xwiki-labs/cryptpad#223]
Hello, 

I just discovered Cryptpad which is very great. 
I currently just have a problem disabling some pages on right top of main page (about, what-is-caryptpad etc .. ) 

Server is a Debian stretch + nginx + nodejs (6.12.3) from nodesource with npm (3.10.10) 

I edited my config.js so to easily see the bahvior (it' s an example) : 
`mainPages: ['about']`, 
The original mainPages block is commented. 
I restart the app with systemd (config provided in the doc, and it seems the page always has all the links 
I also purged my caches (browser, nginx). 

All the rest is functionnal (pads , login, and so) 

Is there something special to achieve that ?  

Thanks in advance. 

Regards,

**Comment by ansuz** [comment]
Hi,

I just tried to reproduce.

1. launch the server with `mainPages` in its default state
2. visit `http://0.0.0.0:3000/what-is-cryptpad.html` to confirm that it loads
3. comment out `'what-is-cryptpad'` from `config.js`
4. restart the server
5. reload my tab

I was redirected to `http://0.0.0.0:3000/what-is-cryptpad.html/`, which displays our 404 page.

It's possible your step to restart the server did not work, or that your custom `config.js` is not being loaded correctly because the current working directory does not allow it to resolve `./config.js`.

I am testing against the current staging branch, but there have not been modifications to this behaviour in some time.

**Comment by nicolass67** [comment]
Hello ansuz,

What I want to do is completly remove the what-about-cryptpad , or blog icons/links. 

What I do is : 

- My cryptpad is behind an nginx, config is ok , all the rest of cryptpad is working. 
- take the config.sample.js and rename it to config.js , I just change tje port 
- give the app user all the files under the folder 
- comment the mainPages. 
- restart cryptpad with systemd file provided. 

Maybe it's related but in the server.js at line 99 you have this comment : 
`// FIXME I think this is a regression .... `
then comes the code about mainPages ... 

Regards,

**Comment by ansuz** [comment]
Assuming I correctly understand your setup, the node process is not the one serving the files. If you've based your Nginx config on the example provided in `cryptpad/docs`, then Nginx is what's serving them.

If you would prefer to serve something different, you'll need to override some of the files in `/customize.dist/` by providing another file with the same name in `/customize/`.

Unfortunately we cannot anticipate everybody's usage, however, we are available for custom support contracts and sponsored development, as specified within the example Nginx config file.

```
#   This file is included strictly as an example of how Nginx can be configured
#   to work with CryptPad. This example WILL NOT WORK AS IS. For best results,
#   compare the sections of this configuration file against a working CryptPad
#   installation (http server by the Nodejs process). If you are using CryptPad
#   in production, contact sales@cryptpad.fr
```

**Comment by nicolass67** [comment]
Hello, 

Thanks for the answer. 
I just managed to make the thing work by creating the customize folder, copying the customize.dist to it , and modifying the file **pages.js** as : 

```
        return h('nav.navbar.navbar-toggleable-md',
                     h('button.navbar-toggler.navbar-toggler-right', {'type':'button'}, {'data-toggle':'collapse'}, {'data-target':'#menuCollapse'}, {'aria-controls': 'menuCollapse'}, {'aria-expanded':'false'}, {'aria-label':'Toggle navigation'},
                    [h('i.fa.fa-bars ')
                    ]),
                    h('a.navbar-brand', { href: '/index.html'}),
                h('div.collapse.navbar-collapse.justify-content-end#menuCollapse', [  
                    h('a.nav-item.nav-link', { href: '/what-is-cryptpad.html'}, Msg.topbar_whatIsCryptpad),
                    h('a.nav-item.nav-link', { href: 'https://blog.cryptpad.fr/'}, Msg.blog),
                    **//h('a.nav-item.nav-link', { href: '/contact.html'}, Msg.contact),**
                    h('a.nav-item.nav-link', { href: '/about.html'}, Msg.about),
                ].concat(rightLinks))
        );
    };

```
