### ISSUE TITLE
Confusing message 'needs localStorage' when cookies disabled

### ISSUE THREAD

**Issue by Sciss** [xwiki-labs/cryptpad#224]
I'm getting a dialog that Cryptpad needs localStorage - use another browser, when I have cookies disabled by default in Firefox. The error message should indicate that missing cookie permission is the problem, instead.

**Comment by ansuz** [comment]
Hi!

The current message was written as such because the direct cause of the error is from localStorage. There are other reasons localStorage might not work other than cookies.

I agree that we should suggest possible fixes, and enabling cookies fits in there.

**Comment by ansuz** [comment]
This issue was addressed by [this line](https://github.com/xwiki-labs/cryptpad/blob/master/www/common/boot2.js#L37) ten months ago, but I forgot to close the issue.
