### ISSUE TITLE
Docker instructions don't include port 3001

### ISSUE THREAD

**Issue by OliverCole** [xwiki-labs/cryptpad#225]
Running through docker works on port 3000, but then http://localhost:3000/pad calls localhost:3001, which isn't exposed.

Easy fix, but not sure if that's the intended behaviour?

**Comment by ansuz** [comment]
Hi!
We don't actually use the docker configuration ourselves, so we don't notice when things aren't right. The intended behaviour is that it works like CryptPad.fr

**Comment by kpcyrd** [comment]
@OliverCole I'm using the image without 3001 being exposed, I think what you're seeing is this:
```
    // This is for allowing the cross-domain iframe to function when developing
    httpSafePort: 3001,
```

This is used for development purpose in the `/api/config` endpoint if:
```
'obj.httpSafeOrigin = ' + (function () {
    if (config.httpSafeOrigin) { return config.httpSafeOrigin; }
    if (config.httpSafePort) {
        return "(function () { return window.location.origin.replace(/\:[0-9]+$/, ':" +
            config.httpSafePort + "'); }())";
    }
    return 'window.location.origin';
}()),
```
the origin contains a port number. You can resolve this by either setting httpSafePort to null or setting up a reverse proxy. Ideally, this value could be over-writable with an environment variable that is then set in the image.

**Comment by ansuz** [comment]
To be clear, CryptPad's default CSP (Content Security Policy) relies on having two domains to prevent XSS attacks.

The `httpSafePort` is there for if you don't have a secondary domain set up (it serves some content over the different port). If I recall correctly, Edge or Internet Explorer don't consider different ports to be a different domain for the purpose of CSP.

The result of this is that if you serve CryptPad over a single port or domain, an attacker could potentially leverage an XSS attack in a shared pad to acquire the keys to a user's drive (effectively leaking all their pads' encryption keys).

As I said, we don't use docker internally, so I don't keep track of all the changes, but the `httpSafeOrigin` configuration point is one of the most important things to get right when setting up a CryptPad instance.

**Comment by ansuz** [comment]
If this is simply a configuration issue, would you say it's resolved? @OliverCole, perhaps you could submit a PR adding documentation regarding the issue you faced?

**Comment by ansuz** [comment]
closing this since it's gone stale. Documentation in [our wiki](https://github.com/xwiki-labs/cryptpad/wiki/Docker-(with-Nginx-and-Traefik)) can be updated.
