### ISSUE TITLE
Test "http://localhost:3000/p" , it dose not work !

### ISSUE THREAD

**Issue by AG0001** [xwiki-labs/cryptpad#23]
After I installed cryptpad successfully , I tested "[http://localhost:3000](http://localhost:3000)" , It's totally OK !
When I test "[http://localhot:3000/p/](http://localhot:3000/p/)" , It dose not work . It should create a new pad automatically . It's url dose not change and the page dose not jump automatically .
When I test "https://cryptpad.fr/p" , this page will automatically jump to '[https://cryptpad.fr/p/#CYf/iyq9wBDnJBGLHKXuqv0L](https://cryptpad.fr/p/#CYf/iyq9wBDnJBGLHKXuqv0L)' ! This page created a new pad .

So , the question is how can I create a new pad after cryptpad is installed on my computer ?

**Comment by cjdelisle** [comment]
Hmm, which branch are you using, master ?  Looks like we made a mistake when we last merged...

**Comment by AG0001** [comment]
Yes , it is master .
 A mistake ?

**Comment by ansuz** [comment]
Hi @AG0001, the path to the _pad_ app should be http://localhost:3000/pad/, not `/p/`.

If the URL does not change to include a identifier, it's possible you're missing some of the clientside dependencies.

Try navigating to the project root and running:

```Bash
# install serverside dependencies
npm install;

# install clientside dependencies
bower install;
```

and please let us know whether that helps.

Thanks for the report.

**Comment by AG0001** [comment]
Hi @ansuz  , It's ok now , my problem is solved .
I checked "bower list" , I found this:
├── ckeditor not installed
├── diff-dom not installed
├── jquery not installed
├── jquery.sheet not installed
├── markdown not installed
├── marked not installed
├── modalBox not installed
├── rangy not installed
├── reconnectingWebsocket not installed
├── requirejs not installed
└── tweetnacl not installed

Then , I try "bower install" , it always suck in             " bower retry     Download of http://jquery-elastic.googlecode.com/files/jquery.elastic-1.6.11.zip failed with ETIMEDOUT, retrying in 31.8s" .
I must have tried 5 times , then it's ok . This is the bower's problem , not cyptpad's problem .

Thanks for your tips , totally helpful !

**Comment by ansuz** [comment]
Excellent.

Don't hesitate to report any other potential bugs you find.
