### ISSUE TITLE
Patch vulnerable dependencies

### ISSUE THREAD

**Issue by kpcyrd** [xwiki-labs/cryptpad#232]
I've toyed around a bit and selected my cryptpad fork as a test repo:

https://snyk.io/test/github/xwiki-labs/cryptpad?severity=high&severity=medium&severity=low

There's a patch available:

https://github.com/kpcyrd/cryptpad/pull/1

Sadly, I can't directly create the PR to cryptpad, you'd have to enable it yourself. :)

**Comment by ansuz** [comment]
I just updated the dependency on our staging branch, which will be merged to master soon.

**Comment by ansuz** [comment]
Thanks for looking out for these things!
