### ISSUE TITLE
[suggestion] Official docker image on Docker Hub?

### ISSUE THREAD

**Issue by Ezwen** [xwiki-labs/cryptpad#233]
The provided `Dockerfile` and `docker-compose.yml` files offer great Docker support for Cryptpad. However, a complete build of the cryptpad docker image must be done for each deployment/upgrade, which is not very convenient.

Would you consider eventually to provide the community with an official pre-built cryptpad Docker image, if possible distributed through https://hub.docker.com/?

This should be automatisable easily either using the free build system from Docker hub (see https://docs.docker.com/docker-hub/builds/), or using the free Github Travis continuous integration (see https://docs.travis-ci.com/user/docker).

**Comment by kpcyrd** [comment]
As far as I can tell the repo is compatible with automated builds, which can be configured with a few clicks on hub.docker.com.

**Comment by ansuz** [comment]
We don't build docker images because we don't use docker in our production workflow. If there's anything more required from the automated build systems out there, we'd be happy to accept a PR implementing it.

**Comment by kpcyrd** [comment]
@ansuz you don't have to build them yourself, you only have to configure an automated build. The process looks round about this:
![configure automated build](https://docs.docker.com/docker-hub/images/create-dialog1.png)
docker hub is then monitoring your repo and building new images if the branch changed. Feel free to ping me on #cryptpad if you need help. :)

**Comment by J0WI** [comment]
I think a better solution would be to move the Dockerfiles to a dedicated repo and fetch the releases from https://github.com/xwiki-labs/cryptpad/releases
This guaranties deterministic builds.

This is also how «official images» work: https://github.com/docker-library

**Comment by J0WI** [comment]
> To achieve determinism you make sure that everything that is pulled over the network is pinned.

You'll have tags/commits in the docker-library. See e.g. https://github.com/docker-library/official-images/blob/master/library/node

**Comment by ansuz** [comment]
I configured dockerhub to autobuild based off of any new commits to our master branch. You can see the latest build (as of this morning) [here](https://cloud.docker.com/repository/registry-1.docker.io/cryptpad/cryptpad/builds/5124cb23-2bf9-414b-9ceb-72c7a4fdcb70).

**Comment by J0WI** [comment]
I thought this issue is about the inclusion in the docker-library?
