### ISSUE TITLE
Improve table display in code pads

### ISSUE THREAD

**Issue by rixx** [xwiki-labs/cryptpad#235]
Markdown table displays are counter intuitive imo, as the very prominently formatted header makes people think there is missing body formatting (happened to me multiple times). Would you be open for a PR for more consistent table formatting in the code pad's markdown preview?
![screenshot-2018-3-22 eventomat](https://user-images.githubusercontent.com/2657547/37781802-beea549e-2df1-11e8-9167-68cd3f8c3986.png)

**Comment by ansuz** [comment]
Thanks for asking! Absolutely, there's a lot of room for improvement, and we're open to PRs.

As far as I know, all the styles are [here](https://github.com/xwiki-labs/cryptpad/blob/master/customize.dist/src/less2/include/markdown.less#L14-L24).

**Comment by ansuz** [comment]
This is fixed in our staging branch, and will be merged to master in our next release.
