### ISSUE TITLE
Export to file

### ISSUE THREAD

**Issue by ehmry** [xwiki-labs/cryptpad#24]
Would be nice to export the contents of a pad to a file, for now I'm interested in the code pad, as this does not require special formatting.

**Comment by ansuz** [comment]
I started testing out file exports in the `/canvas/` app. You can try it out [here](https://beta.cryptpad.fr/canvas/).

It exports .png files. I drew this one not long ago to test:

![trollface](https://cloud.githubusercontent.com/assets/1264398/16120944/9e4eadae-33e1-11e6-93a5-54e4c67e40cd.png)

**Comment by ansuz** [comment]
The same library should work well for other pad types, and I'll see what to do about import soon.

Text files should be fairly simple, and our WYSIWYG editor will be just a little bit more work.

**Comment by ansuz** [comment]
XWiki's [beta instance](https://beta.cryptpad.fr) of Cryptpad is now running the latest code.

You should find a **SAVE** button in the top right of the [code pad](https://beta.cryptpad.fr/code/) which will prompt you to name your file.

**Comment by ehmry** [comment]
Just what I wanted.
