### ISSUE TITLE
Suggestion mode

### ISSUE THREAD

**Issue by jcgruenhage** [xwiki-labs/cryptpad#248]
On Google Docs, instead of editing a page you can also suggest edits. Would be cool to get that here too!

**Comment by mthld** [comment]
Hello @jcgruenhage,

Thanks for your interest into CryptPad! Have you tried our [comment feature](https://docs.cryptpad.fr/en/user_guide/apps/richtext.html#comments) on Rich Text documents?

If so, would it fit your use case?

**Comment by jcgruenhage** [comment]
I hadn't tried that yet, but looking at it it looks like a good first step, but it's not quite up to what Google Docs provides in terms of suggestions.
