### ISSUE TITLE
Feature request: Export all data

### ISSUE THREAD

**Issue by ilu33** [xwiki-labs/cryptpad#251]
The user needs to be able to export all stored data in a commonly used format (json?), Art 20 GDPR. Whether you consider cryptpads data "personal" is open to debate but export possibilities would be useful anyway.

Pads and polls can already be exported but kanban can't.

Click-here-and-get-a-zip would be best - maybe as a right-click option in CryptDrive?  - so you don't have to open every document.

**Comment by ansuz** [comment]
Not being able to export from kanban was an oversight. Data export/import is a feature we've generally supported since long before the GDPR came into effect.

Support for export (as json) and import has been added in the _staging_ branch, and will be included in the next release.

**Comment by ilu33** [comment]
Great!

**Comment by ansuz** [comment]
This has been deployed with v2.5.0
