### ISSUE TITLE
Problem installing on Ubuntu 18.04

### ISSUE THREAD

**Issue by dhowe** [xwiki-labs/cryptpad#260]
I get the following error after installing on Ubuntu 18.04 according to the instructions:
```

$ sudo node server
/home/me/git/cryptpad/server.js:81
            for (let header in h) { res.setHeader(header, h[header]); }
                 ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

```

$ node --version -> v4.2.6
$ npm --version -> 3.5.2
$ uname -a -> Linux .. 4.4.0-130-generic #156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ansuz** [comment]
Hi @dhowe,

as noted in our [installation guide](https://github.com/xwiki-labs/cryptpad/wiki/Installation-guide), we develop CryptPad using _node v6.6.0_. Older versions of node don't feature support for all the required syntax and APIs which we use.

Installing node via [nvm](https://github.com/creationix/nvm) will allow you to run CryptPad with any version of node, no matter what version is packaged by your operating system.

**Comment by dhowe** [comment]
Got it, thanks
