### ISSUE TITLE
Rendering Issues in Markdown Preview Area

### ISSUE THREAD

**Issue by gitjeff2** [xwiki-labs/cryptpad#263]
Links such as `[France](https://en.wikipedia.org/wiki/France_(disambiguation))` break in the Markdown preview because of the ending parentheses in the URL. 

The usual methods to fix this are:

1. Test for this case.
2. Accept backslashes as escapes in the URL's perimeter, like so `[France](https://en.wikipedia.org/wiki/France_(disambiguation\))`.

Many sites accept both methods equally well.

Also, I noticed that code blocks fail to syntax highlight when the coding language is declared in a \`\`\` code block:

```python
def main():
    print('something')
```

The above fails to syntax highlight completely in Cryptpad, though GitHub renders it quite nicely here.

**Comment by ansuz** [comment]
Updating our markdown renderer to a newer version and updating our rendering extensions to accomodate breaking changes fixed the first problem. The commit is currently on our staging branch, and will be deployed in tomorrow's release.

**Comment by ansuz** [comment]
Our latest release includes syntax highlighting as requested.
