### ISSUE TITLE
Please Add AsciiDoc Syntax Highlighting Support

### ISSUE THREAD

**Issue by gitjeff2** [xwiki-labs/cryptpad#264]
Please add [AsciiDoc](https://en.wikipedia.org/wiki/AsciiDoc) support to the syntax highlighter. As a handy reference, here is an example of [Vim syntax highlighting file](https://github.com/asciidoc/vim-asciidoc/blob/master/syntax/asciidoc.vim) with the required regular expressions to make this happen.

**Comment by matbgn** [comment]
+1

**Comment by ansuz** [comment]
I'll prioritize this at the same level as [this issue requesting hard-wrapping in CodeMirror](https://github.com/xwiki-labs/cryptpad/issues/521).

**Comment by matbgn** [comment]
Thx for your so quick answer. I could also imagine a sort of donation/sponsorship. Contact me in private if you have any interest/time to put it in your pipeline this way.

**Comment by matbgn** [comment]
Also, maybe this source code (MIT licensing) for live editing could dramatically simplify the integration:

http://espadrine.github.io/AsciiDocBox/

**Comment by matbgn** [comment]
@ansuz: Also, maybe this source code (MIT licensing) for live editing could dramatically simplify the integration:

http://espadrine.github.io/AsciiDocBox/

**Comment by keturn** [comment]
To support this at the same level as Markdown, with the live preview, I think you'd need  https://github.com/asciidoctor/asciidoctor.js  
It's what the two projects linked in the previous comment use for rendering. AsciiDocBox also uses CodeMirror, as CryptPad does, so it's a good comparison.

Asciidoc does have https://github.com/asciidoctor/codemirror-asciidoc which I imagine would be easy enough to plug in to your codemirror instance, but just by skimming that file, I am assuming it only does a little bit of syntax highlighting, it doesn't render it.

asciidoctor.js is 738 kB minified. That looks like it's more than codemirror itself. That means you'd want to be careful about not loading it when you don't need it, but it looks like you've already got scripts loading in a modular way.

**Comment by mthld** [comment]
This has been released in [v5.1](https://github.com/xwiki-labs/cryptpad/releases/tag/5.1.0) thanks to @mcesson's work. Closing this issue!
