### ISSUE TITLE
Cryptpad is blank on mobile

### ISSUE THREAD

**Issue by Serkan-devel** [xwiki-labs/cryptpad#266]
![screenshot_20180804-153433](https://user-images.githubusercontent.com/16866642/43677267-55aa4052-97ff-11e8-917d-a673cc683338.png)

Device: GT-I9100

{ "user-agent": "Mozilla/5.0 (Android 7.1.2; Mobile; rv:61.0) Gecko/61.0 Firefox/61.0" }

**Comment by Serkan-devel** [comment]
@ansuz could you rewrite it in Rust and/or at least compile it to webassembly to bypass parsing?

**Comment by ansuz** [comment]
no

**Comment by Serkan-devel** [comment]
I've set my phone to full power
![screenshot_20180807-124003](https://user-images.githubusercontent.com/16866642/43775907-89b412dc-9a4e-11e8-9e26-5769b3aee995.png)
and opened cryptpad on the default chromium-based browser on LineageOS, which gets updates every week
![screenshot_20180807-142612](https://user-images.githubusercontent.com/16866642/43775986-d3e65680-9a4e-11e8-8519-e5c3936e65e9.png)
I left it there for a while and now it's overheating

**Comment by ansuz** [comment]
what browser are you using ?

**Comment by Serkan-devel** [comment]
`{
  "user-agent": "Mozilla/5.0 (Linux; Android 7.1.2; GT-I9100 Build/NJH47F) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/66.0.3359.139 Mobile Safari/537.36"
}` but as said, it's the default browser on LinageOS, called "browser"

**Comment by Serkan-devel** [comment]
I can't hold my phone properly

**Comment by scher200** [comment]
same problem here, what can we do to use this on our mobile?

**Comment by andy5995** [comment]
Same here.

* CryptPad Version: 3.0.0
* Server: Debian 10
* Client: Android phone: SM-J727U
* Browsers tried: Fennec Fdroid, Firefox, Aloha

I'm running the server locally, connecting from my phone to my LAN IP on port 3000. Works locally on the same device that the server is running on, using either "localhost" or my LAN IP.

config: ` httpAddress: '::',`

```
tcp6       0      0 :::3000                 :::*                    LISTEN     
tcp6       0      0 :::3001                 :::*                    LISTEN 
```

**Comment by andy5995** [comment]
Same thing happens when I connect from a desktop on my LAN

**Comment by andy5995** [comment]
Tried with nodejs v10.15.2 and v6.6.0

**Comment by ansuz** [comment]
It's possible this is related to your CSP configuration. Check your config.js and see what domain your instance is configured to serve. Anything other than that domain will not work correctly.

**Comment by andy5995** [comment]
_domain is set to `http://localhost:3000/`

I notice now too that only the example config file is getting read. When I run `node server` in the top-level directory.

```
Config not found, loading the example config. You can customize the configuration by copying config/config.example.js to ../config/config
[2019-09-07T04:54:18.816Z] server available http://[::]:3000
Cryptpad is customizable, see customize.dist/readme.md for details
```

I had first copied config.example.js to config.js (within the config/ directory); but after seeing that message, renamed config.js to config. Still got the same message. Then I did as it suggested, creating it as ../config/config (from the top-level directory) but still got the same message.

**Comment by ansuz** [comment]
This is probably a path issue. If you launch with `node server` you need to be in the repo root.

I recommend launching with `npm run fresh`. It starts the server as though you were in the repo root.

**Comment by ansuz** [comment]
In any case, domain needs to be set to LAN_IP if you're going to load it on LAN_IP.

**Comment by andy5995** [comment]
> In any case, domain needs to be set to LAN_IP if you're going to load it on LAN_IP.

That worked!

>This is probably a path issue. If you launch with node server you need to be in the repo root.

I'm running it from the top-level of the extracted release archive. Still can't find config/config.js or config/config

```
andy@oceanus:~/.local/cryptpad-3.0.0$ npm run fresh

> cryptpad@3.0.0 fresh /home/andy/.local/cryptpad-3.0.0
> FRESH=1 node server.js

Config not found, loading the example config. You can customize the configuration by copying config/config.example.js to ../config/config
FRESH MODE ENABLED
[2019-09-10T05:06:56.648Z] server available http://[::]:3000
Cryptpad is customizable, see customize.dist/readme.md for details
```

**Comment by ansuz** [comment]
Closing this as it seems it was a configuration issue.
