### ISSUE TITLE
Edge Case: Attempting to 'change' password to current password results in 'account deletion'

### ISSUE THREAD

**Issue by sairim** [xwiki-labs/cryptpad#267]
Currently, if a user submits their current password as their desired, new password via the 'change password' form in settings, the application deletes the old block but does not create a new block. As such, if / when the user attempts to log in following this change, they will be told that their account doesn't exist (since the application gets a 404 error when requesting the block). While it's rather unlikely a user would intentionally try to 'change' their current password to their current password, it is possible to do this simply by accident and it would be a shame to lose all your data from such a silly mistake. 

Steps to reproduce:
1. Create an account & note the password
2. Navigate to /settings
3. Submit the noted password as the value for the current password, new password, and confirm new password fields.
4. Log out
5. Attempt to log back in

Solution:
A simple way I see to fix this is just to add another check to the basic JS form validations already present in www/settings/inner.js, which should keep any user from accidentally performing this action. Something like:

```
425a426,430
> 	if (oldPassword == newPassword) {
>              UI.alert(Messages.settings_changePasswordNewPasswordSameAsOld);
> 	        return;
> 	} 	
```

accompanied by an appropriate message in customize.dist/translations/messages.js like:

```
617a623
> 	out.settings_changePasswordNewPasswordSameAsOld = "Your new password must be different than your current password.";
```

**Comment by ansuz** [comment]
Merged to master and deployed to https://cryptpad.fr

Thanks again for noticing this issue !
