### ISSUE TITLE
Don't automatically add open tabs with cryptpads to the drive

### ISSUE THREAD

**Issue by b3yond** [xwiki-labs/cryptpad#270]
## Expected Behaviour

When I log into a commonly used cryptpad account, but have private cryptpads open, I don't want them automatically added to the drive. Instead it could ask me in each tab "do you want to add this cryptpad to your account?" This way, only those cryptpad links are exposed, which I want to share.

## Actual Behaviour

As soon as I log into a cryptpad account, all open cryptpads are silently added to it. If you don't expect this, you won't even realize (maybe even for months), exposing your private or possibly incriminating information to others. 

## Steps to Reproduce

1. create a cryptpad and fill it with private data (be creative, maybe a diary with all the times you cheated your wife or stole food in a supermarket?)
2. log in to your family's cryptpad (e.g. to plan your common vacations)
3. optional: be disinherited

## Why do I think this should be the default behaviour?

A friend of mine realized recently, that they leaked legally incriminating information to a larger group, because they didn't know cryptpad's default behaviour. it was not discovered for months.

This is the definition of a data breach through human error. Unfortunately, we can't expect everyone to understand how the software works - in many times, they just hope that it keeps them safe.

(and then they ask me to open a bug report for them, because that's what nerd friends are good for, apparently)

I love cryptpad and I use it a lot - for private matters *and* for group planning and collaboration. This is why this is so hazardous. Of course you could easily circumvent this by just using private tabs for every new account or whatever - but people just don't expect this.

I hate that people rely on software, and stop thinking for themselves. I give workshops about technology, so people start getting into it, and I could also just mention this behaviour in every cryptoparty I organize. But this is not scalable. So please design your software for stupid users, this also lowers the barrier, and enables more people to use it and protect themselves.

Thanks for this wonderful service, btw!

**Comment by ansuz** [comment]
Thanks for the detailed report, this is very valuable feedback!

As someone who knows that pads are saved implicitly, I've come to rely on that behaviour. With that being said, I recognize that we don't communicate this behaviour anywhere in the UI, and I appreciate the risk involved for anyone sharing computers or accounts with other users.

It should be possible to support both behaviours in a visible but non-intrusive manner, but we'll need to put some thought into how to best accommodate either workflow.

PS: I hope your friend was not disinherited!

**Comment by b3yond** [comment]
Thanks :) This sounds reasonable.

This behaviour could already be enough:

* When you login with a cryptpad account, 
  * all pads which are opened in other windows 
  * AND which are not in the account yet
* ask you in a small dialog window, if you want to add them to the account.
  * if yes, they are added,
  * if no, they are not added and won't ask again
    * with an option in the pad settings to reverse this decision, so it will be asked again
  * if the user does not react, they are not added for now, but it will be asked again

PS: In this case, rather hope that the police don't get their hands on the link ;)

**Comment by ansuz** [comment]
As of today's release, we've made it such that CryptPad will not automatically store pads in your drive when you visit them. Instead, a dialog will appear in the bottom-right corner which will prompt you to store it (or not).

Users can change the default behaviour via their settings page, which is also accessible from a link in the dialog. You have the option to:

1. always remember pads (classic behaviour)
2. always ask
3. never ask and don't remember pads unless manually stored

We'd love any feedback you have on this implementation.

**Comment by b3yond** [comment]
Hi, 

awesome, this was fast! Here is my experience:

1. I noticed a checkbox at the login, saying "import pads from your anonymous session". It was checked by default. I noticed the checkbox only when I had already clicked okay... well. It should not be checked by default, I guess. 
2. Anyway, the checkbox didn't work - all of the pads still asked me manually to store the pads. I like the little bubble at the bottom right, beautiful UI.
3. clicking No was easy and hat the expected result immediately. Cool.
4. clicking Yes was also good UI - but when I looked in my drive, I didn't see the pad. That's probably because my account is more than full (144/50 MB). I was not warned about this, which is unexpected and could lead to data loss.
5. Finally I looked into the settings. The options are easy to find. Unfortunately the english translation is... questionable. "results in" makes sense after the 3rd or 4th reading; just leave that out and describe what will happen.

Thanks, keep up the good work!

**Comment by b3yond** [comment]
Unfortunately I don't have transifex, but I will try to find the strings of the settings

**Comment by yflory** [comment]
We've made some improvements for our next release:

1. The checkbox on the login page is not checked anymore by default, to avoid filling the drive with unwanted pads.
2. This checkbox is not related to the new "manual pad storage" feature. When you use CryptPad without a user account, pads are stored in the browser. The checkbox allows you to import all these pads from your browser into your user account. We can maybe find a better way to describe this.
4. There was an issue with the error message which was never being displayed. This should be fixed now.

This should be deployed this week.
Thanks for the feedback!

**Comment by ansuz** [comment]
Closing this, as I believe the issues raised have been resolved. Feel free to re-open if anything else comes to mind.
