### ISSUE TITLE
Blank screen when installed on ubuntu

### ISSUE THREAD

**Issue by coolblock** [xwiki-labs/cryptpad#272]
Not sure where I went wrong, but I can install without error and it seems to come up fine in the bash screen but when I try to bring it up on a browser on another machine, the screen is blank.

(I can install etherpad lite fine).

Keep in mind, I am not building on a desktop, I am installing on a VPS with a static IP and trying to access it from my home desktop.
The VPS runs Ubuntu 18
1 meg ram
1 core

**Comment by polx** [comment]
This looks like the domain name you configured the cryptpad with is not the domain used to access with the browser.

Or some proxies are in the middle but websockets don't come through.

Can it be?

**Comment by coolblock** [comment]
So it has to have a domain name, not an IP?
In fact, I have used the sample config file, I did not modify anything.
Let me do some experiments.

I did 

cp config.example.js config.js;node ./server.js

Are there specific changes I need to make to the config that you can recommend?

**Comment by polx** [comment]
> So it has to have a domain name, not an IP?
Well. even an IP would do but it should be the correct one!

If you did `cp config.example.js config.js;node ./server.js` then your server believes that it's accessible as 'http://localhost:3000/' and will tell the browsers to load other resources on that address. If you are using form outside the domain name will be different and the browser will give different permissions to the scripts which will make them fail.

It's just the first assignment in that file!

paul

**Comment by coolblock** [comment]
Ok, I put in the ip and now:
I can see that there is a contact, as in the browser indicates cryptopad on top, but the rest of the page is blank.
1. Is there a debug log that I could look at?
2. What I have is a simply a test server, I am willing to give root and password info for someone who knows how to make it work so I can see it run once after installing it.

**Comment by polx** [comment]
The first log to look at is that of the browser.
It is the "console" of the web inspector.

**Comment by coolblock** [comment]
Thanks Paul, I see:
Failed to load resource: the server responded with a status of 404 (Not Found)
<myip>/:1 Refused to execute script from 'http://<myip>:3000/bower_components/requirejs/require.js?ver=2.3.5' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

Will research this later

**Comment by polx** [comment]
`http://:3000` ?
Definitely a problem here, or?

(or did you remove the IP?)

**Comment by polx** [comment]
Can you indicate which value you have put in the configuration?
paul

**Comment by coolblock** [comment]
I have abandoned it for now. The error is from Bower. I will have to look at it later.

**Comment by ansuz** [comment]
Closing this as it seems like a configuration issue.
