### ISSUE TITLE
Multiple selection holding Control or/and Shift key

### ISSUE THREAD

**Issue by fdiluch** [xwiki-labs/cryptpad#275]
When importing files into a folder, it is not possible to select multiple files to upload
Also it not possible to select multiple pads

**Comment by ansuz** [comment]
Hi,

assuming I understand you correctly, I think we added support for this a while ago. Below is a screenshot I took while using control-click to select multiple disparate icons, and then using shift-click-drag to select more. I'm using Firefox.

![multiple-select](https://user-images.githubusercontent.com/1264398/45495298-0043ca00-b741-11e8-95a0-3d328dffaa7c.png)

I've noticed that sometimes Firefox seems to get into a bad state where some handlers stop responding. Restarting Firefox makes it respond again.

It's entirely possible that some new update caused this functionality to stop working in another browser, but it worked in all of our supported browsers at the time when we deployed it.

Could you provide some more information about how you're using CryptPad, including the actions you took and the software (browser and add-ons) which you're using?

**Comment by fdiluch** [comment]
Hi Ansuz,
In fact, I meant when you have to import external file into Cryptpad.
Lets assume I have in my personal computer 10 pdf files, How to select them all and import them in 1 shot ?
From now, what I could see is that I have to do it 1 by 1 and this is big drawback from Cryptpad versus other cloud based drives

**Comment by ansuz** [comment]
To upload a number of things, I:

* open my file browser
* select multiple files
* drag the files into my drive
* confirm the names of the files in your drive
* watch the files get uploaded in a queue

How did you try to upload? Maybe we can support different workflows

**Comment by yflory** [comment]
Hi,

As ansuz mentionned, drag&drop was until now the only way to upload multiple files at onces. I've just pushed a patch that should allow multiple files selection in the upload popup.

This should be deployed in the next release, coming this week.
