### ISSUE TITLE
Typo in README?

### ISSUE THREAD

**Issue by ktorn** [xwiki-labs/cryptpad#28]
I'm confused by this sentence in the README (under Security):

> It is acceptable for anyone who does not have the key to be able to change anything in the pad or add anything, even the server.

Isn't the whole pad encrypted, making it _impossible_ for anyone without the key to make changes?

**Comment by cjdelisle** [comment]
basically we're saying that even though a person can't read the data, they can indeed change it.

**Comment by ktorn** [comment]
OK, but any change would essencially destroy the pad (i.e. the clients cannot decrypt the change). Is this correct?

**Comment by cjdelisle** [comment]
Oh actually this issue might be considered bunk because the hashes in ChainPad will fail to validate so trying to change the content will make the hash fail to validate
