### ISSUE TITLE
Bug: weird behaviour with fonts

### ISSUE THREAD

**Issue by georgemillo** [xwiki-labs/cryptpad#284]
Two bugs, probably related:

First, when I have a document where all the text is in Times New Roman, if I hit "enter" twice to make an empty paragraph, then move the cursor back to within that paragraph, the font switches to Arial:

![cryptpad](https://user-images.githubusercontent.com/2656485/46586479-1ceccc80-ca77-11e8-8483-398e5dea730e.gif)

Secondly, as can be seen in this gif, when I select all the text and try to change the font to Times New Roman, I click "Times New Roman" in the dropdown but the font changes to Arial! It only works the second time:

![cryptpad2](https://user-images.githubusercontent.com/2656485/46586489-31c96000-ca77-11e8-9f40-c154cd43f945.gif)

**Comment by ansuz** [comment]
I believe both of these issues have been fixed.

**Comment by kgollmer** [comment]
This bugs us as well, on the following paragraph, Cryptpad will change from Trebuchet back to Arial. It is very annoying.

**Comment by kgollmer** [comment]
Hm, ok, maybe being able to change the font for the <standard> paragraph formatting would be a helpful feature here, this doesn't really seem to be a bug (sorry). Should I open a new thread?
