### ISSUE TITLE
allowSubscriptions: false has no effect

### ISSUE THREAD

**Issue by casipw** [xwiki-labs/cryptpad#285]
I set `allowSubscriptions: false` in `config.js` but the "Log in" and "Sign up" buttons are still present.

For verifying the effect of `allowSubscriptions: false`, I added some debug output to `server.js`:

```
$ git diff
diff --git a/server.js b/server.js
index 17e793f2..a18a50bc 100644
--- a/server.js
+++ b/server.js
@@ -18,6 +18,8 @@ try {
     console.log("You can customize the configuration by copying config.example.js to config.js");
     config = require('./config.example');
 }
+console.log(config.allowSubscriptions);
+
 var websocketPort = config.websocketPort || config.httpPort;
 var useSecureWebsockets = config.useSecureWebsockets || false;
```

`node server` correctly outputs `false`:

```
$ node server
false
loading task scheduler

[2018-10-10T19:29:54.197Z] server available http://[::]:3000
Cryptpad is customizable, see customize.dist/readme.md for details
loading rpc module...
```

However, the buttons "Log in" and "Sign up" (and the corresponding dialogues) are still present in the web UI.

**Comment by ansuz** [comment]
Hi,
subscriptions are different from registrations and login. If you disable subscriptions, then your server doesn't connect to our payment server, or allow your users to purchase upgraded accounts.
There is not currently a way to disable registration and login.

**Comment by casipw** [comment]
Ok, thank you very much for the clarification.
