### ISSUE TITLE
Setting httpSafeOrigin to string in config.js breaks config.js in production

### ISSUE THREAD

**Issue by asdofindia** [xwiki-labs/cryptpad#287]
Setting [httpSafeOrigin as in config.example.js](https://github.com/xwiki-labs/cryptpad/blob/a17235dd7ee69fba7189689bdd6c5725ece61e40/config.example.js#L98) in production leads to /api/config being generated like this:

```javascript
define(function(){
var obj = {
	"requireConf": {
		"waitSeconds": 600,
		"urlArgs": "ver=2.9.0"
	},
	"removeDonateButton": false,
	"allowSubscriptions": true,
	"websocketPath": "/cryptpad_websocket",
	"websocketURL": "ws://cryptpad.example.com:3000/cryptpad_websocket",
	"httpUnsafeOrigin": " https://cryptpad.example.com/"
};
obj.httpSafeOrigin = https://sandbox.example.com;
return obj;
});
```

As the value https://sandbox.example.com is missing quotes, this throws an error in the browser causing the app to stop.

Now, this can be worked around by doing this in config.js

```javascript
httpSafeOrigin: "\"https://sandbox.example.com\"",
```

but that is, maybe, not straightforward. I think there is something that can be done in [this line](https://github.com/xwiki-labs/cryptpad/blob/a17235dd7ee69fba7189689bdd6c5725ece61e40/server.js#L179) to fix this.

Awesome work, cryptpad team! I saw it today for the first time and am absolutely loving it.

**Comment by ansuz** [comment]
Hi,
Thanks for your kind words, and for noticing this issue. You're right about the line which caused the issue, and I've pushed [a fix](https://github.com/xwiki-labs/cryptpad/commit/26540b4b940e61c57b57ad1ac7a5333074b3d263) to our _staging_ branch, which will be merged down to master next Tuesday.
