### ISSUE TITLE
Are local-instance federation or client applications on the roadmap?

### ISSUE THREAD

**Issue by kwill** [xwiki-labs/cryptpad#288]
I am an everyday user who doesn't trust hosted web applications for encryption tasks. Can I run a local instance of Cryptpad, and collaborate with other users also running a local instance?

Briefly, the rationale is that if I decrypt or enter text in my browser, I have no easy way of knowing that hosted JavaScript is not slurping it up an sending it back to the server. I assume this is not possible today, but I wondered if this use-case is on your roadmap? This is a very particular security model, so of course you may not be planning on supporting it.

An alternate solution would be a client application that performs encryption/decryption, and sends the results back to a Cryptpad server. Would this fit your proposed architecture?

**Comment by ansuz** [comment]
Hi,

most of our architecture is compatible with what you want. We run CryptPad.fr using two different servers, one for static assets like js and html, and another for API functionality accessed via websockets. If you run your own instance, you should be able to configure it to direct clients to a remote API server.

There might be a few things that break, but you can try it out by setting `websocketPath: "wss://api.cryptpad.fr/cryptpad_websocket"` in your server configuration file. I would expect some issues related to files and CSP issues, but they might be fine.

Aside from that, in the longer term we are interested in having other client applications. We've also experimented a bit with using browser extensions that validate signed javascript files. Finally, we'd like to eventually implement server to server federation, as noted in the roadmap on our [OpenCollective Page](https://opencollective.com/cryptpad).

**Comment by kwill** [comment]
It sounds like the simplest interface for a cautious everyday user will (eventually) be a desktop app that handles encryption/decryption. (Everyday users probably won't run local instances, and I'm guessing federation from my home laptop will be impossible/harder than a hosted instance.) Thanks for info!

As an aside, I'm curious to hear about extensions validating JS. Do you have an example?

**Comment by ansuz** [comment]
Our `code-integrity` branch features a prototype which works with [this extension](https://github.com/tasn/webext-signed-pages) to validate signatures. There's still considerable work to be done to update our codebase such that signing and validation doesn't impede our development workflow, but it should get merged to master at some point.

**Comment by kwill** [comment]
From the extension:

> This extension solves this by verifying the code really came from the developer. While this doesn't protect you from a malicious developer, it at least brings the security of the web app to a similar level to that of native apps.

Some of my threat models specifically include a malicious developer, so in those cases I guess only an otherwise verified client will do. But for every other case, awesome! It's great to know this is all on the roadmap!

**Comment by ansuz** [comment]
> Some of my threat models specifically include a malicious developer

The same infrastructure could be used to verify signatures from an independent audit, but at some point it becomes necessary to trust _someone_. I suppose for such techniques to be relevant we'd have to identify who the community of CryptPad users would value for such a responsibility.

**Comment by your-friend-alice** [comment]
why was this closed as completed? The `code-integrity` branch wasn't merged, I don't see any info in the documentation about Signed Pages support, from a quick look at the flagship instance i don't see subresource integrity attributes on the script tags.

**Comment by quazar-omega** [comment]
> As of today it's not on our roadmap

Will this be eventually reevaluated in the future? I feel like it would be an important feature
