### ISSUE TITLE
iPad's on-screen keyboard doesn't show up when editing a rich-text pad

### ISSUE THREAD

**Issue by claudehohl** [xwiki-labs/cryptpad#289]
The on-screen keyboard doesn't show up when I try to edit a rich-text pad on Apple's iPad.

Background: One of my clients wants to keep a personal diary on a cryptpad on her iPad; however currently this is only possible with a "code" pad which has limited formatting power for non-technical users. Please, make her happy by having the iPad showing up the keyboard in a rich-text pad.

Thanks and thank you for Cryptpad. Fantastic work!

**Comment by ansuz** [comment]
Unfortunately, nobody on our team has an iPad that we can use to reproduce this issue. I have an android tablet, and I'll try to reproduce, but so far it works on our (android) phones.

The best I can do for now is label this issue as _help wanted_.

**Comment by jcw** [comment]
Unfortunately also, there are several more issues on iPad: I can't seem to paste text in (markdown / code editor), image resize is not working (rich text), some popup dialogs show up incomplete, to name a few. Given iPad's trend towards imore keyboard use, this is bound to affect more people.

Btw, I suspect that anyone with an iPhone can probably reproduce such issues as well.

If there's _serious_ interest to make Safari on iPads work well with CryptPad, I'd be willing to donate a modern iPad Air running iOS 12.4.9 which I have lying around here. While it's not the very latest, it's more than recent enough to test with.

**Comment by mthld** [comment]
Hello,

I can't reproduce any of the issues listed here, does they still occurs to you?

**Comment by mthld** [comment]
I was able to get my hands on an old iOS 8 version device and still wasn't able to reproduce the issue described here. I'll be closing this one for now.

As usual we'll reopen if necessary but no need to keep 3 and half years old issues open. :)
