### ISSUE TITLE
Login Page should have link to Sign up

### ISSUE THREAD

**Issue by asdofindia** [xwiki-labs/cryptpad#291]
I had a friend today go to the login page of my self-hosted cryptpad instance although she doesn't have an account. She was really confused as she didn't know what to do. I asked her to go back to the page she came from and then click signup. But we could just as easily have "Don't have an account? Sign up" under the login form.

**Comment by ansuz** [comment]
The login page featured such a button in a previous version, but it must have been removed during a redesign. I'll see that it gets added back. Thanks for noticing!

**Comment by ansuz** [comment]
Closing this as a link to the registration page was added in our last release (v2.15.0).
