### ISSUE TITLE
Create presentation with Markdown : Only for Geeks ?

### ISSUE THREAD

**Issue by fdiluch** [xwiki-labs/cryptpad#294]
Dears,
Sorry to be a bit direct but in my 20 years experience working for international firms, I have never used "Markdown " to create presentations. 
This "Markdown " is to frighten guys like me. My spontaneous reaction: "oh my goodness, it looks a like a geeks stuff made for geeks"

**Comment by natema** [comment]
I have to admit that I also felt a bit lost when, few minutes ago, I created a _presentation_ on CryptPad.fr for the first time. 
It was not obvious to me how to separate the Markdown text in different slides. 
In fact, I found this issue by searching for "cryptpad presentation" and similar queries. 
It would be good to have a visible button somewhere that points unfamiliar users to [the documentation](https://docs.cryptpad.fr/en/user_guide/apps/slides.html?highlight=presentations).

**Comment by mthld** [comment]
Hello,

We are trialing [a Presentation app based on OnlyOffice](https://www.onlyoffice.com/presentation-editor.aspx), currently limited to subscribers on cryptpad.fr. This is an early-access experimental application for testing purposes. It will soon become available to everyone on cryptpad.fr.

This application would surely be easier to use than the Markdown based one. So don't hesitate to subscribe and try it, for now I'll close this issue. :)
