### ISSUE TITLE
Installation with docker and proxied nginx not working

### ISSUE THREAD

**Issue by lupa18** [xwiki-labs/cryptpad#297]
Hello folks, 
I'm trying to make cp working with a proxied nginx and is not working. It hangs after "create pad" button is pressed: 

![seleccion_746](https://user-images.githubusercontent.com/463429/49182503-37d21380-f339-11e8-8c9c-8a3b3b997f3c.png)

I'm trying to debug but neither cp docker logs nor nginx docker logs show any error. Could you help me ? thanks in advance !

**Comment by sairim** [comment]
If you haven't already, open up your browser's dev tools and check if any error is being printed to the browser console. This may provide more insight into what's going on. Also make sure `logToStdout` and `verbose` are both set to `true` in the app's `config.js` file.

**Comment by lupa18** [comment]
This is console's log: https://bin.disroot.org/?4fdaf3b0a42135d6#34uZDwdQwyJIiyR6+ze9nilnFENUsA9L6NQAB40n5KE=

**Comment by lupa18** [comment]
More: 
```Successfully compiled asm.js code (total compilation time 30ms; storage initialization failed (consider filing a bug))```

**Comment by ansuz** [comment]
Hi, I tried visiting the URL listed in the logs, and making a pad. It seems as though it's a problem with the configuration of the Content Security Policy (CSP) headers. If you visit our matrix/irc channel someone will most likely be able to help you debug the issue.

**Comment by lupa18** [comment]
Thanks @sairim I'm trying and have some doubts: 
1. Why second URL (sandbox) is configures using `frame-scr` var?
1. Why have a root declaration if you are redirecting using proxy to cryptpad:3000 ?

thanks !!

**Comment by sairim** [comment]
to my knowledge, the frame-src var is set to the sandbox url so frames are allowed to be loaded via the sandbox domain, which is required for fundamental functionality of the app + app security, like ckeditor / pad usage.

as for the root var, we stopped using nginx a while back but in our original config (which we used when we were using nginx) the root var was indeed unnecessary (https://github.com/xwiki-labs/cryptpad/wiki/Docker-(with-Nginx-and-Traefik)/c80c3e97c098b8210cb1f313cc9579c4665d6e58#configuring-nginx); as such, this is prob just something that should have been taken out but slipped through. if you try it and it works, feel free to edit the wiki and remove that line (or let me know & i can do it).

**Comment by mcrosson** [comment]
@lupa18 / others

If you're running behind a proxy you'll need to borrow a number of the header option from https://github.com/xwiki-labs/cryptpad/blob/master/docs/example.nginx.conf on the proxy config.

This is my current traefik setup template that keeps the headers happy between traefik and cryptpad: https://git.lollipopcloud.solutions/lollipop-docker/cryptpad/src/branch/master/run.sh

**Comment by lupa18** [comment]
@mcrosson Thanks ! 

Can't see your example, cause network problems... could you paste here ?

**Comment by mcrosson** [comment]
@lupa18 Below is a solid example on how to run cryptpad with Docker behind traefik. I use the below run "script" for one of my production cryptpad instances. The other two cryptpad instance I run inside docker seem to be down presently due to unrelated hiccups. My VPS provider has planned a few migrations and the one VPS needs a hardware bump.

You'll need to fill in the docker repo path as well as the tweak the domains/dns accordingly.

```

docker run -it --name cryptpad \
    --restart unless-stopped \
    -e TZ=UTC \
    -e DEBUG=1 \
    -l traefik.pad_inner.backend=cryptpad \
    -l traefik.sheet_inner.backend=cryptpad \
    -l traefik.sheet_editor.backend=cryptpad \
    -l traefik.main.backend=cryptpad \
    -l traefik.pad_inner.frontend.passHostHeader=true \
    -l traefik.sheet_inner.frontend.passHostHeader=true \
    -l traefik.sheet_editor.frontend.passHostHeader=true \
    -l traefik.main.frontend.passHostHeader=true \
    -l traefik.port=3000 \
    -l traefik.pad_inner.frontend.rule="Host:pad.domain.tld,pad-safe.domain.tld;Path:/pad/inner.html" \
    -l traefik.sheet_inner.frontend.rule="Host:pad.domain.tld,pad-safe.domain.tld;Path:/sheet/inner.html" \
    -l traefik.sheet_editor.frontend.rule="Host:pad.domain.tld,pad-safe.domain.tld;Path:/common/onlyoffice/web-apps/apps/spreadsheeteditor/main/index.html" \
    -l traefik.main.frontend.rule="Host:pad.domain.tld,pad-safe.domain.tld" \
    -l traefik.inner.weight=400 \
    -l traefik.sheet_inner.weight=300 \
    -l traefik.sheet_editor.weight=200 \
    -l traefik.main.weight=100 \
    -l traefik.inner.frontend.headers.customResponseHeaders="$CSP" \
    -l traefik.sheet_inner.frontend.headers.customResponseHeaders="$CSP" \
    -l traefik.sheet_editor.frontend.headers.customResponseHeaders="$CSP" \
    -v /var/cryptpad/data/files:/cryptpad/files \
    -v /var/cryptpad/data/datastore:/cryptpad/datastore \
    -v /var/cryptpad/data/customize:/cryptpad/customize \
    -v /var/cryptpad/data/blob:/cryptpad/blob \
    -v /var/cryptpad/data/blobstage:/cryptpad/blobstage \
    -v /var/cryptpad/data/pins:/cryptpad/pins \
    -v /var/cryptpad/data/tasks:/cryptpad/tasks \
    -v /var/cryptpad/data/block:/cryptpad/block \
    ${DOCKER_REPO}

```

**Comment by mcrosson** [comment]
@lupa18 Below is a solid example on how to run cryptpad with Docker behind traefik. I use the below run "script" for one of my production cryptpad instances. The other two cryptpad instance I run inside docker seem to be down presently due to unrelated hiccups. My VPS provider has planned a few migrations and the one VPS needs a hardware bump.

You'll need to fill in the docker repo path as well as the tweak the domains/dns accordingly. The ```CSP``` variable was pulled from the nginx.conf as well as the main cryptpad config and adapted to work traefik so the header is set properly by the transparent proxy. You'll need to adapt that at a minimum if using nginx or traefik or caddy or similar as a proxy for cryptpad.


```

CSP="Content-Security-Policy:default-src 'none'; child-src https://pad-safe.domain.tld https://pad.domain.tld; worker-src https://pad-safe.domain.tld https://pad.domain.tld; media-src 'self' data: * blob: pad-safe.domain.tld pad.domain.tld; style-src 'self' 'unsafe-eval' 'unsafe-inline' pad-safe.domain.tld pad.domain.tld; script-src 'unsafe-inline' 'unsafe-eval' 'self' pad-safe.domain.tld pad.domain.tld; connect-src 'self' https://pad-safe.domain.tld https://pad.domain.tld wss://pad-safe.domain.tld wss://pad.domain.tld pad-safe.domain.tld pad.domain.tld blob: pad-safe.domain.tld pad.domain.tld; font-src 'self' data: pad-safe.domain.tld pad.domain.tld; img-src 'self' data: * blob: pad-safe.domain.tld pad.domain.tld; frame-src 'self' pad-safe.domain.tld pad.domain.tld blob: pad-safe.domain.tld pad.domain.tld;"

docker run -it --name cryptpad \
    --restart unless-stopped \
    -e TZ=UTC \
    -e DEBUG=1 \
    -l traefik.pad_inner.backend=cryptpad \
    -l traefik.sheet_inner.backend=cryptpad \
    -l traefik.sheet_editor.backend=cryptpad \
    -l traefik.main.backend=cryptpad \
    -l traefik.pad_inner.frontend.passHostHeader=true \
    -l traefik.sheet_inner.frontend.passHostHeader=true \
    -l traefik.sheet_editor.frontend.passHostHeader=true \
    -l traefik.main.frontend.passHostHeader=true \
    -l traefik.port=3000 \
    -l traefik.pad_inner.frontend.rule="Host:pad.domain.tld,pad-safe.domain.tld;Path:/pad/inner.html" \
    -l traefik.sheet_inner.frontend.rule="Host:pad.domain.tld,pad-safe.domain.tld;Path:/sheet/inner.html" \
    -l traefik.sheet_editor.frontend.rule="Host:pad.domain.tld,pad-safe.domain.tld;Path:/common/onlyoffice/web-apps/apps/spreadsheeteditor/main/index.html" \
    -l traefik.main.frontend.rule="Host:pad.domain.tld,pad-safe.domain.tld" \
    -l traefik.inner.weight=400 \
    -l traefik.sheet_inner.weight=300 \
    -l traefik.sheet_editor.weight=200 \
    -l traefik.main.weight=100 \
    -l traefik.inner.frontend.headers.customResponseHeaders="$CSP" \
    -l traefik.sheet_inner.frontend.headers.customResponseHeaders="$CSP" \
    -l traefik.sheet_editor.frontend.headers.customResponseHeaders="$CSP" \
    -v /var/cryptpad/data/files:/cryptpad/files \
    -v /var/cryptpad/data/datastore:/cryptpad/datastore \
    -v /var/cryptpad/data/customize:/cryptpad/customize \
    -v /var/cryptpad/data/blob:/cryptpad/blob \
    -v /var/cryptpad/data/blobstage:/cryptpad/blobstage \
    -v /var/cryptpad/data/pins:/cryptpad/pins \
    -v /var/cryptpad/data/tasks:/cryptpad/tasks \
    -v /var/cryptpad/data/block:/cryptpad/block \
    ${DOCKER_REPO}

```

**Comment by ansuz** [comment]
We've since updated our example.nginx.conf to use variables for the domains used to set CSP. As a result you should only have to change a few lines to get everything correct.

In any case, we're moving docker-related configuration into [this repo](https://github.com/xwiki-labs/cryptpad-docker) so it can be more effectively maintained by the community members that use it. Once the move is complete docker-related issues should be opened there instead.
