### ISSUE TITLE
Reconnection does not work

### ISSUE THREAD

**Issue by elecharny** [xwiki-labs/cryptpad#298]
When I leave my computer alone for a good night sleep, I usually simply close the lid (it's a Mac). In the morning, when I re-open my laptop, all my cryptpad tabs are in a  'reconnection...' state forever. The workaround is simply to reload the page.

**Comment by ansuz** [comment]
We're looking into your issue, but just in case it only happens on a particular browser, may I ask which one you're using?

**Comment by elecharny** [comment]
I have the same problem wit FF and Safari, for the record. I'm using both at, because Cryptpad is working better on Safari (or Chrome) than FF, but FF is still my favorite Browser.

**Comment by ansuz** [comment]
Is this still the case? We've made a number of improvements to ensure connectivity since 2018.

**Comment by polx** [comment]
I haven't seen this in the last month. Tried a few things and had a few connection breaks.
