### ISSUE TITLE
bower install dependency tweetnacl#0.12.2 results in SELF_SIGNED_CERT_IN_CHAIN

### ISSUE THREAD

**Issue by iamdoubz** [xwiki-labs/cryptpad#299]
# My System:
**OS:** Ubuntu 18.04
**NPM:** 3.5.2
**NodeJS:** 8.10.0

# BASH Output:
`user@host:~/cryptpad$ bower install -f
bower jszip#^3.1.5             resolve https://github.com/Stuk/jszip.git#^3.1.5
bower ckeditor#4.7.3           resolve https://github.com/ckeditor/ckeditor-releases.git#4.7.3
bower components-font-awesome#^4.6.3          resolve https://github.com/components/font-awesome.git#^4.6.3
bower json.sortify#~2.1.0                     resolve https://github.com/ThomasR/JSON.sortify.git#~2.1.0
bower codemirror#^5.19.0                      resolve https://github.com/components/codemirror.git#^5.19.0
bower requirejs#2.3.5                         resolve https://github.com/jrburke/requirejs-bower.git#2.3.5
bower hyperjson#~1.4.0                        resolve https://github.com/xwiki-labs/hyperjson.git#~1.4.0
bower marked#0.5.0                            resolve https://github.com/chjj/marked.git#0.5.0
bower secure-fabric.js#secure-v1.7.9          resolve https://github.com/cjdelisle/secure-fabric.js.git#secure-v1.7.9
bower chainpad-crypto#^0.2.0                  resolve https://github.com/xwiki-labs/chainpad-crypto.git#^0.2.0
bower chainpad-listmap#^0.5.0                 resolve https://github.com/xwiki-labs/chainpad-listmap.git#^0.5.0
bower chainpad#^5.1.0                         resolve https://github.com/xwiki-contrib/chainpad.git#^5.1.0
bower rangy#~1.3.0                            resolve https://github.com/timdown/rangy-release.git#~1.3.0
bower jquery#~2.1.3                           resolve https://github.com/jquery/jquery-dist.git#~2.1.3
bower file-saver#1.3.1                        resolve https://github.com/eligrey/FileSaver.js.git#1.3.1
bower alertifyjs#1.0.11                       resolve https://github.com/alertifyjs/alertify.js.git#1.0.11
bower require-css#0.1.10                      resolve https://github.com/guybedford/require-css.git#0.1.10
bower scrypt-async#1.2.0                      resolve https://github.com/dchest/scrypt-async-js.git#1.2.0
bower less#^3.7.1                             resolve https://github.com/less/less.git#^3.7.1
bower bootstrap#^v4.0.0                       resolve https://github.com/twbs/bootstrap.git#^v4.0.0
bower nthen#^0.1.5                            resolve https://github.com/cjdelisle/nthen.git#^0.1.5
bower open-sans-fontface#^1.4.2               resolve https://github.com/FontFaceKit/open-sans.git#^1.4.2
bower html2canvas#^0.4.1                      resolve https://github.com/niklasvh/html2canvas.git#^0.4.1
bower bootstrap-tokenfield#^0.12.1            resolve https://github.com/sliptree/bootstrap-tokenfield.git#^0.12.1
bower diff-dom#2.1.1                          resolve https://github.com/fiduswriter/diffDOM.git#2.1.1
bower localforage#^1.5.2                      resolve https://github.com/mozilla/localForage.git#^1.5.2
bower sortablejs#^1.6.0                       resolve https://github.com/RubaXa/Sortable.git#^1.6.0
bower croppie#^2.5.0                          resolve https://github.com/Foliotek/Croppie.git#^2.5.0
bower saferphore#^0.0.1                       resolve https://github.com/cjdelisle/saferphore.git#^0.0.1
bower jszip#^3.1.5                           download https://github.com/Stuk/jszip/archive/v3.1.5.tar.gz
bower ckeditor#4.7.3                         download https://github.com/ckeditor/ckeditor-releases/archive/4.7.3.tar.gzbower components-font-awesome#^4.6.3         download https://github.com/components/font-awesome/archive/4.7.0.tar.gz
bower json.sortify#~2.1.0                    download https://github.com/ThomasR/JSON.sortify/archive/v2.1.0.tar.gz
bower codemirror#^5.19.0                     download https://github.com/components/codemirror/archive/5.42.0.tar.gz
bower requirejs#2.3.5                        download https://github.com/jrburke/requirejs-bower/archive/2.3.5.tar.gz
bower hyperjson#~1.4.0                       download https://github.com/xwiki-labs/hyperjson/archive/1.4.0.tar.gz
bower json.sortify#~2.1.0                     extract archive.tar.gz
bower jszip#^3.1.5                            extract archive.tar.gz
bower secure-fabric.js#secure-v1.7.9         download https://github.com/cjdelisle/secure-fabric.js/archive/secure-v1.7.9.tar.gz
bower chainpad-crypto#^0.2.0                 download https://github.com/xwiki-labs/chainpad-crypto/archive/0.2.1.tar.gzbower marked#0.5.0                           download https://github.com/chjj/marked/archive/v0.5.0.tar.gz
bower hyperjson#~1.4.0                        extract archive.tar.gz
bower requirejs#2.3.5                         extract archive.tar.gz
bower components-font-awesome#^4.6.3          extract archive.tar.gz
bower chainpad#^5.1.0                        download https://github.com/xwiki-contrib/chainpad/archive/5.1.2.tar.gz
bower chainpad-listmap#^0.5.0                download https://github.com/xwiki-labs/chainpad-listmap/archive/0.5.2.tar.gz
bower rangy#~1.3.0                           download https://github.com/timdown/rangy-release/archive/1.3.0.tar.gz
bower chainpad-crypto#^0.2.0                  extract archive.tar.gz
bower file-saver#1.3.1                       download https://github.com/eligrey/FileSaver.js/archive/1.3.1.tar.gz
bower alertifyjs#1.0.11                      download https://github.com/alertifyjs/alertify.js/archive/v1.0.11.tar.gz
bower scrypt-async#1.2.0                     download https://github.com/dchest/scrypt-async-js/archive/v1.2.0.tar.gz
bower require-css#0.1.10                     download https://github.com/guybedford/require-css/archive/0.1.10.tar.gz
bower chainpad-listmap#^0.5.0                 extract archive.tar.gz
bower less#^3.7.1                            download https://github.com/less/less/archive/v3.9.0.tar.gz
bower marked#0.5.0                            extract archive.tar.gz
bower chainpad#^5.1.0                         extract archive.tar.gz
bower rangy#~1.3.0                            extract archive.tar.gz
bower file-saver#1.3.1                        extract archive.tar.gz
bower nthen#^0.1.5                           download https://github.com/cjdelisle/nthen/archive/0.1.7.tar.gz
bower requirejs#2.3.5                        resolved https://github.com/jrburke/requirejs-bower.git#2.3.5
bower codemirror#^5.19.0                      extract archive.tar.gz
bower jquery#~2.1.3                          download https://github.com/jquery/jquery-dist/archive/2.1.4.tar.gz
bower open-sans-fontface#^1.4.2              download https://github.com/FontFaceKit/open-sans/archive/1.4.2.tar.gz
bower scrypt-async#1.2.0                      extract archive.tar.gz
bower hyperjson#~1.4.0                       resolved https://github.com/xwiki-labs/hyperjson.git#1.4.0
bower bootstrap#^v4.0.0                      download https://github.com/twbs/bootstrap/archive/v4.1.3.tar.gz
bower html2canvas#^0.4.1                     download https://github.com/niklasvh/html2canvas/archive/0.4.1.tar.gz
bower bootstrap-tokenfield#^0.12.1           download https://github.com/sliptree/bootstrap-tokenfield/archive/v0.12.1.tar.gz
bower require-css#0.1.10                      extract archive.tar.gz
bower nthen#^0.1.5                            extract archive.tar.gz
bower diff-dom#2.1.1                         download https://github.com/fiduswriter/diffDOM/archive/v2.1.1.tar.gz
bower localforage#^1.5.2                     download https://github.com/mozilla/localForage/archive/1.7.3.tar.gz
bower chainpad-crypto#^0.2.0                 resolved https://github.com/xwiki-labs/chainpad-crypto.git#0.2.1
bower sortablejs#^1.6.0                      download https://github.com/RubaXa/Sortable/archive/1.6.0.tar.gz
bower less#^3.7.1                             extract archive.tar.gz
bower bootstrap-tokenfield#^0.12.1            extract archive.tar.gz
bower croppie#^2.5.0                         download https://github.com/Foliotek/Croppie/archive/v2.6.2.tar.gz
bower html2canvas#^0.4.1                      extract archive.tar.gz
bower json.sortify#~2.1.0                    resolved https://github.com/ThomasR/JSON.sortify.git#2.1.0
bower saferphore#^0.0.1                      download https://github.com/cjdelisle/saferphore/archive/0.0.1.tar.gz
bower chainpad-listmap#^0.5.0                resolved https://github.com/xwiki-labs/chainpad-listmap.git#0.5.2
bower diff-dom#2.1.1                          extract archive.tar.gz
bower alertifyjs#1.0.11                       extract archive.tar.gz
bower jquery#~2.1.3                           extract archive.tar.gz
bower ckeditor#4.7.3                          extract archive.tar.gz
bower file-saver#1.3.1                       resolved https://github.com/eligrey/FileSaver.js.git#1.3.1
bower nthen#^0.1.5                           resolved https://github.com/cjdelisle/nthen.git#0.1.7
bower rangy#~1.3.0                       invalid-meta for:/tmp/user/bower/2a03342441b84cb1ec59db2e182e0566-1684-mE3ilA/bower.json
bower rangy#~1.3.0                       invalid-meta The "main" field has to contain only 1 file per filetype; found multiple .js files: ["rangy-core.js","rangy-classapplier.js","rangy-highlighter.js","rangy-selectionsaverestore.js","rangy-serializer.js","rangy-textrange.js"]
bower sortablejs#^1.6.0                       extract archive.tar.gz
bower saferphore#^0.0.1                       extract archive.tar.gz
bower localforage#^1.5.2                      extract archive.tar.gz
bower scrypt-async#1.2.0                     resolved https://github.com/dchest/scrypt-async-js.git#1.2.0
bower bootstrap#^v4.0.0                       extract archive.tar.gz
bower rangy#~1.3.0                           resolved https://github.com/timdown/rangy-release.git#1.3.0
bower croppie#^2.5.0                          extract archive.tar.gz
bower saferphore#^0.0.1                      resolved https://github.com/cjdelisle/saferphore.git#0.0.1
bower diff-dom#2.1.1                         mismatch Version declared in the json (2.1.0) is different than the resolved one (2.1.1)
bower diff-dom#2.1.1                         resolved https://github.com/fiduswriter/diffDOM.git#2.1.1
bower chainpad#^5.1.0                        resolved https://github.com/xwiki-contrib/chainpad.git#5.1.2
bower sortablejs#^1.6.0                  invalid-meta for:/tmp/user/bower/f1d4baa153c3b58c7ad2556baf21f37e-1684-pe25MZ/bower.json
bower sortablejs#^1.6.0                  invalid-meta The "name" is recommended to be lowercase, can contain digits, dots, dashes
bower open-sans-fontface#^1.4.2               extract archive.tar.gz
bower bootstrap-tokenfield#^0.12.1           resolved https://github.com/sliptree/bootstrap-tokenfield.git#0.12.1
bower croppie#^2.5.0                     invalid-meta for:/tmp/user/bower/53b32da571c9c217626af038096a6ed8-1684-8mTA7h/bower.json
bower croppie#^2.5.0                     invalid-meta The "name" is recommended to be lowercase, can contain digits, dots, dashes
bower sortablejs#^1.6.0                      resolved https://github.com/RubaXa/Sortable.git#1.6.0
bower require-css#0.1.10                     resolved https://github.com/guybedford/require-css.git#0.1.10
bower components-font-awesome#^4.6.3         resolved https://github.com/components/font-awesome.git#4.7.0
bower croppie#^2.5.0                         resolved https://github.com/Foliotek/Croppie.git#2.6.2
bower html2canvas#^0.4.1                     resolved https://github.com/niklasvh/html2canvas.git#0.4.1
bower alertifyjs#1.0.11                      resolved https://github.com/alertifyjs/alertify.js.git#1.0.11
bower secure-fabric.js#secure-v1.7.9          extract archive.tar.gz
bower localforage#^1.5.2                     resolved https://github.com/mozilla/localForage.git#1.7.3
bower open-sans-fontface#^1.4.2          invalid-meta for:/tmp/user/bower/3b92278b678161ddcf808a1cc9528ed9-1684-4bnBZz/bower.json
bower open-sans-fontface#^1.4.2          invalid-meta The "main" field cannot contain globs (example: "*.js")
bower marked#0.5.0                           resolved https://github.com/chjj/marked.git#0.5.0
bower open-sans-fontface#^1.4.2              resolved https://github.com/FontFaceKit/open-sans.git#1.4.2
bower jszip#^3.1.5                           resolved https://github.com/Stuk/jszip.git#3.1.5
bower jquery#~2.1.3                          resolved https://github.com/jquery/jquery-dist.git#2.1.4
bower secure-fabric.js#secure-v1.7.9     invalid-meta for:/tmp/user/bower/4c69643a2ed038aac1661d95dd6db657-1684-2wMqW2/bower.json
bower secure-fabric.js#secure-v1.7.9     invalid-meta The "main" field cannot contain minified files
bower secure-fabric.js#secure-v1.7.9         resolved https://github.com/cjdelisle/secure-fabric.js.git#secure-v1.7.9
bower bootstrap#^v4.0.0                      resolved https://github.com/twbs/bootstrap.git#4.1.3
bower codemirror#^5.19.0                     resolved https://github.com/components/codemirror.git#5.42.0
bower less#^3.7.1                            resolved https://github.com/less/less.git#3.9.0
bower tweetnacl#0.12.2      SELF_SIGNED_CERT_IN_CHAIN Request to https://registry.bower.io/packages/tweetnacl failed: self signed certificate in certificate chain`

# Solution:
Update npm to latest version. As of the time of this writing, it was 6.4.1 using this command:
`curl -L https://npmjs.org/install.sh | sudo sh`

**Comment by ansuz** [comment]
Hi,
in our [installation guide](https://github.com/xwiki-labs/cryptpad/wiki/Installation-guide#pre-requisites) we recommend using npm. We use version 6.6.0 on our server, so that's our recommended version. If you install node 6.6.0 via nvm it will come packaged with npm 3.10.3, which does not have this certificate issue.

**Comment by ansuz** [comment]
Closing since our installation instructions recommend installing via nvm, which does not have this problem..
