### ISSUE TITLE
anchor

### ISSUE THREAD

**Issue by rustyrzr** [xwiki-labs/cryptpad#306]
Anchor would be useful for shared rtf documents if one could make navigable hyperlinks within document that is actively being edited. 

Any plans for this?

Otherwise I don't see what they are doing, HTML output maybe?

**Comment by ansuz** [comment]
We have discussed adding a table of contents to the rich text pad, based on the headings used in the document.

If we get around to doing that, then we'll probably integrate anchors at the same time, though I don't have a timeline for when this might be added.

**Comment by ansuz** [comment]
Anchors in the rich text editor's table of contents were introduced within the last few releases, but I just noticed this issue now.
