### ISSUE TITLE
Unable to login since Tuesday. Stuck on "Verifying data integrity"

### ISSUE THREAD

**Issue by 3n2pS3P5kG23S96yxRbUHAZajuH2F** [xwiki-labs/cryptpad#310]
Hello Cryptpad Team,

I haven't been able to log in since Tuesday on my PC or mobile. The loading screen hangs on "Verifying data integrity" step. Please advise.

Thank you.

**Comment by ansuz** [comment]
The logs you sent me helped me notice that a change in our feedback API was the cause of the problem.

[This commit](https://github.com/xwiki-labs/cryptpad/commit/6f89156415a9849da826ffb185f87bd328b25e6c) fixes the issue. As long as that was the only problem, you should be able to log in again.

**Comment by 3n2pS3P5kG23S96yxRbUHAZajuH2F** [comment]
> The logs you sent me helped me notice that a change in our feedback API was the cause of the problem.
> 
> [This commit](https://github.com/xwiki-labs/cryptpad/commit/6f89156415a9849da826ffb185f87bd328b25e6c) fixes the issue. As long as that was the only problem, you should be able to log in again.

I am indeed able to log in and access my pads again. Thank you!

**Comment by ansuz** [comment]
Thanks for the report!
