### ISSUE TITLE
Java missing from language dropdown in code pads

### ISSUE THREAD

**Issue by andybalaam** [xwiki-labs/cryptpad#311]
I notice that [CodeMirror supports Java syntax highlighting](https://codemirror.net/mode/clike/index.html) but Java is not shown in the "Language" dropdown in code pads.

Is this deliberate?  If not, please could it be added?

Thank you for a brilliant project!

**Comment by ansuz** [comment]
Hi,

Thanks for the kind words!

We didn't intentionally try to exclude Java. We include the mode that you linked, but it's listed as C-like, and not Java. We could see about creating a _Java_ alias for the _C-like_ mode, so that it's easier to find.

**Comment by andybalaam** [comment]
Hi ansuz, thank you - that is very good news that I can use C-like mode.  An alias would certainly have helped me.

**Comment by ansuz** [comment]
This feature was included in this morning's release: https://github.com/xwiki-labs/cryptpad/releases/tag/2.16.0

**Comment by andybalaam** [comment]
Brilliant, thank you!
