### ISSUE TITLE
Markdown styling

### ISSUE THREAD

**Issue by Frando** [xwiki-labs/cryptpad#313]
Compare 

https://cryptpad.fr/code/#/2/code/edit/L2VeGYjzL2YVqIfpgujF3rD3/

with

https://hackmd.io/C-7Wx2puRmuP-xwl0GeJGQ?both

Readability of the markdown rendering is much better in hackmd. I think some simple CSS tweaks could already do quite some wonders.

**Comment by ansuz** [comment]
We've changed some of the styles in our code and slide editor as of today's release.
