### ISSUE TITLE
More download options?

### ISSUE THREAD

**Issue by makeworld-the-better-one** [xwiki-labs/cryptpad#315]
I was looking at ways to download my Cryptpad files, and noticed there was only HTML as an option. Could more filetypes be added, such as `docx`, `rtf`, `md`, `pdf`, and `odt`? I apologize if this is the wrong place for a feature request.

**Comment by ansuz** [comment]
I'm not sure when we'll have time for this, but we'll see about fitting it into an upcoming release.

**Comment by ansuz** [comment]
Docx has been supported for the last few versions and we've been looking into more options for creating pdfs. Now that our UI supports multiple export types we're in a good position to accept PRs adding support for more document types.

**Comment by makeworld-the-better-one** [comment]
Great, thanks!
