### ISSUE TITLE
cryptpad running on non-root URL

### ISSUE THREAD

**Issue by ineiti** [xwiki-labs/cryptpad#319]
Hi there,

I'm trying to run cryptpad on something like `https://my-url.com/cryptpad`. So far all my tests are in vain. If I use https://github.com/xwiki-labs/cryptpad/wiki/Apache and configure cryptpad to use the `/` path, it works fine. But if I try to use another than the `/` path, the page refuses to load.

I also tried to edit the file `data/customize/config.js`, but this didn't help, neither.

**Comment by ansuz** [comment]
CryptPad doesn't currently support this due to the way our requirejs dependencies are structured. We plan to refactor these dependencies in the future, at which point we'll support your use case, but we don't have a definite timeline for delivery.

**Comment by ansuz** [comment]
It's unlikely that we'll ever implement this because CryptPad relies on domain-based sandboxing rules to ensure some of its security guarantees and running another app in the same scope would compromise those features.
