### ISSUE TITLE
Nested Bullets in Markdown

### ISSUE THREAD

**Issue by inkstain** [xwiki-labs/cryptpad#324]
Issues with nested bullets losing proper indentation level in preview, though fine in code window. Examples as follows

```
+ Parent 1
  + Child 1
  + Child 2 <-- will appear further indented, as a child of child 1
  + Child 3 <-- will appear as a sibling of child 2
```

Likewise if indentation is staggered

```
+ Parent 1
	+ Child 1
  	+ Grandchild 1
	+ Child 2 <-- this does not work as shown if one backspaces twice, but does work if one backspaces 4 times and tabs once
  + Child 3 <-- but merely hitting Enter takes us to the right 
```
  
  
Even if you copy and paste from example 1, preview is foobared

**Comment by ansuz** [comment]
I suspect it's related to the use of tabs instead of spaces, but I'd like to confirm. Can you link to a pad which demonstrates the problem?

**Comment by inkstain** [comment]
sure, please find here...

https://cryptpad.fr/code/#/2/code/edit/gp+mXKcMSlYhlZoys2fGpGuH/

**Comment by ansuz** [comment]
Yes, it seems to be a matter of mixing tabs and spaces for indentation.

If you go to the settings page, you should find a tab on the left sidebar for _Code_ which will allow you to change the settings for editor indentation (tabs vs spaces, number of spaces). If you set this to use spaces, but you still find tabs inserted, then that's definitely a bug. It's possible this was introduced via a recent update to CodeMirror, but we'll have to review the changes to know.

Beyond that, we can see about forcing two-space tabs in markdown mode, though there might be situations in which users really want to use tabs, and that might cause problems for them.

**Comment by inkstain** [comment]
okay thanks, a couple more additional observations

Originally settings were set for 2 space indentation with tab indentation
deselected

I later tried checkmarking tab indentation,

Either way there were inconsistencies when using the tab key, it would
indent in code view properly but often not in preview. When that happens,
if you left arrow through the indentations, there is a mix of tabs or
spaces.

If I strictly used the space key to indent (keeping to two space per indent
but strictly using the space key) it all works fine.

thanks again
