### ISSUE TITLE
Messenger pad

### ISSUE THREAD

**Issue by fdiluch** [xwiki-labs/cryptpad#327]
New feature request.
Since cryptpad is end to end encrypted,
why not create a new type of pad that would be use for messenging, like whatsapp.
I would be like the Chat of the text pad but without the text pad

**Comment by ansuz** [comment]
Like this: https://cryptpad.fr/contacts/  ?

**Comment by ansuz** [comment]
Currently we only handle one on one chats between friends, but the workflow to add friends requires that both users be online in the same pad at the same time. We plan to make an invitation workflow which would work for users that aren't yet registered, as well as a dedicated group chat app, but we have to build a few more components before we can see about integrating them into that functionality.

**Comment by fdiluch** [comment]
https://cryptpad.fr/contacts/
Well. it does not work.
It is a webpage but i cannot do anything on it. ie: How do you create contact ?

**Comment by mthld** [comment]
Hi,

You actually need to add contacts, please see the official documentation: https://docs.cryptpad.fr/en/user_guide/collaboration.html#contacts

Also, as we don't plan to match WhatsApp features, I'll be closing this issue now. There is plenty of very well made encrypted messaging app out here already. :)
