### ISSUE TITLE
Collaborate without User-Account when file is password-protected

### ISSUE THREAD

**Issue by jsaalfeld** [xwiki-labs/cryptpad#330]
I mainly use cryptpad to edit one file on multiple systems I own, but recently I wanted to share a spreadsheet to coordinate an order of T-Shirts.

I created a Spreadsheet document, gave it a password and shared the edit-link in one communication way and the password on another communication way.

Unfortunately most people hit me up, that they had to create a user on the system. For most users, that just want to quickly enter something or collaborate for a "one-time" occasion this is a unnecessary hassle and resulted in using an etherpad again.

It would be nice if users without a user account can edit a document and give themselves an ad-hoc-name, if they have access to a password protected document. So users don't have to share information about themselves or have to register yet to another service they maybe never use again.

**Comment by ansuz** [comment]
This is fixed in our staging branch and will be included in the next release.

**Comment by ansuz** [comment]
This has since been merged to our master branch and included in version 3.10.0.
