### ISSUE TITLE
Cannot download file on mobile device

### ISSUE THREAD

**Issue by fdiluch** [xwiki-labs/cryptpad#331]
I have opened a session of cryptpad on my mobile phone (android)
I could not download a pdf file.
When I use the option :"Exporter ce pad vers un fichier local"
I have the error message "Failed to download"

**Comment by ansuz** [comment]
I've tested this on a number of mobile browsers and I haven't been able to reproduce the issue. Are you still having this problem or can we close this issue?

**Comment by ansuz** [comment]
If the problem persists could you please include the brand and version of the mobile browser in question and list any extensions you may have installed?
