### ISSUE TITLE
Updating cryptpad

### ISSUE THREAD

**Issue by ineiti** [xwiki-labs/cryptpad#336]
I run a cryptpad 2.16.0 and would like to udpate to the latest cryptpad. This is what I did in the `cryptpad` directory, which is a clone of `github.com/xwiki-labs/cryptpad`:

```
git pull
docker build -t xwiki/cryptpad .
docker-compose up
```

Everything seems to run correctly, but if I connect to the server, I only get a white screen. If I do

```
git checkout 2.16.0
docker build -t xwiki/cryptpad
docker-compose up
```

it works again as before. But also checking out `2.17.0` doesn't work. I searched around for some instructions how to correctly update, but couldn't find them. Any hints?

**Comment by ansuz** [comment]
We don't actually use docker to manage CryptPad, though we merge PRs that make it easier for people who do.

Maybe @mcrosson, @coldfix, @kpcyrd or @felixboehm can point you in the right direction.

**Comment by mcrosson** [comment]
@ineiti Can you try the following in your git directory

```
git pull
git checkout 2.18.0
docker buil d-t xwiki/cryptpad
docker-compose up
```

That should get the latest code from github, checkout the 2.18.0 release and then build.

There were also updates to the nginx config which you'll need. There is an example config in the docs folder you can use to reconcile the differences.

**Comment by mcrosson** [comment]
Also: the white screen can sometimes happen if you're on a slower device (like a phone) when you're logged in an viewing the main page of CryptPad.

It may take a minute to finish checking it you're logged in and then re-directed to your drive. It's improved a bit over time but I have seen delays, especially with Virtual Machines low on RAM as well as some phones.

**Comment by ineiti** [comment]
Same result - I only get a white screen, as before. I test it on my desktop, so I don't think it's because of a slower device.

Just in case somebody else wants to try it, the docker build command is:

```
docker build -t xwiki/cryptpad .
```

**Comment by ineiti** [comment]
OK - played around, and now I found what is needed:

```
rm -rf data/customize
```

I could even keep my `config.js`. Which made it play nice after the update while keeping all the data. I didn't dig exactly _which_ file is too different, but the following (outside of `config.js`) is the diff between the 2.16 and 2.18 version. So I guess some of the files in `customize` should not be in there...

```
diff -Naur data/customize/credential.js data.orig/customize/credential.js
--- data/customize/credential.js	2019-03-18 08:56:17.898569568 +0100
+++ data.orig/customize/credential.js	2019-02-07 17:30:16.081050405 +0100
@@ -61,13 +61,7 @@
             }
 
             // grab an unused slice of the entropy
-            // Note: Internet Explorer doesn't support .slice on Uint8Array
-            var A;
-            if (bytes.slice) {
-                A = bytes.slice(entropy.used, entropy.used + n);
-            } else {
-                A = bytes.subarray(entropy.used, entropy.used + n);
-            }
+            var A = bytes.slice(entropy.used, entropy.used + n);
 
             // account for the bytes you used so you don't reuse bytes
             entropy.used += n;
diff -Naur data/customize/login.js data.orig/customize/login.js
--- data/customize/login.js	2019-03-18 08:56:17.906569848 +0100
+++ data.orig/customize/login.js	2019-02-07 17:30:16.089050666 +0100
@@ -113,8 +113,7 @@
     };
 
     var isProxyEmpty = function (proxy) {
-        var l = Object.keys(proxy).length;
-        return l === 0 || (l === 2 && proxy._events && proxy.on);
+        return Object.keys(proxy).length === 0;
     };
 
     var setMergeAnonDrive = function () {
diff -Naur data/customize/messages.js data.orig/customize/messages.js
--- data/customize/messages.js	2019-03-18 08:56:17.906569848 +0100
+++ data.orig/customize/messages.js	2019-02-07 17:30:16.089050666 +0100
@@ -25,22 +25,6 @@
 };
 var language = getLanguage();
 
-// Translations files were migrated from requirejs modules to json.
-// To avoid asking every administrator to update their customized translation files,
-// we use a requirejs map to redirect the old path to the new one and to use the
-// requirejs json plugin
-var reqPaths = {
-    "/common/translations/messages.js":"json!/common/translations/messages.json"
-};
-Object.keys(map).forEach(function (k) {
-    reqPaths["/common/translations/messages."+k+".js"] = "json!/common/translations/messages."+k+".json";
-});
-require.config({
-    map: {
-        "*": reqPaths
-    }
-});
-
 var req = ['/common/common-util.js', '/customize/translations/messages.js'];
 if (language && map[language]) { req.push('/customize/translations/messages.' + language + '.js'); }
 
diff -Naur data/customize/pages.js data.orig/customize/pages.js
--- data/customize/pages.js	2019-03-18 08:56:17.906569848 +0100
+++ data.orig/customize/pages.js	2019-02-07 17:30:16.089050666 +0100
@@ -91,7 +91,7 @@
                     ])
                 ])
             ]),
-            h('div.cp-version-footer', "CryptPad v2.18.0 (Sloth)")
+            h('div.cp-version-footer', "CryptPad v2.16.0 (Quokka)")
         ]);
     };
 
diff -Naur data/customize/src/less2/include/markdown.less data.orig/customize/src/less2/include/markdown.less
--- data/customize/src/less2/include/markdown.less	2019-03-18 08:56:17.906569848 +0100
+++ data.orig/customize/src/less2/include/markdown.less	2019-02-07 17:30:16.093050798 +0100
@@ -1,7 +1,6 @@
 .markdown_main() {
     blockquote {
         background: #e5e5e5;
-        background: rgba(128,128,128,0.5);
         padding: 10px;
         border-left: 3px solid #999;
         padding-right: 0;
@@ -9,41 +8,6 @@
         blockquote { margin: 0; }
     }
     // todo ul, ol
-    // TOC
-    div.cp-md-toc {
-        background: #f3f3f3;
-        padding: 20px;
-        //float: right;
-        margin: 5px;
-        margin-right: 0;
-        max-width: 100%;
-        min-width: 200px;
-        white-space: nowrap;
-
-        & > p {
-            &.cp-md-toc-1 {
-                margin-left: 0;
-            }
-            &.cp-md-toc-2 {
-                margin-left: 25px;
-            }
-            &.cp-md-toc-3 {
-                margin-left: 50px;
-            }
-            &.cp-md-toc-4 {
-                margin-left: 75px;
-            }
-            &.cp-md-toc-5 {
-                margin-left: 100px;
-            }
-            &.cp-md-toc-6 {
-                margin-left: 125px;
-            }
-            margin: 0;
-            overflow-x: hidden;
-            text-overflow: ellipsis;
-        }
-    }
 }
 
 .markdown_preformatted-code (@color: #333) {
```

**Comment by ansuz** [comment]
I think I see the problem...

[This line in container-start.sh](https://github.com/xwiki-labs/cryptpad/blob/master/container-start.sh#L6) copies `customize.dist` to `customize` recursively. This seems like it is most likely _wrong_.

We serve assets from `customize` _if they are available_ and otherwise serve the default asset from `customize.dist`. Basically this means that any changes that we make in `customize.dist` will be ignored by docker installations, which is very likely to break your instance.

**Comment by ansuz** [comment]
And the same issue might be related to #339

**Comment by ansuz** [comment]
As far as I can tell, dropping that recursive copy will prevent this from happening to other docker installations in the future. If you didn't actually customize anything in the copied folder, then you can safely delete its contents and then I'd expect things to work again.

If you did customize parts of your instance, then it's basically up to you to ensure that the changes remain compatible with updates, though we try to ensure backwards compatibility as much as possible.

**Comment by ineiti** [comment]
OK, makes sense. I tried it out, leaving only `config.js` in my `customize` directory, and, lo and behold, it works!

I created a PR here: #344

**Comment by ineiti** [comment]
Fixed by @ansuz in https://github.com/xwiki-labs/cryptpad/commit/4ff7683f2342c19d39f8e1d212f62c01e2905e58
