### ISSUE TITLE
Tag 2.18.0

### ISSUE THREAD

**Issue by a1268512** [xwiki-labs/cryptpad#338]
Hi, 
when i try to checkout to the new tag 2.18.0 i get this : 

```
Note: checking out '2.18.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at dcabff7c Merge branch 'soon'

```
can someone check it out ? 
tks

**Comment by ansuz** [comment]
Hi,
That's git's default message when you check out a tag. It's not telling you something's wrong, just that you are no longer _on a branch_, so you'll need to create a branch from there if you want to commit any changes you make.

**Comment by a1268512** [comment]
tks for the answer but when i do the same with 2.17.0 i get this : 
```
git checkout 2.17.0 
Previous HEAD position was dcabff7c Merge branch 'soon'
HEAD is now at 07c942de drop unnecessary keys from french translation
```
thst's what i find weird

**Comment by ansuz** [comment]
You only get the warning when you first detach. This isn't a problem with CryptPad, just normal git behaviour.

[This link](https://www.git-tower.com/learn/git/faq/detached-head-when-checkout-commit) might help you understand what's happening.
