### ISSUE TITLE
Browser stalls on initialization of new pad - 2.18.0

### ISSUE THREAD

**Issue by nicolass67** [xwiki-labs/cryptpad#339]
Hello, 

I'm encouring a little problem with cryptpad (CP) 2.18.0. My setup worked with a 2.15 version.
The problem appears with a "bare-metal" install or with the docker image. 

The home page of CP  displays , and I can access to the FAQ, features or other html pages. 
But when I click to create a pad (whatever the type) , the initialization page appears but stays so forever. 

I use an apache reverse-proxy in front of CP. Here is the config (stripped the non relevant infos) : 
... 
```
# https://github.com/xwiki-labs/cryptpad/wiki/Apache
ProxyPreserveHost On
ProxyRequests Off
ProxyPass / http://localhost:3000/
ProxyPassReverse / http://localhost:3000/
RewriteEngine On
RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC]
RewriteCond %{HTTP:CONNECTION} Upgrade$ [NC]
RewriteRule .* ws://127.0.0.1:3000%{REQUEST_URI} [P]
```

Cache is disabled , apache proxy_wstunnel is enabled and working 
This setup worked for 2.15.0 of CP. 

The logs in debug dont show errors or whatever. Maybe a clue is this : 
` mod_proxy_fcgi.c(916): [client XX.XX.XX.XX:60772] AH01077: declining URL http://localhost:3000/bower_components/ckeditor/plugins/tableselection/styles/tableselection.css, referer: https://XXXXX/pad/ckeditor-inner.html?ver=2.18.0-1552552142642`

I also tried this workaround, without success : https://github.com/xwiki-labs/cryptpad/issues/216 

Any idea of what can have changed and explain this ?

**Comment by ansuz** [comment]
Most of CryptPad's errors are found in the browser console, not the server's logs. Can you check for errors there?

**Comment by nicolass67** [comment]
Hi ansuz, 

From what I see in the Chrome developper tools the last lines are : 

icons.png?t=H8DC | 200 | png | Other | 9.3 KB | 28 ms
-- | -- | -- | -- | -- | --
tableselection.css | 200 | stylesheet | ckeditor-inner.html?ver=2.18.0-1552552142642

It stalls after ... and there is nothing else that 200 http code ...

**Comment by ansuz** [comment]
is that the network tab or the console tab? The console should show errors if something went wrong.

**Comment by nicolass67** [comment]
This was on the network tab , attached the console tab errors 

![err1](https://user-images.githubusercontent.com/34300716/54432272-03883480-4729-11e9-8892-6435e3007f42.jpg)

**Comment by nicolass67** [comment]
Hello, 

I made some other tests. And it seems there is a workaround. 

To run the docker simply run the docker with the docker container with 3000 and 3001 port mapper : 

`docker run --name pad -r **-p 3001:3001 -p 3000:3000** -v ..... 
`
But what is strange is that you have to do this even when the httpSafePort 3001 is commented (https://github.com/xwiki-labs/cryptpad/issues/216 ) 
Something maybe still tries to speak to the 3001 port ? 

Regards,

**Comment by nicolass67** [comment]
Hello, 

I just pull the 2.19.0, build the docker image , and used it. The problem seems fixed. 
You can now use or not the httpSafePort 3001 with Docker (enabled or not when needed). 

Thanks for responsiveness !

**Comment by ansuz** [comment]
I wasn't sure the new fixes would address your issue, but I'm glad the problem went away. Cheers!

**Comment by nicolass67** [comment]
Due maybe to #349 , the problem again appears. 
Here is what the developper console shows 
![Capture](https://user-images.githubusercontent.com/34300716/55057323-2855a380-5069-11e9-99f1-9edd29d05189.JPG)
