### ISSUE TITLE
Spreadsheet on Mac

### ISSUE THREAD

**Issue by ineiti** [xwiki-labs/cryptpad#341]
When I'm using the Spreadsheet on a mac, every time I press the `Mac` key, the menu pops up. So it is impossible to copy/paste. And how is somebody supposed to live without that? ;)

**Comment by ansuz** [comment]
What browser and keyboard layout are you using?

I can't reproduce on Safari, Firefox, or Chromium on a Macbook running High Sierra with and EN-US keyboard layout.
