### ISSUE TITLE
Option to swap the axis of poll tables

### ISSUE THREAD

**Issue by false-mirror** [xwiki-labs/cryptpad#342]
Having the ability to have 'options' as columns and 'responses' as rows would be really appreciated. I think polls would be more intuitive in some contexts, particularly for event scheduling. 

I think many people are comfortable with reading dates left to right (like a weekly calendar), and it is uncommon to see names listed in columns due to their length. Additionally, this would let people adjust more easily from other popular sites such as Doodle.

**Comment by ansuz** [comment]
As of today's 4.7.0 release the poll app is deprecated in favour of the new _form_ app which includes polls similar to what we already offered as just one of many types of questions the users can answer. It is possible to swap axes with the click of a button.
