### ISSUE TITLE
Spreadsheet won't load

### ISSUE THREAD

**Issue by derekwolters** [xwiki-labs/cryptpad#343]
When trying to load a spreadsheet I have been using in Chrome and Firefox, it stalls on the "Loading spreadsheet" screen. This is after the percentage goes to 50%.

**Comment by derekwolters** [comment]
![image](https://user-images.githubusercontent.com/19533239/54572278-0733e980-49bd-11e9-9cd5-dad9d8aea7ad.png)

**Comment by ansuz** [comment]
I believe this issue has since been fixed.
