### ISSUE TITLE
Add support for markdown mermaid

### ISSUE THREAD

**Issue by p4u** [xwiki-labs/cryptpad#345]
Mermaid is a great tool for creating quick diagrams using MarkDown https://mermaidjs.github.io/

Would be very useful to integrate it into the MarkDown Code cryptpad

**Comment by ansuz** [comment]
Do you have an example of a common syntax for using mermaid inside of a markdown document? I see that they list HackMD as a supported platform, but I couldn't figure out how to embed a diagram after reading their documentation (briefly).

**Comment by ansuz** [comment]
Ahh, I found it elsewhere. `mermaid` code blocks

**Comment by ansuz** [comment]
[This pad](https://cryptpad.fr/code/#/2/code/view/KWzHP98j-fQbIo5atNhCzE7FGddXtteGdCiEB8-9NSo/) shows a basic graph made with mermaid.
