### ISSUE TITLE
delete-inactive.js fails at deleting directories

### ISSUE THREAD

**Issue by billux** [xwiki-labs/cryptpad#355]
Hi,

I set up a cron job as specified [here](https://github.com/xwiki-labs/cryptpad/wiki/Docker#maintenance) to delete inactive pads.

Sometimes the script `delete-inactive.js` fails with this error:

```
$ node delete-inactive.js
Error: EISDIR: illegal operation on a directory, unlink './blob/FMB/FMBX7G0hXjQS5S4RJQ6PGmqqZqbu8LET9kENzXOb0i4=' ./blob/FMB/FMBX7G0hXjQS5S4RJQ6PGmqqZqbu8LET9kENzXOb0i4=
[…]
```

`blob/FMB/FMBX7G0hXjQS5S4RJQ6PGmqqZqbu8LET9kENzXOb0i4=` exists and is indeed a directory.

Should this script be able to delete directories as well as files?

**Comment by ansuz** [comment]
We're planning to drop the requirement for the cronjob by launching this script as a child process of the main server. This will probably be done within the next two releases, so we'll spend some time making sure this is working well.

It does look like a bug, but I haven't looked at this code in some time, and I'll need to review it before commenting in more depth.

**Comment by ansuz** [comment]
I've removed `delete-inactive.js` entirely. It is replaced by `evict-inactive.js`, which first deletes blobs and channels which have been in your `archivePath` for more than `ArchiveRetentionTime` days (as specified by your config.js). After removing old archived data it moves inactive data (not read in the last `inactiveTime` days into the archive.
