### ISSUE TITLE
image paste hangs

### ISSUE THREAD

**Issue by c-amow** [xwiki-labs/cryptpad#359]
from my linux mint 19 / cinnamon and tried on chrome and firefox
copying an image from a screenshot app and pasting into cryptpad looks like it is going to work but hangs indefinitely

![image](https://user-images.githubusercontent.com/42422529/56495110-3c4ec280-64ba-11e9-8557-3da97924123d.png)
nothing else is reponsive within the app/document, but it looks like you could still do things in the browser outside the document, like chat

**Comment by ansuz** [comment]
It looks like you're trying to upload into the spreadsheet editor. We expect to have support for this eventually, but it's still currently in beta.

**Comment by heyarne** [comment]
For me (in a pad) this doesn't work at all. The only feedback I get when trying to paste an image from clipboard is in the console: "Direct image paste is not allowed." Is this intentional? Would be nice if that worked.

**Comment by Atilir** [comment]
Hi, I have the same problem with my instance in v3.23.2 (and on yours too in v3.24.0)

When I copy paste an image, an error message appears : 

![image](https://user-images.githubusercontent.com/36844376/101031258-d7a28780-3579-11eb-9b98-274ecf1aab07.png)

**Comment by ansuz** [comment]
Image paste in spreadsheets no longer hangs the sheet as per the original subject of this issue.
