### ISSUE TITLE
Use of phrase "zero knowledge"

### ISSUE THREAD

**Issue by phiresky** [xwiki-labs/cryptpad#36]
Zero knowledge is commonly used to refer to a method of *proving* knowledge of secret information without revealing it. (https://en.wikipedia.org/wiki/Zero-knowledge, https://www.google.com/#q=zero+knowledge)

I am not seeing how this relates to a collaborative document editor, are you just using the phrase incorrectly? Please elaborate how/why you are using zero-knowledge proofs in this software.

**Comment by cjdelisle** [comment]
It looks like you're thinking of *zero-knowledge proofs* and actually cryptpad is a *zero knowledge cloud service*. But I can understand your confusion.

If you would like to learn more about zero knowledge cloud services, you can look at these links:
* https://en.wikipedia.org/wiki/Comparison_of_online_backup_services#endnote_2
* https://spideroak.com/features/zero-knowledge
* https://www.sync.com/help/what-is-zero-knowledge-cloud-storage/
* https://www.pcloud.com/encrypted-cloud-storage.html
* https://www.google.com/search?q=zero+knowledge+cloud+service

Thanks for your interest in cryptpad.

**Comment by phiresky** [comment]
Interesting. I had not seen that phrase used with this meaning. Thank you for elaborating.
