### ISSUE TITLE
Tried uploading .docx and .odt files but I can't edit them (only download them)

### ISSUE THREAD

**Issue by philiprhoades** [xwiki-labs/cryptpad#360]
People,

I am getting heavily involved in a "saving-the-world" organisation and someone suggested CryptPad for our docs (instead of GD) so I set up an account to check it out but I can't edit uploaded docs - the interface is so simple I can't see that I am doing anything wrong - what am I missing?

I will be a very enthusiastic contributor to the project if I can get started and be convinced it fulfils our needs . . I watched Caleb James' YT presentation and it looks really interesting!

Thanks,
Phil.

**Comment by ansuz** [comment]
Hi,

Our spreadsheet editor integrates a modified version of [OnlyOffice](https://www.onlyoffice.com/). OnlyOffice provides a method of converting docx and odt files to its internal format, but that conversion is performed by the server. Since the server would need to be able to read your documents to convert them, we haven't included this functionality in our integration.

In the future we'd like to either find a way to perform that conversion in the user's browser, or provide a desktop app which could perform some of the work traditionally done by the server. For now, though, our (BETA) spreadsheet editor can only edit sheets created within our platform. We plan to offer support for full word-like documents as well, but it is not yet in our roadmap.

**Comment by philiprhoades** [comment]
OK, so ATM and so I am clear, multi-user WP within CryptPad is not possible?
If that is the case, for the time being we could still make use of CP but only to display non-editable docs to persons the doc has been shared to?
Ideally it would be good if CP also had GD-like facilities for adding comments etc.

**Comment by ansuz** [comment]
> OK, so ATM and so I am clear, multi-user WP within CryptPad is not possible?

We don't offer the ability to edit odt or docx, alone or in groups. We plan to offer it in the future.

> If that is the case, for the time being we could still make use of CP but only to display non-editable docs to persons the doc has been shared to?

We offer real-time _rich text pads_, but those are not quite as rich as full word-like docs. Uploaded files (like your docx and odt) are static, and cannot be modified in place. Successive versions of the file would need different titles to be distinguished. You could use a shared folder for a central directory, and we won't know what you're storing, but I appreciate that this is not an ideal workflow.

>  Ideally it would be good if CP also had GD-like facilities for adding comments etc.

I believe this is covered by two issues: #248 and #143

Again, it's planned for the future but we're a small team, so I'm not sure when we'll get to these features.

**Comment by philiprhoades** [comment]
Right, OK, that's clear I think - so the immediate next question is: "How to create a rich-text file" - which should be adequate for our immediate needs - with folder "Documents" highlighted, when I click on:

  New->Rich Text

. . nothing happens . . no new window or dialog request for a file name etc . .

**Comment by philiprhoades** [comment]
OK - nothing happens from the "New" option but it works from the 3x3 icon . .

**Comment by ansuz** [comment]
> . . nothing happens . . no new window or dialog request for a file name etc . .

It should open the editor in a new tab. It's quite likely that your browser is blocking the new tab from being opened. There might be a dialog near the top of the page where the browser will indicate if it blocked a new tab from being opened.

I tried on Firefox and saw this: 

![Screenshot from 2019-04-23 14-42-59](https://user-images.githubusercontent.com/1264398/56581852-2fbf8c80-65d6-11e9-8817-e40f820015c3.png)

Chromium worked without any popups.

Can you tell me what browser (and version) you're using?

**Comment by philiprhoades** [comment]
Ah . . that is probably it - I almost certainly blocking popups . . 

Fedora Chrome: Version 70.0.3538.102 (Official Build) (64-bit)

**Comment by ansuz** [comment]
I just checked Chrome v72 on a macbook, and it seems ok. I can try other versions on a few linux distros too, but if you have extensions it would be helpful to know which.

**Comment by philiprhoades** [comment]
Just checked - popups unblocked - works now . . but I might have to turn them on / off as approp . .

Thanks!  Now that is going I can test some stuff out with my colleagues but Rich Text looks fine for what we want and I will contribute where I can in future.

Could you save your server data on the SAFE Network (once it goes live) for further security?

**Comment by ansuz** [comment]
> Thanks! Now that is going I can test some stuff out with my colleagues but Rich Text looks fine for what we want and I will contribute where I can in future.

Great!

> Could you save your server data on the SAFE Network (once it goes live) for further security?

I'm not sure what kind of threats you're hoping to protect against, but we have no plans to integrate SAFE's storage APIs into the server. It's probably possible, though.

**Comment by sasharubin** [comment]
So, the only way of importing google docs to cryptpad is to process each document one by one, copy the document to the clipboard, open a new rich text file in cryptpad, and paste. Is that right?

**Comment by ansuz** [comment]
@sasharubin that's correct.

**Comment by SeanPedersen** [comment]
Any update on importing .docx files into CryptPads rich text format? I would guess if it is possible to copy and paste files individually an automation of the workflow should be possible? Asking because I am coming from Google Drive as well, copy and paste works quite good but uploading .docx and converting them automatically would be ideal (since Google Drive allows to download its docs as .docx files).

**Comment by sasharubin** [comment]
Hey Sean,

I stopped using CryptPads a while ago so I don't have an update.

Sasha

**Comment by SirAxolot** [comment]
Helllo, I know that it wasn't that long since the last comment, but I'd like to know the status of importing .ODFs? It's the main barrier to me being able to complete my degoogled workflow, and other than that it seems perfectly complete.

**Comment by ansuz** [comment]
We've introduced support for OnlyOffice's text and presentation editors on an early access basis. More info is available in [this blog post](https://blog.cryptpad.org/2021/10/21/Announcing-new-apps/).
