### ISSUE TITLE
Test exercise - changing password - old and new passwords fail now . .

### ISSUE THREAD

**Issue by philiprhoades** [xwiki-labs/cryptpad#362]
People,

As part of my testing exercise as part of a potential move from GD to CP, I created two shared dirs and one file in one of the dirs.  I then changed the old 99 char account passwd to a new 99 char passwd but LastPass had an issue and now neither passwed works - does this mean the account is now inaccessible?

Thanks,
Phil.

**Comment by ansuz** [comment]
If you're logged out and don't have the password to log back in, then yes, the account is effectively lost.

**Comment by philiprhoades** [comment]
Hmm . . strange . . since I couldn't log back in, I accessed the pad for the file - I still had the passwd for the protected dir it was in and I was asked if I wanted to save the file in my own account instead of being an anonymous user and I said yes.  Once that happened, my original account with the proper user name came back and with the newly accessed file in the original dir but the file was called "Rich text . . " and even after opening it and renaming it to something meaningful, in the dir it is still called "Rich text . .".

So a couple of odd things that happened . . 

At this stage, I would probably make use of CP for single anonymous docs that have a "Use By Date" but need securing until then and continue to take an interest in the development and help where I can.

Thanks!

**Comment by ansuz** [comment]
Cheers!
