### ISSUE TITLE
Cannot Access Admin Page

### ISSUE THREAD

**Issue by hum6ug** [xwiki-labs/cryptpad#363]
Hello,

I was trying to access the admin page on my selfhosted v2.20.0 cryptpad but it always displays "Only administrators can access this page".

I have added my key to the adminKeys like this:

```
    adminKeys: [
        "https://EXMAPLE.ORG/user/#/1/TESTUSER/h-PUBLICKEYSTRING="
        //"https://my.awesome.website/user/#/1/cryptpad-user1/YZgXQxKR0Rcb6r6CmxHPdAGLVludrAF2lEnkbx1vVOo=",
    ],
```

The string is working with customlimits but not with the admin site.

Can you tell me what I am doing wrong?

**Comment by ansuz** [comment]
It looks correct.

Have you restarted your server? The keys are only loaded at startup, so that would do it.

You could try checking https://yourdomain.tld/api/config for the `adminKeys` array. If that's not present that would explain the problem.

**Comment by hum6ug** [comment]
Okay thanks. 

I can see my Public Signing Key but instead of "h-" it says "h/" at the beginning. Is this normal?

And also this part is missung "https://EXMAPLE.ORG/user/#/1/TESTUSER/"

**Comment by ansuz** [comment]
That's all normal. We strip off the first part because the username doesn't need to be public information, just the public key. The slash is replaced by a dash when presented in URLs, but what you see in `/api/config` is the natural representation.

Can you check your browser console to see if there are any errors?

**Comment by hum6ug** [comment]
I just did a clean and fresh install on a different host. Same outcome. As far as I can see there are no errors in the browser console.

**Comment by hum6ug** [comment]
Okay don't ask me why. But I checked again today and it just worked :D Maybe somesort of Cache Problem.

**Comment by ansuz** [comment]
Great!

**Comment by heartbleeded** [comment]
Having exacly the same problem. It the reason is because of cache, is there any way to flush it?

**Comment by ansuz** [comment]
restarting your server with `npm run fresh` will export a new cache-busting string at the `/api/config` endpoint. This value is used to bust the cache for all pages loaded thereafter.

Once you're able to access the admin page there is an option to flush the cache without restarting the server.
