### ISSUE TITLE
Browser stalls on initializing new pad 2.21.0

### ISSUE THREAD

**Issue by cyphunk** [xwiki-labs/cryptpad#366]
I've installed 2.21.0 via docker and attempting to connect to it's 3001 using a localhost appears to fail. The result is the browser window hangs. This is identical to the last report (console log) found here:

https://github.com/xwiki-labs/cryptpad/issues/339

or see:

attempting port 3001:

![Screenshot from 2019-05-08 18-17-29](https://user-images.githubusercontent.com/119662/57391005-d9e60980-71bd-11e9-9722-414b3fa1d8d7.png)

Note that the following settings appear to make no difference to the debug output:

```
logToStdout: true,
logLevel: 'silly',
verbose: true
```

If there are suggestions for what I could do to further investigate and gather more information please let me know.

Oh, also the /asserts/ passes with 40 of 40 tests passing.

**Comment by cyphunk** [comment]
Now attempting with vanilla docker image from cryptpad. Get similar issues:
![image](https://user-images.githubusercontent.com/119662/57394844-d73be200-71c6-11e9-9ca7-4b2ee69ef7a1.png)

**Comment by cyphunk** [comment]
I was able to use the official Dockerfile on a local workstation and access that instance via http://localhost:3000/pad without problem. So I am closing this issue. I will continue to try and resolve the issue I am having on a different host and setup via docker and update this thread if anything useful comes of the effort

**Comment by omar-polo** [comment]
Can we re-open this one? I can confirm the issue.

I'm trying to run an instance of cryptopad in our lan, so I've installed it on a OpenBSD 6.5 server that we have. It's running behind relayd (for ssl and vdoms.)

I've found out that 2.9.0 works perfectly. 2.10.0 hangs when creating a pad (but no error on the console) and 2.15.0-2.21.0 hangs with the exact same error in @cyphunk screenshot. I don't have tried other version.

----

relevant info:
 - node version: `v10.15.0`
 - npm version: `6.4.1`
 - config.js: the only changes from the example are the port and the `_domain`
 - relayd config (note that I don't have much experince with relayd, so the following config may be improved. It's good enough to run gitea and a custom web server without issues tho)
```
table <pad>   { 127.0.0.1 }
# [snip]

http protocol "httpsrelay" {
        # forward request to the right service based on the Host header

        match header set "X-Forwarded-For" \
                value "$REMOTE_ADDR"
        match header set "X-Forwarded-By" \
                value "$SERVER_ADDR:$SERVER_PORT"
        match header set "Keep-Alive" value "$TIMEOUT"

        match query hash "sessid"

        # [snip]
        match request quick header "Host" value "pad.example.com" \
                forward to <pad>

        tcp  { nodelay, socket buffer 65536 }
        http { websockets, headerlen 131072 }

        tls ca key "/etc/ssl/private/ca.key" password ""
        tls ca cert "/etc/ssl/ca.crt"
}

relay "proxy" {
        listen on 0.0.0.0 port 443 tls

        protocol "httpsrelay"

        # forwarding is enabled for the specified services
        forward to <pad>   port 3000
        # [snip]
}
```
