### ISSUE TITLE
Maintenance: check-account-deletion.js missing ed argument

### ISSUE THREAD

**Issue by cyphunk** [xwiki-labs/cryptpad#370]
According the Docker maintenance wiki one should run this script without arguments:

``docker exec cryptpad --workdir /cryptpad/scripts node check-account-deletion.js``

This gives the error ``Missing ed argument``. How should this be resolved?

Also notice the documentation does not say to declare the workdir which is required as well.

**Comment by cyphunk** [comment]
I'd note it appears the other scripts ``expire-channels`` and ``delete-inactive`` also fail when run from workdirectory scripts:

```
+ docker exec --workdir /cryptpad/scripts --user cryptpad:cryptpad cryptpad node expire-channels.js
/cryptpad/storage/file.js:427
throw err;
^
Error: EACCES: permission denied, mkdir '/cryptpad/scripts/data'
at Error (native)
+ docker exec --workdir /cryptpad/scripts --user cryptpad:cryptpad cryptpad node delete-inactive.js
/cryptpad/scripts/pinneddata.js:46
if (err) { throw err; }
^
Error: ENOENT: no such file or directory, scandir './datastore/'
at Error (native)
```

**Comment by ansuz** [comment]
We don't use docker so I'm not sure how to approach this problem.

**Comment by mcrosson** [comment]
@cyphunk This looks like a permissions error and missing datastore dir. You likely want to set your work dir to /cryptpad instead of /cryptpad/scripts

**Comment by ansuz** [comment]
I'm going to start routinely closing very old docker related issues. I'll welcome PRs which correct the problem, but since our development team doesn't use docker this issue is likely to go unfixed forever unless someone else steps up.

**Comment by francoisjacquet** [comment]
Same `Missing ed argument` error here, but not using Docker:
```
cryptpad$ node scripts/check-account-deletion.js
```
