### ISSUE TITLE
Spreadsheet Title bar (cp-toolbar-top) missing

### ISSUE THREAD

**Issue by cyphunk** [xwiki-labs/cryptpad#376]
The top toolbar which shows and permits editing of the file name will show up only initially when opening a spreadsheet (cp-toolbar-top). This makes editing the name difficult.

To resolve I attempted to edit the file name in the drive list. This edits only the file name in the drive list. When opening the file, during the moment when the toolbar is not hidden, one can see that the file name set in the drive list has not affected the name shown in the toolbar (which still shows the default filename/title)

**Comment by ansuz** [comment]
Hi,
regarding the title bar: what browser and OS are you using? Could you provide a screenshot of what you see? We weren't able to reproduce the issue.

As to the issue of renaming from the drive, that's standard behaviour in CryptPad to allow for users to create personal names for documents regardless of whether they have the permission to change a document's title for other users.
