### ISSUE TITLE
Safari won't "calculate" password after login?

### ISSUE THREAD

**Issue by OliverPifferi** [xwiki-labs/cryptpad#379]
Hey there,

when trying to log in under my own instance on macOS with Safari Version 12.1.1 (14607.2.6.1.1), the "calculating" of the password lasts forever. This effect does not appear when using the actual Firefox so I was wondering if this is anything Safari-related?

![Bildschirmfoto 2019-05-26 um 08 55 02](https://user-images.githubusercontent.com/42076599/58378437-21c5a880-7f94-11e9-9787-e85672b0f23f.jpg)

No further plugins in Safari are being used, so this should not be the problem.

Any hints on that one?

Thanks for any help and the great project!

Oliver

**Comment by ansuz** [comment]
We have a macbook that we use for testing but it's running _Safari 11.1.1_. I couldn't reproduce, so it could be that it's related to a new feature. If I figure out how to update to a later version I'll try again.

**Comment by olliware** [comment]
Alright, thanks for the fast reply. Maybe it's just another security-related issue with the latest Safari-build. Works great with Firefox and even Microsoft Edge Version 76.0.161.0 (Official build) Dev (64-bit).

**Comment by SLiebald** [comment]
I experience the same issue with chrome Version 75.0.3770.100 (64-bit) and Firefox 67.0.4 (64-bit) on Ubuntu 18.04.

**Comment by miracee** [comment]
I experience the same issue using Safari 13.0.5. It works fine up to last week. But since yesterday it won't be able to generate password anymore. Even when I try to create a new account it will hang on hashing password ...

**Comment by ansuz** [comment]
are there any errors in the browser console?

**Comment by miracee** [comment]
Hello,

> Am 12.02.2020 um 15:19 schrieb ansuz <notifications@github.com>:
> 
> are there any errors in the browser console?
> 
> 

No. It worked last week, it worked today between 16:00 and 18:00 but yesterday evening, today morning / noon and today evening it won’t work. Looks like sometimes it works, sometimes it won’t work. I couldn’t figure out yet what was different.

**Comment by ansuz** [comment]
Closing this as we haven't received any reports in some time. Please re-open this issue if the problem persists.

**Comment by OliverPifferi** [comment]
After more than two years I implemented my Cryptpad once again, building it from the scratch - and discovered the same problem once again in v.4.12.1 running at Ubuntu 20.04 and NGINX.

The issue is definitely Safari-based while Edge, Chrome, Firefox and Brave work without any problem and log in shortly after "calculating" the password. The checkup finds no issues (21/21 checks successfully) at all and everything works fine besides my main browser ;) !

I know this issue is quite old but is still focuses on Safari, even with cross-site tracking disabled - both on macOS Monterey and the latest iOS 15-iteration.

Any ideas how this can be solved?

Thanks in advance and best regards,

Oliver

![Bildschirmfoto 2021-11-28 um 19 03 53](https://user-images.githubusercontent.com/42076599/143780794-0f2c69a4-615e-49a3-bfbc-b0bb229f50d3.png)
![Bildschirmfoto 2021-11-28 um 19 03 59](https://user-images.githubusercontent.com/42076599/143780795-91aeacaa-c455-4833-8ae5-4dd1002db1c5.png)
![Bildschirmfoto 2021-11-28 um 19 05 11](https://user-images.githubusercontent.com/42076599/143780796-112a92e8-9fb2-4c9a-9dab-af3adfede953.png)
m
