### ISSUE TITLE
Sheets: Inserting and Deleting Rows and Columns

### ISSUE THREAD

**Issue by philiprhoades** [xwiki-labs/cryptpad#381]
People,

Unless I am suffering from Domestic Blindness again . . these operations do not seem possible?

There are tedious work-arounds but could someone please confirm or enlighten me?

Thanks,
Phil.

**Comment by ansuz** [comment]
There are  buttons for this with contextual behaviour depending on whether you've selected a cell, a row, or a column:

![Screenshot from 2019-06-03 18-04-25](https://user-images.githubusercontent.com/1264398/58816712-55ef3800-862a-11e9-8d9e-0f45cb539f48.png)


![Screenshot from 2019-06-03 18-04-39](https://user-images.githubusercontent.com/1264398/58816708-5556a180-862a-11e9-94fe-dcb6d8125b66.png)

![Screenshot from 2019-06-03 18-04-30](https://user-images.githubusercontent.com/1264398/58816709-5556a180-862a-11e9-90b6-aefa29d40db9.png)

**Comment by philiprhoades** [comment]
@ansuz ,

Ah! . .thanks for that!  I was sort of expecting green and red lines and column buttons and didn't notice the pull-down menus on the delete and insert cells buttons . .
