### ISSUE TITLE
Colors for folders like in google drive

### ISSUE THREAD

**Issue by fdiluch** [xwiki-labs/cryptpad#383]
Hello,
Could you implement the possibility to select a color for the folders ?
(like in google drive)

**Comment by ansuz** [comment]
I don't have a firm timeline on when to expect this, but it doesn't seem very hard so we'll probably do it whenever we have a bit of free time.

**Comment by ansuz** [comment]
Right-clicking on a folder in your CryptDrive will now provide the option to set a color:

![Screenshot from 2019-06-21 16-56-56](https://user-images.githubusercontent.com/1264398/59931612-a8f82600-9445-11e9-96dc-f5a2f8d05b25.png)
