### ISSUE TITLE
Docker images for arm

### ISSUE THREAD

**Issue by cinemast** [xwiki-labs/cryptpad#385]
Hi!

Thanks for providing cryptpad. Could you please release docker images for `arm` and `arm64`?

**Comment by ansuz** [comment]
We don't use docker ourselves, so this would have to come from the community. I know @mcrosson uses docker on arm, so they could probably comment.

**Comment by mcrosson** [comment]
The Lollipop Cloud project I work with runs regular docker image builds of Cryptpad for arm.

There is a web based browser for the registry at https://docker.lollipopcloud.solutions/ 

The cryptpad build info is at https://docker.lollipopcloud.solutions/repo/arm%2Fcryptpad/tags

```docker pul registry.lollipopcloud.solutions/arm/cryptpad:[arch]-latest``` should get you going with the builds. (Swap the [arch] piece for arm32v7 or arm64v8)

**Comment by dddddddavid** [comment]
> The Lollipop Cloud project I work with runs regular docker image builds of Cryptpad for arm.
> 
> There is a web based browser for the registry at https://docker.lollipopcloud.solutions/
> 
> The cryptpad build info is at https://docker.lollipopcloud.solutions/repo/arm%2Fcryptpad/tags
> 
> `docker pul registry.lollipopcloud.solutions/arm/cryptpad:[arch]-latest` should get you going with the builds. (Swap the [arch] piece for arm32v7 or arm64v8)

Do you have a sample compose file for this? I absolutely cannot get it to work.

**Comment by mcrosson** [comment]
> Do you have a sample compose file for this? I absolutely cannot get it to work.

The build script (uses the main Dockerfile from cryptpad repos) and ```run.sh``` should be handy for getting it going.

**Comment by ansuz** [comment]
I'm closing this issue here and leaving a reference to it from the [community-maintained docker repo](https://github.com/xwiki-labs/cryptpad-docker) that we're setting up.
