### ISSUE TITLE
Sheet: Pasting only works from internal data

### ISSUE THREAD

**Issue by ExpandingFoam** [xwiki-labs/cryptpad#386]
Hello, 

I am using Sheet (Beta) with Brave (Version 0.61.52 Chromium: 73.0.3683.86 (Official Build) (64-bit)) on Mac OS Mojave.  Copy/paste is behaving strangely. 

If I type some text into a cell, "TEXT IN CELL", and I right click on the cell, select "copy", then go to another window/application (eg TextEdit), and use "paste",  it pastes "TEXT IN CELL". This is expected. 

Then in TextEdit I type "TEXT IN TEXTEDIT", select it, copy it, and return to Sheet. Right-click to paste (using command keys is a bit off [as described by this person](https://github.com/xwiki-labs/cryptpad/issues/341)) and what lands is "TEXT IN CELL". 

If instead of selecting the cell I right-click and paste into the bar at the top (not sure the name, the one with ƒx beside it), it pastes "TEXT IN TEXTEDIT". This is expected. 

I can't paste more than one cell at a time that way, and also formatting etc are not preserved. 

Earlier today, it worked fine in the same sheet. I copy/pasted directly from Google Sheets with no problem. Everything came along: content, formatting and formula. 

Now I have tried with google sheets (running in Chrome), Text Edit (native Mac OS) and webmail (in Brave). Same situation! 

Hope that's a clear description. It's very simple to see but difficult to describe. Let me know if there's more info or other troubleshooting etc.

**Comment by mthld** [comment]
Hello,

Copy/pasting from outside the spreadsheets is meant to be done with keyboard shortcuts. When you try to do it a pop-up explain this to you.

![Screenshot 2022-08-05 at 15 34 54](https://user-images.githubusercontent.com/41020854/183088447-79fe07ad-2fe3-42f4-917b-8dddad290539.jpg)

As this issue is mostly outdated, I'm closing it now. :)
