### ISSUE TITLE
shared spreadsheets can only be accessed by signing up

### ISSUE THREAD

**Issue by uxmld** [xwiki-labs/cryptpad#390]
I wanted to make a collaborative spreasheet, but when I shared the link people let me know they could oly access the document by creating an account which can be impractical. ACcess without an account seems to work fine in rich text documents, is cryptpad planning to do that for spreadsheets too? That'd be super helpful :)

**Comment by spacekookie** [comment]
Really wish this was resolved. Makes it hard to use spreadsheets with others

**Comment by vasilevich** [comment]
I think spreadsheet is one of the most important features a cloud solution can have,
I mean look at google docs, one of the most used solutions is the spreadsheet, used to share lists etc.

**Comment by bristow** [comment]
It would be very useful in order to stop using Google Docs (not GPDR compatible)

**Comment by ansuz** [comment]
This is fixed on our staging branch and will be included in our next release.

**Comment by ansuz** [comment]
This has since been merged to our master branch and included in version 3.10.0.
