### ISSUE TITLE
Read only link of a spreadsheet is not opening

### ISSUE THREAD

**Issue by neagee** [xwiki-labs/cryptpad#391]
Hi,
We have a self hosted instance of cryptpad, version 2.23, and if i share a link for a spreadsheet with the read-only option, when i open this link in another browser with another user logged in, the document never opens.
The "Loading spreadsheet"spin wheel is displayed.
In the console i get those errors: (78 times)
```
Error
    at decryptStr (crypto.js?ver=2.23.0:18)
```
which is 
```
    var decryptStr = function (str, key) {
        var arr = str.split('|');
        if (arr.length !== 2) { throw new Error(); }
```
And i checked, indeed, some of the decoded strings do not have a column | character in them

When the document is opened in read-write mode, there is no problem of this kind.

Could you check what is going on?

**Comment by ansuz** [comment]
We've merged a fix to our master branch and deployed on CryptPad.fr
