### ISSUE TITLE
Verifying data integrity

### ISSUE THREAD

**Issue by tripletwo** [xwiki-labs/cryptpad#394]
I'm having the same issue as #310, but given the thread requested a private chat elsewhere, I cannot access a solution. 

My access to Cryptpad was normal this afternoon but then when I reloaded a page it got stuck loading with the message in the picture/title.

I tried 3 different browsers and cleared all cache, but nothing can seem to get past this screen.
![Screen Shot 2019-06-23 at 8 31 27 pm](https://user-images.githubusercontent.com/51003087/59974987-2ebad380-95f6-11e9-89b1-f42d14ab6c86.png)

**Comment by tripletwo** [comment]
Also, this happens on my Android once I've attempted to sign in to my account. Perhaps an account problem, not a device problem.

**Comment by ansuz** [comment]
We believe that we've fixed this on [cryptpad.fr](https://cryptpad.fr). Could you confirm that you're able to log in again?

**Comment by tripletwo** [comment]
@ansuz I had to create a new account. Every time I tried with my original account it would get stuck. I didn't have any important data on there so starting fresh was not a huge drama, but I do get concerned it will happen again and I'm doing uni work on here. My new account seems to be working fine at the moment.

**Comment by ansuz** [comment]
> Every time I tried with my original account it would get stuck.

Did you try this morning or before yesterday afternoon (France time)?

As long as you still have your username and password the data there should be recoverable, but if not we can't know what the exact problem was or if it was fixed.

**Comment by ansuz** [comment]
Closing as we haven't received any updates.
