### ISSUE TITLE
Revoke Access once link has been shared?

### ISSUE THREAD

**Issue by storyjesse** [xwiki-labs/cryptpad#397]
Perhaps I just haven't seen how, but it does not appear possible to revoke access to a document once the link to it has been shared. This seems like a very large security issue to me.
At very least there should be a way to reset the link so that old links will no longer work.

Allowing multiple links would be a great feature addition. It was mentioned in issue [#372](https://github.com/xwiki-labs/cryptpad/issues/372) that it might be possible to display individual user's a unique URL in their browser. Perhaps this could be used to allow document owners to get a list of the people/browsers that have accessed the document.

For example:

- Share Link 1 oHfyuOrMAIRHlhEIGrud1kNnc2kM0p [Read-Only]
  - User A access ID: Qwi9mypQ7u7i   (include a space for owner to write notes about this user)
  - User B access ID: pP8SIccMAbxr    (include a space for owner to write notes about this user)
- Share Link 2 ~~NP5KR290dHoCrVV0bOHbXoa5ROm2uC [Read-Only]~~ [REVOKED]
  - ~~User C access ID: vTIBBE3IrxWQ   (include a space for owner to write notes about this user)~~
- Share Link 3 ruqj3lsBuQa0sSCeu46ynyyyNMG6Bt [Read-Only]
  - User D access ID: PX78KIsYXg2y   (include a space for owner to write notes about this user)
- Share Link 4 K0PPy6yiBryjTPrzRBBDrZhYh0SAO0 [Read/Write]
  - User E access ID: A1tQE6k3OeWv   [Read/Write] (include a space for owner to write notes about this user)

User A & B are in a team and were given the same share link, User C's link has been revoked and they no longer have access. User D's link is different to User A & B and could be changed to Read/Write without affecting user A & B. User E's link is Read/Write but could be changed to Read-Only at any time.

Logged in users should have their own links different to the shared links generated and these would then be invisible to the user (ie. you wouldn't see them, you'd just see the user's profile image not the link)

**Comment by ansuz** [comment]
We're planning to work on revocation in the next few months.

Unfortunately it's a bit harder than changing the link since anyone who had access to the link would necessarily have access to the encryption keys as well. Revoking access in a meaningful way means creating a copy of the document encrypted with new keys and delivering those keys to the clients who should have access, then deleting the original.

Just changing the links would be more efficient and might be enough for most use cases, so we might do that as well, but we'd like to handle the most severe case first.

**Comment by storyjesse** [comment]
Ahh! Yes that makes sense. I like your forward thinking. <Thumbs Up!>

**Comment by mtheek** [comment]
Hi guys,

I have 2 questions:
I have a client that needs to work on a spreadsheet as a team.
This means various users need access to the same speadsheet, however, only these users should have access. 

At the moment, if I share a link to a document, everyone with that link can access it.

Question 1:
Can you more or less say by when you will have the option to revoke access to a shared link online?

Question 2:
Are there plans to allow access only to specific users? If so, can you already say by when these would be online?

Thanks and regards!

**Comment by ansuz** [comment]
Hi @mtheek,

In most of our apps there are two workarounds you can use to emulate revocation

**Comment by ansuz** [comment]
Hi @mtheek,

In most of our apps there are two workarounds you can use to emulate revocation:

* if the document is password-protected, change the password. The link will stay the same, but anyone currently viewing it will see that it has been deleted. If they reload they will be prompted to enter a new password. Entering the updated password will open the document with its re-encrypted content.
  * (this doesn't work in our _beta_ spreadsheets editor yet)
* export the content to a file, make a new pad/sheet, upload the original content, delete the original from the server, and send the new link to whoever should have access

Either workaround only works if you created the document as _owned_ and each requires some manual intervention.

Regarding your two questions:

1. We are nearing the completion of our _CryptPad teams_ research project (sponsored by NLnet foundation). We plan to submit another grant proposal for a follow-up project which would include better revocation, among other things. If all goes well we'd start that by late 2019 or early 2020


2. As a part of our _teams_ project we implemented _editable metadata for documents. Previously you needed to create a pad with all the settings it could possibly need (owners, expiration time, etc). Our thinking is to include the public keys of editors in an _allow list_ in the metadata. If an allow list were specified, the server would require that clients prove their cryptographic identity to access the content. Removing a key from the allow list would basically accomplish revocation. We could also share the private component of a random key-pair along with a link, making specifically-crafted links revocable on an individual basis.

As noted in my earlier response, this kind of revocation is an easy way to limit the risk of data leaking but there's no real way to take back encryption keys once leaked.

**Comment by ansuz** [comment]
We've implemented the ability to restrict access to a document via a server-side allow list. It will be included in our next release, planned for March 10th, 2020.

**Comment by ansuz** [comment]
This new functionality is described in the release notes for [CryptPad 3.13.0](https://github.com/xwiki-labs/cryptpad/releases/tag/3.13.0).
