### ISSUE TITLE
Add Table of Content to Rich Text

### ISSUE THREAD

**Issue by SebastianSolidwork** [xwiki-labs/cryptpad#399]
I'd like to add TOCs to my Rich Text documents.

There are existing plugins for CKEditor. I'm not familiar which one is a good one.
https://ckeditor.com/cke4/addon/toc
https://ckeditor.com/cke4/addon/contents
Could at least the devs install such plugins for the CKEditor?

**Comment by frlen123** [comment]
Forgive my ignorance, but can plugins be added to Cryptpads? This would be awesome, and might also solve this issue, since it'd only take one to install the plugin

**Comment by SebastianSolidwork** [comment]
I guess not for users. As Cryptpad uses CKEditor for rich text, this is my suggestion for the devs.
I hope that this comparable easy to integrate than to develope it from scratch.

**Comment by SebastianSolidwork** [comment]
My hope is that at least the devs can install plugins, but I don't know for sure. Cryptpad uses CKEditor for rich text documents.
I hope that installing a plugin is comparable easy to integrate than to develope the feature from scratch.

**Comment by ansuz** [comment]
We've enabled CKEditor plugins in the past, but it's not always a simple matter. CKEditor4 wasn't designed to be real-time and so the plugins can cause serious bugs when used in the context of CryptPad.

If you're hosting your own instance, you can test out the inclusion of any particular plugin by adding it to your instance's [ckeditor config](https://github.com/xwiki-labs/cryptpad/blob/master/customize.dist/ckeditor-config.js). Assuming you're satisfied with its UI and it doesn't cause problems when used in a collaborative session, we could see about testing it on our side and then moving towards making it a standard part of CryptPad's configuration.

**Comment by sharethewisdom** [comment]
:pray: :crossed_fingers: :+1: please add this feature to cryptpad.fr

I'm actively promoting cryptpad in Belgian schools, and a  table of contents feature is often expected. I don't manage a server myself, but I'll ask http://coderdojobelgium.be to host an instance.

**Comment by ansuz** [comment]
We added this functionality several releases ago, but I forgot to close this issue.
