### ISSUE TITLE
What should I fill into config.js

### ISSUE THREAD

**Issue by vinhqdang** [xwiki-labs/cryptpad#4]
Hello again,

For config.js file, and for testing purpose only, what should I fill into this file?

I have MongoDB in my system already

**Comment by ansuz** [comment]
Cryptpad now uses leveldb by default.

The first time you run your server it will try to load a database from the location specified in the config file. If a database does not exist at that location (on the filesystem) it will be created.

Comments in the config file should be explain the meaning of each variable fairly well.
