### ISSUE TITLE
Integrating into Atom text editor?

### ISSUE THREAD

**Issue by aconite33** [xwiki-labs/cryptpad#40]
Thoughts on integrating a plugin for Atom text editor? They have something [similar](https://github.com/Fankserver/atom-firepad), using collaborative tools like [Firepad](https://github.com/firebase/firepad). The bad thing is that it goes through the Firebase proxy to share the contents. Would be great if you could use something like cryptpad, with a powerful text editor like Atom, but share locally and encrypted. E.g., if you're the same network, you can share the url with your buddy, and then you can point to point share the data/collaborate over encrypted channels.

**Comment by ansuz** [comment]
Our server is fairly lightweight, so it's probably possible to spin up an httpd/websocket server that could manage this.

Cryptpad uses two kinds of encryption:

1. TLS, for getting to the server and back
2. symmetric key encryption for encrypting messages before they're transmitted and stored in the database

You could probably do without the TLS, and avoid the trouble of issuing a certificate (I don't use https while developing locally).

In our current model, one of the peers would have to play the role of _history keeper_, hosting the server, relaying to multiple users, and keeping a log of the recent messages.

Personally, I don't use atom (I'm a vim kind of guy), and so I'm not familiar with whether these requirements are possible within an atom plugin.

We don't have a very strong reason to write this kind of plugin, but I do think it's probably possible.

If you join our irc channel on freenode (`#cryptpad`), we should be able to help you navigate the architecture we use.

**Comment by ansuz** [comment]
I'm going to go ahead and close this issue as I have not received any interest from anyone else in contributing to its development.
