### ISSUE TITLE
Right-aligning left-aligned lists and tables doesn't work

### ISSUE THREAD

**Issue by GPery** [xwiki-labs/cryptpad#401]
If a list or table is already left-aligned, you can't change it to be right-aligned without re-creating it.

**Comment by mthld** [comment]
Hello @GPery,

If you're trying to do that on a Rich Text document it's indeed possible. You need to right click the table, access "Properties":

https://user-images.githubusercontent.com/41020854/185351752-75b2c4fa-829c-477c-83ac-7f989a6115c8.mov

Does it fit your use case?

**Comment by GPery** [comment]
> Does it fit your use case?  

I'm not sure since it was three years ago, but it looks great!
