### ISSUE TITLE
Right-to-left support

### ISSUE THREAD

**Issue by GPery** [xwiki-labs/cryptpad#402]
Right-to-left text, such as Arabic and Hebrew, aren't currently supported.
This can be seen, for example, when typing with an RTL script and appending a colon (for example: العَرَبِيَّة‎: ).
I'm not an expert on the subject, but I think w3 has some relevant resources, something like https://www.w3.org/International/questions/qa-bidi-unicode-controls

**Comment by polychromia** [comment]
RTL functionality is a very important internationalization feature. CryptPad should definitely support it.

**Comment by ahangarha** [comment]
I have a practical solution. and this is how it is working:

![image](https://user-images.githubusercontent.com/11241315/74191907-2214e980-4c72-11ea-9563-400a2a561cdd.png)

It only uses `dir="auto"` and little css tweak. So actually it doesn't need explicit functionality to specify a given text is RTL or LTR. It detect the direction based on the first character of paragraph or list.

Should I send PR?

**Comment by ansuz** [comment]
Please do!

**Comment by ahangarha** [comment]
Assign it to me. I will do it ASAP

**Comment by hopebeckary** [comment]
I still need help getting removed from this list; was originally signed up
by one of my children using an email that is now being aliased to my email
after a domain hosting migration.

Please help.

I don't have enough info to successfully unsubscribe

Pete Beckary
pete@beckary.com
littleismuch.com
petebeckary.com
beckary.com
717.468.1866

**Comment by ansuz** [comment]
@ahangarha any progress?

**Comment by ahangarha** [comment]
I have worked a bit. I got busy with other works and I postponed working on this project.

**Comment by ahangarha** [comment]
I cannot run the project. this is the result of running `npm run dev`:

```
> cryptpad@3.10.0 dev /home/XYZ/myProg/cryptpad
> DEV=1 node server.js

DEV MODE ENABLED
events.js:287
      throw er; // Unhandled 'error' event
      ^

Error: listen EAFNOSUPPORT: address family not supported :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1296:21)
    at listenInCluster (net.js:1361:12)
    at doListen (net.js:1500:7)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1340:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EAFNOSUPPORT',
  errno: 'EAFNOSUPPORT',
  syscall: 'listen',
  address: '::',
  port: 3000
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cryptpad@3.10.0 dev: `DEV=1 node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cryptpad@3.10.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/XYZ/.npm/_logs/2020-04-11T16_09_35_763Z-debug.log
```

This is also the log content:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'dev' ]
2 info using npm@6.14.4
3 info using node@v12.16.2
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle cryptpad@3.10.0~predev: cryptpad@3.10.0
6 info lifecycle cryptpad@3.10.0~dev: cryptpad@3.10.0
7 verbose lifecycle cryptpad@3.10.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle cryptpad@3.10.0~dev: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/XYZ/myProg/cryptpad/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/XYZ/bin/
9 verbose lifecycle cryptpad@3.10.0~dev: CWD: /home/XYZ/myProg/cryptpad
10 silly lifecycle cryptpad@3.10.0~dev: Args: [ '-c', 'DEV=1 node server.js' ]
11 silly lifecycle cryptpad@3.10.0~dev: Returned: code: 1  signal: null
12 info lifecycle cryptpad@3.10.0~dev: Failed to exec dev script
13 verbose stack Error: cryptpad@3.10.0 dev: `DEV=1 node server.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:310:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:310:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid cryptpad@3.10.0
15 verbose cwd /home/XYZ/myProg/cryptpad
16 verbose Linux 5.3.0-46-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
18 verbose node v12.16.2
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error cryptpad@3.10.0 dev: `DEV=1 node server.js`
22 error Exit status 1
23 error Failed at the cryptpad@3.10.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by ansuz** [comment]
It looks like your host environment environment doesn't support IPv6. Changing the [_httpAddress_ value in your config file](https://github.com/xwiki-labs/cryptpad/blob/master/config/config.example.js#L75) from `'::'` to `'0.0.0.0'` should cause the server to have the server listen on all IPv4 addresses instead of all IPv6.

**Comment by ahangarha** [comment]
Yes. It solved the issue.

It might be good to keep this tip in documentation. no?

**Comment by ansuz** [comment]
I haven't seen that kind of error in years and I thought modern hosts all supported IPv6. Now that I know it's still a problem I agree that it could be in the docs. May I ask what OS you're running?

**Comment by ahangarha** [comment]
Actually because I have had issue with my networks, I have disabled IPv6 on my laptop right from boot and by passing arguments to kernel.

Just informing you that I could open homepage and also register. but none of the apps in the projects work! Only blank page appears if I open drive, pad, sheet,...

**Comment by ahangarha** [comment]
Since I cannot run CryptPad locally, I share what I wanted to do:
 - all `p` tags should get html attribute of `dir="auto"`.
 - in case of lists:
    - the `ul` and `ol` should get `dir="auto"` attribute.
    - the `li` should get CSS style of `unicode-bidi: plaintext;`

The result would be as such:
![image](https://user-images.githubusercontent.com/11241315/80471132-36ef4800-8958-11ea-9da2-30195d9ee2f2.png)

You may also remove me as assignee.

**Comment by ehsanix** [comment]
Hi!
Is there anyway to update the Sheets as well to support the Farsi/Arabic characters properly connected to each other?

This is the current situation of characters in a sheet:
 ![image](https://user-images.githubusercontent.com/5164351/88084226-6216bb80-cb84-11ea-940d-434fc82067fc.png)

The correct form should be this:
![image](https://user-images.githubusercontent.com/5164351/88084359-94c0b400-cb84-11ea-92b4-85f6f15b469c.png)

**Comment by GPery** [comment]
Seems like RTL does work currently, although not perfectly.
The cursor is still a bit off with RTL languages, but it works overall.

Cheers everyone!

**Comment by peylight** [comment]
The problem still exist and there are no RTL languages support:

![RTL not supported](https://files.catbox.moe/h22t29.png)
