### ISSUE TITLE
Collaborative working in a document doesn‘t work on mobile devices

### ISSUE THREAD

**Issue by whale1432** [xwiki-labs/cryptpad#405]
We are experiencing a bug where it is almost impossible to edit a shared document on a mobile device as the cursor is jumping randomly through the text no matter where you place it. Sometimes you start typing a sentence and in the middle of typing the cursor jumps to another position in the text. This bug makes cryptpad absolutely useless, as it is impossible to work in a team under these conditions.

Additionally, we are also experiencing the text replication bug that has been already described here.

**Comment by ansuz** [comment]
@whale1432 has there been any improvement in this area since last July? We've made a number of improvements which have largely addressed cursor issues on desktop browsers in the meantime.

**Comment by ansuz** [comment]
Closing as there haven't been any updates.
