### ISSUE TITLE
Make web sockets work behind port forwarding

### ISSUE THREAD

**Issue by mlopezr** [xwiki-labs/cryptpad#42]
I'm trying to set up cryptpad (listening at http and websocket on port 3000) behind a nginx reverse proxy that forwards requests sent to e.g. mycryptpad.example.com:80 to 192.168.0.1:3000

It works for static web content.

However, when the web client performs a GET on /api/config, it is told to open a websocket to ws://mycryptpad.example.com:3000, but it should be 80
The relevant code is at [server.js line 55](https://github.com/xwiki-labs/cryptpad/blob/master/server.js#L55)

This is hard to rewrite in reverse proxy configuration.

Could you add in config.js an optional parameter with the port to be shown to web clients in case it's different to the listening port?

Thanks so much for your work!

**Comment by ansuz** [comment]
Hi, we've been migrating from apache to nginx on our production machine. We've had the same issue, and it is now patched in the `soon` branch. We have a little more testing to do, and then it will be merged to master.

**Comment by mlopezr** [comment]
I had a look at the soon branch and it looks like it will solve the problem. Thank you!

**Comment by Moredread** [comment]
But what was the issue!

**Comment by ansuz** [comment]
The server used to try to infer the URI for the websocket. Now you explicitly set the value in your config.js file.

**Comment by Moredread** [comment]
Thanks :)
