### ISSUE TITLE
Add Sign out from every session button on Top right Menu

### ISSUE THREAD

**Issue by fdiluch** [xwiki-labs/cryptpad#420]
Could you please add Sign out from every session button on Top right Menu instead of going to Account/Preferences/

**Comment by ansuz** [comment]
We're planning to include this in our next release. The button on the settings page logs out _every **other** session_, but leaves the current session intact. Do you want the same behaviour in a more accessible place, or different behaviour which terminates every session including the current one?

**Comment by ansuz** [comment]
This was included in our [3.13.0 release](https://github.com/xwiki-labs/cryptpad/releases/tag/3.13.0) which is already live on https://cryptpad.fr
