### ISSUE TITLE
Bug: fresh installed localhost cryptpad does not remove expired pads on time

### ISSUE THREAD

**Issue by umonaca** [xwiki-labs/cryptpad#431]
I have been able to reproduce the bug on Ubuntu 18.04 LTS. 

Steps:
1. Follow the [wiki instructions of installation](https://github.com/xwiki-labs/cryptpad/wiki/Installation-guide) on Github exactly. Use the example config. Node version 6.6.0. Not using docker. Did not use `/customize`.
2. Open http://localhost:3000, sign up and create either a owned pad which expires in `1 hour`, or a not-owned pad which expires in `1 hour`. 
3. Close the browser and wait for 1 or more hours. 
4. When the time runs out, open browser, the pads are still in the Cryptdrive and Documents. But they are inaccessible, showing that they are expired. 

By using `CryptPad_Hash.hrefToHexChannelId(window.location.href)`, I can get the channel id of the expired pads, and the corresponding channel files are still available in `/datastore`.

The machine is not using UTC as local timezone, but RTC time is the same as Universal time. Not sure if it is related.

I have tried executing `node scripts/expire-channels.js` but it does not help. It still shows the pads. Tried changing to another browser, but these expired pads are still in the CryptDrive.

**Comment by ansuz** [comment]
This is fixed on staging, and will be included in our next release.
