### ISSUE TITLE
Question: how can i find out the current installed version from bash console?

### ISSUE THREAD

**Issue by cremesk** [xwiki-labs/cryptpad#432]
hello,
i have a question. how can i find out the current installed version from bash console or from a json file?
thanks

**Comment by ansuz** [comment]
package.json contains the version of your cryptpad instance. The output of `curl <your-instance-url>/api/config` should contain the version of the instance that is currently running, in case you've updated but not restarted the server.

**Comment by cremesk** [comment]
Thank you ansuz! Nice to know =)
This works for me to get the version:
`wget -q -O - https://<instance-url>/api/config | grep 'ver=' | sed "/^$2/{s#^.*=##;}" | sed '$ s/.$//'`
