### ISSUE TITLE
Unable to login twice

### ISSUE THREAD

**Issue by blitz** [xwiki-labs/cryptpad#433]
## Issue

When creating an account on one system, I'm unable to login to this account on another system.

## Steps to reproduce

1. Set up cryptpad 2.25.0 and run on localhost with default configuration
2. Create an account and login
3. Open a different browser session and try to login to that account

Upstream Nixpkgs has a slightly older version that shows the same behavior and can be run via:

```
% nix-shell -p nixpkgs.cryptpad
% cryptpad
```

## Expected Behavior
Login succeeds.

## Actual behavior
Login fails with "Invalid username or password. Try again, or sign up"

**Comment by blitz** [comment]
I also cannot login again after logging out.

**Comment by ansuz** [comment]
I'm not able to reproduce with a fresh installation using the default `config.example.js`.

What browsers are you using? I tried Firefox 68.02 (with adblock plus installed) and Chromium 76.0.3809.100 with no extensions, both on Ubuntu 16.04

**Comment by blitz** [comment]
I've seen this with Firefox 68.0.2 and Chrome 76.0.3809.132 both on Fedora 30. This was with the Nix deployed version of cryptpad. I'm going to try the docker setup next.

Maybe it's Nix specific, but I'm unsure how that would be the case.

@zimbatm

**Comment by blitz** [comment]
The docker build failed for me:

```
Sending build context to Docker daemon 160.7 MB
Step 1/27 : FROM node:6-stretch-slim AS build
Error parsing reference: "node:6-stretch-slim AS build" is not a valid repository/tag: invalid reference format
```

But both master and 2.25.0 build on Fedora 30 natively work and don't exhibit this problem. So there is definitely something weird in the Nix setup.

@ansuz Is there any way of debugging this?

**Comment by blitz** [comment]
After some digging in the Javascript, it seems that the files from block are not served. This is an nginx config issue apparently.
