### ISSUE TITLE
404 on Startup

### ISSUE THREAD

**Issue by vigneshtdev** [xwiki-labs/cryptpad#434]
Followed the development wiki
https://github.com/xwiki-labs/cryptpad/wiki/Installation-guide

On going to localhost:3000, all I see is a white screen with the following error in console

GET http://localhost:3000/bower_components/requirejs/require.js?ver=2.3.5 net::ERR_ABORTED 404 (Not Found)

Error is from this line
   <script async data-bootload="/customize/template.js" data-main="/common/boot.js?ver=1.0" src="/bower_components/requirejs/require.js?ver=2.3.5"></script>

**Comment by polx** [comment]
I think that you missed the _dependencies_ part of the [installation instructions](https://github.com/xwiki-labs/cryptpad/wiki/Installation-guide).

**Comment by vigneshtdev** [comment]
Nope, I did run mom install and Bower instakl

**Comment by vigneshtdev** [comment]
@yflory  @ansuz  any solutions?

**Comment by vigneshtdev** [comment]
Woah going to http://127.0.0.1:3000/
rather than localhost:3000 fixed it

**Comment by vigneshtdev** [comment]
New issue
Going to any of the routes like `http://127.0.0.1:3000/code/`
Prints the foloowi
require.js?ver=2.3.5:1961 Refused to load the script 'http://127.0.0.1:3000/common/loading.js?ver=3.0.0-1567094633080' because it violates the following Content Security Policy directive: "script-src 'self' http://localhost:3000/". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

**Comment by vigneshtdev** [comment]
replacing _domain value in `config.js` to http://127.0.0.1:3000/ seems solve  CSP bug for me

**Comment by cityrolr** [comment]
I've installed CryptPad via the [installation guide on UberLab](https://lab.uberspace.de/guide_cryptpad.html); I also ran `npm install` and `bower install` but I am contantly getting a 404. Any idea what I did wrong? 🤔
<img width="774" alt="Screenshot 2020-01-05 at 10 47 10" src="https://user-images.githubusercontent.com/13933169/71778139-43672380-2faa-11ea-8ce8-907ca1b3e2d5.png">

**Comment by ansuz** [comment]
I don't see anything obviously wrong in their instructions, but I can't possibly know whether you followed them correctly with the information you've provided.

Are you updating an existing instance that was previously working or starting from scratch? Have you set up other web services before or is this your first such project? What is the URL that results in a 404?

**Comment by cityrolr** [comment]
Am trying to set up CryptPad from scratch on https://cityrolr.uber.space/cryptpad – I just re-did the installation following the instructions from UberLab, now I'm just having a blank page.
It's still one of my first projects to set up.

**Comment by ansuz** [comment]
CryptPad can't currently be set up on a subpath like that. It needs its own subdomain at the very least. To benefit from our sandboxing system which provides additional protection in the event of an XSS vulnerability you need a second subdomain.

**Comment by cityrolr** [comment]
Oh right, I see. Thanks

**Comment by mohamad-rai** [comment]
it's super weird, requirejs will not load only with `?ver=2.3.5` it will load with `?ver=2.3.5.0` and any version!!
didn't load for me with localhost and 127.0.0.1 on ver 2.3.5

**Comment by mthld** [comment]
@mohamad-rai this issue has been closed years ago. In case you're facing some issues I would recommend you to take this to [our community forum](https://forum.cryptpad.org).
