### ISSUE TITLE
Filter by document type

### ISSUE THREAD

**Issue by teolemon** [xwiki-labs/cryptpad#438]
Feature Request: Filter the drive view by document type (only spreadsheets…)
Alternatively, create pages like:
https://cryptpad.fr/drive/slides
https://cryptpad.fr/drive/kanbans

**Comment by davidbenque** [comment]
Not quite a filter, but you can sort by document type in the drive list view.

**Comment by mthld** [comment]
Hello @teolemon,

As explained by my colleague you can see it's already possible:

https://user-images.githubusercontent.com/41020854/185352711-f6364be8-9d0b-4410-a230-daaa1ec4c5e4.mov

Does it work for you?

**Comment by mthld** [comment]
Improvements made by @mcesson has been released, you can now filter the drive view by document type.

<img width="417" alt="Screenshot 2022-10-27 at 10 45 44" src="https://user-images.githubusercontent.com/41020854/198239130-37af4340-9930-450e-a083-b8b82c2d7821.png">

Closing this as completed. 😊

**Comment by teolemon** [comment]
Thank you Mathilde 👍 @mthld

**Comment by teolemon** [comment]
and thanks @mcesson :)
