### ISSUE TITLE
Other users writing in pad hiijacks chat window

### ISSUE THREAD

**Issue by headap** [xwiki-labs/cryptpad#441]
While collaborating on a document if another user starts to type into the pad while I am typing in chat, the text cursor is hijacked from the chat window to the pad causing the subsequent part my message to be inserted there rather than in the chat window. 

In effect this makes the chat window unusable while someone else is writing in the pad.

**Comment by ansuz** [comment]
This has been fixed in our [LabradorDuck](https://github.com/xwiki-labs/cryptpad/releases/tag/3.11.0) release and deployed to https://cryptpad.fr.
