### ISSUE TITLE
Relatively high CPU usage when tab opened in Firefox

### ISSUE THREAD

**Issue by Sosthene00** [xwiki-labs/cryptpad#443]
Hi, I've been using Cryptpad for the past weeks and I'm pretty happy with it as an alternative to gdoc. I noticed a running process called "Web Content" that constantly uses about 20 to 30% of my cpu. After playing around with my browser extensions and tabs, it seems that cryptpad is behind this process. Is this something to be expected? What is the explanation for the constant usage of CPU power even when cryptpad is idle?
My system info :

- Linux 5.0.0-27-generic #28~18.04.1-Ubuntu SMP Thu Aug 22 03:00:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Firefox 69.00

**Comment by blitz** [comment]
I can confirm this. I'm running Firefox 69.0.2 on Linux.

**Comment by mthld** [comment]
Hello,

Is this issue still occurring? If so can you try on our up-to-date flagship instance: https://cryptpad.fr?

I can't reproduce it on my end, not on macOS nor Windows 10, with both latest Firefox versions.

**Comment by Sosthene00** [comment]
Hi, it's been a long time. I've been using cryptad (the instance you mentioned) on 2 machines recently and didn't notice anormal cpu usage. 
I'll keep an eye on it for the days to come and let you know if I notice something.
