### ISSUE TITLE
What is the STORAGE .env variable used for?

### ISSUE THREAD

**Issue by ovizii** [xwiki-labs/cryptpad#445]
as the title says, can someone please explain what the STORAGE .env variable is used for?

**Comment by ansuz** [comment]
I believe that's docker's way of setting which storage back-end should be used by the node process inside the container.

In theory CryptPad supports a variety of backing storage mechanisms as long as they implement the same APIs as the one found in `cryptpad/storage/file.js`.

In practice, there is only the one module that provides everything CryptPad needs. At one point we had compatible implementations using Mongodb, leveldb, and sql, but they are all horribly out of date.

**Comment by ovizii** [comment]
Thanks, it seems to be used here: https://github.com/xwiki-labs/cryptpad/blob/master/container-start.sh
