### ISSUE TITLE
Some docker related questions

### ISSUE THREAD

**Issue by ovizii** [xwiki-labs/cryptpad#446]
I'm not that advanced with using docker so here are some questions but I must admit I might just  have overlooked the answers here.

If I am running cryptpad behind a reverse proxy which solves SSL, do I set this variable to true or false?
```
environment:
      - USE_SSL=${USE_SSL}
```

Comparing instructions from here: 
https://github.com/xwiki-labs/cryptpad/blob/master/docker-compose.yml 
and here: 
https://github.com/xwiki-labs/cryptpad/blob/master/docs/cryptpad-docker.md 

the list of folders to mount to external storage differ. Which is the more "correct" one?

This instruction mentions `var safeDomain`
https://github.com/xwiki-labs/cryptpad/wiki/Docker#customizing-cryptpad 
but further on I can't find any documentation what this safe domain is used for.

Also inside config.js I find `myDomain: _domain,` with no explanation about what format this variable can or should have. 
**###EDIT###**
figured this one out, _domain is configured at the top of this config.js: 
`var _domain = 'http://localhost:3000/';`

Also, I can't figure out how to do any customizations. I have these line in my docker/compose.yml 
```
    volumes:
      - /home/ovi/docker/cryptpad/_data/customize:/cryptpad/customize:rw
      - /home/ovi/docker/cryptpad/_data/config:/cryptpad/cfg:rw
```
and I copied config.example.js => /home/ovi/docker/cryptpad/_data/customize/config.js and modified a few things but they are not being picked up. If I make the same modifications inside /home/ovi/docker/cryptpad/_data/config/config.js they are being correctly picked up. 

I entered the command line of the container and have verified that both files are actually inside the /cryptpad/config/ and /cryptpad/customize/ folders.

Any idea why the changed are not being applied?
Looking at https://github.com/xwiki-labs/cryptpad/tree/master/customize.dist it says: 

> If you wish to customize cryptpad, please copy /customize.dist/ to /customize and then edit it there, this way you will still be able to pull from (and make pull requests to (!) the git repository.
Was I wrong about just copying config.example.js into the customize folder and renaming it to config.js?

This page: https://github.com/xwiki-labs/cryptpad/wiki/Customizing also seems to hint that I can place config.js into the customize folder.

**Comment by mason1900** [comment]
>  If I am running cryptpad behind a reverse proxy which solves SSL, do I set this variable to true or false?
> 
> environment:
>       - USE_SSL=${USE_SSL}
> 
> Comparing instructions from here:
> https://github.com/xwiki-labs/cryptpad/blob/master/docker-compose.yml
> and here:
> https://github.com/xwiki-labs/cryptpad/blob/master/docs/cryptpad-docker.md
> 
> the list of folders to mount to external storage differ. Which is the more "correct" one?

You should probably set it to false. The default configuration is serving the site on http://localhost:3000 and http://localhost:3001 without reverse proxy. Regarding reverse proxy, the answer to the following question might be helpful:

> This instruction mentions `var safeDomain`
> https://github.com/xwiki-labs/cryptpad/wiki/Docker#customizing-cryptpad
> but further on I can't find any documentation what this safe domain is used for.

You may want to read the cryptpad.fr's blog about [sandbox](https://blog.cryptpad.fr/2017/08/30/CryptPad-s-new-Secure-Cross-Domain-Iframe/). In a standalone installation with default config without reverse proxy, the program is serving the same content through port 3000 and port 3001, so that CSP sandbox works without an sandbox domain name. 

> Also, I can't figure out how to do any customizations. I have these line in my docker/compose.yml
> 
>     volumes:
>       - /home/ovi/docker/cryptpad/_data/customize:/cryptpad/customize:rw
>       - /home/ovi/docker/cryptpad/_data/config:/cryptpad/cfg:rw
> 
> and I copied `config.example.js` => `/home/ovi/docker/cryptpad/_data/customize/config.js` and modified a few things but they are not being picked up.

Whether you make a standalone installation or run it in docker container, the config.js file that the program is using is `config/config.js`, not `customize/config.js`. The `customize` folder is for `application_config.js` and other things like HTML files and translations

**Comment by ovizii** [comment]
thanks for clarifying most of my questions. I'm going to read up on that sandbox link you gave and then give setting up an instance of cryptpad another go!
