### ISSUE TITLE
cryptpad Document stays loading/no access

### ISSUE THREAD

**Issue by 42536876** [xwiki-labs/cryptpad#449]
1 day old doc pad is not opening on any device, cant recover the content
goes to loading 100% and stays there
can someone help?

**Comment by ansuz** [comment]
Hi,

If the affected document is hosted on CryptPad.fr and you're willing to expose the contents to us you can send the link to contact@cryptpad.fr and we'll determine the cause.

**Comment by ansuz** [comment]
Alternatively, if you've registered for an account and you're able to load other pages without issue you could use [our support page](https://cryptpad.fr/support/) to send the URL. This is a little more private as it won't reveal your email.

**Comment by 42536876** [comment]
thank you! tried the support since i am on cryptpad.de not fr or does this not matter?

**Comment by ansuz** [comment]
It might still be relevant since it could be a bug in the software, but we don't administrate that instance so there's little we can do if it's a server problem.
