### ISSUE TITLE
Teams - invite by link

### ISSUE THREAD

**Issue by cjdelisle** [xwiki-labs/cryptpad#451]
Excellent work on the Teams feature, this satisfies a lot of my needs. A small but important feature suggestion is an invitation link for on-boarding colleagues who are potentially not yet registered on CryptPad.

Workflow might look like:
1. Enter the team admin page, there is a "request to join" link
1. Give someone the link via another messaging platform
1. They click the link
1. They can choose to login or register if they are not yet registered
1. After registering and/or logging in, they immediately see a window saying "request to join team WXYZ ?" and when they click yes, I get notified so I can let them in.

**Comment by yflory** [comment]
This is already planned in our "Teams" roadmap and it should be ready in a few weeks!

**Comment by ansuz** [comment]
This was included in 3.7.0 and improved in 3.8.0
