### ISSUE TITLE
Many if statements in nginx example config

### ISSUE THREAD

**Issue by mason1900** [xwiki-labs/cryptpad#452]
According to [nginx documentation](https://www.nginx.com/resources/wiki/start/topics/depth/ifisevil/), "if is evil" because it produces unexpected behavior. When the if condition evaluates to true, `try_files` and `alias` are not inherited into the implicit location and are not executed. 
Did you intentionally write [the config file](https://github.com/xwiki-labs/cryptpad/blob/master/docs/example.nginx.conf) in this way?

**Comment by ansuz** [comment]
> Did you intentionally write the config file in this way?

Yes, as it allows us to configure the common aspects of both the outer domain and the sandboxed domain in a more maintainable way than if we had to configure either domain separately. The undefined behaviour does not affect a correctly configured instance and our use of if statements doesn't introduce any performance bottlenecks, so I consider it worth the tradeoffs.

On a related note, our staging branch contains [an updated example.nginx.conf](https://github.com/xwiki-labs/cryptpad/blob/staging/docs/example.nginx.conf) with some refactoring and a number of explanatory comments.
