### ISSUE TITLE
If you don't want people hosting a copy of this with limits removed can you make a mode that matches your wishes?

### ISSUE THREAD

**Issue by Leopere** [xwiki-labs/cryptpad#456]
I think it would make more sense and be less generally offensive to tell me how I should be provisioning my own users if I had a private CryptPad instance for my Organization/Friends usage.  I really respect the concept of what you're trying to do here but it doesn't make sense for me to have financial limitations on my own technology when I've already got enough drive space for my purposes.  

I guess I might now know enough about how this works here yet to really speak much on the subject. However, I just downloaded and ran a kick the tires instance on my own testing machine in hopes that I would soon be playing with my own CryptPad instance. Instead, now, after hitting this paywall on my own instance, I basically want to just delete the thing and wait for NextCloud to do this without this restriction. Maybe just wait someone to fork the code and just remove the restriction and I'll use that instead.

Self hosting is not the place you limit people to use their own tech especially with opensource tech because theres really nothing to stop someone from writing an installation script that just removes the restriction and then people will just do that instead.  

What I propose is just if you don't want public instances with unlimited storage offer a simple button in the admin interface however the hell you get to that from here.  That would switch from this mode to a mode where I don't have limitations for my organization / friends / family.  Privacy should be easy and available to everyone I understand you need to get paid but this feels wrong.

**Comment by umonaca** [comment]
Have you ever read the wiki and config files? You can change everything, from adjusting storage limit to removing subscription / paywall  etc by editing the config file.

**Comment by Leopere** [comment]
oh god no I got ultra excited about this then really disappointed when I hit the paywall on my own hardware.  I'll have a look thanks so much for pointing out that the only imitation was my ignorance.

**Comment by ldubost** [comment]
Hi @Leopere,

I'm from the cryptpad team, actually the XWiki SAS CEO who pays the developers to do this work, and probably the person responsible for the way this setting works.

I'm sorry you have felt this was wrong. It probably shows we would need to explain things in the default message unless administrators have acknowledge the configuration set in the configuration file.

As @umonaca has mentioned, the way cryptpad works is that there is a configuration file (see here https://github.com/xwiki-labs/cryptpad/blob/master/config/config.example.js) which includes settings for subscriptions:

/* =====================
     *     Subscriptions
     * ===================== */

    /*  Limits, Donations, Subscriptions and Contact
     *
     *  By default, CryptPad limits every registered user to 50MB of storage. It also shows a
     *  subscribe button which allows them to upgrade to a paid account. We handle payment,
     *  and keep 50% of the proceeds to fund ongoing development.
     *
     *  You can:
     *  A: leave things as they are
     *  B: disable accounts but display a donate button
     *  C: hide any reference to paid accounts or donation
     *
     *  If you chose A then there's nothing to do.
     *  If you chose B, set 'allowSubscriptions' to false.
     *  If you chose C, set 'removeDonateButton' to true
     */
    allowSubscriptions: true,
    removeDonateButton: false,

You can change the behavior for your instance. Note that you can join our matrix channel where we would also answer questions.

Now why do we do this. Open Source does not come out of thin air and we want people and administrators to understand that. If we want more open source code, we can't just believe it will get funded miraculously. We want our code to be open source and we want other people to host it, however we need to find a way to fund this beast. When building subscription for our own hosted instance (cryptpad.fr) we decided to just leave the code in any open source instance and decided to propose a deal to hosters which would be to leave the subscription system on and share the revenue of it 50/50. 50 For the hoster, 50 for the developers. We do understand of course that individuals would not want to go for this so there is a way to deactivate it.

Now we decided to activate subscriptions by default, actually to force people to DECIDE to deactivate subscriptions and donations. Now maybe in the administrator UI (which did not exist at the time) we would need a button to quickly deactivate it and also have a link and explanation of what I have just written here. We'll look into this.

Sorry for your bad experience, and I hope you will enjoy CryptPad once you are able to unblock the storage.
