### ISSUE TITLE
The share button does not work

### ISSUE THREAD

**Issue by medienberater** [xwiki-labs/cryptpad#457]
If a new pad is opened without registration and the share button is clicked, unfortunately nothing works anymore. No button is clickable anymore. You can't write anything anymore. The selection window, where you can copy the URL into the cache, does not appear.

This error appeared with different browsers and at different Windows-computers.
Exception: If you are logged in, everything works perfectly. The share button can be clicked and the selection window appears.

**Comment by yflory** [comment]
This is fixed on staging, and will be included in our next release.
