### ISSUE TITLE
try to disable survey

### ISSUE THREAD

**Issue by cremesk** [xwiki-labs/cryptpad#458]
Hello,
thank you for your great work! I really like the Cryptpad very much.

i just upgraded my cryptpad from version 3.3.0 to 3.4.0. It works really great.
I like the update method. This is really super easy.

I have tried a small thing now. And I wanted to hide the survey.
> * A link to the new CryptPad survey has been added to the user menu
>   * This link can be changed or removed using the "surveyURL" key in `/customize/application_config.js`. An empty value will remove the link from the menu.
> 

So I entered the following in `customize/application_config.js`:
```
/*
 * You can override the configurable values from this file.
 * The recommended method is to make a copy of this file (/customize.dist/application_config.js)
   in a 'customize' directory (/customize/application_config.js).
 * If you want to check all the configurable values, you can open the internal configuration file
   but you should not change it directly (/common/application_config_internal.js)
*/
define(['/common/application_config_internal.js'], function (AppConfig) {
    surveyURL = "";

    return AppConfig;
});
```

Is this correct?
I still see the survey link in the menu in my pad.

![cryptpad_menu](https://user-images.githubusercontent.com/7526990/67771530-c0c96180-fa58-11e9-897e-d4b9877989fc.png)

Thanks for any help.

~creme

**Comment by yflory** [comment]
Hi,

You should use `AppConfig.surveyURL = "";` instead of `surveyURL = "";`
I'm going to put an example in the default `application_config.js` file to make it easier to understand.

**Comment by cremesk** [comment]
> Hi,
> 
> You should use `AppConfig.surveyURL = "";` instead of `surveyURL = "";`

Perfect @yflory ! Thanks for this.
now works as it should.

> I'm going to put an example in the default `application_config.js` file to make it easier to understand.

That's a good idea. ty =)
