### ISSUE TITLE
ODT-Export for RichText documents

### ISSUE THREAD

**Issue by pintman** [xwiki-labs/cryptpad#459]
It would be great to have an export option for RichtText documents. Currently I can copy from the pad into a LibreOffice or MS-Word document. However, images and formulas are are not correctly copied into the target document. An export option into a document format which can be edited afterwards would therefore be necessary. Currently HTMl is the only option.

**Comment by ansuz** [comment]
Our latest update introduces the ability to export to .doc, which LibreOffice and MS-Word are both capable of opening.

**Comment by sudwhiwdh** [comment]
I'm a little surprised why the Issue has already been closed. If I understand the request correctly, it is about support for the free .odt standard. To my knowledge, .doc is not a free standard in the sense of the Open Document Foundation. I therefore kindly ask you to reopen the issue.

**Comment by sudwhiwdh** [comment]
@pintman Do you specifically want to export to .odt or do you want to be able to save your text files directly as .odt as well?

**Comment by pintman** [comment]
I do not have a specific need but want to be able to edit documents when they leave cryptpad. Having an open document format would help a lot for this.

**Comment by ansuz** [comment]
I've been using the .doc export for that purpose (opening pads in LibreOffice) and have found it to be sufficient, but if there are any tangible differences between opening in .doc vs .odt I'd be okay to reopen this.

**Comment by sudwhiwdh** [comment]
> but if there are any tangible differences between opening in .doc vs .odt

Qualitatively, this would be a good research task. I only use free formats. And that's what I would be interested in in the first place. Especially if there are no big differences in quality, I would always support the free format.

**Comment by ansuz** [comment]
I'll happily accept a PR, but I'm unlikely to allocate time towards something motivated strictly by ideological reasons.

**Comment by valerio-bozzolan** [comment]
As additional context, nowadays these are not just "ideological reasons". There are national legal obligations for public administrations to avoid `.doc` Microsoft® format and adopt instead `.odt` Open Document standard.

Example that covers Italy, to avoid `.doc`:

https://docs.italia.it/AgID/documenti-in-consultazione/lg-opendata-docs/it/bozza/allegato-b-standard-di-riferimento-e-formati-aperti.html

> I'll happily accept a PR

Nice. Do you happen to know any part that is managing `.doc` export at the moment, to extend for `.odt`? I've seen this, but seems too short / unrelated:

https://github.com/cryptpad/cryptpad/blob/main/www/doc/export.js
