### ISSUE TITLE
Cryptpad view mode shows nothing in portrait mode on mobile phones

### ISSUE THREAD

**Issue by nwalfield** [xwiki-labs/cryptpad#460]
I only see a blank page when I visit the following link from my phone (Pixel 3a running Android 10) using either Firefox (68.2.0) or Chrome (10.81.10.21.arm64):

  https://cryptpad.fr/code/#/2/code/view/nBYQ0gKZrILo1A5+yLEwpcHON1CoM-+CMxChRPZH34k/embed/present/

If I switch to landscape mode, then I see the expected content.

Perhaps this has something to do with the huge margins.

I was hoping to use a cryptpad to share relevant information with a small group of not technically savy people.  Unfortunately, this is a deal breaker for them.

**Comment by nwalfield** [comment]
From irc:

> 23:05 <LudovicDubost[m]> > When sharing a read-only, embedded, presentation link to a code pad (e.g.,
>                          https://cryptpad.fr/code/#/2/code/view/nBYQ0gKZrILo1A5+yLEwpcHON1CoM-+CMxChRPZH34k/embed/present/ ), only a blank page shows
>                          up on mobile devices in portrait mode
>23:05 <LudovicDubost[m]> We need to modify the css on small screens. Thanks for the jira. This should be looked at.

**Comment by ansuz** [comment]
We've implemented a fix and deployed it to CryptPad.fr. It will be included in the upcoming release (4.5.0) which will be published as soon as I finish writing its release notes.
