### ISSUE TITLE
admin page with docker-compose

### ISSUE THREAD

**Issue by rototom** [xwiki-labs/cryptpad#462]
In installed cryptpad via the docker-compose file and added my key in config/config.js.
I can't use mydomain/admin "only administrators can use...". So, what config file do I have to edit to make this happen?

**Comment by wolfskaempf** [comment]
Assuming you haven‘t modified the `docker-compose.yml` file you‘ll need to go to `cryptpad/data/config/config.js` and edit that file, as it is the one loaded through the volume feature of docker. After that run `docker-compose down && docker-compose up -d` to make sure the config is properly reloaded.

**Comment by ansuz** [comment]
If I understand correctly this is not a problem with the CryptPad platform, but with a particular configuration value when used with docker. I'm going to go ahead and close this since a solution was proposed and it seems there's little to do on our side.
