### ISSUE TITLE
Dead link to the "full tutorial" on Docker setup

### ISSUE THREAD

**Issue by nim65s** [xwiki-labs/cryptpad#463]
Hi,

It looks like the link https://github.com/xwiki-labs/cryptpad/wiki/Docker-(with-Nginx-and-Traefik) given in https://github.com/xwiki-labs/cryptpad/blob/master/docs/cryptpad-docker.md#L5 is dead.

**Comment by yflory** [comment]
Hi,
Thanks for the report, I've just fixed the link.
