### ISSUE TITLE
Team Drive is read only even for owners

### ISSUE THREAD

**Issue by wolfskaempf** [xwiki-labs/cryptpad#464]
Browser: Safari on iOS 13.2.2

I‘m owner of Team A, however, when I log into CryptPad on my iPad or iPhone I am always forced into read only mode for the entire team drive. Clearing Cache or using Chrome on iOS did not solve the issue.

Edit: If I am not mistaken teams are loaded in an iframe or equivalent, right? How is the string after the # handled in that case? Perhaps something is omitted from that part in iframes in mobile Safari.

Edit 2: I saw that in a recent version read-only team drives were introduced. Perhaps the issue is hidden somewhere inside the js logic which determines who has which level of access? I can report that promoting and demoting of users is working as expected even on affected devices.

Edit 3: I have no experienced a similar behaviour in Chrome (78.0.3904.70 (Official Build) (64-bit) macOS) as well, however logging out and back in again is more or less consistently able to fix the issue.

**Comment by yflory** [comment]
Thanks a lot for the detailed report!
We were aware of this issue but we didn't know how to reproduce it.
The issue should be fixed on cryptpad.fr. If you're using a different instance, the fix is available on our `master` branch.

**Comment by wolfskaempf** [comment]
Thank you for the quick response. Even after pulling from master and running `docker-compose down && docker-compose up -d` on my instance, I am experiencing the same faulty behaviour. Is there anything else that needs to be changed to fix this?
