### ISSUE TITLE
Request: Update Org Mode library

### ISSUE THREAD

**Issue by ryanpcmcquen** [xwiki-labs/cryptpad#466]
There have been some excellent updates to the Org Mode library used here:
https://github.com/mickael-kerjean/codemirror-orgmode

Would love to see it updated.

**Comment by yflory** [comment]
Hi,

I was only able to update a part of the library.
The code found in the repo you mentioned is incomplete, it's using functions that are not defined: https://github.com/mickael-kerjean/codemirror-orgmode/blob/master/orgmode-mode.js#L107
`org_cycle`, `org_shifttab`, etc. aren't defined anywhere.

**Comment by ryanpcmcquen** [comment]
@yflory, thanks, that is strange.

I made an issue there:
https://github.com/mickael-kerjean/codemirror-orgmode/issues/1

**Comment by ryanpcmcquen** [comment]
@yflory, they are defined in these two places:
https://github.com/mickael-kerjean/filestash/blob/master/client/pages/viewerpage/editor/emacs-org.js#L1-L4
https://github.com/mickael-kerjean/filestash/blob/master/client/pages/viewerpage/editor/emacs-org.js#L20-L30

**Comment by ryanpcmcquen** [comment]
@yflory, did you ever get these?

**Comment by yflory** [comment]
Yes, these changes were implemented in a previous release and are already deployed on cryptpad.fr
A small issue affecting some click events may appear in the current version but it's already fixed and we'll deploy the fix very soon.
