### ISSUE TITLE
Show link to account management page for paid users

### ISSUE THREAD

**Issue by ataraxia937** [xwiki-labs/cryptpad#467]
Right now, there's no link that I can find to accounts.cryptpad.fr from the drive, for paid subscribers. Of course it's easy to find for free users, because the upgrade button is shown. But for paid users, we just have to know the URL for account management.

**Comment by davidbenque** [comment]
There are links to the accounts page in your profile menu (upper right) and in Settings > Subscription

**Comment by ataraxia937** [comment]
I see it now. Sorry for the noise.

**Comment by davidbenque** [comment]
No problem, we are also on [Matrix](https://riot.im/app/#/room/#cryptpad:matrix.org) if you need support in future.
