### ISSUE TITLE
Recipient cannot download shared documents

### ISSUE THREAD

**Issue by fdiluch** [xwiki-labs/cryptpad#476]
Dears,
Looks, can you make cryptpad working and usefull !
I am paying for it !
but it is a mess to share SIMPLY documents.
How it comes the recipient cannot download documents when they are shared on edit mode ??????
It is super frustrating ....
You have the company protonmail.com which is working on an equivalent tool.
I am already using them and soon they will be better than you

**Comment by ansuz** [comment]
Hi,

I think what your friend is looking for is the "export" function. It's available in edit or view mode.

I've attached a screenshot for clarification.


![Screenshot from 2019-12-11 09-56-50](https://user-images.githubusercontent.com/1264398/70632541-03a45a80-1bfd-11ea-975a-9fd7fc65116b.png)
