### ISSUE TITLE
Duplicate documents

### ISSUE THREAD

**Issue by ineiti** [xwiki-labs/cryptpad#477]
I would like to be able to create duplicate of documents by simply right-clicking on them and chosing "duplicate".

Workaround: create a template of the document, and then create a new document using that template. Afterwards delete the template.

**Comment by ineiti** [comment]
Bumping this, because it really would be nice...

**Comment by ansuz** [comment]
We've discussed this recently in the context of our _self-destructing pad_ feature, where it would be nice to create a copy of something and then share self-destructing copies with particular people.

You're right to compare this to templates, as most of the functionality to do this is already implemented. It's mostly an issue of implementing the UI to expose it to users. We're pretty busy trying to crank out a few big features in the next few releases, but I'll keep this in mind and try to fit it into our roadmap in the near future.

**Comment by ansuz** [comment]
This has been implemented and merged to master as a part of [v3.12.0](https://github.com/xwiki-labs/cryptpad/releases/tag/3.12.0).
