### ISSUE TITLE
nginx customize.dist//libs/app.bundle.min.js not found

### ISSUE THREAD

**Issue by ybaumy** [xwiki-labs/cryptpad#479]
When starting cryptpad the first time with _node server_ I am getting the following nginx error message. I cannot find this directory nor file anywhere. I tried that with the master branch and the 3.7.0 release. both get the same error

> 2019/12/17 18:55:19 [error] 24029#24029: *23 open() "/home/user/cryptpad/customize.dist//libs/app.bundle.min.js" failed (2: No such file or directory), client: 10.10.10.10, server: sub.domain.tld, request: "GET /libs/app.bundle.min.js?v=3729 HTTP/2.0"

**Comment by ansuz** [comment]
I suspect your nginx configuration for CryptPad is conflicting with that of another application, since CryptPad doesn't have a file with that name.

**Comment by ybaumy** [comment]
you were right. somehow nginx tried to access the jitsi server that is running on that host.
