### ISSUE TITLE
Consider enhancement to support sandstorm.io deployments

### ISSUE THREAD

**Issue by qcu** [xwiki-labs/cryptpad#48]
Great job XWiki team! A very nice app.

I would like to propose the [Sandstorm](https://sandstorm.io/) platform as an excellent option for hosting (and self-hosting) CryptPad.

Many successful collaboration applications are already available within the [Sandstorm App Market](https://apps.sandstorm.io/), the distribution channel is growing every week, and it seems that Sandstorm would be a perfect fit for hosting (or self-hosting) instances of CryptPad applications/documents.

My initial experiment with bundling CryptPad as a Sandstorm app is available on the [sandstorm-master branch](https://github.com/qcu/cryptpad/tree/sandstorm-master/.sandstorm) of my fork. (Edit: see the [sandstorm-soon branch](https://github.com/qcu/cryptpad/tree/sandstorm-soon/.sandstorm) for the latest.) See [.sandstorm/README.md](https://github.com/qcu/cryptpad/blob/sandstorm-soon/.sandstorm/README.md) for more information.

Currently, I am troubleshooting some WebSocket connection issues. All of the CryptPad apps launch and load. However, the UI freezes with a WebSocket connection failure message in the JS console. I do plan to submit a PR, once this issue is resolved.

**Comment by ansuz** [comment]
I met one of the Sandstorm devs last summer, and it definitely seemed like a cool platform.

We're pretty busy working on UI and core algorithms, so we can't commit to explicit support for sandstorm. That being said, if you submit a PR that doesn't affect non-sandstorm users, I'll merge it.

I'd recommend testing against our [soon branch](https://github.com/xwiki-labs/cryptpad/tree/soon), as it features commits that might fix your issues.

If you have any questions that would be easier to discuss in real time, I'm typically available on IRC (freenode, #cryptpad) during the daytime in France (UTC +2).

**Comment by ansuz** [comment]
By the way, thanks for the kind words :smile:

**Comment by qcu** [comment]
@ansuz: Thanks for the hints re. the soon branch. That took care of the WebSocket issues experienced with the current beta on master. 

The clients for all document types are now running as Sandstorm grains within the [sandstorm-soon branch on my fork](https://github.com/qcu/cryptpad/tree/sandstorm-soon/.sandstorm).

Just need to work out a few [known issues](https://github.com/qcu/cryptpad/tree/sandstorm-soon/.sandstorm#known-issues--roadmap) so that everything plays nicely with Sandstorm's use of ephemeral random per-session subdomains and IFRAMEs.

**Comment by ansuz** [comment]
Since Sandstorm has apparently gone out of business, I'm going to close this issue as there does not seem to have been progress. Feel free to reopen it if the situation changes.

**Comment by qcu** [comment]
Hi @ansuz. No worries, and this has been on the back burner for me since October.

However, IMHO the _open source_ project has not quite gone "out of business." : )

N.B. [Sandstorm](https://github.com/sandstorm-io) and [capnproto](https://github.com/sandstorm-io/capnproto) are still active open source projects, and all of the previous enterprise components are now available in the community edition of Sandstorm.

Yes, the Sandstorm founders did suspend their initial round of commercialization, however @kentonv and others are still maintaining Sandstorm as an open source project.

On a tangential note, I am also looking at other personal cloud hosting platforms for cryptpad. Thanks again for cryptpad and other XWiki software!
