### ISSUE TITLE
cryptpad tableur : la copie d'un champ "Date" produit des dates invalides

### ISSUE THREAD

**Issue by SilverFox15** [xwiki-labs/cryptpad#481]
cryptpad tableur : la copie d'un champ "Date" produit des dates invalides

Copier en utilisant le point noir en bas à droite de la sélection suivante

2020/8/06
2020/8/20

Donne :
2020/8/34
2020/8/48
2020/8/62
2020/8/76
2020/8/90

**Comment by mthld** [comment]
Must have been fixed, it's working as intended:

![Screenshot 2022-08-08 at 10 13 33](https://user-images.githubusercontent.com/41020854/183371587-3dd6af90-752b-449d-bebe-ea39fa5da55d.jpg)
