### ISSUE TITLE
Imprint link on every page?

### ISSUE THREAD

**Issue by michaelschefczyk** [xwiki-labs/cryptpad#489]
To be able to operate self-hosted cryptpad instance in the German speaking countries, it would be good to be able to provide a link to an imprint and a GDPR policy on every page available to users at least prior to logging in. Otherwise, every provider is at risk either because of the paid account revenue sharing model cryptpad offers by default or because the provider it self is not completely non-commercial (i. e., any provider not just being a hobby provider). Even providers which are likely to be classified as non-commercial by anyone except legal opponents like this one: https://cryptpad.gwdg.de/ should be at risk, because the publicly accessible pad has no such link. It would be great if a footer with clickable links or something on the top row of each page could be configured as easy as the other customizations by any average admin.

**Comment by ansuz** [comment]
We added a fix for this in today's release ([v3.10.0](https://github.com/xwiki-labs/cryptpad/releases/tag/3.10.0)).
