### ISSUE TITLE
Option to add collaborations to Bookmarks ?

### ISSUE THREAD

**Issue by JtLively** [xwiki-labs/cryptpad#49]

**Comment by ansuz** [comment]
I'm not clear on what you mean. Are you asking to display the collaborators on a document in the front page document list?

**Comment by JtLively** [comment]
No, just an option to save links to the documents in browser bookmarks folder.

**Comment by kpcyrd** [comment]
I think you mean a feature like this: https://www.thewebflash.com/how-to-add-a-cross-browser-add-to-favorites-bookmark-button-to-your-website/

I didn't know this is possible, yet I'm not sure if that's actually easier than just bookmarking the document when you opened it :)

**Comment by JtLively** [comment]
@kpcyrd It makes it more obvious to the user that they need to bookmark their docs to access them should they delete their history/cache.

**Comment by ansuz** [comment]
Sorry to have taken so long to respond to this. We'll definitely keep this in mind for our next set of UI iterations. We're currently wrapping up one change set that we hope to deploy very soon.

**Comment by ansuz** [comment]
I think this use case is addressed by the CryptDrive application, so I'm going to close this issue. If you disagree feel free to open it up again.
