### ISSUE TITLE
Transfer "last opened pads" into a different folder

### ISSUE THREAD

**Issue by mp-4** [xwiki-labs/cryptpad#490]
**Problem:**

If you look at your resently open pads and you want to click and drag to a folder in your drive, it is not possible. 
The pad isn't selected. 
If you drag you created a rectangle - (normaly used to select more pads)

Here a picture to expain it:
![LastOpenPads](https://user-images.githubusercontent.com/44546897/72925817-9cc5a580-3d53-11ea-8520-5f64546f9627.jpg)

CryptPad-Version: 3.9.0

**Comment by ansuz** [comment]
This is fixed in today's [v3.18.1 release](https://github.com/xwiki-labs/cryptpad/releases/tag/3.18.1).
