### ISSUE TITLE
Imprint

### ISSUE THREAD

**Issue by michaelschefczyk** [xwiki-labs/cryptpad#493]
The quick response to the "imprint" request was really super supreme - thank you very much!

Nevertheless, I cannot get this to work. Testing without a custom pages.js file, I have set application_config.js to:

define(['/common/application_config_internal.js'], function (AppConfig) {
    AppConfig.appBackgroundColor = '#f9f5e4'
    AppConfig.loginSalt = '...'
    AppConfig.surveyURL = ''
	AppConfig.imprint = 'https://.../impressum.html';
    return AppConfig;
});

However, this does not seem to show an imprint anywhere, while my login salt does definitely work and the menue is displayed without a survey entry.

Did I get something wrong?

**Comment by yflory** [comment]
> Did I get something wrong?

No, we did! The translation key for "imprint" was missing from our release.
It will be available in the next release ([see this commit](https://github.com/xwiki-labs/cryptpad/commit/66ef508e0e7f784bfc8e70b3bb5ec4a098b71c9a)).
If you know how to [add custom translation keys](https://github.com/xwiki-labs/cryptpad/blob/master/customize.dist/translations/messages.js#L1-L7), you can fix this issue in your instance directly.

**Comment by ansuz** [comment]
This has been fixed in our [LabradorDuck](https://github.com/xwiki-labs/cryptpad/releases/tag/3.11.0) release and deployed to https://cryptpad.fr.
