### ISSUE TITLE
Uploading a folder does not show progress for more than five files

### ISSUE THREAD

**Issue by wolfskaempf** [xwiki-labs/cryptpad#496]
When uploading a folder with more than five files, it will not be possible to correctly observe the progress. The five entries in "Uploaded files" which usually shows progress are all shown as waiting in queue and the currently uploading file(s) are not shown.

**Comment by hopebeckary** [comment]
How can I unsubscribe when I don't know which email they are being sent to?

Help me here.

Pete Beckary
pete@beckary.com
littleismuch.com
petebeckary.com
beckary.com
717.468.1866

**Comment by ansuz** [comment]
@hopebeckary use the _unwatch_ UI at the top of this repository's page.

**Comment by hopebeckary** [comment]
Sorry - I don't understand - where do I find "this repository's page"?


Pete Beckary
pete@beckary.com
littleismuch.com
petebeckary.com
beckary.com
717.468.1866

**Comment by davidbenque** [comment]
Hi @wolfskaempf this issue will be fixed in the next release planned for Feb 11th.

**Comment by davidbenque** [comment]
Hi @hopebeckary there is an unsubscribe link at the bottom of the emails you are receiving, alternatively you can visit the [repository](https://github.com/xwiki-labs/cryptpad) and click the unwatch button at the top right.

**Comment by ansuz** [comment]
This has been fixed in our [LabradorDuck](https://github.com/xwiki-labs/cryptpad/releases/tag/3.11.0) release and deployed to https://cryptpad.fr.
