### ISSUE TITLE
Team Drive access ranks do not grant write access if "Member" stage is skipped

### ISSUE THREAD

**Issue by wolfskaempf** [xwiki-labs/cryptpad#497]
Steps to reproduce

1. Set up a team
2. Add someone to the team via any method
3. They accept and are now a "Viewer"
4. They are offline until step 6
5. I increase their rank to higher than "Member" (e.g. "Admin" or even "Owner")
6. They come online and access the drive for the first time

Result: They now have Admin or Owner rights but only read access to the team drive.

**Comment by yflory** [comment]
Thanks for the report, we were aware of this issue but we didn't know how to reproduce it!
This is fixed on our "staging" branch and will be included in the next release.

**Comment by ansuz** [comment]
This has been fixed on and merged to master as a part of [v3.12.0](https://github.com/xwiki-labs/cryptpad/releases/tag/3.12.0).
