### ISSUE TITLE
Registering and Logging get stuck with console error, 

### ISSUE THREAD

**Issue by dev0null0** [xwiki-labs/cryptpad#498]
I have recently installed cryptpad on an nginx webserver for a small community of DYI enthusiasts.
But nothing seems to go beyond the home page. When users try to register console shows:

`Failed to load resource: the server responded with a status of 404 ()
login.js?ver=3.11.0-1582643934082:173 no block found
netflux-client.js?ver=3.11.0-1582643934082:326 ERROR: join to non-existent chan [0,"131e65561467db89","JOIN","2f10d40208be29ee374bf849801389fe"]
`
Opening pads without user registration also fails but withput any error messages.
There are no errors in the logfiles of nginx.
The cryptpad service status is ok.

Version: CryptPad v3.11.0 (LabradorDuck)

**Comment by ansuz** [comment]
We just released v3.12.0. Since it's a fresh install you may want to start with that.

**Comment by dev0null0** [comment]
Threw away 3.11 re-cloned using 3.12 - now it does work even though I copied the config.
Now I am happy - but also puzzled why it didn't work with the other installation. 
Thank you anyway!
While you are here - where do I find the admin key to put in my config after registerig user#1 ?

**Comment by ansuz** [comment]
`node scripts/generate-admin-keys.js` from your repository root will generate a new keypair you can use.
