### ISSUE TITLE
Pages load slowly (especially on mobile)

### ISSUE THREAD

**Issue by andybalaam** [xwiki-labs/cryptpad#499]
Cryptpad is brilliant, thank you!

Sometimes it takes several seconds for cryptpad.fr to load a document, especially on my mobile phone.  I think this is because of the large number of JavaScript files that are loaded sequentially when I load a page.

To get some evidence for this idea I ran the [pingdom](https://tools.pingdom.com) tool against the [Build an App tutorial page](https://cryptpad.fr/pad/#/1/view/aN5Xj2fXF4FANtYhmiia9g/UKkWIfnnM2YaCScaHW4m4NSADaLY8dWY11+DmvGSkJs/) on cryptpad.fr.  The result is attached: [cryptpad-tutorial.har.txt](https://github.com/xwiki-labs/cryptpad/files/4255469/cryptpad-tutorial.har.txt)

This shows that 341 HTTP requests were made to load this page, which seems a lot.  241 of those were loading JavaScript files, and 24 were loading CSS.

I believe that by bundling assets with a tool like [webpack](https://webpack.js.org/) the page load time could be improved a lot.

What do you think?  If you like the idea I might be able to help try to implement it.

**Comment by ansuz** [comment]
We're gearing up to start a new project in which we'll develop a mobile app prototype, so we're going to start looking into build systems. I've looked into webpack before and I wasn't impressed, but we may end up using something like it in the end.

Otherwise, there are still lots of steps in between loading all the static assets and being able to use the app, such as synchronizing documents in the background: including your drive, teams, and shared folders. The biggest gains will come from implementing an on-device cache for these messages, and we want to do that anyway since it will move us one step closer to working offline.

**Comment by andybalaam** [comment]
Really glad to hear you are working on it.  Do you have measurements of how much time is spent loading assets vs. synchronizing documents?  Loading assets should be pretty easy to fix, so worth knowing whether it will have a significant effect.  I had a look at the profile in Firefox, and I see vast numbers of setTimeout and setInterval calls but I can't figure out whether these concern loading assets or documents or something else...

**Comment by ansuz** [comment]
I don't have anything readily available, we've just profiled things in the past. The big thing to consider is that we use a very aggressive caching policy. Assets are only loaded once per CryptPad version, so if you're visiting more than once every two weeks your subsequent loads should be much faster, but the time to load document data is constant. Faster asset loading makes a better impression on first-time or occasional visitors, but beyond that point it's diminishing returns.

**Comment by andybalaam** [comment]
A quick profile here: 
![image](https://user-images.githubusercontent.com/76812/75356436-e13ee680-58a7-11ea-8873-2caa0836159e.png), which should help me get started if I have time to look into this.

It shows 40% of the time is spent idle, so I feel like looking into those setTimeout and setInterval calls would be worth doing.  There are lots of DOM Events listed in the profile, which might mean the page is getting updated and re-rendered lots of time while things are being loaded.

**Comment by ansuz** [comment]
We made a number of improvements since this issue was opened which have improved mobile performance considerably, especially after the first load.
