### ISSUE TITLE
Rich Text application throws errors

### ISSUE THREAD

**Issue by dev0null0** [xwiki-labs/cryptpad#500]
In "rich text" Pad clicking the button **Styles** resulted in nothing happening and the console showing the following errors:

`Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'self' cryptpad.freiland-potsdam.de". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.`

**Comment by ansuz** [comment]
Looks like your instance isn't configured correctly. The rich text app should have a special set of content-security policy headers applied, but it seems like you've loaded it with the global rules used through most of the rest of the platform.

**Comment by dev0null0** [comment]
I used the nginx config provided here, basically only editing pathes.
Only real alteration is the addition of basic_auth on the server level, so we're not offering cryptpad to the general public.

**Comment by ansuz** [comment]
I'm using the config for my own instance running the latest version of CryptPad and I don't have this issue.

**Comment by ansuz** [comment]
Since your instance is blocking access I can't check it for myself. 

I suspect you set the `$sandbox_domain` variable in the nginx config but didn't set the corresponding variable in` `config/config.js`. Review [these lines of the config](https://github.com/xwiki-labs/cryptpad/blob/master/config/config.example.js#L94-L96), as I suspect that will solve your problem.

**Comment by ansuz** [comment]
I'm currently reworking our `config.example.js` file to remove a lot of unnecessary information and to put that variable at the top, since many people seem to skip past it. These changes will be included in  our next release.

**Comment by dev0null0** [comment]
Thank you for the advice. 
I changed the appropriate line to use the sandbox domain which is also a name alias in the server config. Yet that doesn't change anything.

**Comment by ansuz** [comment]
In any case, I'm certain this is a configuration problem as it doesn't affect our instance. I prefer to reserve github issues for problems with the platform's code, so I'm going to go ahead and close this. 

Please visit our matrix channel for issues affecting your instance. We have an active community of admins who I'm sure will be happy to help you debug.
