### ISSUE TITLE
Stuck loading in chrome

### ISSUE THREAD

**Issue by adelmang14** [xwiki-labs/cryptpad#501]
Updated to Cryptpad version 3.12.0,
it works fine in Firefox and IE, but in Chrome it hangs after submitting the login-credentials (eternal loading-screen). 
Weird thing is that their is no error (not in the browser console and not in the error log of the nginx server). 
The last few entries in the browser console are 
Posting CONNECT
Compiling [/drive/app-drive.less] took 903ms

**Comment by ansuz** [comment]
Try running `npm i` and restarting your server.

**Comment by ansuz** [comment]
I can't reproduce this problem and I haven't heard back, so I'm going to go ahead and close this.
