### ISSUE TITLE
Sheet loading is stuck

### ISSUE THREAD

**Issue by gerwinn** [xwiki-labs/cryptpad#502]
Hello,

I'm using Cryptpad on Chrome (Version 80.0.3987.132  (64 bits))

Loading is stuck "Sheet loading".
![image](https://user-images.githubusercontent.com/4949399/76004639-1da6be00-5f0a-11ea-9440-03f754aa3cea.png)

Server : https://cryptpad.organise.earth/   (i'm not the owner)

Error in the console :

![image](https://user-images.githubusercontent.com/4949399/76004580-f94ae180-5f09-11ea-9056-a72cdeed2a46.png)

**Comment by 3n2pS3P5kG23S96yxRbUHAZajuH2F** [comment]
I'm also experiencing this issue as of today.

**Comment by ansuz** [comment]
For spreadsheets on CryptPad.fr please use the built-in support ticket functionality to send us the link to the spreadsheet. We don't have enough information here to identify what's causing the 404 or the javascript errors.

**Comment by 3n2pS3P5kG23S96yxRbUHAZajuH2F** [comment]
> 
> 
> For spreadsheets on CryptPad.fr please use the built-in support ticket functionality to send us the link to the spreadsheet. We don't have enough information here to identify what's causing the 404 or the javascript errors.

I'd forgotten about the ticket function. I've just submitted a report. Thank you.

**Comment by ansuz** [comment]
We've deployed a patch in our [v3.14.0](https://github.com/xwiki-labs/cryptpad/releases/3.14.0) release which we believe should fix this. I'm closing, but feel free to re-open if the problem persists.
