### ISSUE TITLE
Want a color palette in Kanban, so make assign color a more easy thing

### ISSUE THREAD

**Issue by maptile** [xwiki-labs/cryptpad#504]
I use Kanban as a communication tool in a small project. I can assign a color to each item. But there is no color palette, when I want to assign the 'same' color to multiple items, the color is more or less the different, and it seems ugly to me.

It would be easier to use if there is a preset color palette when assign colors.

**Comment by ansuz** [comment]
Good timing! We plan to release a big Kanban update next Tuesday (March 17th). It will replace the color-picker with a preset 9-color palette.

**Comment by maptile** [comment]
Wow! Looking forward to this new release
