### ISSUE TITLE
Document reaches 100% and never ends up opening 

### ISSUE THREAD

**Issue by XRccs** [xwiki-labs/cryptpad#506]
**Describe the bug**
The document was created and shared normally. Yet it doesn't open after 100% charge is reached. 
It happens whereas opening from where it is shared nor in my crypdrive (I own this pad) 

**Where did it happen?**
https://cryptpad.piratenpartei.de/oodoc/#/2/oodoc/edit/SgNbMU1OTxSh4l--JNIWSsbC/

**To Reproduce**
simply try to open the document

**Expected behavior**

**Screenshots**
![pad not working](https://user-images.githubusercontent.com/62118722/76565230-70541d00-64aa-11ea-9bd5-6f05cfc619aa.PNG)

**Browser (please complete the following information):**
 - OS: Win 8.1
 - Browser : Chrome
   - variations 
 - Extensions installed: Ecosia
 - Browser tweaks 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ansuz** [comment]
The editor you're trying to use is **extremely experimental**. It's disabled on CryptPad.fr (our instance) and we don't recommend its use at all.
