### ISSUE TITLE
Sheet hangs up when delete last column "XFD"

### ISSUE THREAD

**Issue by mp-4** [xwiki-labs/cryptpad#507]
**Describe the bug**
If you want to hide all columns you dont need (especially the last column "XFD"), the hole pads hangs up.
+
It displays the lines in a "funny" way. (see screenshot - yellow marks)
Maybe only side effect.

**Where did it happen?**
Instance: https://pads.c3w.at/
Should be on the last version.

**To Reproduce**
1. Open a spreadsheet
2. Mark all column you dont need inclusive column "XFD"
3. Rightclick
4. Choose "hide"
5. after clicking - spreadsheet hangs up.

**Expected behavior**
Columns are hidden.

**Screenshots**
Yellow Mark - Side effect on lines.
(white field - only GDPR-compliant) 
![Pads_Spreadsheet_HideColumn](https://user-images.githubusercontent.com/44546897/76786742-02fd0080-67b8-11ea-84d4-2edf740758d1.PNG)

**Browser (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version Version 80.0.3987.132 (64-Bit)
 - Extensions installed (UBlock Origin, uMatrix, HttpsEverywhere)

**Comment by MacLemon** [comment]
We're running CryptPad v3.13.0 (NorthernWhiteRhino) (which is *current* at the time of writing.)

**Comment by MacLemon** [comment]
Here's an [empty sheet](https://pads.c3w.at/sheet/#/2/sheet/edit/e8ktOJlT1ZsqB357GA9VR8gt/) where I followed the instructions to reproduce the issue by scrolling all the way to the last column *XFD*.
I then selected the column by clicking on the column header.
Then I did a secondary click on the selected column and selected “Hide” from the context menu.

The result is a completely collapsed sheet gutter. Interestingly, clicking into the blank area shows a coordinate of XFD#.

Could be an upstream big in OnlyOffice as well.

Reproducible with 
Firefox 74, Chromium 80, Google Chrome 80 with and without extensions.

When I reload the sheet in the browser the collapsed view is completely restored again and the hidden columns are visible again as well.

**Comment by ansuz** [comment]
Thanks for the detailed report! We're going to be working on spreadsheets following tomorrow's release of v3.14.0.

**Comment by davidbenque** [comment]
We've reproduced this, although in most cases hiding the XFD column results in all columns being hidden without the side-effects you are describing. We can also reproduce outside of CryptPad on the [OnlyOffice Demo](https://api.onlyoffice.com/editors/demopreview?type=spreadsheet#DemoPreview) so it's an OnlyOffice bug.

**Comment by mthld** [comment]
Hello,

I can't reproduce this, it must have been fixed some time in the past 2 years.
