### ISSUE TITLE
Allow voting on images in the poll app

### ISSUE THREAD

**Issue by vmassol** [xwiki-labs/cryptpad#508]
Hi,

Would be awesome if we could display images in the poll options to be voted on. Right now we have to store the images elsewhere and give them a reference id and then when voting, keep all the image in one's head, which makes it not so easy.

Thanks for this awesome tool! :)

**Comment by ansuz** [comment]
You can upload images into the poll description. I don't think it would look nice to have it in the table rows.

**Comment by vmassol** [comment]
> I don't think it would look nice to have it in the table rows.

You would resize them ofc so that they're all the same size and so that they're not too large so that you see the various poll lines, and when you click on them you'd get a modal view showing it in a larger format.

**Comment by ansuz** [comment]
Sounds like you have a good idea of what to do next, then. I'll leave you to it.

**Comment by vmassol** [comment]
Sure, I'm on it (just need to finish XWiki first and then I'll do it) ;)

**Comment by vmassol** [comment]
More seriously you do what you want with it. It's just user feedback so you decide how to handle that (close the issue, keep it for later, etc). No hard feeling at all. All I can tell you is that I've tried to use Cryptpad with a poll today, to choose between images and I won't repeat that experience, it was just too painful (actually I didn't even vote because of that so it was a #fail for me, and since I like Cryptpad a lot for other usages, I thought I'd take some of my time to report the idea. And since I really like Cryptad, I'm taking the time to answer with more details ;)).

Note: That poll didn't have images in the desc, they were in some other website. Would it have helped if they had been in the desc? I think so. Would it have been enough? Depends on the number of images to choose from I think. I think it's not as good as having them in the choices. 

What's even possibly more important is that the person who did the poll is not a novice in using Cryptpad and she didn't think about putting the images in the desc. So maybe that should tell you something about the usability. If OTOH, when creating a poll you have the visible possibility to insert an image in the poll choice, maybe that would incite users to use it. idk.

Keep the good job

**Comment by ansuz** [comment]
Thanks!
