### ISSUE TITLE
one persistent data volume instead of 7

### ISSUE THREAD

**Issue by abate** [xwiki-labs/cryptpad#509]
**Describe the bug**

In the docker file you add 7 persistent volumes. 
I'd like to have all the cryptpad data in *one volume* by adding `-v cryptpad-data:/cryptpad`
This clearly does not work as the `start-container.sh` script is also in the `/cryptpad` directory.

My solution would be to either move the `start-container.sh` in `/usr/loca/bin` and leave the
`cryptpad` directory reserved only for persistent data, or move all persistend data in a subdiretory
as `/cryptpad/persistent` that I can bind with a docker volume.

Having one docker volume for all the cryptpad related data would make it easier to backup the data.

**Comment by ansuz** [comment]
Please create docker issues in this community-maintained repository: https://github.com/xwiki-labs/cryptpad-docker as we're in the process of dropping support.

**Comment by abate** [comment]
so the dockerhub repo https://hub.docker.com/r/cryptpad/cryptpad is also going to be abandoned ?
thank you for your quick anser

**Comment by ansuz** [comment]
yes, I only added it in response to pressure from docker users. We never actively tested it or recommended it. [This comment](https://github.com/xwiki-labs/cryptpad/blob/master/config/config.example.js#L3-L20) explains my position.
