### ISSUE TITLE
Read only Rich Text document images still editable locally

### ISSUE THREAD

**Issue by cyphunk** [xwiki-labs/cryptpad#510]
Viewer of a readonly document can change the dimensions of inline images. These changes only effect local viewing. So this is likely not a major bug. Example: Open cryptpad app tutorial read-only document, scroll down to inline image and double click on image to change dimensions.

https://cryptpad.fr/pad/#/1/view/aN5Xj2fXF4FANtYhmiia9g/UKkWIfnnM2YaCScaHW4m4NSADaLY8dWY11+DmvGSkJs/

**Comment by ansuz** [comment]
Good catch. This should be easy to disable, but at present the modifications don't affect the document for anyone else, so I'm not sure when we'll get to fixing this.

**Comment by ansuz** [comment]
This has been merged and deployed as a part of [today's 3.19.0 release](https://github.com/xwiki-labs/cryptpad/releases/tag/3.19.0).
