### ISSUE TITLE
code markdown checkboxes erroniously checked

### ISSUE THREAD

**Issue by cjdelisle** [xwiki-labs/cryptpad#511]
**Describe the bug**
Checkboxes erroniously checked

**Where did it happen?**
https://cryptpad.fr/code/#/2/code/view/bVEekVyr5qYvme0-ghGarTtrqW7yOCka2bfBdorebSw/

**To Reproduce**
1. Go to /code
2. type a checkbox
3. place the word "checked" in the description

**Expected behavior**
it's unchecked

**Screenshots**
see link

**Browser (please complete the following information):**
 - OS: OSX
 - Browser FF Nightly 75.0a1 (2020-02-17) + Chrome 79.0.3945.130
 - Extensions installed: UBlock Origin
 - Browser tweaks -

**Additional context**

**Comment by ansuz** [comment]
I've cherry-picked the fix to master. We have some other server updates to deploy once we get a little downtime in the evening, so we'll update the client at the same time.

**Comment by ansuz** [comment]
The fix has now been deployed to CryptPad.fr
