### ISSUE TITLE
Enlarging / resizing of whiteboard possible?

### ISSUE THREAD

**Issue by r4dh4l** [xwiki-labs/cryptpad#512]
Hi,

sorry, this is not a bug but a help request: Is it possible to enlarge or resize the whiteboard? The default format is not very comfortable for some use cases.

Thx for cryptpad!

**Comment by ansuz** [comment]
I agree that the whiteboard is very limited in its current state. Unfortunately we don't have any funding dedicated towards improving it at the moment and our roadmap is very full with other features. We may be able to fit some minor improvements into our short to medium-term plans, but I can't guarantee it.

**Comment by r4dh4l** [comment]
> We may be able to fit some minor improvements into our short to medium-term plans, but I can't guarantee it.

Thanks for you reply and for considerung the request! :)

**Comment by r4dh4l** [comment]
Just to explain a certain use case: Currently CryptPad is the only FLOSS tool I know which would provide a way for digital classes in mathematics if the pad would could be at least used in landscape mode. Yes, there is BigBlueButton which certinaly provides such features but this software is impossible to host on small servers.

**Comment by ansuz** [comment]
We just deployed an update which allows the canvas to be resized. Obviously there's much more that could be done to improve the app, but I hope this is sufficient in the short term.

**Comment by ansuz** [comment]
[An example](https://cryptpad.fr/whiteboard/#/2/whiteboard/edit/szoajq7Z3VSnf7VhLchoMxby/)

**Comment by r4dh4l** [comment]
> We just deployed an update which allows the canvas to be resized. Obviously there's much more that could be done to improve the app, but I hope this is sufficient in the short term.

THANK YOU SO MUCH - that's why I love FLOSS! That's exactly what I needed! :)

**Comment by ansuz** [comment]
> Next stop: https://opencollective.com/cryptpad/ ;)

Thanks for your support! I'm going to close this issue since it seems to have been resolved.
