### ISSUE TITLE
Read-only link displays old version of document

### ISSUE THREAD

**Issue by Grarap** [xwiki-labs/cryptpad#514]
**Describe the bug**
I have a document which I worked on for some time and it now has the desired layout, even if I close and later reopen that document, i.e. it seems to have been saved properly.
However if I make that same document available for viewing only (embed enabled or not, there is no difference), the document is shown in a much older state, reproducibly so. There is at least an hour of work's difference between the write and the read-only version.

I noticed that sometimes when opening the document in write mode, it will first show an older version of the document but then quickly load all the recent edits (and some unfortunate edits OnlyOffice comes up with to destroy my document but that's a different story).

**Where did it happen?**
On cryptpad.fr.

**To Reproduce**
1. Open the documents. I am not sure how to provide them to you. They are not exactly private but I do not want to post them here in public, at least the editable one.

**Expected behavior**
The document should look the same, whether opened in viewing or writing mode.

**Browser (please complete the following information):**
 - OS: a recent Linux
 - Browser Vivaldi (but same result with Android browser app DuckDuckGo)
 - Version  2.11.1811.47
 - Extensions installed: uMatrix but same result with uMatrix disabled.
 - Browser tweaks: None

**Comment by ansuz** [comment]
It's difficult to debug this without an example spreadsheet to review, but we'll try to investigate. If you ever do want to share access to a particular pad with us you can do so via the support ticket functionality on cryptpad.fr which is encrypted so that only we can read it.

**Comment by ansuz** [comment]
I'm going to close this issue in favour of the more recent duplicate (#543).
