### ISSUE TITLE
Documentation: wiki / Understanding-the-database outdated

### ISSUE THREAD

**Issue by cyphunk** [xwiki-labs/cryptpad#527]
**Describe the bug**
The portion of the wiki that describes how to reverse URL's to datastore files is not working or outdated. If it could be updated that would be great or if not perhaps a note about the documentation being out dated could help.

https://github.com/xwiki-labs/cryptpad/wiki/Understanding-the-database#finding-particular-documents

Executing the suggested code from the wiki and resulting error. Tested on server running v3.15.0

```
require([
    "/common/common-hash.js",
    "/common/common-util.js"
], function (Hash, Util) {
    var data = Hash.parsePadUrl(window.location.href);
    console.log(Util.base64ToHex(data.hashData.channel));
});
ƒ localRequire(deps, callback, errback) {
                    var id, map, requireMod;

                    if (options.enableBuildCallback && callback && isFunction(callback)) {
                      …
common-util.js?ver=3.15.0-1586853142230:178 Uncaught TypeError: Cannot read property 'replace' of undefined
    at Object.Util.base64ToHex (common-util.js?ver=3.15.0-1586853142230:178)
    at <anonymous>:6:22
    at Object.execCb (require.js?ver=2.3.5:1696)
    at Module.check (require.js?ver=2.3.5:883)
    at Module.enable (require.js?ver=2.3.5:1176)
    at Module.init (require.js?ver=2.3.5:788)
    at require.js?ver=2.3.5:1460
Util.base64ToHex @ common-util.js?ver=3.15.0-1586853142230:178
(anonymous) @ VM2322:6
execCb @ require.js?ver=2.3.5:1696
check @ require.js?ver=2.3.5:883
enable @ require.js?ver=2.3.5:1176
init @ require.js?ver=2.3.5:788
(anonymous) @ require.js?ver=2.3.5:1460
setTimeout (async)
req.nextTick @ require.js?ver=2.3.5:1815
localRequire @ require.js?ver=2.3.5:1449
requirejs @ require.js?ver=2.3.5:1797
(anonymous) @ VM2322:1
boot2.js?ver=3.15.0-1586853142230:46 Uncaught Uncaught TypeError: Cannot read property 'replace' of undefined
```

**Comment by vivekvj18** [comment]
@cyphunk 
@ansuz 
Can you direct me how to fix this problem so that i am able to fix it.

**Comment by ansuz** [comment]
We're in the process of moving these pages from the GitHub wiki to our documentation. The page you referenced can now be found [here](https://docs.cryptpad.fr/en/dev_guide/database.html).

In any case, we now display document identifiers in each pad's [properties modal](https://docs.cryptpad.fr/en/user_guide/apps/general.html#properties), so you shouldn't need any custom code in order to find a document.
