### ISSUE TITLE
ONLYOFFICE sheet self-corrupted after refocus / reload

### ISSUE THREAD

**Issue by bfackland** [xwiki-labs/cryptpad#528]
I created my first spreadsheet with CryptPad today (using Brave browser - based on the Chrome engine - on macOS Catalina), containing numbers and formulae. For about 30 minutes, while I was working on it, everything seemed to be going ok. I then returned to the sheet and found that there were numerous "#REF!" and "#VALUE!" cells; here's a snippet (with a couple of numbers deliberately greyed-out):

![Screenshot 2020-04-15 at 11 01 17](https://user-images.githubusercontent.com/2538526/79327108-ce41ad80-7f0b-11ea-9691-5c8924fa62ec.jpg)

You'll also see that at least one column heading (rightmost "Ant. Growth") has started auto-repeating over many rows.

I tried to export the sheet to obtain the data pre-corruption, but the export (XLSX) also contained incorrect data. I tried opening the read-only share URL and export there, but can't do anything with the BIN file right now.

Upon reloading the sheet I found that some of the data was restored, but some rows had been duplicated - e.g. I had 4 rows and now there are 6, two of which have duplicate content.

Overall I think there's a significant issue here with data consistency as it's being stored and read from the server, and/or rendered in the ONLYOFFICE UI.

Hope that's a useful report. Do let me know if you need any further information to debug.

**Comment by ansuz** [comment]
If you're able to share the link to the affected spreadsheet via an (encrypted) support ticket it might help us figure out what went wrong. We've gotten similar reports from a few other users, but so far we haven't had enough data to isolate the problem.

**Comment by ansuz** [comment]
We've addressed this issue and a number of related issues in our more recent releases, so I'm going to close this.
