### ISSUE TITLE
Eraser tooltip in trash misleading

### ISSUE THREAD

**Issue by keunes** [xwiki-labs/cryptpad#531]
**Describe the bug**
I moved an owned file to the trash. Once it's there, I can't seem to delete it from the server. I can only 'Remove from my CryptDrive', which supposedly (like with not-owned pads) just deletes them from my overview but keeps them on the server.

... Except that this isn't true, and the eraser in fact removes the file from the server (at least, if I may believe the modal window that's shown after clicking on the icon).

**Where did it happen?**
On CryptPad.fr

**Expected behavior**
Eraser tooltip says 'delete from server' for owned files in the trash.

**Comment by ansuz** [comment]
As with #532, this is addressed in our [3.20.0 release](https://github.com/xwiki-labs/cryptpad/releases/tag/3.20.0).
