### ISSUE TITLE
Tell what happens if I empty the trash

### ISSUE THREAD

**Issue by keunes** [xwiki-labs/cryptpad#532]
I suspect owned files will be removed from server, and other files are removed from my CryptDrive overview (and may become orphaned if nobody else picks them up). For me as a new user this isn't immediately clear. It would be helpful to have a small explanatory sentence in the modal window.

**Comment by ansuz** [comment]
We spent some time improving the workflow and text related to emptying the trash and the deletion of owned files as a part of our [3.20.0 release](https://github.com/xwiki-labs/cryptpad/releases/tag/3.20.0).
