### ISSUE TITLE
Latest docker image on docker hub does not work

### ISSUE THREAD

**Issue by Xefir** [xwiki-labs/cryptpad#534]
**Describe the bug**
The latest docker image get this error on start and stops immediately : 
`/sbin/tini: 2: /sbin/tini: Syntax error: newline unexpected`

**Where did it happen?**
On my instance, when I update my image with a docker pull.
Right now, sadly, my instance show a 502 bad gateway : https://pad.crystalyx.net

**To Reproduce**
1. Run `docker run -it cryptpad/cryptpad`
2. The error will appear instead of launching the container.

**Expected behavior**
The container should run.

**Screenshots**
Not needed.

**Browser/Smartphone (please complete the following information):**
 - OS: Linux (Debian) and macOS with the latest Docker
 - No browser needed

**Additional context**

**Comment by ansuz** [comment]
My comment on [this PR](https://github.com/xwiki-labs/cryptpad/pull/523#issuecomment-611044181) explains our policy on docker. Essentially we don't use it ourselves and don't recommend that anyone does. We have neither the time nor the budget to support it.

I recommend to either migrate your instance to install from source or to contribute to the [cryptpad-docker](https://github.com/xwiki-labs/cryptpad-docker) repo so we can finally remove the unsupported docker files from this repository.

**Comment by zem** [comment]
I did start a  fork of cryptpad-docker  here: https://git.conesphere.cloud/conesphere/podman/hub/cryptpad with recent builds once in a week and about 2-3 systems running from that source. 

As the name suggests my image is running with podman. ;-)

You can use that image with podman or docker by using 

registry.conesphere.cloud/conesphere/podman/hub/cryptpad:latest
