### ISSUE TITLE
Can't print text documents

### ISSUE THREAD

**Issue by nleecp** [xwiki-labs/cryptpad#535]
**Describe the bug**
Printing correctly a multi-page text document into a PDF is not possible anymore. It only prints out the first page, overflow is hidden.

**Where did it happen?**
On public instance cryptpad.fr, since yesterday's update (the one that brings up the "centered page" look into text documents edition interface.

**To Reproduce**
1. Create/Open a text document long enough to span on several pages (e.g. with this Lipsum doc : https://cryptpad.fr/pad/#/2/pad/edit/xDLvbkDGnM2G1EoCTQLtzUkS/ )
2. Click on the "print" icon in the icon bar, try to print into a pdf file
3. the output PDF only has the first page of the document (even with the scrollbars with Chrome)

**Expected behavior**
The PDF should contain the whole document.

**Screenshots**
https://hostpic.fr/uploads/20200422/77f4760a35bf152a0903b21295d7af8f17c58bc0.png

**Browser (please complete the following information):**
 - OS: Windows 10 1709
 - Browser : 
   - Firefox 75.0 (64 bits), with uBlock Origin
   - Chrome 81.0.4044.122 (official build) (64 bits), no extensions

**Additional context**
I tried printing in PDF with PDFCreator and Chrome's built-in PDF export printer.

**Comment by ansuz** [comment]
This has been fixed in our 3.18.0 release, deployed to https://CryptPad.fr on Wednesday, May 27th, 2020.
