### ISSUE TITLE
Spreadsheet data corrupted: moved/removed

### ISSUE THREAD

**Issue by apfeltaschen** [xwiki-labs/cryptpad#536]
**Describe the bug**
Made a spreadsheet directly in cryptpad. 
When i returned to spreadsheet the next day extra rows had been added, data had been moved/duplicated in the spreadsheet, and some data had been removed. 

**Where did it happen?**
The issue occur on CryptPad.fr 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Browser (please complete the following information):**
 - OS: Mac OSX
 - Browser: Chrome
   - variations [e.g. Firefox nightly, Firefox ESR, Chromium, Ungoogled chrome]
 - Version 80
 - Extensions installed (UBlock Origin, Passbolt, LibreJS]
 - Browser tweaks [e.g. firefox "Enhanced Tracking Protection" strict/custom mode, tor browser "safer" security level, chrome incognito mode]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ansuz** [comment]
We're working on a fix for this and hope to include it in a minor release once the fix is finished.

**Comment by laxman18a** [comment]
Same thing happened to me. My spreadsheet was open over night. When I came back to it I saw a message that there is an update available. I reloaded the page and everything on the worksheet was screwed up. When I refresh the page for the first few seconds I see the worksheet as it is suppose to be, but after that cells/rows get added, deleted, replaced, etc. I can send screenshots privately.

**Comment by cyphunk** [comment]
Same issue has been happening to me for a while. Can confirm issue still persists on latest release (3.17.1). Notice in the following recording: page is reloaded, upon reload it shows two sheet tabs, with current second tab selected. The data shown is correct for this tab. Then after a second the tab is removed, still showing the second tab data. Then as we scroll up and back down the second tab data is removed and first tab data shown. The tab data for the first tab shown is correct but now we can no longer find or access the second tab as it has been removed.

![Peek 2020-05-13 10-02](https://user-images.githubusercontent.com/119662/81787864-f10eb400-9501-11ea-94c2-2ca01c7a450c.gif)

Note: this spreadsheet was created some time about (a couple months ago)

**Comment by ansuz** [comment]
I'm closing this issue in favour of the more recent #547 for increased visiblity.
