### ISSUE TITLE
If pdf.js thumbnail code fails, file upload fails silently

### ISSUE THREAD

**Issue by ldubost** [xwiki-labs/cryptpad#540]
**Describe the bug**

For a specific PDF file, there seems to be a pdf.js error in the console which seems to block the upload and as well all further uppload.
The error is silent with no feedback to the user

**Where did it happen?**
cryptpad.fr

**To Reproduce**

1. Drive, Documents folder
2. Drag and drop specific pdf (I can only share it privately)
3. Nothing happens

Open the console. See the following messages

Warning: EvalError: call to Function() blocked by CSP pdf.worker.js:344:13
Warning: getOperatorList - ignoring errors during task: RenderPageRequest: page 0
Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à eval (« script-src »).

**Expected behavior**
File should be uploaded

**Browser (please complete the following information):**
 - OS: OSx
 - Browser Firefox 
 - Version 75
 - Extensions installed UBlock Origin, Passbolt
 - Browser tweaks many

I believe it is the thumbnail code which is not checked for failure and then it blocks the upload.

**Comment by ansuz** [comment]
This was fixed as a part of our [3.17.0](https://github.com/xwiki-labs/cryptpad/releases/3.17.0) release.
