### ISSUE TITLE
cannot upload xlsx table to sheet

### ISSUE THREAD

**Issue by private-lock** [xwiki-labs/cryptpad#548]
**Describe the bug**
Firefox - clean profile:
By default, the file-selector only offers to take *.bin
Switching to all, I get the Error message: This file cannot be uploaded.
On OK I'm back to the table.

Using a *.bin file instead, as directly exported from crpytpad, I get the same behavior as in chromium below.

Chromium with ublock:
On upload of an xlsx file after some processing, I get a "Server-error: The file cannot be uploaded."
On OK a second empty dialog is shown only with an OK button.
Clicking OK again, I am back to the "import-spinner", that turns endlessly.
After reload of the browser, I see the empty table again - nothing was imported.

**Where did it happen?**
reproduced in:
https://cryptpad.fr/sheet
https://cryptpad.piratenpartei.de/sheet

**To Reproduce**
1. I created a simple table (single sheet, no formatting, plain ascii data, no formula) and exported it in both formats bin and xlsx
2. source: https://cryptpad.fr/sheet/#/2/sheet/edit/KgGuj8Bp05YFeL5qRGMkK5UR/
3. saved the file to disk (and verified, the xlsx opens fine in libreoffice-calc)
4. (optional I can modify and save it again by libreoffice-calc)
5. created a new table sheet and tried to import it back to cryptpad
6. See error

**Expected behavior**
I wanted to exchange data between a cryptpad-sheet and my local Calc to work offline. Download succeeds and upload should reproduce the same table.

**Browser (please complete the following information):**
 - OS: Kubuntu 19.10
 - Browser Firefox 76.0.1 & Chromium 81.0.4044.138
 - Extensions installed (UBlock Origin, Passbolt, LibreJS]

**Additional context**
Already tried few days ago, was notified of "new cryptpad-version" in a tab I kept open since. But the error did not go away.

**Comment by ansuz** [comment]
It's possible you experienced the same problem as was mentioned in [this issue](https://github.com/xwiki-labs/cryptpad/issues/515). We've deployed a new version of the import code which allocates more memory as necessary rather than failing when the importer's conversion process needs more than was originally allocated.

I've successfully tested this with a number of spreadsheets. If the issue persists on your side could you please:

1. close all your CryptPad tabs
2. disable your browser extensions
3. try again

**Comment by private-lock** [comment]
Import for anonymous users was removed.
Import for logged-in users seems to work now - at least Chrome could import XLSX, Firefox still only accepts BIN format.
