### ISSUE TITLE
Kanban: tasks temporarily disappear

### ISSUE THREAD

**Issue by dafqs** [xwiki-labs/cryptpad#551]
**Describe the bug**
If I delete a task in the kanban, the next one also disappears. Only a manual refresh brings back the undeleted one.

**Browser (please complete the following information):**
- Cryptpad.fr, Version 3.17.1
 - OS: Windows 10
 - Browser Chrome, Firefox, Opera (newest version)

(But I really like the kanban tool.)

**Task 1 is deleted**
![task1](https://user-images.githubusercontent.com/65040381/82466332-8f7db500-9ac0-11ea-983e-1fb7d3e2ea42.png)

**Task 1 and Task 2 disappear**
![task2](https://user-images.githubusercontent.com/65040381/82466343-93113c00-9ac0-11ea-81bd-2b183696b8c5.png)

**Comment by ansuz** [comment]
This should have been addressed in our latest release (3.18.0). I'm going to close this issue, but please follow up if you still experience the issue when using 3.18.0 or later.
