### ISSUE TITLE
Cryptpad version number not visible

### ISSUE THREAD

**Issue by 101100** [xwiki-labs/cryptpad#554]
**Describe the bug**
The CryptPad version number is not visible anywhere I could find in the application. (It can be seen via `https://hostname/api/config`, but that isn't user-facing.) For those running their own instances, it is not possible to see what version you are running.

**Where did it happen?**
This happens everywhere, but is only relevant to those running their own server (or using someone's personal server).

**To Reproduce**
N/A

**Expected behavior**
I would expect that the version would appear at least on the home page and possibly the administration section and the drive.

**Screenshots**
N/A

**Browser (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by ansuz** [comment]
Hi,

The version is displayed in the footer of the home page (pictured below):

![Screenshot from 2020-05-28 13-28-53](https://user-images.githubusercontent.com/1264398/83173674-3e387b80-a0e7-11ea-81b6-ee46bd31acdc.png)

It's similarly displayed in all of the other static pages that have a similar footer (faq.html, privacy.html, etc.).

That being said, it's not readily available in any of the editors. We were planning to include this information somewhere in the user administration menu (the dropdown in the top-right corner) as of our next release (3.19.0).

**Comment by 101100** [comment]
Ah, thanks for pointing it out.  I didn't notice that footer on my search.  This can be closed from my perspective.

**Comment by ansuz** [comment]
Thanks!
