### ISSUE TITLE
Design: add more borders, border radius, shadows, paddings, margins, etc.

### ISSUE THREAD

**Issue by yannicka** [xwiki-labs/cryptpad#555]
Currently, there are only a few borders, shadows, radius, etc., in the area of the building. I think it could be improved.

I'm not a webdesigner but rather a developer, however here's an idea of design improvement that I would like to propose.

The current rendering:

![Screenshot_2020-05-29 Texte - ven 29 mai 2020](https://user-images.githubusercontent.com/22885898/83295352-1a605d00-a1ef-11ea-8e2b-3666cb58dd0a.png)

![image](https://user-images.githubusercontent.com/22885898/83296317-e2f2b000-a1f0-11ea-8a67-e86c28ecf805.png)

The modified rendering:

![Screenshot_2020-05-29 Texte - ven 29 mai 2020(1)](https://user-images.githubusercontent.com/22885898/83295358-1cc2b700-a1ef-11ea-9f8f-62ff9ff2cf07.png)

![image](https://user-images.githubusercontent.com/22885898/83296287-d1a9a380-a1f0-11ea-8659-ab2521ffe3ee.png)

Of course, everything is not perfect, and there should probably be an overall guideline, but here's one area for improvement that I would suggest.

I open a ticket rather than a PR in order to know if you want help on this subject or if you already know where you are going.

Anyway, I can help on this subject if you wish.

**Comment by davidbenque** [comment]
Many thanks for your feedback. The redesign of the last release is a first step towards a more simple and useable CryptPad UI where the use of colour is more considered.

I agree that the area of the user-list and chat could use some more contrast. At the moment there are too many shades of grey in there. We have further improvements lined up for this part of the UI in the coming releases, namely merging the user-list and chat together. We will take this opportunity to refine the design.

**Comment by yannicka** [comment]
As I said, I'm not a webdesigner, but don't hesitate if you need feedback or help on this subject.

**Comment by mthld** [comment]
Hello,

We released [CryptPad v5](https://github.com/xwiki-labs/cryptpad/releases/tag/5.0.0) in June, it improves the design, introducing rounded corners, a more subtle use of colors, and some updated icons.

I'm closing this issue now. 😊
