### ISSUE TITLE
Email addresses can't be enclosed in code blocks.

### ISSUE THREAD

**Issue by johnnymatthews** [xwiki-labs/cryptpad#556]
**Describe the bug**
In a code document, email addresses surrounded by code blocks ` the email address doesn't get formatted as code.

**Where did it happen?**
This issues happens in CryptPad Code editor, in Firefox 76.

**To Reproduce**
1. Create a new Code editor in CryptPad.
2. Enter an email address and surround it in a code block (using back-ticks ``)
3. The markdown preview will show the email address _not_ in a code block.

**Expected behavior**
Everything between back-ticks should be previewed within code blocks.

**Screenshots**

![image](https://user-images.githubusercontent.com/9611008/83421986-e2c40180-a3f6-11ea-8ace-5b447022ff1f.png)

**Browser (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 76
 - Extensions installed: none, this still happens in Private Browsing with no extensions enabled.
 - Browser tweaks: none.

**Additional context**
Can't think of anything. Happy to answer questions.

**Comment by ansuz** [comment]
This was reported in [marked #1218](https://github.com/markedjs/marked/issues/1218) and subsequently fixed. I'm testing an update to the latest version of the library (1.1.0) from what we've been using (0.5.0) and can confirm it fixes this issue, but changes some unspecified behaviour that users might be relying on. In any case, I think it's worth the update, so you can expect this to land in our next release.

**Comment by johnnymatthews** [comment]
That was super fast! Thanks @ansuz! Not sure what your _closing process_ is, but I'm happy if you want to close this issue now since it'll end up in production some time soon.

**Comment by ansuz** [comment]
Usually I leave tickets open until the fix is merged to our master branch.

**Comment by ansuz** [comment]
This has been merged and deployed as a part of [today's 3.19.0 release](https://github.com/xwiki-labs/cryptpad/releases/tag/3.19.0).
