### ISSUE TITLE
Upload Image dialog in Sheet doesn't present an image upload button

### ISSUE THREAD

**Issue by anoadragon453** [xwiki-labs/cryptpad#557]
**Describe the bug**
In a sheet, I clicked Image->Insert and received this dialog:

![image](https://user-images.githubusercontent.com/1342360/83637201-1c377100-a59f-11ea-818e-57dfb1ddb09d.png)

How do I "upload a new one"?

**Where did it happen?**
cryptpad.fr

**To Reproduce**
1. Go to a new sheet
2. Click on the "Insert" tab
3. Click on "Image"
4. Be unable to upload a new image

**Expected behavior**
In addition to pulling from CryptDrive, having a button that lets you upload an image from your hard drive.

**Browser (please complete the following information):**
 - OS: Debian Linux
 - Browser: Firefox Nightly
 - Version: 78.0a1
 - Extensions installed: None
 - Browser tweaks: Not in private mode

**Comment by ansuz** [comment]
File uploads are restricted to registered users, so it might just be that you haven't registered or aren't logged in.

I've updated this modal to display a disabled upload button stating as much on our `staging` branch.

**Comment by anoadragon453** [comment]
Ah, no I was not logged in, so this was likely the case :)

**Comment by ansuz** [comment]
This has been merged and deployed as a part of [today's 3.19.0 release](https://github.com/xwiki-labs/cryptpad/releases/tag/3.19.0).

**Comment by anoadragon453** [comment]
Looks great, thank you!
