### ISSUE TITLE
oodoc and ooslide not working at all

### ISSUE THREAD

**Issue by phoerious** [xwiki-labs/cryptpad#558]
**Describe the bug**
I know that both oodoc and ooslide are highly experimental and not enabled by default. They do not even have translation strings. I was wondering, though, if they were supposed to work at all.
I can open them and I can edit text, but after a few seconds I am usually getting an error "An unrecoverable error occurred" and the page reloads. None of my changes are saved, even if I exit before the error pops up. The document I open is always blank. However, I have seen non-blank documents in other CryptPad instances (but perhaps they were just uploaded .docx files or something).

Collaborative editing doesn't seem to be working either. Everybody is just working on their own blank copy which they are unable to save.

Perhaps your answer is "No, none of that works yet and we know about it", in which case feel free to close it or take it as a feature request. I couldn't really find any statement about the state of oodoc or ooslide in CryptPad on the web except the one that it's "highlight experimental". This is beyond highly experimental, though.

**Where did it happen?**
Two independent custom instances.

**Browser (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome, Edge
 - Version Newest
 - Extensions installed Ghostery / None
 - Browser tweaks None

**Comment by ansuz** [comment]
Hi,

We don't recommend using them at all in their present state.

We do plan to enable them by default in the future, but until we have [the various spreadsheet issues](https://github.com/xwiki-labs/cryptpad/issues?q=is%3Aissue+is%3Aopen+label%3Aspreadsheets) under control we won't have the time or resources to maintain their added functionality.
