### ISSUE TITLE
Suggestion: Security -  optional remove version information

### ISSUE THREAD

**Issue by cyphunk** [xwiki-labs/cryptpad#559]
**Describe the bug**
Currently easy to determine version of installed instance and then search for known vulnerabilities against that version. While perhaps not relevant now it could be relevant in future. Speaking from experience as a security analyst and OSINT practitioner, a lazy attacker will find version and quickly search CVE's. (e.g. <script type="text/javascript" charset="utf-8" async=" data-requirecontext="_" data-requiremodule="/api/config" src="/api/config?ver=**3.18.1**-...>). Removing this information would increase effort required by forcing attacker to download a set of versions of the source code from cryptpad github repo and comparing with dates, directory structures or file hashes of installed version.

**Where did it happen?**
Any instance of cryptpad

**To Reproduce**
1. Go to instance front page and find version at bottom, look in source of page for version strings or date codes.

**Expected behavior**
Option in install to remove date and version information from public facing code and interface.

**Comment by ansuz** [comment]
I was able to find plenty of resources for hiding version strings via configuration, but it seems like the jury is still out on whether application developers should adopt this practice. There are points and counterpoints [here](https://security.stackexchange.com/a/53064).

> As a mail-system admin, I think it's prudent show the major version number; a number of times I've solved deliverability issues to other sites just by researching common problems with the major version, which eliminates the need to do extensive troubleshooting with the remote site's Postmaster(s).
>
> In practical terms, the security benefit here is minimal (security through obscurity, as mentioned). Good patching, appropriate system isolation, well-configured firewalls and a host of other Best Practices that can be implemented would make your server considerably more secure and would render any benefit (real or perceived) of this change moot.

We often find ourselves in this situation ^, where admins ask us to help diagnose their problems, and the first thing I check is the version they're running. Furthermore, this seems at odds with [this issue](https://github.com/xwiki-labs/cryptpad/issues/554) explicitly requesting that we make it more visible.

In any case, the version string is distributed in only two places:

1. From the `/api/config` server endpoint, generated [here](https://github.com/xwiki-labs/cryptpad/blob/master/server.js#L222)
2. [In the client's footer](https://github.com/xwiki-labs/cryptpad/blob/master/customize.dist/pages.js#L65), hardcoded into the source for each release

I'd be willing to move the second instance to into the same block as the first and have an easy option to disable it, but I don't consider this high priority. Attackers generally try every known attack, not just attacks known to work against a known version, and there are other means of fingerprinting an instance.

**Comment by cyphunk** [comment]
You rightly point out the primary hesitation is support. Hiding version information by default would create support headaches. Also I also understand that it could break things when turned off in the API and paranoid admins like myself that turn off and then several years later forget that we did that and then when the API breaks as a result neither myself nor support would know why. I think though that here you gave enough information should one want to turn off version than they could do so.

I agree also version recovery is not difficult. I've done it for OSINT projects various times. But each time there is a hesitation that is relevant. 

Also the way that "security through obscurity is not obscurity" is used is often counter productive in a way that reduces use-cases and context. In sensitive infrastructure and critical components, version strings, symbol tables, anything clear text, are typically filed as "information disclosure" findings. Mitigating those findings is not called "obfuscation". 

But still, in conclusion, I agree support is probably as important or more important to consider.

**Comment by ansuz** [comment]
> But still, in conclusion, I agree support is probably as important or more important to consider.

That being the case, I'm going to close this. If you'd like to document this in the GitHub wiki I think that would be an appropriate solution for other admins with this concern.
