### ISSUE TITLE
Embarassing question

### ISSUE THREAD

**Issue by slowonthechildproof** [xwiki-labs/cryptpad#561]
I have a feeling this is a me issue and as i'm a new user i need help.

on cryptpad desktop version (macOS) i can't seem to edit any sheets. Once the file loads everything is greyed out and i can't input text or do anything other than name the sheet and there is a + symbol where there should be an arrow. 

I know i'm doing something really stupid. i just want to make a shareable spreadsheet on cryptpad. It works on IOS but hate making spreadsheets on a phone. 

i also attempted to make a spreadsheet elsewhere and upload an editable version on cryptpad and it doesn't work either.

 please help. thank you.

**Comment by ansuz** [comment]
Hi,

Can you please clarify what browser you're using? Do you have any extensions installed? Would you mind uploading a screenshot so I can see what you mean about the `+` symbol where there should be an arrow?

**Comment by slowonthechildproof** [comment]
Sure, using firefox 77.0.1 no extensions and attaching screenshots of everything being greyed out and the + situation.
![cryptpad sshot01](https://user-images.githubusercontent.com/66761135/84412363-27148600-abdd-11ea-8492-5a89fb4705f5.jpeg)

<img width="1106" alt="cryptpad sshot 02" src="https://user-images.githubusercontent.com/66761135/84412434-3e537380-abdd-11ea-8a97-d1509c20c304.png">

**Comment by ansuz** [comment]
Thanks for the images.

It seems like there are more problems than just the spreadsheet's toolbar, as there should normally be more elements in the main CryptPad toolbar. 

For instance, you don't have a user admin menu or notifications icon, as pictured below:

![Screenshot from 2020-06-12 12-17-00](https://user-images.githubusercontent.com/1264398/84524207-98207000-aca7-11ea-85a1-7573f56e09fb.png)

Similarly, you should see buttons which toggle the presence of the chat interface and user list, both of which are absent.

![Screenshot from 2020-06-12 12-17-26](https://user-images.githubusercontent.com/1264398/84524184-8b038100-aca7-11ea-9ce1-84e07fc108c2.png)

Can you please check and see if this is the case in the other editors (rich text, code)?

I'm using the exact same browser, and I've tested with my extensions disabled, so it might be that it's related to your account. Could you also try editing a document in another browser (logged out) and logged in using the same account?

Thanks in advance.

**Comment by slowonthechildproof** [comment]
Ok, so Rich Text and code both work fine in firefox as is, it just seems to be sheets that i can't input anything. I do have the info to the right and upper toolbar, chat, profile name, etc. Tried it on safari and it works fine. Sounds like i need to adjust settings in firefox? Any insight as to what might be holding me up there? thanks.

**Comment by ansuz** [comment]
> Sounds like i need to adjust settings in firefox? Any insight as to what might be holding me up there? thanks.

I haven't been able to trigger that behaviour using the same version of Firefox. If you've made any advanced tweaks to your settings I'd start by looking there. You might also want to look in your Firefox developer console to see if there are any errors displayed.

**Comment by slowonthechildproof** [comment]
Ok, so Rich Text and code both work fine in firefox as is, it just seems to be sheets that i can't input anything. I do have the info to the right and upper toolbar, chat, profile name, etc. Tried it on safari and it works fine. Sounds like i need to adjust settings in firefox? Any insight as to what might be holding me up there? thanks.
