### ISSUE TITLE
Spreadsheet Filter/Sort broken in beta builds of Firefox and Chrome

### ISSUE THREAD

**Issue by carimura** [xwiki-labs/cryptpad#562]
Seems like filtering and sorting are pretty broken in beta builds of Firefox (78b) and Chrome. Just a heads up. I switched to Firefox 77.0.1 and they're working fine again.

This is hosted on Cryptpad.fr

**Comment by ansuz** [comment]
Thanks for the warning! We used to see rendering and js regressions more regularly, so we might be overdue.

Can you clarify what you mean by broken? Are they displayed incorrectly or do they not work at all? Maybe a screenshot would be the easiest.

**Comment by carimura** [comment]
It's a little weird, both filter and sort just stopped working. I would hit the filter and/or sort buttons (or use the menu items) and nothing would happen. I can try and reproduce later and take a video if you have a hard time reproducing.

**Comment by ansuz** [comment]
I have nightly installed, I'm just not familiar with the differences between it and beta. A screenshot would be easier, but I'll dig deeper on my own if I get the chance.

**Comment by smokyblisters** [comment]
I've occasionally run into this issue with Chrome (not beta build). 

It appears to occur after using the ctrl+z / undo function, but only if the undo function crashes the spreadsheet. By crash, I mean the user is unable to edit the spreadsheet after using the undo feature and has to reload the spreadsheet in the browser. (Crashes usually occur if you use the undo function too many times in a row.) After reloading, the file can be edited again but the filter/sort feature doesn't work. It doesn't permanently affect files in my experience, but I have to log out of CryptDrive and log back in to reset the filter/sort feature.

**Comment by ansuz** [comment]
This was fixed in our 4.2.0 release.
