### ISSUE TITLE
Large image import into whiteboard

### ISSUE THREAD

**Issue by Murmele** [xwiki-labs/cryptpad#563]
**Describe the bug**
When importing an image into the whiteboard, which is to large, an error message is shown that the image is too large, but no information if the pixel size is too large, or the image file.

**Where did it happen?**
CryptPad.fr

**To Reproduce**
1. Open a new whiteboard
2. Import a large image for example this one:
![2020-06-08_22-38](https://user-images.githubusercontent.com/10099533/84564237-3c1a2200-ad61-11ea-82ed-f4ad690dfb55.png)

3. See error message "File too large"

**Expected behavior**
Seeing if the pixel size is too large or the file size. Seeing the maximum size which can be imported

**Screenshots**

**Browser (please complete the following information):**
 - OS: Linux
 - Browser firefox
 - Version 77.0.1

**Comment by ansuz** [comment]
The limit is currently hardcoded to 1MB (1024KB). I've made a note to display the limit along with the error message we currently display.

**Comment by Murmele** [comment]
Thank you :)
