### ISSUE TITLE
Image drag and drop blocks onlyoffice documents

### ISSUE THREAD

**Issue by ldubost** [xwiki-labs/cryptpad#566]
**Describe the bug**
If in a spreadsheet or in ooslide (app not activated yet) you drag and drop an image, it will fail and block the document. A reload of the page is necessary.

In the console the stack trace is:

TypeError: window.parent.APP.UploadImageFiles is not a functionsdk-all-min.js:627:169
    UploadImageFiles https://meet-alpha-sandbox.cryptpad.fr/common/onlyoffice/v2a/sdkjs/cell/sdk-all-min.js:627
    _uploadCallback https://meet-alpha-sandbox.cryptpad.fr/common/onlyoffice/v2a/sdkjs/cell/sdk-all-min.js:1490
    _onEndLoadSdk https://meet-alpha-sandbox.cryptpad.fr/common/onlyoffice/v2a/sdkjs/cell/sdk-all-min.js:1501
    ondrop https://meet-alpha-sandbox.cryptpad.fr/common/onlyoffice/v2a/sdkjs/cell/sdk-all-min.js:627

**Where did it happen?**
Cryptpad.fr instance and local instance

**To Reproduce**
1. Open a spreadsheet document
2. Drag and drop an image from your desktop
3. A popup "image loading" is showing and an error pops up in the console

**Expected behavior**
At least not an error or the upload of the image

**Browser (please complete the following information):**
Tested on Firefox on MacOSX but the error should be every where

**Comment by ldubost** [comment]
A fix that will avoid breaking is to add

// Image uploads in office files
 APP.UploadImageFiles = function(files, documentId, documentUserId, jwt, callback) {
 }

in www/common/onlyoffice/inner.js

This will not handle the upload of the images which is more complex

**Comment by ansuz** [comment]
The fix for this has been merged to our `main` branch and deployed as part of our [3.20.0 release](https://github.com/xwiki-labs/cryptpad/releases/tag/3.20.0).
