### ISSUE TITLE
Adding mathjax support in code pad

### ISSUE THREAD

**Issue by ldubost** [xwiki-labs/cryptpad#571]
Using the following syntax

```mathjax
(x = {-b \pm \sqrt{b^2-4ac} \over 2a})
```

It would be nice to support svg rendering using mathjax

**Comment by ansuz** [comment]
This has been merged to our `main` branch and deployed as part of our [3.20.0 release](https://github.com/xwiki-labs/cryptpad/releases/tag/3.20.0).
