### ISSUE TITLE
Update documentation: Run Cryptpad as a dedicated user

### ISSUE THREAD

**Issue by lazyteddy** [xwiki-labs/cryptpad#574]
Hi all,
I successfully installed my own instance, and it really was a breeze to get everything up and running, so thank you.

There is one thing I noticed, though, that surprised me: the documentation does not specify creating a dedicated user. I *really* dislike running web apps as root, so I created a user with --disabled-login and modified the systemd init file accordingly. I was wondering if there's a specific reason not to do it this way; I haven't run into any problems so far, so this seems to make more sense. Maybe the documentation could be updated accordingly?

Thanks for your great work :-)

**Comment by ansuz** [comment]
I agree that it's best to only run apps as root if absolutely necessary and that isn't the case with CryptPad. The example systemd service file we provide references a `cryptpad` user, but we don't explicitly say how to do that.

We recently published a [user guide](https://docs.cryptpad.fr) that we've been working on for a while, and we plan to publish an admin guide in the coming months. When we get around to that we'll make a note warning against running as root and indicating how to create a user.

I take for granted that people don't just go around running random software as root, so thanks for the reminder :wink:

**Comment by ansuz** [comment]
For context, the systemd service file is [here](https://github.com/xwiki-labs/cryptpad/blob/main/docs/cryptpad.service#L17).

**Comment by ansuz** [comment]
A warning about running CryptPad as root is included in [this section](https://docs.cryptpad.fr/en/admin_guide/installation.html#install-cryptpad) of our recently released docs.
