### ISSUE TITLE
Attempting to delete pad history results in an error

### ISSUE THREAD

**Issue by rag93** [xwiki-labs/cryptpad#576]
**Describe the bug**
Attempting to delete the history of a pad results in a red error message that says "Error while deleting history", which eventually leads to a pad becoming unusable if the history gets long enough to make the document lag significantly.

**Where did it happen?**
Cryptpad.fr

**To Reproduce**
1. Open a pad
2. Click on File>Properties
3. Click red "Delete History" Button
4. Click again to confirm
5. See error

**Expected behavior**
That clicking delete history would delete the document history

**Screenshots**
![image](https://user-images.githubusercontent.com/39537389/87114221-0d974600-c23e-11ea-9a46-d4869d860597.png)

**Browser (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 78.0.1
 - Extensions installed: Ublock , but error persisted after Ublock was disabled
 - Browser tweaks: None

**Additional context**
This was tested on multiple pads, all of which had the same error.

As mentioned above, this issue leads to significant lag with longer / older documents. An alternative fix would be adding an option to disable history, preventing it from being recorded or taking up document memory.

It is also possible that this is related to several other errors that have occurred recently when attempting to do things that deleted document history, for example adding a password after creating a document also results in an unspecified error. Will try to submit bug logs for those too when I get a chance.

**Comment by ansuz** [comment]
I believe this issue should have been addressed in a previous release.
