### ISSUE TITLE
Unable to change password of pad

### ISSUE THREAD

**Issue by rag93** [xwiki-labs/cryptpad#577]
**Describe the bug**
When trying to change the password of a pad or add a password to a pad that previously did not have one, it throws a popup that says "An error occurred while trying to change the password. Please try again.". (Trying again results in the same thing)

**Where did it happen?**
Cryptpad.fr

**To Reproduce**
1. Create a pad/open an existing pad
2. Click on Access
3. Add a password or attempt to change a password
4. Press the Submit button
5. Press "OK" for the confirmation dialogue
6. See error

**Expected behavior**
The password will change properly

**Screenshots**

![image](https://user-images.githubusercontent.com/39537389/87210565-00cd2d80-c2e4-11ea-98de-d4abef648f73.png)

**Browser (please complete the following information):**

 - OS: Windows
 - Browser: Firefox
 - Version: 78.0.1
 - Extensions installed: Ublock , but error persisted after Ublock was disabled
 - Browser tweaks: None

**Additional context**
Tested on multiple pads, you can create a pad with a password just fine but attempting to add a password or change a password results in error. 

Suspect this may be related to issue #576 , as changing the password is also supposed to delete the history.

**Comment by ansuz** [comment]
We fixed a bug that caused this behaviour when the document in question was protected by an access list. I'll close this, but please re-open the issue if you can reproduce on CryptPad.fr
