### ISSUE TITLE
Can't Export a Text Pad to a ".doc" document.

### ISSUE THREAD

**Issue by AnneJuin** [xwiki-labs/cryptpad#578]
Hello

**Describe the bug**
I'm testing Drycat and I would like to export the documents I made to my computer (Windows 10, working on Firefox 78.0.2 64bits). 

I click on the "File" menu in the colored menu bar
Click on "Export".
A window opens, where I can choose between exporting to a .html link, or a .doc document. 
I select the ".doc" option and then click on the "OK" button (it says that you can simply press on your "entry" button on your keyboard but doesn't work on mine)

The window closes itself and then nothing more happens. I can't find the .doc document anywhere on my computer, nor on Drycat.

**Where did it happen?**
The issue occurs on https://pad.drycat.fr/pad/#/3/pad/edit/

**Expected behavior**
I expect to get a .doc document exported on my computer.

**Browser (please complete the following information):**
 - OS: Windows 10
 - Browser : Firefox
 - Version : 78.0.2
 - Extensions installed : Adblock, VPN
 - Browser tweaks : firefox "Enhanced Tracking Protection" custom mode

**Comment by ansuz** [comment]
It seems the drycat instance is configured incorrectly. .doc export should work as expected on https://cryptpad.fr.

Perhaps you could contact the admins and suggest that they visit our matrix channel if they need help correcting their configuration issues.
