### ISSUE TITLE
Unable to register

### ISSUE THREAD

**Issue by jframeau** [xwiki-labs/cryptpad#579]
Using Firefox 78.0.2 on Linux CentOS 7, I'm not able to register an new account.

![image](https://user-images.githubusercontent.com/498115/87454010-b01b4480-c603-11ea-8a50-44277281d830.png)

Is there something I need to configure on my Firefox ?

Thx

**Comment by ansuz** [comment]
CryptPad downloads static assets (HTML, CSS, JavaScript) over regular HTTPS, but receives and sends dynamic content (encrypted account information and document history) over a websocket connection to the server.

t looks like something is blocking your browser from establishing a websocket connection. Tor browser can be a useful tool for diagnosing this kind of issue as it usually bypasses filtering on restrictive networks (assuming Tor itself is not blocked).

In any case, I would expect that this browser would also be unable to load and edit documents. If you're able to edit documents but not register, then it's worth investigating. If nothing works then I'm not sure we'll be able to fix it from within the application's code.
