### ISSUE TITLE
Resource usage by cryptpad

### ISSUE THREAD

**Issue by Vibhigupta** [xwiki-labs/cryptpad#580]
I'm thinking to host one instance of cryptpad but my server run multiple services so I wanted to know how much resource it requires to run?

* Without user after install
* With around 50 active user (guess would be fine as well)

**Comment by ansuz** [comment]
This many users can probably be supported by a gen3 raspberry pi.

**Comment by Vibhigupta** [comment]
How much ram is required?

My server has around 3 CPU Core and 2 Gb of  free Ram.

**Comment by ansuz** [comment]
CryptPad.fr has about 1500 active users right now and is using a little over 1GB of RAM.

**Comment by Vibhigupta** [comment]
Thank You ❤️ You saved me
