### ISSUE TITLE
Unable to create spreadsheet from template

### ISSUE THREAD

**Issue by jdnicolas** [xwiki-labs/cryptpad#581]
**Description**
I create a spreadsheet in the Templates directory. Once created (with or without content), I change into the Documents directory and click on "New Pad". In the following pop-up, I see the button "No templates". The same procedure works for Rich text documents. The issue occured on CryptPad.fr. Help is greatly appreciated.

**To Reproduce**
1. Go to 'Templates'
2. Click on 'New pad'
3. Click on 'Sheet'
4. Click on 'Create' 
5. Close tab and go to 'Documents'
6. Click on 'Sheet'

**Expected behavior**
I would have expected for a template file to appear.

**Browser**
 - OS: Ubuntu 18.04.4 LTS
 - Browser: Firefox Browser
 - Version: 78.0.2
 - Extensions installed: All Extensions were disabled
 - Browser tweaks: None

**Comment by ansuz** [comment]
Hi,

The root of this is that spreadsheets in CryptPad work very differently than other types of documents, so the existing template system doesn't work, even though utilities (like the template folder) imply that they do. We're planning on developing a proper sheet template solution in the coming months, but in the meantime we might just warn users of the inconsistency if they try to create a sheet in the template directory.

**Comment by ansuz** [comment]
We fixed this some time ago but forgot to close it.
