### ISSUE TITLE
Few Questions

### ISSUE THREAD

**Issue by Vibhigupta** [xwiki-labs/cryptpad#582]
I am installing cryptpad on my server everything went smooth now, I am running the server it basically running it on loaclhost so its on server i cant really access the localhost.

* For production should i do complete setup with nginx,systemd,csp and then create the admin account?
* I seen one another instance of crypt pad which also show Premium account option, so how does i setup the payment gateway?
* Looking at nginx example it also ask to contact sales team if running it in production what that suppose to mean?

**Comment by ansuz** [comment]
1. Yes, do exactly that. I'd also recommend setting up some scripts to monitor your server's disk usage so you don't run out of space without realizing it. Many VPS providers offer their own monitoring solution, so this may already be available.
2. Some time ago we stopped supporting premium accounts (via accounts.cryptpad.fr) on third-party instances. There's nothing stopping you from accepting payments for accounts on your instance, but we don't provide a ready-made solution for that.
3. We offer support contracts in case you want our assistance running your instance. You're under no obligation to take a support contract to run the software, just as we're under no obligation to do anything more than provide its source.

**Comment by Vibhigupta** [comment]
> * Yes, do exactly that. I'd also recommend setting up some scripts to monitor your server's disk usage so you don't run out of space without realizing it. Many VPS providers offer their own monitoring solution, so this may already be available.

Ok i will keep an eye on storage usage although we got around 3TB so we good there, one more question,

>Pads that are not 'pinned' by any registered user can be set to expire

What this means? if we dont remove does this will pile up and use alot of storage or less?
 
> * Some time ago we stopped supporting premium accounts (via accounts.cryptpad.fr) on third-party instances. There's nothing stopping you from accepting payments for accounts on your instance, but we don't provide a ready-made solution for that.
So does latest version remove all this from Registration page?

> * We offer support contracts in case you want our assistance running your instance. You're under no obligation to take a support contract to run the software, just as we're under no obligation to do anything more than provide its source.

Got it, its more like you providing additional services.

**Comment by ansuz** [comment]
> What this means? if we dont remove does this will pile up and use alot of storage or less?

Yes. [`cryptpad/scripts/evict-inactive.js`](https://github.com/xwiki-labs/cryptpad/blob/main/scripts/evict-inactive.js) removes unpinned and inactive files.

>  So does latest version remove all this from Registration page?

I think you're mixing up _registered accounts_ (which allow users to log in from multiple devices) and _premium accounts_ (which provide an increased storage quota). [This issue](https://github.com/xwiki-labs/cryptpad/issues/242) tracks the ability to disable registration.

**Comment by Vibhigupta** [comment]
Ohh Yes I mixed it up. Can cryptpad privde code(payment processor) so people can add support to premium account?
