### ISSUE TITLE
Preview Bug 

### ISSUE THREAD

**Issue by Vibhigupta** [xwiki-labs/cryptpad#588]
**Describe the bug**
Preview bug in Presentation

When the text exceed a certain number of line, the content start to overlap with each other see added image.
Printing A PDF file result in same overlapped text. 
When click on Present button, things remain the same and You can even scroll it down.

**Where did it happen?**
Did the issue occur on CryptPad.fr or an instance hosted by a third-party? I tried mine and Your instance 
If on another instance, please provide its full URL.

**To Reproduce**
1. Go to Presentation and Copy Paste a paragraph multiple times

**Expected behavior**
Overlapped Text in Preview window 

**Browser (please complete the following information):**
 - OS: [ Elementary OS] 
 - Browser [Firefox]
- Version [0.72]
 - Extensions installed (UBlock Origin]
 - Browser tweaks [NA]

Feature Request - (I just added here as i dont want to discuss anything about it, Just few suggestion Working on Presentation is Horrible atm)

* Use Better and Good Looking Font
* Visual Control over Images Config alignment and size 
* Responsive images 
* More controls in editing section

![bug cryptpad](https://user-images.githubusercontent.com/51713176/88847619-e7454480-d204-11ea-82f7-a0cc1f63b652.png)

**Comment by ansuz** [comment]
Hi,

You can separate content into slides by inserting `---` on its own line. For example:

```
# Slide 1

* list
* items
* like
* this

---

# Slide 2

1. ordered
2. list
3. items

```

We don't currently have any plans to work on the other points you mentioned, as the presentation editor is intended for very basic use cases. In the future (after spreadsheets are working flawlessly) we will most likely integrate the OnlyOffice presentation editor for people who want full powerpoint-style functionality.
