### ISSUE TITLE
Feature request : Hiding keywords

### ISSUE THREAD

**Issue by LinkTroisUn** [xwiki-labs/cryptpad#590]
Feature request: add the possibility to hide the keyword list in kanbans. 

I have one where there's a huge list of them, and it's starting to decrease the amount of text that is displayed on screen. I'll have to add more keywords, and I worry it would hide every boards. Something which could solve this would be to add this feature, so, when I open the file, I scroll the list, select keywords to accurate my search, and when it's done, I close the keywords' list.

Here's a screenshot
![image](https://user-images.githubusercontent.com/32373005/89088476-d75e6980-d398-11ea-8e8b-67ef63799b97.png)

**Comment by ansuz** [comment]
I agree that this would be a useful feature. I'm not sure when we'll get around to it but we'll keep it in mind for future development.

**Comment by ansuz** [comment]
Tags now be hidden by clicking the using the _Tags_ button in the toolbar.
