### ISSUE TITLE
Feature Request: Adjustable margins (like Show Rulers in MS Word)

### ISSUE THREAD

**Issue by e-t-l** [xwiki-labs/cryptpad#591]
It would be great to be able to adjust the page margins or even the page size. Currently I'm finding that the text of my documents feel a little cramped horizontally, and it would be nice to be able to expand the margins of the writable area like you can using the rulers in MS Word or Google Docs, for example.

Full-width mode alleviates the issue a little, but sometimes users want to format a document to have specific margins (and personally, I've always found that full-width mode, or the equivalent Web Layout in MS Word, is distracting).

**Comment by mthld** [comment]
Hello,

We are trialing [a Document app based on OnlyOffice](https://www.onlyoffice.com/document-editor.aspx), currently limited to subscribers on cryptpad.fr. This is an early-access experimental application for testing purposes. It will soon become available to everyone on cryptpad.fr.

This application is way more complete than the Rich Text one. So don't hesitate to subscribe and try it, for now I'll close this issue. :)
