### ISSUE TITLE
Pad stuck in Loading Screen

### ISSUE THREAD

**Issue by andydelany** [xwiki-labs/cryptpad#595]
This is the second time a pad has become inaccessible to me for this reason. As this is a collaborative pad I'm not sure exactly what edit preceded this, but the pad no longer loads. It gets past the inital loading/password screen, and loads the title, but the grey "loading spreadsheet" box with moving wheel just stays until the page times out. 

The pad is hosted on CryptPad, and as I mentioned I didn't access this pad any differently to cause this error, and unfortunately don't know what the last action on the pad was.

Here is a screenshot of the browser console with the errors:

<img width="555" alt="Screen Shot 2020-08-11 at 11 00 53 AM" src="https://user-images.githubusercontent.com/69525032/89921449-576ba700-dbc3-11ea-8074-9d2dc83d210b.png">

This is on a Mac using Chrome version 84.0.4147.89, with no tweaks or extensions, and it also won't load for other people who have access to the pad.

Alot of our info for time sensitive organizing is stored on this pad! So as quickly as people have ideas for how to fix this please let me know, Thank you so much!

**Comment by datesastick** [comment]
I have the similar problem but only with Firefox and not with Chrome on my Android

**Comment by ansuz** [comment]
If either of you are able to share a link to an affected sheet via our support ticket form that would be very helpful.

**Comment by datesastick** [comment]
> If either of you are able to share a link to an affected sheet via our support ticket form that would be very helpful.

It's every single sheet I want to open.

**Comment by ansuz** [comment]
We're still investigating the underlying cause of this issue, but in the meantime I can propose a workaround:

1. open an affected sheet in a new private window (not logged in)
2. export its contents to a .bin file
3. create a new sheet using your account in a normal window
4. import the .bin file

**Comment by mthld** [comment]
It's impossible to help us if you don't share an incriminated document with us. Even more if we can't reproduce the issue on our end.
