### ISSUE TITLE
Feature Request: Regular unencrypted file sharing on the server

### ISSUE THREAD

**Issue by dereks** [xwiki-labs/cryptpad#596]
Thanks for working on Cryptpad.

I am looking for a self-hosted Google Suite alternative.

A requirement is that the files are stored on the server in regular file formats. Not in a CryptDrive, but in a regular mounted ext4 filesystem. (This directory will also be shared with WebDAV and sftp, and will be backed up regularly with rsync.) I want the paths shown in CryptDrive to be the same paths shared with other protocols and editor applications. Also, the files should be regular unencrypted files in standard file formats, like .xls or .docx, so that OpenOffice could also open these files when not collaborating online, or so I can later import the file into Google Suite if working with a client who prefers that.

Basically, I want your collaborative editing and web-based file manager, but without the zero knowledge feature. I need files with filenames that can be opened later by other apps, and backed up like all the other files on the server.

Presently I am unable to use Cryptpad because then only Cryptpad will be able to access the files. This is vendor lock-in, albeit for the noble purpose of zero knowledge. 

I can still work with OpenOffice documents from 10 years ago, and will still be able to work with them 10 years from now. That is a type of data security that is not related to encryption. I think you'd find more customers if one could collaborate on regular files and still use 3rd party apps on those files in conjunction with Cryptpad.

Thank You!

**Comment by ansuz** [comment]
You're welcome to fork the project. We have no plans to support use plans without encryption.
