### ISSUE TITLE
The bug that Chinese characters cannot be displayed in SHEET

### ISSUE THREAD

**Issue by hzl110520** [xwiki-labs/cryptpad#598]
I like cryptpad very much. I am Chinese and I need to write something in Chinese characters. Chinese characters are supported in rich text, but Chinese characters cannot be displayed normally in Sheet. I hope you can solve this bug as soon as possible.

**Comment by p2635** [comment]
Same

**Comment by hzl110520** [comment]
Thank you very much

**Comment by laodc** [comment]
I have the same issue but with Lao characters.
The official font is Phetsarath OT, but Noto Sans Lao is commonly used as well.
