### ISSUE TITLE
Consider sharing a Markdown Tutorial link?

### ISSUE THREAD

**Issue by JtLively** [xwiki-labs/cryptpad#60]
Really good and quick one:
http://www.markdowntutorial.com/

**Comment by ansuz** [comment]
Good idea, and easy to add.

**Comment by JtLively** [comment]
Another one.

https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown

**Comment by ansuz** [comment]
I just added http://www.markdowntutorial.com/ to the intro text for the slideshow app in the `soon` branch. It'll be deployed with the next batch of changes.
