### ISSUE TITLE
How to re-enable Ctrl+Z even if more than one user is using the sheet?

### ISSUE THREAD

**Issue by rainwater11** [xwiki-labs/cryptpad#600]
I saw this [issue](https://github.com/xwiki-labs/cryptpad/issues/195). How can I enable ctrl+z for when two users are using the same sheet? I don't mind if pressing Ctrl+Z undoes what the other user did. I would rather have that than not have Ctrl+Z not work at all. What code do I need to change to re-enable ctrl+z?

**Comment by ansuz** [comment]
As of our 4.2.0 release, pressing ctrl-Z in a sheet should prompt you to enter OnlyOffice's "Strict mode", which:

1. does not display other user's edits in real-time
2. only saves your local work when you press ctrl-z
3. **supports local undo**
