### ISSUE TITLE
CryptPad crashed with ERR_IPC_CHANNEL_CLOSED

### ISSUE THREAD

**Issue by MacLemon** [xwiki-labs/cryptpad#603]
**Describe the bug**
The CryptPad node process crashed with ERR_IPC_CHANNEL_CLOSED.

Error dumped to the console:
```shell
UNCAUGHT EXCEPTION IN DB WORKER
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at process.target.send (internal/child_process.js:708:16)
    at Object.Env.Log.<computed> [as error] (/usr/home/cryptpad/cryptpad/lib/workers/db-worker.js:24:17)
    at /usr/home/cryptpad/cryptpad/lib/storage/tasks.js:152:33
    at waitFor (/usr/home/cryptpad/cryptpad/node_modules/nthen/index.js:21:22)
    at FSReqCallback.oncomplete (fs.js:164:23) {
  code: 'ERR_IPC_CHANNEL_CLOSED'
}
TERMINATING
```

**Where did it happen?**
https://pads.c3w.at/

**To Reproduce**
Sorry, we don't know.

**Expected behavior**
Should not crash.

**Screenshots**
n/a

**Browser (please complete the following information):**
Does not apply.

**Smartphone (please complete the following information):**
Does not apply.

**Additional context**
Server OS: FreeBSD 12.1-p8
node: 14.6.0
CryptPad: v3.21.0 (VietnameseRhinoceros)
Webserver: nginx 1.19.2

**Comment by ansuz** [comment]
I believe this occurs when the main process sends a query to one of the worker processes which is in the process of crashing. I think it's a race condition where the error occurs before another event is emitted to indicate that the child process has crashed. I've seen it once or twice in practice but haven't been able to reliably reproduce it. If you have a trick to do so it'll be easier to address.

**Comment by ansuz** [comment]
I haven't seen this bug occur for some time, so I'm going to go ahead and close this.
