### ISSUE TITLE
Spreadsheets: random changes and history missing

### ISSUE THREAD

**Issue by medrimonia** [xwiki-labs/cryptpad#606]
**Describe the bug**
- 8 hours after last modification, I went back to an open cryptpad spreadsheet and the context had entirely changed
  - A lot of lines were emptied
  - Content of some cells was replaced by content of other cells
    - To me, this sounds similar to random copy-pasting I already experienced on the classic pad tool: see #352
  - I'm roughly certain no one else modified the pad, I did not find a way to check it, but:
    - Access is protected
    - It occured between midnight and 8am on a file no one else than me has worked on for a long time

I wanted to restore it through history but despite the fact that "File->properties" shows that 90% of the file usage is history, there's no "history" button as in the Rich Text Pad.

**Where did it happen?**
This issue occured on cryptpad.fr

**To Reproduce**
Not applicable

**Expected behavior**
- Content should stay the same without human intervention
- It should be possible to restore history

**Browser (please complete the following information):**
 - OS: Ubuntu 18,04
 - Browser: Firefox
 - Version 80.0
 - Extensions installed
      - Download Star
      - DownThemAll!
      - Mendeley Web Importer
      - Tree style tab
      - uBlock origin
      - vimium
      - Web Developer
      - Youtube mp3 320kbps
 - Browser tweaks: None

**Comment by mthld** [comment]
Hello,

To be able to help you on this we really need to be able to access an incriminated document. You can privately contact us from the Support page bundle into CryptPad: https://cryptpad.fr/support/

In the meantime I would like to invite you to try in a Firefox private window with all extensions disabled.
