### ISSUE TITLE
messages.js - referring to Finnish as a language

### ISSUE THREAD

**Issue by ilogreensward** [xwiki-labs/cryptpad#609]
Hello,

I would like to report a minor translation issue in customize.dist/messages.js pertaining to the language selector. 
The Finnish language is referred incorrectly as "**Suomalainen**" (adjective), while the correct proper noun for the language is **Suomi**.

Thank you and have a good day.

**Comment by sisco0** [comment]
Have a good day, the pull request has been submitted in order to overcome this issue.
I do not know very much about Suomi, but I must admit that _Nightwish_ was a great music band. 😄

**Comment by ilogreensward** [comment]
Thank you for fixing this one!
