### ISSUE TITLE
Will you consider implementing GitHub-flavored Markdown - task list, table, etc.

### ISSUE THREAD

**Issue by JtLively** [xwiki-labs/cryptpad#61]
Maybe I'm doing something wrong but I can't get task lists or tables in my presentation -
https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown

**Comment by ansuz** [comment]
[This pad](https://cryptpad.fr/slide/#/1/edit/rP4yoDxVOP83Vi9bDlLsbA/OIxnMvkk+1ZOqsHiDiLFnYkn/present) demonstrates a gfm table in a presentation.

I don't think the library we're using supports task lists out of the box, but iirc it's really extensible.

I'll see if that's an option soon.

**Comment by ansuz** [comment]
Good news! This will be included in our next release, April 11th, 2017.

![task-lists](https://cloud.githubusercontent.com/assets/1264398/24499214/39766740-1541-11e7-9218-8ca3a0bed348.png)

**Comment by elimisteve** [comment]
@ansuz Is GitHub-flavored Markdown supported on Rich Text pads? If so, I'm not sure how to enable that mode. Thanks!

**Comment by ansuz** [comment]
I'm not sure what you mean

**Comment by elimisteve** [comment]
I saw a "GitHub-flavored Markdown" feature was added to CryptPad, and I'd like to use this feature from Rich Text pads (the ones anyone can create by visiting <https://beta.cryptpad.fr/pad/>). How do I do this? Thanks.

**Comment by ansuz** [comment]
It's supported in our slide and code editor. Which you can test here: https://cryptpad.fr/code/

Our rich text pads are mostly limited by what's available in http://ckeditor.com/
