### ISSUE TITLE
Cannot press enter and complete entering certain functions

### ISSUE THREAD

**Issue by eojjn** [xwiki-labs/cryptpad#611]
**Describe the bug**
Many Functions do not seem to work, the sheet will not allow them to be inserted.

**Where did it happen?**
cryptpad.disroot.org

**To Reproduce**
type function into function bar or cell (functions I have tested and found to not work are IFERROR, ROUND, ROUNDDOWN. IF and SUM seem to work)
choose variables/data as applicable
press enter
nothing happens, pressing escape will cancel everything and the inserted function will be lost

**Expected behavior**
pressing enter should confirm the input and move to the next cell.

**Screenshots**

**Browser (please complete the following information):**
Linux Mint 19.3
Waterfox Browser 2020.06
uBlock origin 
strict tracking protection enabled

 - Browser [e.g. firefox, tor browser, chrome, safari, brave, edge, ???]
   - variations [e.g. Firefox nightly, Firefox ESR, Chromium, Ungoogled chrome]
 - Extensions installed (UBlock Origin, Passbolt, LibreJS]
 - Browser tweaks [e.g. firefox "Enhanced Tracking Protection" strict/custom mode, tor browser "safer" security level, chrome incognito mode]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sisco0** [comment]
Same for me using Windows and Chrome.

**Comment by eojjn** [comment]
Would it make sense to open an issue on the ONLYOFFICE repository then?

**Comment by sisco0** [comment]
Please, could you confirm that when using ROUND you are using the two parameters that the function needs?

**Comment by ansuz** [comment]
Since there was no answer to the @sisco0's question to confirm that the correct number of arguments were supplied to the function I'm going to assume this is a case of user error and close this issue.
