### ISSUE TITLE
How can I notify my users?

### ISSUE THREAD

**Issue by georgkrause** [xwiki-labs/cryptpad#613]
I am running a cryptpad which I sadly need to stop. So all the data will be gone. Since I know people using it, but have no idea who is using it, I would like to notify my users about the fact the instance will be gone soon. This way they can backup their data and search for a new place to be.

But I can't find a way to do this, there are not even settings to change the front page. Sure, I could do this manually but who would see this? Most of the time I get instantly directed to my cryptdrive.

Is there something I oversee? If not, it would be nice to implement a way to notify users!

**Comment by sisco0** [comment]
Have a good day @georgkrause 
How about modifying the _index.js_ source code by adding a new row before the one cited below? You could customize your _index.js_ page to show some kind of modal or any other bootstrap notification.
 [https://github.com/xwiki-labs/cryptpad/blob/1ef0651bc8d0a6d44e996ff4b89e0d9821daddde/customize.dist/pages/index.js#L149](https://github.com/xwiki-labs/cryptpad/blob/1ef0651bc8d0a6d44e996ff4b89e0d9821daddde/customize.dist/pages/index.js#L149)

**Comment by ansuz** [comment]
We do plan to develop some functionality for instance-wide notifications in the future, but there's nothing prepared right now. In the meantime, something like what @sisco0 proposed is your best option.

**Comment by georgkrause** [comment]
thanks, this was quite helpful. Would be nicer to have a native way in the future anyway, so I would like to keep this issue open.

**Comment by ansuz** [comment]
CryptPad 4.4.0 includes the admin broadcast functionality we've been planning for some time. It's available on the _broadcast_ section of the admin panel.
