### ISSUE TITLE
Feature: Nextcloud integration

### ISSUE THREAD

**Issue by J0WI** [xwiki-labs/cryptpad#621]
**Describe the ~bug~ feature**
I'd like to use Cryptpad in Nextcloud.
Currently the Nextcloud editor support only simple files like plain text and Markdown or office documents though a (fairly complex) Collabora/Onlyoffice API. Cryptpad could be a much simpler and more secure alternative.

**Expected behavior**
Documents can be created and edited with Cryptpad in Nextcloud, without breaking the "[userkey](https://docs.nextcloud.com/server/stable/admin_manual/configuration_files/encryption_details.html#key-type-user-key)" encryption.

**Additional context**
There is a similar app for Etherpad in Nextcloud:
https://github.com/otetard/ownpad/issues/101

**Comment by ansuz** [comment]
This is a bit like asking to have Google suite inside of Office 365. Both platforms are intended to be self-contained.

It can understand that CryptPad seems to be a number of standalone editors, but there's a lot of stuff that happens in the background to handle encryption keys in a secure environment that isn't easily reconciled with Nextcloud's security model.

**Comment by rasos** [comment]
Agree that a full integration of CryptPad into the nextcloud file system is a technical contradiction, especially when it comes to syncing files. 

What you always can do is add CryptPad as an additional app to the top menu of nextcloud with the `External sites` app or add a CryptPad document in your nextcloud file tree with its URL using the `Link editor` app.

**Comment by strypey** [comment]
@J0WI 
> I'd like to use Cryptpad in Nextcloud.

Have you tried this?

https://apps.nextcloud.com/apps/openincryptpad
