### ISSUE TITLE
Empty document // loading changes not working

### ISSUE THREAD

**Issue by lucamarkus** [xwiki-labs/cryptpad#623]
In this document (https://cryptpad.piratenpartei.de/oodoc/#/2/oodoc/edit/pcoe9cWVd7DAMkbPCI2IoDea/), the content is not loading or loading of changes takes endless without a result. Is there a possibility to fix that and to rebuild the content of the document?

**Comment by ansuz** [comment]
OnlyOffice's document editor was explicitly enabled by your instance's administrator. We don't support or recommend its use.
