### ISSUE TITLE
AdminKey instructions are wrong

### ISSUE THREAD

**Issue by reetp** [xwiki-labs/cryptpad#626]
**Describe the bug**

Instructions say this:

"To give access to the admin panel to a user account, just add their user id, which can be found on the settings page for registered users."

    adminKeys: [
        //"https://my.awesome.website/user/#/1/cryptpad-user1/YZgXQxKR0Rcb6r6CmxHPdAGLVludrAF2lEnkbx1vVOo=",
    ],

No such information exists under settings.

URL is https://my.awesome.website/settings/#account

**Where did it happen?**

On my test instance

**To Reproduce**

Go to Settings. Look for ID etc 

**Expected behaviour**

Go to Settings, find ID, and copy link to paste into config,js

**Browser (please complete the following information):**
 - OS: Linux
 - Browser: Firefox & Chromium

**Comment by yflory** [comment]
I've just updated the example config file to use the correct term "Public signing key" instead of "user id". The example now uses the new public key format:
```
    adminKeys: [
        //"[cryptpad-user1@my.awesome.website/YZgXQxKR0Rcb6r6CmxHPdAGLVludrAF2lEnkbx1vVOo=]",
    ],
```
