### ISSUE TITLE
Cryptpad does not start to work any more on Vivaldi Browsers

### ISSUE THREAD

**Issue by rpzzw** [xwiki-labs/cryptpad#629]
**Describe the bug**
Cryptpad is a great web-based teamworking solution - until yesterday evening. Then I got (instead of my team document) this unspecified failure message: 
![2020-11-03 19 26 31 cryptpad fr 4a3affffbf57](https://user-images.githubusercontent.com/73933695/98088282-8c655e00-1e81-11eb-9457-2f5dc925d81e.png)

**Where did it happen?**
It is not even possible to start cryptpad.fr directly.

**To Reproduce**
1. Install a Vivaldi Browser
2. Write "cryptpad.fr" into the address line and type enter.
3. See error

**Expected behavior**
Cryptpad should start browser-independently

**Screenshots**
See above

**Browser (please complete the following information):**
 - Vivaldi | 3.4.2066.76 (Stable channel) (64-Bit)
 - Vivaldi for Android

**Comment by ansuz** [comment]
We received some more detailed reports from other users that helped us to solve the underlying issue here. Can you confirm that service has been restored?
