### ISSUE TITLE
CORS/CSP Headers Duplicated for /api/config endpoint

### ISSUE THREAD

**Issue by twnk** [xwiki-labs/cryptpad#633]
**Describe the bug**
When attempting to debug users unable to load Cryptpad in Chrome (& other Blink-based browsers such as Edge) I discovered that the CORS & CSP headers were being duplicated only for the `/api/config` endpoint. This resulted in chrome refusing to load `https://[selfhosted-cryptpad-domain]/api/config?ver=3.24.0-1604604192119` (despite the duplicate headers being identical). Firefox did not object to the duplicate headers. 

The issue was solved by using the NGINX configuration to drop the duplicated headers via the following block. 

```
# /api/config is loaded once per page load and is used to retrieve
    # the caching variable which is applied to every other resource
    # which is loaded during that session.
    location = /api/config {
        proxy_pass http://localhost:3123;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # on Cryptpad 3.24.0, all of these headers are served by cryptpad and thus duplicated
        proxy_hide_header Access-Control-Allow-Origin;
        proxy_hide_header Cache-Control;
        proxy_hide_header Content-Security-Policy;
        proxy_hide_header Cross-Origin-Embedder-Policy;
        proxy_hide_header Cross-Origin-Opener-Policy;
        proxy_hide_header Cross-Origin-Resource-Policy;
        proxy_hide_header X-Content-Type-Options;
        proxy_hide_header X-XSS-Protection;
    }
```
NB: `:3123` is our `httpPort` in the config, not `httpSafePort`. The site is served over SSL using the template NGINX config provided, with minimal modifications (just what CertBot adds automatically and with url variables set)

**Where did it happen?**
3rd party instance. This instance is not publicly accessible so URL not provided.

**Browser (please complete the following information):**
 - OS: Windows, Linux
 - Browser: Chrome (Windows & Linux), Edge (Windows)
 - Version: Latest
 - Extensions installed: None
 - Browser tweaks: None

**Additional context**
Did not occur on 3.22.0 (We updated from 3.22.0 to 3.24.0 and then this issue arose)

**Comment by mark4409** [comment]
I have the same issue with duplicate headers and can confirm that adding the proxy_hide_header directives to /api/config fixes the issue on nginx

**Comment by ansuz** [comment]
Our [4.2.0 release](https://github.com/xwiki-labs/cryptpad/releases/4.2.0) includes a fix to avoid setting the duplicated headers in the NodeJS process. I've tested this on a personal instance which is running the provided example NGINX and confirmed that it works as expected in Chromium, Brave, and a few other browsers, so I'm going to close this issue.

**Comment by twnk** [comment]
Cool to see this make it into the latest version! Glad it's helped :D
