### ISSUE TITLE
Getting "SyntaxError: JSON.parse: unexpected character at line 1 column 2 of the JSON data" after logging in

### ISSUE THREAD

**Issue by s0m3guy** [xwiki-labs/cryptpad#639]
**Describe the bug**
Wanted to log in  today but after typing in my login data and hitting the button the interface shows up initializing all the data but then I get "SyntaxError: JSON.parse: unexpected character at line 1 column 2 of the JSON data" and cannot see my drive.

**Where did it happen?**
It happens when logging in on https://cryptpad.fr/drive/#

**To Reproduce**
1. Go to https://cryptpad.fr/
2. Click on "Log in"
3. Typing in my data
4. Click "log in"
5. See that message

**Expected behavior**
I expect to see my drive

**Screenshots**
https://imgur.com/a/aDpDubU

**Browser (please complete the following information):**
 - OS: Windows 10 x64
 - Browser Newest Firefox (it seems to work with Chrome)
 - Extensions installed: uBlock Origin
 - Browser tweaks: to my knowledge no explizit settings are set, everything should be default settings

**Comment by s0m3guy** [comment]
Seems to work again. Not sure what caused this

**Comment by luniki** [comment]
We are experiencing this behaviour too. On inspection this line in `sframe-common-outer.js` causes this:

`var data = JSON.parse(msg.data);`

`msg.data` isn't a string at this point but a JS object: `{"topic":"mg-unloadFrame","data":{}}"`

**Comment by ansuz** [comment]
@luniki the `{"topic":"mg-unloadFrame","data":{}}"` message you shared doesn't originate from our code, so it's most likely a case of CryptPad receiving an unrecognized message sent by a browser extension. The release which I'm just about to tag (`4.5.0`) adds some guards to ignore messages that don't match our internal protocols, so this shouldn't occur anymore.

It would still be nice to know what extension was sending this message as it could be responsible for other errors that we haven't handled explicitly. If you can provide a list of your installed extensions we'll investigate further.
