### ISSUE TITLE
Admin page unavailable

### ISSUE THREAD

**Issue by SeanPedersen** [xwiki-labs/cryptpad#640]
**Describe the bug**
The admin page is unavailable after I entered my admin key (found in profile settings) into settings at key adminKeys. Like so:
```
adminKeys: [
        "[cryptpad-user1@my.awesome.website/YZgXQxKR0Rcb6r6CmxHPdAGLVludrAF2lEnkbx1vVOo=]",
    ],
```
I then restarted the server but the admin page was still unavailable. I then found other old bug reports where I read about trying to launch the server with $ npm run fresh. That is what I tried (after stopping the daemon of course) but sitll no admin page access. I checked at /api/config endpoint and it says: `"adminKeys": [],`

**Where did it happen?**
This happens on my own instance.

**To Reproduce**
1. Install 3.24.0
2. Start server
3. Stop server
4. Add admin key
5. Start server

**Expected behavior**
After adding admin key, access to the admin page.

**Screenshots**

**Browser (please complete the following information):**
 - OS: Arch lInux
 - Browser Firefox
 - Version 83
 - Extensions installed (UBlock Origin, PrivacyBadger]

**Comment by SeanPedersen** [comment]
Ok that is a lil bit embarassing but I just fixed my problem. The config comes as follows:
```
/*
    adminKeys: [
        //"[cryptpad-user1@my.awesome.website/YZgXQxKR0Rcb6r6CmxHPdAGLVludrAF2lEnkbx1vVOo=]",
    ],
*/`
```

I only uncommented the // but forgot about the block comment.... sigh. Maybe remove one comment to prevent future confusions for blind people like myself. Anyway love cryptpad so far, keep it up!

**Comment by jmlutgemeier** [comment]
I also was blind. It is very easy to oversee the block comment here. I will try to create a PR
