### ISSUE TITLE
Unmaintained Bower dependency bootstrap-tokenfield

### ISSUE THREAD

**Issue by c7hm4r** [xwiki-labs/cryptpad#641]
**Describe the bug**
CryptPad uses the Bower package `bootstrap-tokenfield`. [According to their authors, this software is unmaintained.](https://github.com/sliptree/bootstrap-tokenfield). Furthermore, the package depends on older, incompatible versions of jQuery and Bootstrap, leading to the following errors when updating Bower packages:

```
Please note that,
    bootstrap-tokenfield#0.12.1 depends on jquery#~2.1.0 which resolved to jquery#2.1.4
    cryptpad depends on jquery#2.2.4 which resolved to jquery#2.2.4
    bootstrap#3.1.1 depends on jquery#>= 1.9.0 which resolved to jquery#2.2.4
Resort to using jquery#2.2.4 which resolved to jquery#2.2.4
Code incompatibilities may occur.
Please note that,
    bootstrap-tokenfield#0.12.1 depends on bootstrap#~3.1.1 which resolved to bootstrap#3.1.1
    cryptpad depends on bootstrap#^v4.0.0 which resolved to bootstrap#4.5.3
Resort to using bootstrap#^v4.0.0 which resolved to bootstrap#4.5.3
Code incompatibilities may occur.
```

**Where did it happen?**
On a custom server.

**To Reproduce**
1. Run `node_modules/.bin/bower update` in the repository.

**Expected behavior**
No unmaintained dependencies.

**Versions**
- Node: v12.20.0
- NPM: 6.14.8
- Bower: 1.8.8
- OS: Ubuntu Server 18.04

**Related**
- #612 includes this error but also other things

**Comment by ansuz** [comment]
I've [changed our bower.json to only use bootstrap-tokenfield 0.12.1](https://github.com/xwiki-labs/cryptpad/commit/1c2a6949e2cd30ae88333b0557e8f08b951d66e4) and [forked the source repository](https://github.com/cryptpad/bootstrap-tokenfield) so that its source remains available. If we need anything more from it we will implement the changes ourselves.
