### ISSUE TITLE
config.example.js customLimits incorrect example

### ISSUE THREAD

**Issue by cyphunk** [xwiki-labs/cryptpad#643]
https://github.com/xwiki-labs/cryptpad/blob/master/config/config.example.js shows using a profile URL as the key for setting custom quota limits. From my examination of current server version (3.24.0) it appears that the profile pub key link is required instead.

(while related to an additional issue I opened the two bugs I believe require different consideration)

**Comment by yflory** [comment]
Thanks for the report, I've updated the example. The URL that was previously displayed in this config file was the old format of the Public Signing Key. Both formats are still valid, but only the newer one is easily obtainable from the UI.
