### ISSUE TITLE
show/hide comments (like users, chat)

### ISSUE THREAD

**Issue by mooseyboots** [xwiki-labs/cryptpad#648]
hi cryptpaders,

the comments feature is great but it takes up a lot of screen space. it would be great if they could be click to hide as chat and user list are. hiding them would make for a less busy screen while writing.

**Comment by Hnasar** [comment]
Especially on mobile having any comments makes the document impossible to view when viewed in portrait mode.
I would consider this more than just an enhancement because of that reason.

**Comment by ansuz** [comment]
We added more controls to hide these elements in our [4.2.0 release](https://github.com/xwiki-labs/cryptpad/releases/4.2.0).
