### ISSUE TITLE
After Adding A User As An Owner To A Cryptpad Team, Need To Log Out And Log Back In To See Team Files

### ISSUE THREAD

**Issue by mhfowler** [xwiki-labs/cryptpad#653]
**Describe the bug**
When adding a user to a cryptpad team, for them to see files for the team which they are now a member of, they needed to log out and log back in. 

**Where did it happen?**
This occurrred on CryptPad.fr 

**To Reproduce**
1. Invite a user to join a crypt pad team via an invite link
2. user accepts invite
3. user unable to see files without logging out and logging back in

**Expected behavior**
It would be nicer if they didn't have to log out and log back in

**Browser (please complete the following information):**
Firefox

**Comment by ansuz** [comment]
We haven't been able to reproduce this issue, so it's possible it was fixed along with some other issue in the last few releases. Can you confirm whether you're still experiencing this behaviour?

**Comment by mhfowler** [comment]
@ansuz I don't have time to replicate the test right now, if you can't reproduce it, then maybe it got fixed ! Feel free to close was just trying to be helpful

**Comment by ansuz** [comment]
Ok, thanks!
