### ISSUE TITLE
cryptpad stuck loading

### ISSUE THREAD

**Issue by mojii100** [xwiki-labs/cryptpad#655]
**Describe the bug**
On both my laptop and PC using chrome and firefox respectively, any attempts to access drive, log in, or access guest pads results in loading screen.

**Where did it happen?**
Cryptpad.fr

**To Reproduce**
1. Go to 'cryptpad.fr'
2. Click on 'Log In'
3. Enter username and password
/
2. Click on 'Rich Text'

**Expected behavior**
Either drive loads or guest text pad does.

**Browser (please complete the following information):**
 - OS: macOS and Windows 10
 - Browser firefox, chrome
 - Version firefox 83 and chrome 87
 - Extensions installed duckduckgo on firefox, startpage on chrome

**Additional context**
I tried in incognito/private as well as normal for both and it still happened. This is my first time doing this so sorry if there's not enough information.

**Comment by ansuz** [comment]
See [my comment on this related issue](https://github.com/xwiki-labs/cryptpad/issues/654#issuecomment-740950826).
