### ISSUE TITLE
CryptDrive will not Load

### ISSUE THREAD

**Issue by tizzler1234** [xwiki-labs/cryptpad#656]
This is my first time posting. I am an admin of a team and right now my drive account will not load. I have used Chrome and Firefox on apple desktop and android. When I input my account information it get stuck on the loading screen step of “loading drive”. It then times out. Pads that I have saved on this drive also will not load and encounter the same issue.

Urgently need help with this.

**Comment by ansuz** [comment]
See [my comment on this related issue](https://github.com/xwiki-labs/cryptpad/issues/654#issuecomment-740950826).
