### ISSUE TITLE
Cryptpad does not load

### ISSUE THREAD

**Issue by l-jessen** [xwiki-labs/cryptpad#657]
Cryptpad doese not load on any devices and any Browsers. Please help. We cant work anymore.

<img width="809" alt="Bildschirmfoto 2020-12-08 um 19 33 19" src="https://user-images.githubusercontent.com/75694224/101525990-5ccbd900-398c-11eb-9634-7e40c540430f.png">

**Comment by ansuz** [comment]
See [my comment on this related issue](https://github.com/xwiki-labs/cryptpad/issues/654#issuecomment-740950826).
