### ISSUE TITLE
Add OO Doc/Slid Options to New Pad Menu

### ISSUE THREAD

**Issue by iamdoubz** [xwiki-labs/cryptpad#658]
**Describe the bug**
Not a bug! Just, how do I add menu options for OO Word (oodoc) and OO PowerPoint (ooslid)?

**Where did it happen?**
Did the issue occur on CryptPad.fr or an instance hosted by a third-party?  
[3rd party](https://pad.dou.bet)

**To Reproduce**
1. Go to 'Drive'
2. Click on 'New'
3. See "undefined" menu options

**Expected behavior**
Human readable name for OpenOffice Word/PP.

**Screenshots**
| ![oodoc-ooslid-menu](https://user-images.githubusercontent.com/4871781/101676274-93533380-3a20-11eb-9a4e-54600f2f4623.png) |
| :---: |

| ![oodoc-ooslid-new-pad](https://user-images.githubusercontent.com/4871781/101813956-06bd7980-3ae3-11eb-9658-5df2f4a68b6a.png) |
| :---: |

**Browser (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 18.04 (backend) / Windows 10 (frontend)
 - Browser [e.g. firefox, tor browser, chrome, safari, brave, edge, ???] Google Chrome 87
   - variations [e.g. Firefox nightly, Firefox ESR, Chromium, Ungoogled chrome] N/A
 - Version [e.g. 22] 87
 - Extensions installed (UBlock Origin, Passbolt, LibreJS] uBlock Origin
 - Browser tweaks [e.g. firefox "Enhanced Tracking Protection" strict/custom mode, tor browser "safer" security level, chrome incognito mode] N/A
- CryptPad Version [e.g. 3.24.0] 521b59088

**Additional context**
I edited in `/path/to/cryptpad/customize/application_config.js` the ability for logged in users to utilize the OO Word/PP Pads. Now, where do I go to add the "type???" menu options.

I tried editing `/path/to/cryptpad/customize/translations/message.js` with below, but I'm certain it's wrong:

```js
define(['/common/translations/messages.js'], function (Messages) {
    // Replace the existing keys in your copied file here:
    // Messages.button_newpad = "New Rich Text Document";
    Messages.oodoc = "Word";
    Messages.ooslid = "PowerPoint";
    return Messages;
});
```

Thanks in advanced!

**Comment by ansuz** [comment]
Hi,

These editors aren't officially supported in CryptPad yet. We might still make breaking changes to how they work before we properly introduce this functionality, and we won't introduce any migrations to correctly load any documents created before their official introduction. I don't recommend relying on this behaviour as you might end up losing your work.

**Comment by iamdoubz** [comment]
Good to know!

**Comment by iamdoubz** [comment]
If anybody else wants to know how to do this:

1. Edit the file `/path/to/cryptpad/www/common/translations/messages.json`
2. Add oodoc and ooslide as types and buttons
```json
{
    "main_title": "CryptPad: Zero Knowledge, Collaborative Real Time Editing",
    "type": {
        "pad": "Rich text",
        "code": "Code",
        "poll": "Poll",
        "kanban": "Kanban",
        "slide": "Presentation",
        "drive": "CryptDrive",
        "whiteboard": "Whiteboard",
        "file": "File",
        "media": "Media",
        "todo": "Todo",
        "contacts": "Contacts",
        "sheet": "Sheet",
        "teams": "Teams",
        "oodoc": "Document",
        "ooslide": "SlideShow"
    },
    "button_newpad": "New Rich Text pad",
    "button_newcode": "New Code pad",
    "button_newpoll": "New Poll",
    "button_newslide": "New Presentation",
    "button_newwhiteboard": "New Whiteboard",
    "button_newkanban": "New Kanban",
    "button_newsheet": "New Sheet",
    "button_oodoc": "New Document",
    "button_ooslide": "New SlideShow",
    "common_connectionLost": "<b>Server Connection Lost</b><br>You're now in read-only mode until the connection is back.",
```
3. Edit the file `/path/to/cryptpad/customize/application_config.js`
4. Add oodoc and ooslide as available pad types.
```js
AppConfig.availablePadTypes = ['drive', 'teams', 'pad', 'sheet', 'code', 'slide', 'poll', 'kanban', 'whiteboard', 'file', 'contacts', 'oodoc', 'ooslide'];
```
