### ISSUE TITLE
Typo in cryptpad/www/profile/main.js:53

### ISSUE THREAD

**Issue by Asharas** [xwiki-labs/cryptpad#662]
Hi!  

By searching for a typo I made in code, I found this in `cryptpad/www/profile/main.js` on line 53:  
```
var addData = function (meta, Cryptad, user) {
    meta.isOwnProfile = !window.location.hash ||
        window.location.hash.slice(1) === user.profile;
};
```  
Since it's the only occurrence of `Cryptad` I assumed it's a mistake.

**Comment by ansuz** [comment]
Yes, this is a typo. This function argument is only serving as a placeholder, since it isn't actually used in the scope of the function. As such, it couldn't possibly have caused any errors. I've corrected it anyway.
