### ISSUE TITLE
Snapshots don't work in sheets

### ISSUE THREAD

**Issue by chairmantheboring** [xwiki-labs/cryptpad#665]
**Describe the bug**
Creating a snapshot in a sheet then clicking the open button opens a new tab, where CryptPad proceeds to load the document, then complains that the revision no longer exists, even when it actually does. This also applies to shareable links that contain a link to a specific revision.

**Where did it happen?**
Cryptpad.fr

**To Reproduce**
1. Go to any sheet.
2. Click on the snapshots button.
3. Make a snapshot.
4. Open the snapshot using the open button. 

**Expected behavior**
The snapshot/revision loads without issue.

**Browser (please complete the following information):**
 - OS: Arch Linux
 - Firefox 83
 - Version 3.25.0
 - Extensions installed: uBlock Origin, Firefox Container Tabs, HTTPS Everywhere, Cookie Autodelete, Privacy Redirect, and a user agent switcher
 - Browser tweaks: Custom Firefox tweaks.

**Additional context**
This problem also happens in a clean Chromium (87) profile.

**Comment by 0ki** [comment]
I'd say this is very high priority as sheets is the most unstable part of the system an on rare occasions would lose content. So having snapshots not work is a bummer.

**Comment by chairmantheboring** [comment]
@0ki This issue was fixed in v4.2.1 and is [listed as bugfix in the changelog](https://github.com/xwiki-labs/cryptpad/releases/tag/4.2.1). This issue is now fixed.
