### ISSUE TITLE
LaTeX support in Presentations

### ISSUE THREAD

**Issue by natema** [xwiki-labs/cryptpad#671]
Just a feature request, in case its implementation would be easy: 
what about adding LaTeX support in presentations, e.g. through MathJax?

**Comment by ansuz** [comment]
Hi,

Mathjax is already supported in presentations and code pads, although it isn't well documented or easily discovered. I've provided a basic example of the syntax in [this presentiation](https://cryptpad.fr/slide/#/2/slide/view/0U+M77J-Lv0NStzYkNm1wEzhBM5x8F9hIk1rE+neKNc/).

We plan to improve documentation and discoverability about this and other similarly hidden features over the next few months.

**Comment by ansuz** [comment]
The syntax for `mathjax` blocks in markdown can now be found in [our docs](https://docs.cryptpad.fr/en/user_guide/apps/code.html#markdown).
