### ISSUE TITLE
Kanban board doesn't work with drag and drop of items on mobile / touch

### ISSUE THREAD

**Issue by Hnasar** [xwiki-labs/cryptpad#674]
**Describe the bug**

When I open a cryptpad kanban document on iOS Safari, or Firefox on Android, or Chrome on Android, I cannot use my finger to drag and drop the items to reorganize them. I need to pull out my laptop to move the items around.

**Where did it happen?**

This occurred on cryptpad.fr.

**To Reproduce**

1. Make new kanban board.
2. Add two columns and two items.
3. Observe that if you are on a desktop browser you can drag and drop the items to move them between the columns or reorder them.
4. Observe that if you use a mobile browser you cannot drag the items. You can scroll the board, but none of the items are movable.

**Expected behavior**

I expect that if I touch and drag on an item, the item moves. And if I touch and drag on the board (without an item) then the board scrolls.

**Screenshots**

**Browser (please complete the following information):**
Works on stock firefox/chrome on Linux.

**Smartphone (please complete the following information):**
Doesn't work on stock mobile browsers on Android 10 & latest iOS.

**Comment by ansuz** [comment]
This was fixed in our [4.1.0 release](https://github.com/xwiki-labs/cryptpad/releases/4.1.0).
