### ISSUE TITLE
Use of Object Storage type S3 for storage backend

### ISSUE THREAD

**Issue by Ddataa** [xwiki-labs/cryptpad#675]
**Describe the bug**

It is more a technical question than a bug per se
I want to use an S3 type object storage backend, how is it possible ?

Thanks a lot for your amazing work on that project !!

**Comment by ansuz** [comment]
This isn't currently possible with CryptPad and we have no plans to implement support for Amazon or any other proprietary cloud services.

**Comment by Ddataa** [comment]
Yes, I know and I know.

I was planning on a self-hosted Minio instance, https://min.io/

Not on Amazon, obviously...just the idea of having possibility of adding a backend storage, could be NFS or anything you sure it really no way at all to do that ?

**Comment by ansuz** [comment]
I'm not saying it isn't possible, just that we have no plans to spend time on it.

**Comment by Ddataa** [comment]
Yes I understand your position.

Would you be able just to explain or guide on where to investigate about how/where the storage is done on the backend ?
I am missing some documentation on that..

Thanks a lot @ansuz

**Comment by ansuz** [comment]
You can follow issue #527 for updates.

**Comment by Ddataa** [comment]
Thanks @ansuz
