### ISSUE TITLE
How to use one CryptPad with different domains?

### ISSUE THREAD

**Issue by Tigerente01** [xwiki-labs/cryptpad#676]
I have a working CryptPad instance but want the reach it with different URLs.

I can reach the mailpage but that'S all. I can't start a new pad.

I think the fault is in the  config.js. at the httpSafeOrigin-tag

I already have tried to add all three domains but then only the last one is able to start a new pad.

* CUSTOMIZE AND UNCOMMENT THIS FOR PRODUCTION INSTALLATIONS.
*/
httpSafeOrigin: "https://schulpad.uber.space",
httpSafeOrigin: "https://pad.bramau-schule.de",
httpSafeOrigin: "https://pad.bramauschule.de",

Is it anyhow possible to add more than one domain at the httpSafeOrigin or is there anyother hint, how to get it really working with more than one domain?

Thx
Soenke

**Comment by ansuz** [comment]
This isn't supported at the moment. I'd recommend choosing one domain and having the others redirect to it.

**Comment by Dominion5254** [comment]
With this issue closed as completed, does that mean CryptPad supports multiple domains?

If so, is there documentation for doing so? I can't seem to find anything about multiple domains in the CryptPad docs.

**Comment by ivaninja** [comment]
Is it supported now?
