### ISSUE TITLE
Feature request: Auto snapshots

### ISSUE THREAD

**Issue by udf2457** [xwiki-labs/cryptpad#677]
In user settings (and maybe also in central server settings for people running their own server), it might be a nice idea to set automatic timed shapshots so that people have a way to roll back (perhaps especially useful in collaborative environments with multiple people making edits).

**Comment by ansuz** [comment]
The  majority of our editors feature a history mode that allows users to review and revert to earlier states of the document. Every revision is available and includes the exact time at which it was received by the server. Users can manually create snapshots and assign them names to make navigation easier. Can you confirm that you're aware of these features and explain why they're insufficient if so?

**Comment by monperrus** [comment]
Hi,

I don't find the widget History / Past versions in the Cryptad 

How to access the history of a cryptpad?

Thanks!

--Martin

**Comment by innir** [comment]
> How to access the history of a cryptpad?

File -> History

**Comment by monperrus** [comment]
Thanks a lot @innir 

Is that possible to preview a previous version before restoring it?

cc/ @bbaudry

**Comment by mthld** [comment]
Hello,

It's currently how the functionality works, you preview the changes using the timetable and then click "Restore" when you want.

https://user-images.githubusercontent.com/41020854/183384962-b257ea69-4003-478a-9e9f-a001066bc385.mov

I'll close this issue now. :)
