### ISSUE TITLE
Log out everywhere. This option logs  **NOT** out other sessions

### ISSUE THREAD

**Issue by pflegende** [xwiki-labs/cryptpad#680]
**Describe the bug**

User menu (avatar at the top-right) >  Log out everywhere.
This option logs  **NOT** out all other sessions

**Where did it happen?**
Did the issue occur on CryptPad.fr or an instance hosted by a third-party?  
https://cryptpad.fr/

**To Reproduce**
1. Go to 'User menu (avatar at the top-right) >  Log out everywhere.'
2. Click on 'Log out everywhere..'
3. go to other device (separate connected)  
4. See running session with also the content of the pad 
5.  so embarrassing  

**Expected behavior**

expect to see a closed session and no more content from the '"old"-pad on this device

**Screenshots**
seems not necessary

**Browser (please complete the following information):**
 - OS: [W10 (source and target)]
 - Browser [e.g. firefox, tor browser, chrome, safari, brave, edge, ???]
   - source (sessions with account-user):  chrome
   -  target (seesion with anonym user)  tested with edge and also with firefox 85.0 64bit

 - Extensions installed (UBlock Origin, Passbolt, LibreJS]
 - nothing

 - Browser tweaks [e.g. firefox "Enhanced Tracking Protection" strict/custom mode, tor browser "safer" security level, chrome incognito mode]
 -  - nothing

**Smartphone (please complete the following information):**
both are notebooks

**Additional context**
seems not necessary

**Comment by pflegende** [comment]
looking forward what to do with not eraseabele cryptopad ....
sitting and starring on the screen if somebody steels  the data ...

but not at all, it's covid time it's homeoffice time ...

;)

**Comment by davidbenque** [comment]
> target (seesion with anonym user) tested with edge and also with firefox 85.0 64bit

I think you are confusing "log out everywhere" and revoking access to a document after sharing the link. 

Log out everywhere is about logging out of your account on other devices, [there are two ways of doing this with slightly different outcomes](https://docs.cryptpad.fr/en/user_guide/security.html#remote-disconnect). 

Here you are not logged in on the "target" device, so it is normal that they keep seeing the document you have shared with them, regardless of whether you are logged in. Once you have shared the link to a document, access cannot be revoked, as indicated by the following message in that dialog. 

> This link contains the keys to your document. Recipients will gain non-revokable access to your content.
