### ISSUE TITLE
PC Freezes when trying to upload a big file

### ISSUE THREAD

**Issue by Pretuer** [xwiki-labs/cryptpad#682]
**Describe the bug**
Files over 250MB freeze up your computer and forces a page refress

**Where did it happen?**
Cryptpad FR

**To Reproduce**
1. Go to 'Crypt Drive'
2. Click on 'New Pad'
3. Upload a File around 300MB

**Expected behavior**
The site will freeze (or your PC) and then you should see a message that it's slowing your PC down (on firefox) then it will refresh to the homepage or crash

**Screenshots**
N/A

**Browser (please complete the following information):**
 - OS: [Linux, Zorin OS - i3wm]
 - Browser [ firefox]
  
 - Version [85.0]
 - Extensions installed (UBlock Origin, Bitwarden, Facebook Container, CrypText, Block Site, DuckDuckGo Privacy Essentials]

**Comment by ansuz** [comment]
This was fixed some time ago. The client should know ahead of time that 250MB is above the maximum storage limit, so it won't try to encrypt anything and will instead inform the user that the file is too large.
