### ISSUE TITLE
How to remove certain elements?

### ISSUE THREAD

**Issue by tiotrom** [xwiki-labs/cryptpad#683]
I apologize, this is not a bug but I am going crazy trying to remove the pricing and other elements. We provide no pricing, but there is no easy way to remove that as I see...feel free to remove this issue, but I thought to try :(

**Comment by ansuz** [comment]
Hi,
I just pushed a commit to change the text of the _pricing_ link to _features_ by using a string that had already been translated. The features page itself (`features.html`) should already hide the third column (_Premium_) which is displayed on instances with premium subscriptions.

This will be merged into our upcoming 4.6.0 release which we plan to release on May 27th.

**Comment by ansuz** [comment]
The previously mentioned fix was included in [yesterday's release](https://github.com/xwiki-labs/cryptpad/releases/tag/4.6.0), but I realized today that the link's text was only adjusted in the static pages' footers and not their headers. I've added a fix on our `main` branch.
