### ISSUE TITLE
Custom css

### ISSUE THREAD

**Issue by PierreMacherel** [xwiki-labs/cryptpad#684]
Could you add an option to inject custom css in a rich text document?
My use case would be to add [automatically numbering headings](https://2ality.com/2012/01/numbering-headingshtml.html), but it would be nice to also be able to customize the styles.

Regards

**Comment by ansuz** [comment]
Hi,

Please see [my answer to this similar issue](https://github.com/xwiki-labs/cryptpad/issues/691#issuecomment-833300738).

**Comment by mthld** [comment]
Hello,

As this feature (automatically numbering headings) is available on our early-access Document app and we won't implement this on Rich Text, I'll now be closing this issue.

Until they reach global availability I invite you to subscribe to a Premium plan so you can test it. :)
