### ISSUE TITLE
Editing locked in Sheet

### ISSUE THREAD

**Issue by Hypercube1234** [xwiki-labs/cryptpad#685]
I started experimenting with CryptPad and created a Sheet. It worked fine, but at certain point CryptPad reloaded in my browser and suddenly the document was locked. I can view it, but can’t edit anymore. Maybe I pressed a key, but I can’t find an option in the setting to revert this. This is also the case for every new Sheet I create. However, is not the case for Rich Text documents etc.  Here is an example:

https://cryptpad.fr/sheet/#/2/sheet/edit/oK5R9qtwulDPp65hSxHNY+DR/

How do you unlock?

I used Firefox 85.0.1,
I just checked it in Chrome (88.0.4324.182): I could edit there without problems.

However, I would prefer to be able to edit it in Firefox as I specifically chose CryptPad to avoid google :). I use a Lubuntu 20.04 operating system.

**Comment by ansuz** [comment]
Can you provide a screenshot of the what you see in Firefox? We tried opening the provided link and it was unlocked.
