### ISSUE TITLE
Feature request: Modify default styles and font formats

### ISSUE THREAD

**Issue by andreasmjg** [xwiki-labs/cryptpad#689]
**Feature request**
Currently the default styles and formats cannot be changed in the Cryptpad web app. Only the ones pre-defined can be applied. This means that if I want to change the font of the text in a document, I must go to each instance of that text in the document and change it manually. 

It would be good to be able to modify the default styles & formats, as I can in a Word/Google doc, and then the fonts that are based off of these styles/formats changes across the whole document.

If this could be saved with a template, it would be even better, so the styles/formats do not need to be reset for each new document opened. 

Thanks..!

**Comment by mthld** [comment]
Hello,

This indeed isn't possible on our Rich Text app. However, as announced in [this blog post](https://blog.cryptpad.org/2021/10/21/Announcing-new-apps/) we are currently trialing another apps based on OnlyOffice. Which enable a lot more functionalities.

I encourage you to [subscribe to a Premium plan](https://cryptpad.fr/features.html) and try them out! :)
