### ISSUE TITLE
Possibility to add table of contents to document body

### ISSUE THREAD

**Issue by andreasmjg** [xwiki-labs/cryptpad#690]
**Feature request**

It would be good to have the option of adding a table of contents to the document body that automatically provides page numbers and hyperlinks to the titles.

**Comment by mthld** [comment]
Hello,

As this feature is available on our early-access Document app and we won't implement this on Rich Text, I'll now be closing this issue.

Until they reach global availability I invite you to subscribe to a Premium plan so you can test it. :)
