### ISSUE TITLE
Ability to specify headers & footers

### ISSUE THREAD

**Issue by andreasmjg** [xwiki-labs/cryptpad#691]
**Feature request**

It would be useful to be able to specify headers and footers in a document, with the option to make the header/footer appear on each page and with the option to not display header/footer on the first page.

**Comment by ansuz** [comment]
Hi,

We're unlikely to implement this in our current rich text editor, however, we plan to integrate OnlyOffice's Word-like editor in the future.

**Comment by ansuz** [comment]
I saw that you created multiple issues for similar features that would be addressed by the addition of a more feature-rich word processor, so I made a new `word` label and applied it to all of them.

**Comment by mthld** [comment]
Hello,

As this feature is available on our early-access Document app and we won't implement this on Rich Text, I'll now be closing this issue.

Until they reach global availability I invite you to subscribe to a Premium plan so you can test it. :)
