### ISSUE TITLE
Cryptpad login hangs/fails at "Load Shared Folders (0%)" when using current Tor Browser Bundle (10.0.12) in Arch Linux

### ISSUE THREAD

**Issue by sirl1on** [xwiki-labs/cryptpad#693]
**Describe the bug**
* Cryptpad login hangs/fails at "Load Shared Folders (0%)" when using current Tor Browser Bundle (10.0.12) in Arch Linux.
* Other Browsers under Arch Linux are not affected.
* Tor Browser using TAILS live USB is not affected.

**Where did it happen?**
Using a private hosted instance running Cryptpad 4.0.0: Cryptpad hangs at "Load Shared Folders (0%)" with the following error:
`OperationError: The operation failed for an operation-specific reason cryptpad-common.js:2318:33
    onerror https://cryptpad.westring.digital/common/cryptpad-common.js?ver=4.0.0-1613938573057:2318`

Using cryptpad.fr running Cryptpad 4.2.0, the login fails with a visible error message:
`OperationError: The operation failed for an operation-specific reason`

**To Reproduce**
1. Go to cryptpad.fr in Tor Browser 10.0.12 in Arch Linux (installed from AUR)
2. Click on 'Log In'
3. Authenticate with valid credentials
4. See error `OperationError: The operation failed for an operation-specific reason`

**Expected behavior**
Login will succeed and the CryptDrive of authenticated user is shown.

**Screenshots**
On Cryptpad.fr (4.2.0)
![image](https://user-images.githubusercontent.com/26429/109863894-76667f00-7c62-11eb-84fb-9f86c57de51b.png)

**Browser (please complete the following information):**
 - OS: Arch Linux
 - Browser Tor Browser
 - Version 10.0.12 (from AUR or downloaded from TorProject)
 - Extensions installed NONE
 - Browser tweaks [NONE]

**Additional context**
- A self hosted instance using 4.2.0 was not tested
- Windows Tor Browser Bundle seems not to be affected

**Comment by MacLemon** [comment]
Additional data point:
I cannot reproduce this using Tor Browser bundle 10.0.12 on macOS.

**Comment by sirl1on** [comment]
Tor Browser 10.0.13 also does **not** seem to exhibit that bug! Still the bug is present in 10.0.12 so I would rule out a fix in a system dependency of Tor Browser (which should be few).

The only [change](https://blog.torproject.org/new-release-tor-browser-10013) between 10.012 and 10.013 seems to be [this bug](https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/40328), which does not seem to relate to the cryptpad error I am observing. Very weird.

As the bug is resolved by updating Tor Browser (which is mandatory) and the bug in my opinion is on Tor Browser's side, I feel this issue could be closed, but I rather want someone with more insight into cryptpad and it's crypto implementation to verify this.

**Comment by ansuz** [comment]
Thanks for the extra info!
