### ISSUE TITLE
unable to open any pad or create any new pad on 4.2.0 (C) when not logged in.

### ISSUE THREAD

**Issue by MacLemon** [xwiki-labs/cryptpad#695]
**Describe the bug**
Unable to open any pad or create any new pad on 4.2.0 (C) when not logged in.
The session hangs at the “Update content” stage infinitely.
(In any of Chromium, Firefox, Tor-Browser).

**Where did it happen?**
This happens since updating to 4.2.0 (C) on our instance https://pads.c3w.at/
It *may* already have been an issue with 4.1.0 or 4.0.0 which I cannot test anymore.

**To Reproduce**
1. Go to https://pads.c3w.at/
2. Check that you're ending up at the start page and you are *not* logged in.
3. Click on *any* of the pads to anonymously create a new pad
4. The new pad never loads.

Same for sharing links of existing pads.

**Expected behavior**
Existing pads should open, new pads should get created and subsequently open as well.

**Screenshots**
![Creating any pad hangs](https://user-images.githubusercontent.com/90635/110221895-145e8180-7ecf-11eb-923e-5df4137ba944.png)

**Browser (please complete the following information):**
 - OS: macOS 10.15.7 (Catalina)
 - Browsers 
   - Chromium 88.0.4324.96 (Official Build) (x86_64)
   - Firefox 86.0
   - Tor Browser 10.0.12
 - Extensions installed (uBlock matrix, but disabling it does not change behaviour)
 - Browser tweaks: none

**Additional context**
The issue *only* happens to sessions that are *not* logged in.
If you log in (which is perfectly possible in all cases) everything starts to work fine. Can create new pads, can open existing ones from the drive or sharing links.
The issue is happening with the tagged version 4.2.0.
Since `cryptpad.fr` is not running the tagged release version, it doesn't seem to be affected.
 
The `nginx.sample.conf` is severly out of sync with how CryptPad creates HTTP response headers. See #694.

** Workaround **
When switching from `tag 4.2.0` to `main 9826a4f87` seems to fix the issue, so we have done that.

**Comment by davidbenque** [comment]
This has been fixed in 4.2.1

**Comment by MacLemon** [comment]
Yes, I can confirm that the issue is fixed in 4.2.1 (C++).
