### ISSUE TITLE
Upgrade instructions correct?

### ISSUE THREAD

**Issue by TheNomad11** [xwiki-labs/cryptpad#697]
I am new to Cryptpad and recently installed 4.2.0. In order to update to the most relect release 4.2.1, I followed the [update instruction from the wiki](https://github.com/xwiki-labs/cryptpad/wiki/Installation-guide).

Inside the cryptpad folder:

```
git pull
npm update
bower update
```
But I am still on 4.2.0

In the release notes for 4.20 the upgrade process from 4.10 involves more steps:

 >Stop your server
> Get the latest code from the 4.2.0 tag (`git fetch origin && git checkout 4.2.0`, or just `git pull origin main`)
> Install the latest dependencies with `bower update` and `npm i`
> Restart your server

Are these specific instructions for this release only? How do I upgrade correctly? Thanks!

**Comment by davidbenque** [comment]
We had incorrectly tagged version 4.2.1 so it didn't include the right version number in the UI. We have re-tagged to correct this. To update delete your existing 4.2.1 tag and re-fetch as follows: 

```
git tag -d 4.2.1
git fetch origin tag 4.2.1
```

However the only change that this will produce is correctly showing the version number in the UI. Feel free to wait until the next version to update.
