### ISSUE TITLE
Sheets will crash when pressing ctrl+z

### ISSUE THREAD

**Issue by 0ki** [xwiki-labs/cryptpad#699]
**Describe the bug**
Sheets will crash when pressing ctrl+z

**Where did it happen?**
CryptPad.fr hosting a current version

**To Reproduce**
1. Go to cryptpad.fr/sheet/
2. Press CTRL+Z
3. Error appears "An error occurred during work with the document"
4. Document gets locked.

Testcase 2:
1. Go to cryptpad.fr/sheet/
2. Click cell E3
3. Type "lol"
4. Click cell B2
5. Press CTRL+Z
6. Error appears "An error occurred during work with the document"
7. Document gets locked.

**Expected behavior**
Testcase 1 - nothing should happend
Testcase 2 - cell E3 should be emptied.

**Screenshots**
![image](https://user-images.githubusercontent.com/3155267/110530001-985c7780-8122-11eb-8739-61f98bdc1b28.png)

**Browser (please complete the following information):**
Firefox

**Comment by davidbenque** [comment]
We are unable to reproduce this issue by following the supplied steps using Firefox on Ubuntu and Windows. When pressing Ctrl-Z you should be prompted to switch to "Strict" collaboration mode with popup in the screenshot below. Has this appeared in your case? 

![](https://user-images.githubusercontent.com/11028490/110623381-aa76fe00-8194-11eb-8b90-b4dcfdbf9e0e.png)

**Comment by 0ki** [comment]
Does neither testcase work? I updated the first testcase and also tested it to fail on Chromium.

1.    Go to cryptpad.fr/sheet/
2.  Click cell D10
3.    Press CTRL+Z
4.    Error appears "An error occurred during work with the document"
5.    Document gets locked.

**Comment by yflory** [comment]
I was able to reproduce the issue using Chromium in private mode only. It's a bug coming from OnlyOffice when used in a cross-origin iframe.
I've implemented a fix, it will be deployed with our next release.

**Comment by 0ki** [comment]
Thanks. That makes sense. I also use FPI on Firefox.
