### ISSUE TITLE
Firefox jumping to beginning of the page whenever link or comment is added

### ISSUE THREAD

**Issue by kertase** [xwiki-labs/cryptpad#701]
The issue is similar to an earlier issue.

When adding a comment or a link in the rich text editor the page jumps back to the beginning. Might be also found in some other options.

Firefox 85.0.1
Cryptpad 4.2.1

_Originally posted by @kertase in https://github.com/xwiki-labs/cryptpad/issues/406#issuecomment-796597073_

**Comment by ansuz** [comment]
This should be fixed as of 4.3.0.
