### ISSUE TITLE
Blob fetch fails with 401 Unauthorized when HTTP basic auth is enabled

### ISSUE THREAD

**Issue by Enteee** [xwiki-labs/cryptpad#705]
**Describe the bug**
With HTTP basic auth enabled, fetching a blob fails with a 401 Unauthroized. The blob fetch does not send the `Authorization: Basic XXXXXXXX` HTTP header.

**Where did it happen?**
I run a self hosted cryptpad instance behind a nginx reverse proxy. The full nginx config is [here](https://github.com/Enteee/duckpond.ch/blob/e0cd4db28a6b1417b7c583b78bddb08ffaa1d5ce/_env/nginx-https/conf.d/cryptpad.conf). I have http basic auth enabled for all all domains.

https://github.com/Enteee/duckpond.ch/blob/e0cd4db28a6b1417b7c583b78bddb08ffaa1d5ce/_env/nginx-https/conf.d/cryptpad.conf#L221-L222

**To Reproduce**

1. Upload file
2. Clear all local browser cache
3. Try downloading the just uploaded file again

**Expected behavior**
Blob should be fetched and document should be displayed.

**Screenshots**
![error](https://user-images.githubusercontent.com/5493775/111460755-a14dda00-871c-11eb-848b-ab987dd236d7.png)

**Browser (please complete the following information):**
 - OS: Nixos
 - User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0
 - Extensions installed: UBlock Origin, HTTPS everywhere, NoScript, uMatrix (can also reproduce with no plugins)
 - Browser tweaks: firefox "Enhanced Tracking Protection" strict/custom mode (can also reproduced if disabled)

**Additional context**
A workaround for this is to download the file manually from the drive by right click -> download. Then the file is cached and can be displayed normally.

**Comment by Enteee** [comment]
I am not quite sure if this is a configuration issue, I do believe this is a bug.

**Comment by ansuz** [comment]
I get the motivation for enabling basic auth, but we only test the provided example configuration. If we can find time in our roadmap I'd like to investigate the cause, but I'm not sure when that will happen.

**Comment by Enteee** [comment]
thank you for you answer @ansuz . I am on it, see last commit. I am going to deploy this to my cryptpad instance now and give it a bit of live testing. If that is successful, I will open a pr.

**Comment by ansuz** [comment]
The change to `Access-Control-Allow-Origin` seems unnecessary, and I know of instances where the increased specificity will cause problems. Otherwise it seems like a good direction. Feel free to submit the PR whenever you're content with it and I'll check again.

**Comment by Enteee** [comment]
> The change to `Access-Control-Allow-Origin` seems unnecessary, ...

According to [[1]](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin):

> For requests without credentials, the literal value "*" can be specified, as a wildcard; the value tells browsers to allow requesting code from any origin to access the resource. Attempting to use the wildcard with credentials will result in an error.

So no, the change is needed. Also there is a [whole page just discussing that](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSNotSupportingCredentials). I did try `*` and it's indeed not working. As expected.

**Comment by ansuz** [comment]
Thanks for the info. I won't accept it as it is, but either a comment describing that the `*` should be changed to what you have to support basic auth should work for everyone.

**Comment by ansuz** [comment]
I'll need to test further to confirm that `withCredentials` won't interfere with the standard behaviour.

**Comment by Enteee** [comment]
I've been running this now for a week in production without any issues. Just updated to 4.4.0 and will continue testing.

**Comment by ansuz** [comment]
I tested your branch and configuration on my personal instance and found that it broke some functionality.

There are two main use-cases that you aren't testing:

## CryptPad client changes on instances _without_ basic auth

Applying your changes to media-tag.js (the addition of `withCredentials` on all xhr requests) doesn't seem to work, presumably because the server isn't expecting the supplied credentials.

This will break every instance that is not using basic auth (eg. most of them).

## Purposefully loose _Access-Control-Allow-Origin_

**With _basic_auth_ disabled, standard configuration**

1. upload a file to your drive
2. right-click the file, then choose the _share_ option from the contextmenu and select the _Embed_ tab from the resulting modal.
3. copy the generated script tag that allows third-party sites to embed encrypted media and add it to a page on a third-party site
4. copy the media-tag from below this script tag and add it to the same third-party page
5. observe that the encrypted media loads and is displayed

**With a stricter _...Allow-Origin_ applied (`https://$sandbox_domain` as per your branch)** 

Do the same actions as above and observe that the media is _not_ displayed because the third party that was included in by `...Allow-Origin '*'` is disallowed by `...Allow-Origin https://$sandbox_domain`.

---

There may be other cases that fail, but these two are sufficient to prevent merging this changeset.

Unfortunately I don't have any solutions in mind that will support your use-case without introducing a considerable amount of complexity. You might be better off maintaining a slightly diverged fork which includes your own reverse proxy config and changes for media-tag.js.

**Comment by Enteee** [comment]
Thank you for testing this @ansuz. I will have a look at the found issues.

Am I right in the assumption that you were using firefox for your tests? If not, could you please provide your name and version of the tested browser?

I had issues with Firefox when it comes to nested HTTP Basic auth contextes. FF does sometime not seem to ask for credentials when it actually should. For example, when chain loading sub documents in an iframe. Quick first testing showed that with chrome I can not reproduce the "Purposefully loose Access-Control-Allow-Origin" you documented, but with FF I can. I am interested in this issue, and will dig deeper.

## Chrome
![chrome](https://user-images.githubusercontent.com/5493775/115669596-b7b50a00-a348-11eb-890b-f16860265837.png)

## Firefox
![test-ff](https://user-images.githubusercontent.com/5493775/115669943-24c89f80-a349-11eb-982b-006be15286dd.png)

**Comment by ansuz** [comment]
I tested with Firefox 87.0 on Ubuntu 20.04.

**Comment by Enteee** [comment]
I am still working on this/ I can easily reproduce this in firefox. But the more I look at it, the more it looks like firefox is the root of the problem. There used to be  quite a few people discussing subresource and http authenitcation dialogs (i.e. [here](https://bugzilla.mozilla.org/show_bug.cgi?id=647010)). It even seems to be a feature that was once implemented because of possible security concerns (tricking a user into sending his creds in a x-origin request). But what's unclear to me is what the current state of the implementation is in firefox.  I have also tried playing around with `network.auth.subresource-http-auth-allow` without any luck so far.

**Comment by mthld** [comment]
@Enteee is that something you're still trying to achieve? Is this issue still needed?

**Comment by Enteee** [comment]
@mthld , I am using this in production for more than a year now with an up to date cryptpad (5.0)
All the concerns @ansuz mentioned are either not an issue for me or don't exist anymore. Furthermore, the embed mode seems to have been removed from cryptpad anyways. Or it was moved, maybe, but we are not using this anyways so i don't really care..

So I am not quite sure about what to do with this.

**Comment by mthld** [comment]
Hey,

Embedding document is disabled for all OnlyOffice based apps, as it would create huge security issues: https://docs.cryptpad.fr/en/admin_guide/admin_panel.html?highlight=embed#enable-remote-embedding

Your use-case seems really particular, I'm not sure any other user will encounter this kind of issue. As we won't make these changes in CryptPad code base, I'm gonna close this issue now. :)

**Comment by Enteee** [comment]
@mthld Wat? 
Well it's a good thing that embedding is disable for this issue.
Cryptpad's attack surface is massive and it does only provide very little to lock down itself. Which i think is a crucial feature when somebody wants to run cryptpad privately. So putting it behind HTTP basic auth seems to be the cheapest and easiest for people to do who want to run a "private cloud". 

I even prodivde a fix for this isuse in: 
https://github.com/Enteee/cryptpad/commit/cf0058e5be605754aea16328f30004fe62af2722

Which I have tested and experience with for more than a year! And now you are simply closing this?
Its all there, but its only a matter of you not wanting to test and merge this.

**Comment by ansuz** [comment]
> All the concerns @ansuz mentioned are either not an issue for me or don't exist anymore.

As I described [here](https://github.com/xwiki-labs/cryptpad/issues/705#issuecomment-824462876), when I last tested your changeset it broke other configurations which we do support, such as the _purposefully loose Access-Control-Allow-Origin_ (`*`) which is needed to embed CryptPad documents in remote sites via iframe.

The fact that this is not an issue _for you_ is not sufficient justification for us to invest more time testing your changes and merging them into the mainline codebase. For that reason I agree with closing this so we can focus on more widely impactful issues.

**Comment by Enteee** [comment]
@ansuz last time i checked, embedding was no longer a cryptpad supported feature. At least all the UI integration for that has vanished.

Also embedding also just didn't work in firefox. Chrome was always fine. Firefox has moved forward: I re-tested this with modern ff and it works just fine. But yeah.... :+1:

**Comment by ansuz** [comment]
I've tested your patch under various configurations and confirmed that Firefox's incorrect behaviour has been fixed, and some iOS/iPadOS issues were resolvable. I've merged it into an experimental branch featuring some other access control features, and I expect it will eventually land in the `main` branch.
