### ISSUE TITLE
Uncaught TypeError while opening sheet

### ISSUE THREAD

**Issue by qwrtln** [xwiki-labs/cryptpad#706]
**Describe the bug**
Opening an existing sheet renders the following error in the console:

```
Uncaught TypeError: this.Content[Index].Get_AllFontNames is not a function
```
Sheet stops loading, data is inaccessible. 

**Where did it happen?**
cryptpad.fr

**To Reproduce**
Not sure, can't open my existing sheet, happens every time.

**Expected behavior**
Sheet opens without errors.

**Actual behaviour**
Sheet stops loading after error in the console.

**Screenshots**
Screen capture attached in support ticket #5jp2q8o2qn9 (visible to CryptPad support only).

**Browser:**

OS: Linux
Browser: Firefox, Brave, Chromium
Version 86.0.1 (Firefox), 1.21.77 (Brave), 89.0.4389.82 (Chromium)
Extensions installed: NoScript, Decentraleyes, ClearURLs - Firefox only
Browser tweaks: Chromium and Brave not tweaked, Firefox privacy hardened, no WebRTC, custom privacy mode, no 3rd party cookies, etc.

**Comment by ansuz** [comment]
We deployed a fix that should have addressed this some time ago but I forgot to check back that it had resolved the issue. Can you confirm whether this error still occurs?

**Comment by ansuz** [comment]
In the meantime, I'm going to close this.

**Comment by qwrtln** [comment]
After update and your intervention I could open the sheets without errors but the charts I had in there were gone. I suppose they were the culprit of the error. Updated sheets with regenerated charts work without problems. Thanks.
