### ISSUE TITLE
Safari and Firefox on iOS Problems

### ISSUE THREAD

**Issue by markwaypoint** [xwiki-labs/cryptpad#710]
Safari and Firefox from iOS as well as Safari from macOS won't open any pad from my cryptpad instance which was installed following the description from here. Firefox and Chrome from macOS are not experiencing any problems whatsoever. Opening any pad from cryptpad.fr works fine for all browsers and OSes I tried.

**Where did it happen?**
This happens on thirdparty cryptpad.akkon-hh.de

**To Reproduce**
1. Go to [cryptpad.akkon-hh.de](http://cryptpad.akkon-hh.de)
2. Click on rich text using one of the above browsers (Safari from macOS or Safari or Firefox from iOS)
3. See error, not loading properly, freezing at loadstate shown in the image below.
<img width="908" alt="Bildschirmfoto 2021-03-28 um 15 42 43" src="https://user-images.githubusercontent.com/81476082/112754406-42ba1300-8fdc-11eb-9888-b303327add01.png">

**Expected behavior**
It should open the cryptpad editor without problems.

**Browser (please complete the following information):**
 - OS: iOS 14.4.1  macOS 11.2.3
 - Safari + Firefox on iOS, Safari 14.0.3 (on macOS)
 
**Smartphone (please complete the following information):**
 - Device: iPhone XR, (unknown) iPad
 - OS: 14.4.1
 - Stock safari, Firefox App

**Additional context**
Might as well be a problem of the installation itself that I am not able to diagnose.

**Comment by ansuz** [comment]
We've recently introduced a "checkup" page which performs some automated diagnostics on the host instance. Its error messages aren't yet very helpful unless you can read the code, but [the page hosted on your instance](https://cryptpad.akkon-hh.de/checkup/) confirms that it isn't correctly configured.

It looks like the `httpUnsafeOrigin` and `httpSafeOrigin` in your `config.js` file are incorrect. There is [a comment in the example file](https://github.com/xwiki-labs/cryptpad/blob/main/config/config.example.js#L38-L57) which indicates they should be available only over HTTPS using the default port (443).

The [/api/config](https://cryptpad.akkon-hh.de/api/config) endpoint on your server suggests that you haven't configured [the httpSafeOrigin value](https://github.com/xwiki-labs/cryptpad/blob/main/config/config.example.js#L59-L75), which will effectively cause clients to load resources from an unreachable source.
