### ISSUE TITLE
Feature: table export: implement support for Firefox export as .xlsx .ods .csv .pdf

### ISSUE THREAD

**Issue by foss-** [xwiki-labs/cryptpad#711]
**Describe the bug**
Currently export in Chromium browsers supports .xlsx .ods .bin .csv .pdf
while Firefox only supports export as .bin

**Expected behavior**
Would be great if Firefox could support export to those common formats as well.

**Browser (please complete the following information):**
 - OS: macOS 11.2.3
 - Browser: Firefox 89.0a1 (2021-04-01) (64-Bit)

**Comment by ansuz** [comment]
Hi,
Are you testing this on CryptPad.fr or your own instance?

**Comment by foss-** [comment]
Sorry my bad. This is instance specific and I will follow up with the responsible person. Excuse the noise.

**Comment by meaz** [comment]
I see the exact same thing on cryptpad.fr...

**Comment by ansuz** [comment]
@meaz: this feature depends on some fairly new APIs being enabled in client browsers. It may break under extreme conditions: such as when using an old version of Firefox (ESR) or Edge/IE, if you've made modifications to your about:config, or if you're running extensions which actively interfere with standard behaviour.

**Comment by meaz** [comment]
thanks ansuz

**Comment by meaz** [comment]
@ansuz  I've tried with firefox 87, with no plugin and no change in about:config.
It is working fine on cryptpad.fr but not on cryptpad.disroot.org. Could it be a server issue? And if yes, what should be looking for?

**Comment by ansuz** [comment]
@meaz the most likely explanation is that you're not setting [the headers that enable SharedArrayBuffer](https://github.com/xwiki-labs/cryptpad/blob/main/docs/example.nginx.conf#L63-L69).

**Comment by meaz** [comment]
@ansuz it is set. I forgot that I have this error with firefox only, not chromium...

**Comment by ansuz** [comment]
> @ansuz it is set. I forgot to tell you that I have this error with firefox only, not chromium...

There are around 700 third-party instances, so ss a rule we can't realistically spend much time helping to configure them. That said, here's a quick check that suggests the headers aren't being set as you believe.



```bash
ansuz:~$ for d in https://cryptpad.fr https://cryptpad.disroot.org;do echo $d;curl -vvv $d/common/onlyoffice/v4/web-apps/apps/spreadsheeteditor/main/index.html --stderr - | grep "cross-origin";echo;done;
https://cryptpad.fr
< cross-origin-resource-policy: cross-origin
< cross-origin-embedder-policy: require-corp

https://cryptpad.disroot.org
```

We've been developing a "checkup" page (`/checkup/`) that automatically runs some diagnostics on instances to detect these common errors. I'll try to integrate this test into that page before our next release.
