### ISSUE TITLE
Which Port to Internet

### ISSUE THREAD

**Issue by 4nanook** [xwiki-labs/cryptpad#712]
Which port is to be accessed from the Internet, 3000 or 3001 (I will setup a reverse proxy just need to know which to point it to)?

**Comment by ansuz** [comment]
CryptPad is meant to be server via two domains with strict CSP headers that restrict the functionality of the second "sandbox" domain. Port 3001 should only be used for the purposes of testing and development purpose when accessing the site via http://localhost or a similar local address.

**Comment by 4nanook** [comment]
The Apache configuration only shows one virtual host.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.

**Comment by ansuz** [comment]
The apache config was not written by the development team. It doesn't take advantage of the recommended security features and should be considered insecure. [We recommend NGINX](https://github.com/xwiki-labs/cryptpad/blob/main/config/config.example.js#L3-L20).

**Comment by ansuz** [comment]
As per my [recent comment on another Apache-related issue](https://github.com/xwiki-labs/cryptpad/issues/698), I've updated our wiki to indicate that Apache is neither supported nor recommended.
