### ISSUE TITLE
Feature request: File → Save (Show) in CryptDrive

### ISSUE THREAD

**Issue by sebalis** [xwiki-labs/cryptpad#713]
After about 9 months of regular CryptPad experience including some local administation and user support, the request that I keep hearing is a clearer way of saving an opened document in one’s personal CryptDrive. We all know that there is a pop-up that can appear when a pad is opened. But this pop-up is both slightly annoying and premature: Often the need to save is only realised much later. Also it’s not entirely clear for which documents the pop-up appears and for which it does not. I propose that an item „Save in CryptDrive“ be added to the File menu. If the document is already saved in the personal CryptDrive, the item could change to „Show in CryptDrive“ to open a new browser tab in which the CryptDrive view is opened in the correct folder and the document is selected. That would also be a helpful function for previously saved docs that got lost in a complex folder structure.

**Comment by CryptOwl** [comment]
Seconding this. It's rather confusing for users not being able to import/save an opened document into one's own CryptDrive at any time.

**Comment by ansuz** [comment]
We've implemented this feature and deployed it to CryptPad.fr. It will be included in the upcoming release (4.5.0) which will be published as soon as I finish writing its release notes.
