### ISSUE TITLE
Cryptpad update process not working

### ISSUE THREAD

**Issue by grrrrr** [xwiki-labs/cryptpad#719]
**Describe the bug**
I have a cryptpad instance running that I am attempting to update.

The system was installed following the [installation guide](https://github.com/xwiki-labs/cryptpad/wiki/Installation-guide#upgrading-cryptpad) and updated using the steps outlined in the same guide.

despite the upgrade steps apparently workings, the web interface still shows it running version `3.19.0`,  and files on disk such as CHANGELOG.md reference 3.19 as latest release.

There is no customization in place.

running git pull results in

```
$ git pull
Already up to date.
```

**Where did it happen?**

3rd party instance not accessible from internet

**Comment by ansuz** [comment]
You have most likely checked out a particular git tag or a different branch. Switch to the `main` branch and pull.
