### ISSUE TITLE
Upgrade from v3 to v4 - blank landing page

### ISSUE THREAD

**Issue by hugotlz** [xwiki-labs/cryptpad#720]
After upgrading cryptpad instance from v3 to v4, we have a blank landing page.
the url is pad.data-expertise.com
We have an ssl reverse proxy and behind clear stream on http/80 port.
but the instance is working with /pad
thanks

**Comment by ansuz** [comment]
It looks like you've updated to version 4.1.0, which was the release which introduced support for the dark theme. We noted the following in [the CHANGELOG](https://github.com/xwiki-labs/cryptpad/blob/main/CHANGELOG.md#update-notes-3):

> ..this release introduces some major changes to CryptPad styles. **If you have customized the look of your instance we recommend testing this new version locally before deploying it to your server to ensure that there are no critical conflicts.**

Visiting the home page yields an error in the browser console: 

>  `variable @colortheme_pad-bg is undefined`

Which suggests that you have customized the style pages and not resolved conflicts as noted above.
