### ISSUE TITLE
Contacts between 2 instances of self-hosted Cryptad

### ISSUE THREAD

**Issue by infocilla** [xwiki-labs/cryptpad#721]
Hi everyone,
Would it be possible to add a contact from another distant instance into my own instance and then share documents with or from this "external" contact ? Or contacts are only registered user from one unique instance of Cryptpad ?
Thanks a lot.
Romain

**Comment by ansuz** [comment]
You can only add contacts from your local CryptPad instance as we don't currently implement federation.

**Comment by infocilla** [comment]
Ok thanks @ansuz 
And thank you for the great work done on Crypto as, what an amazing app !
