### ISSUE TITLE
CryptPad Stuck at black screen

### ISSUE THREAD

**Issue by mxamusic** [xwiki-labs/cryptpad#722]
I have followed the wiki to install Cryptpad just to test it out. 

Created an account when I log in I get nothing but a black page

![image](https://user-images.githubusercontent.com/16447622/116131812-e7179e00-a6dd-11eb-8629-6166d620037e.png)

Knowing that the server is running on Debian 10 all the packages are installed (NPM, Bower) Nodejs version 16 using NVM

![image](https://user-images.githubusercontent.com/16447622/116131906-fd255e80-a6dd-11eb-8fac-5829c46feb45.png)

even when I click on code without log in I still get the same black page

I tried a different browser and still the same 
![image](https://user-images.githubusercontent.com/16447622/116132061-280fb280-a6de-11eb-834d-c08b940e7af4.png)

**Comment by ansuz** [comment]
Please see [the comment for the `httpUnsafeOrigin` config value](https://github.com/xwiki-labs/cryptpad/blob/main/config/config.example.js#L34-L41). It looks like you're trying to access your instance via an IP that doesn't match what you have configured.

Assuming you're running the latest release (4.4.0) you can also visit `http://<your-instance-URL>/checkup/`, which should provide a fairly detailed error message explaining what is wrong with it.
