### ISSUE TITLE
Pasting text removes the page border

### ISSUE THREAD

**Issue by l0drex** [xwiki-labs/cryptpad#724]
**Describe the bug**
When pasting text into a document, the page border gets removed for that paragraph.

**Where did it happen?**
cryptpad.fr

**To Reproduce**
1. Open a document
2. Past some text
3. The text goes beyond the page border on the left and right side.

**Expected behavior**
The page border should remain after pasting text.

**Screenshots**

**Browser (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 88
 - Extensions installed: UBlock Origin
 - Browser tweaks: Firefox "Enhanced Tracking Protection" custom mode

**Additional context**
Happens while working with others.

**Comment by ansuz** [comment]
This is most likely related to the content that is being pasted. Can you please provide a screenshot and view link (from the share menu) of a document containing some example text which demonstrates this? If you prefer not to share in public please create a support ticket on CryptPad.fr which references this GitHub issue.

**Comment by l0drex** [comment]
What I mean with *removes page border* is that the pasted text had the default page border size. The other text within that document had a custom one.

While trying to create an example document I realized that cryptpad has actually no way of setting a custom border size, so I'm going to close this issue. I really have no idea how that custom page border got into that document in the first place.
