### ISSUE TITLE
Administration Panel?

### ISSUE THREAD

**Issue by longestmt** [xwiki-labs/cryptpad#726]
I recently stood up a (mostly) functioning cryptpad instance via docker. (Thank you guys for such a great product)

My question is regarding administration. Is there an administration portal I can access? It looks like the administration documentation has not been written (perhaps I could help there!).

I'd like to do the following:

1. Disable sign-ups (Preferably I'd like to send invitation links to my users)
2. Increase storage space per user
3. Block anonymous usage (outside of links provided to documents)

I'm comfortable with editing a config file if there isn't an administration portal.

Thanks!

**Comment by ansuz** [comment]
The current installation guide has [this section](https://github.com/xwiki-labs/cryptpad/wiki/Installation-guide#setting-up-admin-keys) which documents how to add an administrator's public key to the server's config. After restarting the server any admin users should see an "Administration" entry in their user admin menu (in the top-right corner of the page).

We plan to publish our new admin docs [here](https://docs.cryptpad.fr/en/admin_guide/index.html) later this week. It will answer most of your questions.
