### ISSUE TITLE
'Uncaught EvalErrors' for Spreadsheets

### ISSUE THREAD

**Issue by longestmt** [xwiki-labs/cryptpad#727]
**Describe the bug**
When I try to create or access a spreadsheet I get this error.

> Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' resource: sub.domain.xyz".

**Where did it happen?**
My self-hosted instance

**To Reproduce**
1. Install via docker-compose

> cryptpad:
> image: "promasu/cryptpad:nginx"
> hostname: cryptpad
> container_name: cryptpad
> environment:
> - PUID=1000
> - PGID=1000
> - CPAD_MAIN_DOMAIN=sub.domain.xyz
> - CPAD_SANDBOX_DOMAIN=sandbox.domain.xyz
> - CPAD_HTTP2_DISABLE=true
> volumes:
> - ./cryptpad/blob:/cryptpad/blob
> - ./cryptpad/block:/cryptpad/block
> - ./cryptpad/customize:/cryptpad/customize
> - ./cryptpad/data:/cryptpad/data
> - ./cryptpad/files:/cryptpad/datastore
> - ./cryptpad/config.js:/cryptpad/config/config.js
> ports:
> - "780:80"
> - "7443:443"
> expose:
> - "780"
> - "7443"
> ulimits:
> nofile:
> soft: 1000000
> hard: 1000000

2. Try to open a spreadsheet after signing up

**Expected behavior**
Spreadsheet should open without issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/1509654/116888204-2cb1fa80-abf9-11eb-9062-926eaf5449e1.png)

**Browser (please complete the following information):**
-Brave

**Comment by ansuz** [comment]
This is caused by incorrect configuration of the sandboxing system. Loading the /checkup/ page on your instance will provide hints of what you've done wrong.
