### ISSUE TITLE
No access to drive while trying to customize

### ISSUE THREAD

**Issue by ghost** [xwiki-labs/cryptpad#728]
Hi,
On my personal cryptpad instance (v4.5.0), I've followed the instructions to customize (https://docs.cryptpad.fr/en/admin_guide/customization.html#application-config).

However, after restarting the service and with the default values of the variables, I can not access to my drive anymore. I'm stuck on a blank page with the following adress: `https://xx.xxxxxxx.xx/drive/#/4/drive/login=e30%3D/` and the browser console give me the following message: 
```
Uncaught TypeError: **plugin.load is not a function**
    at Module.<anonymous> (require.js?ver=2.3.5:1095)
    at require.js?ver=2.3.5:134
    at require.js?ver=2.3.5:1189
    at each (require.js?ver=2.3.5:59)
    at Module.emit (require.js?ver=2.3.5:1188)
    at Module.check (require.js?ver=2.3.5:938)
    at Module.enable (require.js?ver=2.3.5:1176)
    at Module.init (require.js?ver=2.3.5:788)
    at callGetModule (require.js?ver=2.3.5:1203)
    at Object.completeLoad (require.js?ver=2.3.5:1590)
```

I can see the home page still, but any other action (login, opening a new document as Anonymous) gives me a blank page.

I'm using Apache2 (I know it is not supported...) because I use other services on this server that require apache. So I have no sandboxing feature and so on and for the moment I'm OK with it (it is just a personal testing environment)

My question: What does mean "plugin.load is not a function" ? **I was just wondering if it was only a webserver/reverse proxy issue or someting else.**

PS: in the documentation, at the "restricting guest access" section (https://docs.cryptpad.fr/en/admin_guide/customization.html#restricting-guest-access) the variables in the line to add in `customize/application_config.js` begin with `AppConfig.` whereas all variables in `www/common/application_config_internal.js` start with `config.` What would be the correct prefix of the variables name ?

Thanks 
Infocilla

OS: Lubuntu 20.04
node version: 12.14.0
npm version: 7.12.0
bower version 1.8.12

**Comment by ansuz** [comment]
> I've followed the instructions to customize (https://docs.cryptpad.fr/en/admin_guide/customization.html#application-config).
> 
> However, after restarting the service and with the default values of the variables, I can not access to my drive anymore.

I'm not sure I understand. You customized your instance with the default values of the variables? If you're using the default values then you shouldn't need to customize anything.

Am I correct to believe it was working before you made any modifications? If so, then the error will probably be obvious if you can post what those modifications are.

I'd suggest either:

1. paste the contents of your `customize/application_config.js` here
2. paste the diff of the default file in `customize.dist` and that in `customize` (the output of `diff customize.dist/application_config.js customize/application_config.js`)

Alternatively, remove the customizations which are presumably incorrect, restart the server to apply them, and repeat the customization process more slowly while restarting the server after each minor change. It will be slow but it will tell you exactly what change introduces the problem.

**Comment by infocilla** [comment]
Hi,
Thanks for your help.
I now understand my mistake:
I was copying the whole `www/common/application_config_internal.js` content into `customize/application_config.js`, including the code at the begining.
```
define(function() {
    var config = {};
```
It works perfectly fine now, just copying the lines I want to customize.

The `customize/application_config.js`now looks like: 
```
/*
 * You can override the configurable values from this file.
 * The recommended method is to make a copy of this file (/customize.dist/application_config.js)
   in a 'customize' directory (/customize/application_config.js).
 * If you want to check all the configurable values, you can open the internal configuration file
   but you should not change it directly (/common/application_config_internal.js)
*/
define(['/common/application_config_internal.js'], function (AppConfig) {

/* Select the buttons displayed on the main page to create new collaborative sessions.
     * Removing apps from the list will prevent users from accessing them. They will instead be
     * redirected to the drive.
     * You should never remove the drive from this list.
     */
    AppConfig.availablePadTypes = ['drive', 'teams', 'pad', 'sheet', 'code', 'slide', 'poll', 'kanban', 'whiteboard',
                                /*'doc', 'presentation',*/ 'file', /*'todo',*/ 'contacts' /*, 'calendar' */];
    /* The registered only types are apps restricted to registered users.
     * You should never remove apps from this list unless you know what you're doing. The apps
     * listed here by default can't work without a user account.
     * You can however add apps to this list. The new apps won't be visible for unregistered
     * users and these users will be redirected to the login page if they still try to access
     * the app
     */
    AppConfig.registeredOnlyTypes = AppConfig.availablePadTypes;

    return AppConfig;
});
```

**However, it is still needed to change the variables name, from `config.xxxx` to `AppConfig.xxx` into the file `customize/application_config.js` otherwise it doesn't work. It could be worth updating the documentation to reflect this.**
