### ISSUE TITLE
Not saving changes in current pads or new pads

### ISSUE THREAD

**Issue by DanielW1064** [xwiki-labs/cryptpad#730]
**Describe the bug**
I upgrade our CryptPad step-by-step following the instructions in the releases (from 4.1.0 - 4.5.0). Also I changed the nginx-configuration. Now I can access the main page and login to my account. This seems to work so far.
But when I open a current pad (doc) or create a new one, after a short time I get the error: "An unrecoverable error has occured. Click OK to reload."

It seems to be a problem with storing or the access of the folders?

I can not find any error in my browser console or in the logs of nginx. Is there a possible to get more information from the path of cryptpad?

**Chekup**
When I take pad.dbh-meet.de/chekup/, I get the following error:
Failed test number | 8

`Unable to create, retrieve, or remove encrypted credentials from the server. This is most commonly caused by a mismatch between the value of the blockPath value configured in cryptpad/config/config.js and the corresponding settings in your reverse proxy's configuration file, but it can also be explained by a websocket error. Changes to cryptpad/config/config.js will require a server restart in order for /api/config to be updated.`

**Where did it happen?**
On my own server: pad.dbh-meet.de

**Screenshots**
[https://pad.dbh-meet.de/pic.png](https://pad.dbh-meet.de/pic.png)

**Browser (please complete the following information):**
 - OS: Windowes 10
 - Browser: firefox, chrome, edge

**Comment by ansuz** [comment]
This isn't a bug in the platform, but a result of your misconfiguration. 

There is [a large, detailed comment in our example config](https://github.com/xwiki-labs/cryptpad/blob/main/config/config.example.js#L38-L47) that explains how `httpSafeOrigin` should be set.

If further assistance is required please consider contacting as at sales@cryptpad.fr for a paid support contract.

**Comment by DanielW1064** [comment]
Sorry - you were absolutely right. The problem was due to the permissions of the folders and files on the file server.
