### ISSUE TITLE
Code editor jumps to current cursor position when other users make changes

### ISSUE THREAD

**Issue by JanRei** [xwiki-labs/cryptpad#731]
**Describe the bug**
The code editor jumps to the current position of my cursor whenever another user makes a change to the document. In most cases this undesirable because I am currently reading an other part of the document.

**Where did it happen?**
CryptPad.fr

**Expected behavior**
Scroll position should be preserved to avoid disruptions of the workflow.

**Browser (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 88.0.1, Google Chrome 90

**Comment by CryptGoat** [comment]
I and my team share the sentiment that is a major problem for the workflow while working with multiple persons in a code pad.

**Comment by CryptGoat** [comment]
From the 4.7.0 changelog:
> The code that is responsible for preserving your cursor position when using the code editor collaboratively was capable of interfering with active scrolling when other users' edits were applied.
Scroll position is still jumping to my cursor whenever somebody is editing.

**Comment by JanRei** [comment]
I cannot reproduce this issue anymore with version 4.7.0.
