### ISSUE TITLE
& symbol shows up as HTML in Calendar

### ISSUE THREAD

**Issue by n194** [xwiki-labs/cryptpad#736]
**Describe the bug**
`&` shows up as `&amp;` in Calendar event preview.

**Where did it happen?**
Occurs on Firefox on cryptpad.fr.

**Screenshots**
![Screenshot_20210527_200034](https://user-images.githubusercontent.com/67550725/119815444-0ff8a200-bedb-11eb-8383-ab9604bad4fa.png)

**Comment by mthld** [comment]
Would that be some encoding/UTF-8 issue?
