### ISSUE TITLE
Feature request: Import Kanban from Wekan/Trello

### ISSUE THREAD

**Issue by n194** [xwiki-labs/cryptpad#737]
For migration from popular Kanban platforms, it would be helpful to be able to import Kanban exports from Wekan and Trello.

**Comment by ansuz** [comment]
Import from Trello's json format was included in our [4.8.0](https://github.com/xwiki-labs/cryptpad/releases/tag/4.8.0) release. I'm not sure whether Wekan's format differs, so I'll close this for now and wait for further information from a Wekan user that hopes to migrate to CryptPad.

**Comment by n194** [comment]
Trello import works! Wekan's JSON export format is different though and doesn't work..
