### ISSUE TITLE
Poll with option ranking

### ISSUE THREAD

**Issue by steinjer** [xwiki-labs/cryptpad#739]
Feature Request for Poll:
currently you can only vote between YES, MAYBE and NO. But if I like to rank the options it would be nice to give points to options.

Example:
```
Which fruit do you like? You can vote with max. 5 points.
Option 1: apple
Option 2: banana
Option 3: zitrone

User 1 votes:
Option 1: 4 points
Option 2: 1 point
Option 3: 0 points

User 2 votes:
Option 1: 1 point
Option 2: 3 points
Option 3: 1 points

Sum:
Option 1: 5 points
Option 2: 4 points
Option 3: 1 points
```

**Comment by ansuz** [comment]
As of today's 4.7.0 release we've introduced a new _form_ app that allows users to create detailed surveys. Ranked choices are one of the supported types of questions. As of this first version we only support ordered preferences, not a point-spending scenario as you have described.
