### ISSUE TITLE
Login leads to white page although already logged in instance seems to work

### ISSUE THREAD

**Issue by s0m3guy** [xwiki-labs/cryptpad#740]
**Describe the bug**
I got cryptpad running on my raspberry pi and wanted to create a new account. Did so but after trying to log in, I only see a white page. So the login seems to work (otherwise it says the login information was wrong), but I don't see anything. In one Firefox tab, I am already logged in as the administrator account and see the drive perfectly fine. But when I try to log in using the administrator information in another tab, I see this white blank page. So this applies to new accounts but also already existent accounts.

**Where did it happen?**
This happens on my local raspberry pi which is running cryptpad. I access it via LAN. 

**To Reproduce**
1. Create new account or use admin account
2. Log in using the account information
3. See white blank page

**Expected behavior**
I expect to see the drive with all my directories and files

**Screenshots**
Nothing really to see, it's just a white blank page, zero information on it.

**Browser (please complete the following information):**
 - OS: Both newest Firefox 88.0.1 and Chrome 91.0.4472.77, also newest Bromite on mobile Android.
 - Extensions installed: uBlock Origin, not sure if there is anything else which is relevant as the same thing occurs on my mobile bromite browser with no extensions
 - Browser tweaks: nothing I know of, default settings

**Smartphone (please complete the following information):**
 - Device: OnePlus 6T
 - OS: Android 10
 - Browser: Bromite
 - Version: 91.0.4472.50

**Comment by ansuz** [comment]
This is most likely not a bug in the software. Please consult the /checkup/ page from the device that is having problems for more information.

**Comment by s0m3guy** [comment]
> 
> 
> This is most likely not a bug in the software. Please consult the /checkup/ page from the device that is having problems for more information.

What's that /checkup/ page and how do I access it?

**Comment by ansuz** [comment]
Navigate to that page on your instance, like: https://your-domain.com/checkup/

**Comment by s0m3guy** [comment]
Ok then I understood it correctly. I tried that but nothing comes up. Also
tried that on my raspberry itself via remote and visiting
http://localhost/checkup/ but it can't find anything with that address, it
seems. I do access cryptpad via a specific port so I usually use
http://x.x.x.x:z but http://localhost/checkup:z or
http://localhost/checkup/:z also does not work.

**Comment by ansuz** [comment]
It sounds like you have some fundamental misconceptions about networking. `localhost` refers to an address on the machine you are currently using. Attempting to access a remote machine via `localhost` will naturally fail because your browser will try to load a server from your current device, so of course it will fail.

**Comment by s0m3guy** [comment]
No, I did that on the machine running Cryptpad. On that specific device the
address is indeed localhost.

**Comment by s0m3guy** [comment]
> 
> 
> It sounds like you have some fundamental misconceptions about networking. `localhost` refers to an address on the machine you are currently using. Attempting to access a remote machine via `localhost` will naturally fail because your browser will try to load a server from your current device.

I got it working now using checkup and fixing the issues, no idea what I did wrong before. Thank you!
