### ISSUE TITLE
[Feature] "Store in CryptDrive" option within Team documents

### ISSUE THREAD

**Issue by CryptGoat** [xwiki-labs/cryptpad#744]
In reference to this issue https://github.com/xwiki-labs/cryptpad/issues/713 and to this commit https://github.com/xwiki-labs/cryptpad/commit/7e8d26e66835c1070cd44ea8f349070b52d3d32d I suggest that the "Store in CryptDrive" option should also be introduced to documents that are accessed via team CryptDrives. Although it is already possible to store documents in your own CryptDrive via right-click in the team file explorer it would be more consistent and convenient to have this option available in all cases where one should be able to do this.

**Comment by ansuz** [comment]
As of today's 4.7.0 release it is possible to store the currently open document in your own drive via the File menu regardless of whether it is already stored in one of your teams' drives.
