### ISSUE TITLE
[Feature] Login prompt when trying to access a restricted document while not being logged in

### ISSUE THREAD

**Issue by CryptGoat** [xwiki-labs/cryptpad#747]
There are situations when you are not logged in and trying to access a document via a share link but only authorized users have access to this document. Instead of or additionally to showing the corresponding error message the user could be prompted to provide login data to gain access to the document (as long the user account has the rights to access the document). If the account is not authorized the current error message can be shown.

**Comment by ansuz** [comment]
> There are situations when you are not logged in and trying to access a document via a share link but only authorized users have access to this document.

Can you be specific about which situations you have in mind? We can review our code and come up with a list ourselves, but we're far more likely to implement this if that part is already out of the way.

**Comment by CryptGoat** [comment]
Sure.
1. Somebody from a team sends a link to document with restricted access to another member of that team. In my case it is a sensitive protocol file that is being accessed for meeting on a regular basis.
2. That team member clicks the link (e.g. in an external chat or mail) and the browser launches. 
3. If that team member is not logged in (yet) CryptPad will simply tell the person that it is not authorized to access the document with no further option for interaction. 
4. The person has to close that window/tab and open CryptPad in a new window, login and either access the document from a personal or team drive or click the link after logging in. 
5. A login prompt would allow direct access without these additional steps - as long the provided account is authorized to access the document.

It's no so much trouble if you stay logged in at all times but many around me don't keep all their cookies saved at all times so this situation happen quite a lot.

**Comment by ansuz** [comment]
As of today's 4.7.0 release users that are not logged in should be prompted to visit the login page when they try to access a document with an access list.
