### ISSUE TITLE
Hi! if you can help me please, how can i disable "Non-registered user"?

### ISSUE THREAD

**Issue by SanduEugeniu** [xwiki-labs/cryptpad#751]
Hi! if you can help me please, how can i disable "Non-registered user"?

**Comment by ansuz** [comment]
This is described in [our documentation](https://docs.cryptpad.fr/en/admin_guide/customization.html#application-config). The relevant configuration point is described [here](https://github.com/xwiki-labs/cryptpad/blob/main/www/common/application_config_internal.js#L16-L23).

**Comment by SanduEugeniu** [comment]
thank
