### ISSUE TITLE
Move the Add document button to the left

### ISSUE THREAD

**Issue by Th0rgal** [xwiki-labs/cryptpad#752]
Hello,

Thank you very much for this tool, I love it! I have a suggestion for the drive because I find the position of the "add document" button really annoying. When I add a lot of documents at the same time it is constantly moving. Would it be possible to put it at the start of the list instead of the end?

![image](https://user-images.githubusercontent.com/41830259/122034093-746b9a80-cdd1-11eb-8d89-c458f9997d90.png)

Thanks again,
Thomas

**Comment by davidbenque** [comment]
The screenshot does not include it, but there is a New button in the toolbar which offers the same functionality in almost the same place

<img width="745" alt="218880410-2d1172dc-02a6-4ee9-97e7-955e32c97325" src="https://user-images.githubusercontent.com/11028490/219338737-eecf7e27-3f30-4ef0-9c03-94d41398433a.png">
