### ISSUE TITLE
Erroneous `nginx-src` in Content-Security-Policy Header?

### ISSUE THREAD

**Issue by MacLemon** [xwiki-labs/cryptpad#756]
https://github.com/xwiki-labs/cryptpad/blob/8074a6191ccce3744203a2c96beb2ed87a1e82d6/docs/example.nginx.conf#L134

The part with `nginx-src 'SELF'` seems to be a mistake. There's no CSP part by that name. Maybe a missing variable substitution?

I don't think it causes any problems with browsers other than a log line in the console, but it may be indicative of something important that's missing instead.

Line Logged (on multiple occasions):
```
Unrecognized Content-Security-Policy directive 'nginx-src'.
```

(CryptPad 4.7.0)

**Comment by ansuz** [comment]
I don't see where this might have come from or how it might have been injected. Firefox is a bit weird about logging in that errors and warnings in shared workers can be printed in every console, not just those related to the related domain. Is it possible this is coming from another domain from an unrelated tab you have open?
