### ISSUE TITLE
Recently typed text gets lost when another user joins a document

### ISSUE THREAD

**Issue by iskandr** [xwiki-labs/cryptpad#76]
I just started using cryptpad but I noticed that when a collaborator joins my document the past ~10 seconds of writing get reverted.

**Comment by cjdelisle** [comment]
Is the document non-sensitive (meaning you can share the link with us) ?
With debugging tools we are able to go back in time and understand what happened and why if we have the keys to the document. You can contact us at research at xwiki dot com if you want to share this information privately.

**Comment by lgierth** [comment]
I think we've noticed a similar bug a few times in notetaking sessions with ~10 participants. I'll watch out for it.

**Comment by ansuz** [comment]
This issue should have been addressed some time ago. Please re-open it if you notice this behaviour.
