### ISSUE TITLE
folder download as ZIP contains not useful json-files of spreadsheets

### ISSUE THREAD

**Issue by abelbabel** [xwiki-labs/cryptpad#762]
Hi,

when I download a folder as ZIP-archive, I get most of the content in a usable state. But the spreadsheets in that folder will be JSON files in the ZIP-archive that seem to contain only (for me) useless meta-data.

Could you please fix it? I want to have the content of the spreadsheets in that ZIP-archive (as csv, json or whatever) ...

Kind regards,
abelbabel

**Comment by mthld** [comment]
Hello,

Thanks for your report. To do so you'll need to use a supported web browser, I encourage you to try using Mozilla Firefox latest version. It works perfectly on my end. :)
