### ISSUE TITLE
Weblate "account" license

### ISSUE THREAD

**Issue by comradekingu** [xwiki-labs/cryptpad#768]
https://weblate.cryptpad.fr/projects/cryptpad/#information

"accounts" is for some reason proprietary.
With everything else being AGPLv3+, that counts as a mistake that can be corrected I would think.

Also, it isn't possible to add new languages for users. Is that intentional?

My account is https://weblate.cryptpad.fr/user/kingu/

**Comment by ansuz** [comment]
Aren't you the person who wrote to us saying you don't contribute to projects that use codes of conduct?

**Comment by comradekingu** [comment]
Would that matter?
