### ISSUE TITLE
LESS: '/customize/src/less2/include/usergrid.less?ver=4.8.0-1625683485727' wasn't found (0)

### ISSUE THREAD

**Issue by francoisjacquet** [xwiki-labs/cryptpad#769]
**Describe the bug**
After login, when loading the CryptDrive, an error on the screen reads:
> LESS: '/customize/src/less2/include/usergrid.less?ver=4.8.0-1625683485727' wasn't found (0)

**Where did it happen?**
Third-party instance at https://demo.rosariosis.com/

**To Reproduce**
1. Upgrade to v4.8.0
2. Click on Login, enter your credentials and login
3. See error "LESS: '/customize/src/less2/include/usergrid.less?ver=4.8.0-1625683485727' wasn't found (0)"

**Expected behavior**
The file not found can be found under the `customize.dist` folder, so why was it not loaded from there?

**Screenshots**

**Browser (please complete the following information):**
 - OS: Debian 
 - Browser Firefox 68
   - variations ESR
 - Version 68
 - Extensions installed: UBlock Origin
 - Browser tweaks : Firefox "Enhanced Tracking Protection"

**Additional context**
The error cannot be seen anymore, as the file was copied from `customize.dist`.

Edit:
After deleting the `usergrid.less` file from the `customize` dir, in order to take a screenshot of the error, I cannot reproduce it anymore, even when logging from Chromium...

**Comment by ansuz** [comment]
I'm going to close this as it seems related to whatever customizations you made rather than the platform as it was provided.
