### ISSUE TITLE
reference link definitions only work for one slide

### ISSUE THREAD

**Issue by snlemons** [xwiki-labs/cryptpad#77]
When creating slides, references for links are only defined for a single slide. Example:

```
[eff]: https://www.eff.org

# Slide 1

[EFF][eff]

---

# Slide two

[EFF][eff]
```

The first link works, but the second one appears as plaintext of "[EFF][eff]", because the reference is not defined for any slide but the first.

**Comment by ansuz** [comment]
Thanks for the report. I've never used this feature in markdown, so I didn't notice that it wasn't working.

I have a fix in mind, and it's something that I'd been thinking about doing anyway, but it means a bit of a refactoring. It'll be at least a few weeks until there's time for this, but we should be able to get it working for your use case.

**Comment by ansuz** [comment]
@snlemons you may be interested to know that we have a fix for this which will be included in our next release, which will be deployed Tuesday the 14th of March, as per our [release schedule](https://blog.cryptpad.fr/2017/02/24/Announcing-biweekly-releases/).

**Comment by snlemons** [comment]
Great! Looking forward to it.
