### ISSUE TITLE
Cap on Forms Responses

### ISSUE THREAD

**Issue by smartyballer20** [xwiki-labs/cryptpad#770]
Started a form and got responses. Came back and the early responses were gone. It seemed to be capped at 69 responses in total that I could see? Actively saw the oldest response disappear after the latest response was submitted. Is there any way to retrieve that very important data or is it gone for good? Any way to make unlimited responses?

**Comment by ansuz** [comment]
We don't intentionally impose any limit on the number of stored or visible responses, so this sounds like a bug in the component that displays them. All of the data should still be on the server, so once we identify the bug and deploy a fix you should see all responses as expected.
