### ISSUE TITLE
All features give 404

### ISSUE THREAD

**Issue by Ninoprs** [xwiki-labs/cryptpad#771]
Hey
I'm trying to set up a Cryptpad Instance on a debian based system. I followed the installation manual and believe to have done everything correctly. The main page is loading fine, but if I click on any feature (rich text, drive, etc.), I get a "paged blocked" from an external browser and a 404 on a browser on localohst. The error seems to be
`Because your site has the Cross-Origin Embedder Policy (COEP) enabled, each embedded iframe must also specify this policy. This behavior protects private data from being exposed to untrusted third party sites.
To solve this, add the following to the embedded frame’s HTML response header: Cross-Origin-Embedder-Policy: require-corp`

My instance is [cryptpad.so-gsi.ch ](url). I'm pretty much out of ideas on how to fix this because this really isn't my area of expertise and I'd be very happy for some help. Also, I know that quite a bit of optional config stuff isn't done yet, you don't need to remind me of that.

**Comment by ansuz** [comment]
hi,

The link your provided doesn't seem to resolve to a cryptpad instance anymore. In any case, this doesn't seem to be a bug, so I'll close this.

Our team provides support contracts and single days of consulting to ensure correct configuration of production instances. If you're interested in these services please contact us at sales@cryptpad.fr.

**Comment by robotfactory** [comment]
I'm running into this on a fresh Docker install of 2025.9.0. I can't find any references to this anywhere. I've made no changes to config other than the required domain names and admin email address.
