### ISSUE TITLE
Blurry interface in OnlyOffice

### ISSUE THREAD

**Issue by N-Upchurch** [xwiki-labs/cryptpad#772]
**Describe the bug**
The UI is blurry in OnlyOffice applications. For example, the grid, tool icons, and row and column labels in Sheets are blurry.

**Where did it happen?**
This occurs on the public instance, and on my self-hosted instance

**To Reproduce**
Open a new or existing sheets document.

**Expected behavior**
UI to render sharply.

**Screenshots**
![Screenshot of blurry UI issue](https://upchur.ch/piwigo/upload/2021/07/12/20210712130110-7d028cfc.png)

**Browser (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 89.0.2
 - Extensions installed UBlock Origin

**Comment by N-Upchurch** [comment]
Just to note that this occurs in firefox. Doesn't seem to be an issue in Chrome

**Comment by mthld** [comment]
Hello,

This is indeed due to poor antialiasing support from Firefox on Microsoft Windows. Sadly nothing we can do about it! ☹️
