### ISSUE TITLE
tip Script error.

### ISSUE THREAD

**Issue by ChowSings** [xwiki-labs/cryptpad#775]
https://cryptpad.fr/
![image](https://user-images.githubusercontent.com/3196768/126874512-c84cac21-4cd3-4d95-934a-158f674f9eb6.png)

**Comment by ansuz** [comment]
Hi,
It would be helpful to have more information about the context of this error so we can try to reprodce.

1. What OS are you using?
2. What browser are you using?
3. What extensions are installed in your browser, if any?
4. Does this occur when logged in or when using CryptPad as a guest?

If you can think of anything else that might be relevant please include it as well.

**Comment by mthld** [comment]
No answer in a year, closing. 😊
