### ISSUE TITLE
Wrong linked resources when migrating data from instance to another

### ISSUE THREAD

**Issue by cmouche2** [xwiki-labs/cryptpad#776]
**Describe the bug**
When migrating data from an instance (on domain1.example) to another (on domain2.example), images embedded in text pads (at least) aren't displayed when document is opened.
If I do right click > Open this file on the "broken-image" the image is correctly shown in the file explorer of the new instance.
In the text pad, according to the browser console, the CSP is preventing the image to be loaded. More specifically, Cryptpad (new instance) still tries to load the blob from the original instance.

I suppose the text pad blob does not keep track of its originating instance URL, so it can replace linked resources accordingly after migration.

**Where did it happen?**
Happened on my own instance (not publicly reachable).

**To Reproduce**
1. On first instance, plublished on domain1.example, create a new text pad and paste a few images in it
2. Save data directories (blob, block, data, datastore) from first instance
3. Set up a new instance on domain2.example, load these directories
4. Access the text pad after logging in with your account

**Expected behavior**
Images should be shown. Migrating could automatically update links upon pad opening?

**Screenshots**
![cp_mig](https://user-images.githubusercontent.com/87976099/126987107-498719fb-5834-44d7-8c11-d5cf7a72dfde.png)

**Browser (please complete the following information):**
 - OS: Windows 10 1909
 - Browser : Firefox (90.0.1 standard, with Ublock Origin, Umatrix), Edge (83.0.478.56), Chrome (92.0.4515.107)

**Comment by ansuz** [comment]
Hi,
Should I assume you're interested in sponsoring the development of your preferred behaviour?
