### ISSUE TITLE
CONFIG Problem with httpSafeOrigin (No process running on port 3001)

### ISSUE THREAD

**Issue by SeanPedersen** [xwiki-labs/cryptpad#778]
Hey,
I just updated my instance and checked out the /checkup/ page and noticed following issue: "httpUnsafeOrigin and httpSafeOrigin are equivalent"
AFAIU I need another subdomain for the sandbox which redirects to port 3001 for max security. Which I tried but then I noticed cryptpad is only running on port 3000 on my system (nothing running on port 3001). I run cryptpad using: `$ node server`

Hope someone can help me out!

P.S.
I have used following installation / setup guide: https://docs.cryptpad.fr/en/admin_guide/installation.html#admin-cryptpad-config

**Comment by ansuz** [comment]
In a production environment both domains should be handled via a reverse proxy (we recommend NGINX and provide an example config file). Neither port 3000/3001 should not be exposed directly to the public, as all traffic should be served exclusively via HTTPS.

Our team provides support contracts and single days of consulting to ensure correct configuration of production instances. If you're interested in these services please contact us at sales@cryptpad.fr.
