### ISSUE TITLE
Data lost in cryptpad.sheet after 17 August 21 update

### ISSUE THREAD

**Issue by fromtheoff** [xwiki-labs/cryptpad#783]
We are using cryptpad.sheet to document our working hours. The sheet is saved in my private crypt.drive. After the 17 August 21 update, all data was lost from the sheet which now appears to be blank. I can also not restore it through recreating an older version. Does this happen to more people? If so, is there any way to restore our lost data?

**Comment by ansuz** [comment]
Hi,

So far this is the only report we've received about such a problem following our 4.10.0 release. I suspect it's a coincidence as the only modifications we made to our sheet editor concerned a fix for its import/export functionality in Chrome, and while that was described in the release we'd actually deployed the fix as soon as it was available two weeks before.

We'll probably need to investigate the details of this particular sheet which will only be available to us if you're using CryptPad.fr. If that's the case then please submit a support ticket through [the platform's integrated support ticket page](https://cryptpad.fr/support/) referencing this issue and including the sheet's document id (available via its properties menu). We archive data for a period of 15 days before deleting it, so any data should be recoverable.

If you're using a different instance then you'll need to work with its administrators.

**Comment by fromtheoff** [comment]
Great thanks. We aren't using cryptpad.fr. so I will get in touch with the other administrators.
