### ISSUE TITLE
CONFIG Nginx on a different machine

### ISSUE THREAD

**Issue by rderensy** [xwiki-labs/cryptpad#785]
Hi!

I'm trying to setup Cryptpad but my architecture is different that what's in the documentation. I am using Nginx as a reverse proxy for multiple domains and VMs, so I have one dedicated Nginx machine to handle all 80/443 traffic, I believe similar to https://github.com/xwiki-labs/cryptpad/issues/42 (the issue is so old I'm not sure it's relevant anymore).

My problem is that I can't seem to find a correct configuration that works. I obviously can't use the directives `root`, `index` and `try_files` that are provided in the [example Nginx configuration](https://github.com/xwiki-labs/cryptpad/blob/main/docs/example.nginx.conf).

When I'm not logged in, I can access all apps (Rich Text, Sheet, Drive, etc) but once I log in, I get `Blocked Page - An error occurred during a connection to sandbox.domain.com.` from Firefox when trying to load Sheet or Drive.

Right now I pass all the traffic from Nginx to xx.xx.xx.xx:3000 (the "main" domain/port) and I guess the problem is that nothing is ever passed to xx.xx.xx.xx:3001. I also tried to setup Nginx on the CryptPad VM, and pass everything from the main reverse proxy to it but it worked even less than now. Here's my Nginx config file:

``` Bash
server {
    server_name cryptpad.domain.com sandbox.domain.com;

    set $main_domain "cryptpad.domain.com";
    set $sandbox_domain "sandbox.domain.com";
    set $api_domain "cryptpad.domain.com";
    set $files_domain "cryptpad.domain.com";

    location / {
        proxy_pass http://xx.xx.xx.xx:3000;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection upgrade;
    }

    # SSL stuff

    # add_header stuff

    location ~ ^/(register|login|settings|user|pad|drive|poll|slide|code|whiteboard|file|media|profile|contacts|todo|filepicker|debug|kanban|sheet|support|admin|notifications|teams|calendar|presentation|doc|form|report|convert)$ {
        rewrite ^(.*)$ $1/ redirect;
    }
}

server {
    if ($host = sandbox.domain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = cryptpad.domain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;

    server_name cryptpad.domain.com sandbox.domain.com;
    return 404; # managed by Certbot
}
```

I even tried the following config in the server block:
``` Bash
if ($http_host = 'cryptpad.domain.com') {
    proxy_pass http://xx.xx.xx.xx:3000;
}
if ($http_host = 'sandbox.domain.com') {
    proxy_pass http://xx.xx.xx.xx:3001;
}
````

It looks better, I don't get the error message from Firefox but I end up on a black webpage and nothing happens, no error in the console either.

How should it be configured?

**Comment by mthld** [comment]
Hello,

Sadly we can't afford to give everyone free support regarding setup/configuration issues. Please contact us at sales@cryptpad.fr if you need support setting up an instance.

**Comment by s2713** [comment]
Hi @Jerroder I have a network architecture very similar to yours. Have you found a solution to this?
I ran into a similar problem and I found I had neglected to set httpAddress to the correct LAN address in config.js on the host machine (localhost by default). It seems to work now although I'm not expert enough to be sure my config is clean. Also the symptoms were similar, but not exactly the same as yours so maybe this is something different.

I'm considering cryptpad as a cloud solution for a couple of non-profit organizations, they may eventually pay for support but they want to be sure this is a viable solution (a good deal of intense lobbying was required of me to steer them away from GAFAMs already ^^).

Cheers and thanks a lot to all of XWiki for the great piece of software

**Comment by Jerroder** [comment]
Hi @s2713 

I'm sorry to say I have not figured it out. I moved it to a local network and access it with a VPN when I'm not home :/

**Comment by s2713** [comment]
A shame, although it's good to read you set up a workaround. If you're ever willing to test again, I think this does the job (I have not yet tested all functionalities though I hope I wont run into bad surprises).

in the reverse proxy configuration:

    location / {
        proxy_pass            http://IP.OF.CRYPTPAD.SERVER:3000;
        proxy_set_header      X-Real-IP $remote_addr;
        proxy_set_header      Host $host;
        proxy_set_header      X-Forwarded-For $proxy_add_x_forwarded_for;
        client_max_body_size  150m;
        proxy_http_version    1.1;
        proxy_set_header      Upgrade $http_upgrade;
        proxy_set_header      Connection upgrade;
    }

    location ^~ /cryptpad_websocket {
        proxy_pass            http://IP.OF.CRYPTPAD.SERVER:3003;
        proxy_set_header      X-Real-IP $remote_addr;
        proxy_set_header      Host $host;
        proxy_set_header      X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version    1.1;
        proxy_set_header      Upgrade $http_upgrade;
        proxy_set_header      Connection upgrade;
    }


IP.OF.CRYPTPAD.SERVER is the non-routable IPv4 adress of the real cryptpad server on the LAN.

THe second location directive seems to be missing in your config but maybe you just didn't copy it here.
The rest of the file is the usual stuff.

in config.js on the actual cryptpad server:

`httpAddress: 'IP.OF.CRYPTPAD.SERVER'
`

If you decide to try it out I'd love your feedback.
