### ISSUE TITLE
A small inconvenience with the popups

### ISSUE THREAD

**Issue by tio-trom** [xwiki-labs/cryptpad#786]
I am trying to create some webapps for cryptpad for ease of use, but since at times it opens the drive or other documents in new tabs and that means the browser should allow for popups to open up, it either fails to open them or when it does it is not a good experience (suddenly you have multiple windows open).

It is also a bit awkward in the browser as well when it opens up so many tabs. I am wondering is there a technical reason you have to, at times, open documents or the drive into a new wondow?

Cheers!

**Comment by ansuz** [comment]
The reason for this is described in #485
