### ISSUE TITLE
HIPAA Compliance

### ISSUE THREAD

**Issue by parthsharma1996** [xwiki-labs/cryptpad#787]
Hi,
Is Cryptpad HIPAA Compliant? Or can be made HIPAA Compliant? 
Thanks!

**Comment by mthld** [comment]
Hello,

Thanks for your interest in CryptPad! As of today there is no official certification on our software, if you have a specific use case in mind, please contact us at sales@cryptpad.fr, we'll figure something out to satisfy your needs. :)
