### ISSUE TITLE
Make a copy of a spreadsheet in teams

### ISSUE THREAD

**Issue by theejnar** [xwiki-labs/cryptpad#789]
Is a user I would be really happy if I was able to make a copy of a spreadsheet in any team by right click and choose Make a copy. In the CryptDrive this feature is present but not in any team. There might be a reason why it is not present, or?

**Comment by mthld** [comment]
Hello,

Thanks for your report and your interest! If I understand well, you would like to be able to duplicate a file from your CryptDrive by using the right-click menu?

**Comment by ejnask** [comment]
This feature is probably already implemented. I tried today and you are now able make a copy in any team by right-click any spread-sheet. This one can be closed.

**Comment by mthld** [comment]
> This one can be closed.

Well, are you the original author of this issue? I would like to be sure that I properly understood what they meant in the first time before closing it.

**Comment by theejnar** [comment]
1. Go to a Team
2. Create a Spread Sheet and edit it
3. Go back to the team tab and right-click the document
Actual: It was not possible to select Make a copy
Expected: It should be possible to Make a copy

However this now works, I guess this issue can be closed. Thanks for a fantastic product

**Comment by mthld** [comment]
Thanks for your feedback!

I see it's now working as expected, closing the issue now. :)
