### ISSUE TITLE
Contacts Pad

### ISSUE THREAD

**Issue by emailBrodes** [xwiki-labs/cryptpad#792]
Hello, (big fan).
I have had a fully working instance of version 4.10.
Everything still works except for the Contacts pad when you go to Your Icon --> Contacts.
I have tried on windows and linux using 4 different browsers, same issue everywhere so must be the instance.
The screen is left with the twirling icons in the middle of the frame forever. This was working in the past. All of a sudden it stopped, no changes in Admin or server.

![cryptpad issue](https://user-images.githubusercontent.com/90590786/133021890-b9ad5d50-51cf-473e-b6a0-ef0dc6472fe3.JPG)
 
Any advice will be appreciated.

**Comment by emailBrodes** [comment]
This is only affecting some users. I have had reports that other users are unaffected. From what I can tell it is a user based issue within the system.

**Comment by heybrodes** [comment]
upgraded to 4.11 - still no change

**Comment by emailBrodes** [comment]
![image](https://user-images.githubusercontent.com/90590786/133745821-3f885bd9-11fe-4b69-af61-dbae20751533.png)
This is from the console tab in Firefox

**Comment by emailBrodes** [comment]
I've exported the console tab to file
[console-export-2021-9-17_17-55-1.txt](https://github.com/xwiki-labs/cryptpad/files/7183753/console-export-2021-9-17_17-55-1.txt)

**Comment by emailBrodes** [comment]
the is the console tab export with the customize tab removed.
[console-export-remove customize folder.txt](https://github.com/xwiki-labs/cryptpad/files/7183880/console-export-remove.customize.folder.txt)

**Comment by mthld** [comment]
Hello,

Is this issue still occurring on your instance? Have you updated it through v5.0?

As we can't afford offering free help to third party instance configuration, I invite you to contact us through sales@cryptpad.fr in case of need.
