### ISSUE TITLE
Always display date when All Day is enabled

### ISSUE THREAD

**Issue by arichiardi** [xwiki-labs/cryptpad#794]
**Describe the bug**
It seems like the Calendar suffers of some sort of bug related to "All day". Or maybe it is by design but it could probably be improved.

**Where did it happen?**
CryptPad.fr

**To Reproduce**
* Go to Calendar
* Create a new event
* Toggle "All Day"
* The date input fields go away

**Expected behavior**
The date should stay visible so that you can change it if you change your mind.

**Browser (please complete the following information):**
 - OS: linux
 - firefox

**Comment by mthld** [comment]
Hello,


In case you want to change the date of an all day event, you just have to untick the "All day" case, see bellow:

![Screenshot 2022-08-05 at 14 38 37](https://user-images.githubusercontent.com/41020854/183078852-4fae4e95-2bda-4d99-ba4b-fe4bf92a3928.jpg)

![Screenshot 2022-08-05 at 14 39 42](https://user-images.githubusercontent.com/41020854/183079060-9eddc702-59bf-4c8e-adf0-7c4bc8601364.jpg)

I'll be closing this issue now. :)

**Comment by arichiardi** [comment]
Hi @mthld, thank you for your answer but I have to say that form an UX perspective it is not a great flow:
As a user I'd still want to see the selected day 

Maybe we can reopen and I can tweak the title and have a better description?

**Comment by mthld** [comment]
Hello!

Sure, I'll reopen this. I let you edit your first message to describe this feature request. 😊
