### ISSUE TITLE
Not allowing to record multiple responses from same user

### ISSUE THREAD

**Issue by Parth-kalkotwar** [xwiki-labs/cryptpad#798]
Currently, when a cryptpad form is shared as a participant, it allows the user to record just a single response to the form. After submitting the response to the form, it allows editing the response ( update or reset ), however, there exists no way to record another response to the form using the same user account or even anonymously. 

![image](https://user-images.githubusercontent.com/54177487/135033405-2c14c89f-b281-4591-be04-5595e06fc7eb.png)

Most of the other forms(Google, Zoho) provide this functionality. Can we resolve this issue somehow? Is there a workaround?

Thank You.

**Comment by efrr** [comment]
I hope a dev can confirm this to be the case:

From what I have tested, you can send multiple responses, you just have to use a new session in the form of Incognito mode (Chrome) or Private window (Firefox). This leads me to believe that the activity tracking is cookie-based and not network IP based.

It works for me if you use:
1. A different computer on the same network
2. A different browser on the same computer
3. Clear the cookies on the same browser
4. Incognito/private mode on the same browser

You should be able to use Firefox's container feature for this as well.

I hope that helps!

**Comment by franzihei** [comment]
Came here with the same question! Love CryptPad btw so huge thanks to all of the CryptPad devs! <3

I know it is possible to submit several responses by either using Incognito mode or deleting cookies, but that is not very convenient / self-explanatory for the average user. Is there a way to add an option to the forms settings which allows for multiple responses? i.e. the buttons for the users after submitting the form then could be "submit another response", "edit response" and "reset".
