### ISSUE TITLE
Problems with uploading large files

### ISSUE THREAD

**Issue by MrCyjaneK** [xwiki-labs/cryptpad#804]
**Describe the bug**
Web browser either crash, or give error when trying to upload files larger than 500mb

**Where did it happen?**
It happened on my own instance, I can provide user account if required.

**To Reproduce**
1. Go to drive
2. Upload a file larger than 500mb
3. See error

**Expected behavior**
The file being uploaded

**Screenshots**
![image](https://user-images.githubusercontent.com/20381330/136691608-09e80e12-e75a-4081-a7cb-0d35a7a56efd.png)

**Browser (please complete the following information):**
 - OS: Droidian (debian)
 - Browse: firefox
      - variations: Firefox ESR
 - Extensions installed: UBlock Origin
 - Browser tweaks: Phosh Mobile Config, only change the UI

**Additional context**
Upload limit on my server is set to 10GB, so this shouldn't be a problem.

**Comment by mthld** [comment]
Duplicate #828
