### ISSUE TITLE
I can't access my personal account following the creation of another account. 

### ISSUE THREAD

**Issue by NocturnalDoom** [xwiki-labs/cryptpad#805]
**Describe the bug**
I had an account; no issues with it. Created a new account on Friday for our organization. It was working fine on saturday. Now today I can't log into my personal account. Every time I try it just logs me into the organization one. 

**Where did it happen?**
Cryptpad.fr

**To Reproduce**
1. Go to crytpad.fr
2. Click on Log in, use personal details 
3. Ends up being logged in to the wrong account 
4. Try to create a new file and it does recognise I'm disconeccted from my account. 

**Expected behavior**
Be able to access my account! 

**Screenshots**
<img width="740" alt="Screenshot 2021-10-11 at 11 34 01" src="https://user-images.githubusercontent.com/92305768/136777533-fef4c8ab-b1ff-44db-b538-ac3a63c7fc70.png">
<img width="292" alt="Screenshot 2021-10-11 at 11 45 13" src="https://user-images.githubusercontent.com/92305768/136777683-85e20622-da99-4b8e-82b4-ae1240418577.png">
<img width="637" alt="Screenshot 2021-10-11 at 11 44 48" src="https://user-images.githubusercontent.com/92305768/136777686-8dfd37d1-abd6-4ac8-ba94-b659e45c7e48.png">

**Browser (please complete the following information):**
 - OS: [e.g. Mac]
 - Browser  brave
 - Extensions installed (UBlock Origin, Passbolt, LibreJS]
 - Browser tweaks [e.g. firefox "Enhanced Tracking Protection" strict/custom mode, tor browser "safer" security level, chrome incognito mode]

**Smartphone (please complete the following information):**
 - Version 1.26

**Additional context**
Please help and thanks :)

**Comment by mthld** [comment]
Also, I would like to encourage you to contact us through the dedicated Support page: https://docs.cryptpad.fr/en/user_guide/user_account.html#support
