### ISSUE TITLE
CPad for schools (e.g. LDAP)

### ISSUE THREAD

**Issue by diolwe** [xwiki-labs/cryptpad#807]
# 1

It would be nice to have a feature to auto-create CPad accounts for pupils who are used to using school infrastructure with their LDAP accounts. 

Would it be possible to implement a LDAP-auth-plugin?

And: Would it be possible to restrict the use of a cpad server to users who have logged in via LDAP?

# 2

This second part of my feature request can be seen as being directed against the motif of having a CPad server in the first place - I know!

But **teachers** a) **love to use the cpad features** in their lessons **but** b) also like to know who is doing what in their classroom (which is also true for online-classrooms). And school admins have to be able to check who created which content if "things go bonkers" (e.g. bullying, mobbing, hate speech).

Would it be possible to implement a deanonymizing cpad-4schools-plugin?

**Comment by ansuz** [comment]
We're in the process of setting up a project website for CryptPad that is separate from the flagship instance of CryptPad.fr. We're planning to include a dedicated page listing our offerings for educational purposes, as that makes up a large percentage of our total usage.

Either option is possible, but not yet implemented. Custom development is something we typically discuss beyond the terms of our basic support contracts, the terms of which will also be listed on the project site once it's ready to go live. If you require those services on a shorter timeframe, you can email sales@cryptpad.fr (and mention this issue to avoid explaining these requirements all over again).

**Comment by KiaraGrouwstra** [comment]
see #749
