### ISSUE TITLE
Copy-paste / cut-paste no longer works in Sheets in Firefox

### ISSUE THREAD

**Issue by ericmaxwell** [xwiki-labs/cryptpad#814]
**Describe the bug**
On macOS 11.6 and Linux Mint 20.2 using Firefox ﻿﻿93.0 (64-bit)
In both "regular" windows with extensions and private window with all extensions disabled

Copy-paste and cut-paste does not work anymore from within a Sheet. It used to work just fine, but stopped working recently. I can not copy-paste from either key combo (command-c / command-v on Mac and ctrl-c / crtl-v on Linux Mint)

This action works as expected in Chrome browser

Note I'm using a 3rd party (Ducky) mechanical keyboard with the keys mapped in the following way:

MacOS
--------
Alt -> Command
Window -> Alt

Linux Mint
-----------
Alt -> Ctl
Win -> Alt

I did try un-mapping the keys and had the same result.

Note that this functionality works as expected in Docs.

**Where did it happen?**
CryptPad.fr

**To Reproduce**
1. Go to cryptpad.fr
2. New sheet
3. Move to cell
4. Type "test"
5. Click off cell
6. Click on cell with "test"
7. Hit command-c
8. Click blank cell
9. Hit command-v 
10. Nothing

**Expected behavior**
It should replace blank cell in step 8 with a cell that has the words "test" in it

**Browser (please complete the following information):**
 - OS: On macOS 11.6 and Linux Mint 20.2 
 - Browser using Firefox ﻿﻿
   - Regular w/ extensions and in private browsing w/ no extensions
 - Version 93.0 (64-bit)
 - Extensions installed Anonaddy, CanvasBlocker, ClearURLs, Decentraleyes, FB Container, Firefox Multi-Account Container, Ground News Bias Checker, Hover Zoom+, HTTPS Everywhere, LastPass, Privacy Badger, Privacy Redirect, Temporary Containers, TOS TL;DR, ToGoogle Translate, uBlock Origin, xBrowseSync
 - Browser tweaks :  about.config changes
 
privacy.firstparty.isolate = true
privacy.resistFingerprinting = true
privacy.trackingprotection.fingerprinting.enabled = true
privacy.trackingprotection.cryptomining.enabled = true
privacy.trackingprotection.enabled = true
privileged pages where add-ons that usually do that are disabled.
browser.send_pings = false
browser.urlbar.speculativeConnect.enabled = false
dom.event.clipboardevents.enabled = false
media.eme.enabled = false
Decryption Module provided by Google Inc. Details
media.gmp-widevinecdm.enabled = false
content. Details
media.navigator.enabled = false
network.cookie.cookieBehavior = 1
network.http.referer.XOriginPolicy = 2
network.http.referer.XOriginTrimmingPolicy = 2
webgl.disabled = true
browser.sessionstore.privacy_level = 2
beacon.enabled = false
network.IDN_show_punycode = true

**Comment by mxmilkiib** [comment]
That config is set to true for me, but I can't paste into cells, apparently most of the time, where as pasting in to the formulae bar bit is np.
