### ISSUE TITLE
RIGHT <CLICK> does NOTHING!

### ISSUE THREAD

**Issue by MrYnLA** [xwiki-labs/cryptpad#817]
All of a sudden, and by this it is meant that as of October 20, 2021, I am completely NOT ABLE to manage any of the folders and files in my Cryptpad drive using the ONLY method to do so (as contained in the documentation) which is with RIGHT CLICK.  A selection list does open, however, NO selection is able to be applied;  in short NOTHING HAPPENS!

This is an issue that has just appeared, and is critical to using Cryptpad.  It has rendered Cryptpad NOT FUNCTIONAL, and therefore not usable.

INFO:  Windows 10 laptop, cryptpad.fr instance (4.12.0), logged in user with a paid account.

Please advise as how to best mitigate this issue, as it has essentially rendered Cryptpad not useable.

**Comment by ansuz** [comment]
Hi,
I think I can see what the problem is and I've just deployed a patch which I hope will help to CryptPad.fr. Can you try reloading your Drive and see if the issue still occurs?

**Comment by laodc** [comment]
Do you never release patch versions? e.g. 4.12.1 ?

This is quite a major break of functionality.
Don't really want to switch to main on a production server to fix this one line patch.

**Comment by ansuz** [comment]
[4.12.1](https://github.com/xwiki-labs/cryptpad/releases/tag/4.12.1) is now available.

**Comment by bluenevus** [comment]
Thanks @ansuz any chance in getting this on your dockerhub?
