### ISSUE TITLE
Supporting Passwords

### ISSUE THREAD

**Issue by CSDUMMI** [xwiki-labs/cryptpad#818]
I don't know if this is in any way appropriate for this project,
I would like it if Cryptpad could support the storage of encrypted Password
Databases.

If this is outside of the scope of this project, I'll be closing the issue.

**Comment by giraffekey** [comment]
Adding on to this. This doesn't sound like a bad idea. I would place it under the same scope as the Kanban and Whiteboard features that have already been implemented. Seems like a longer term goal but wouldn't be bad to plan to implement.

**Comment by ansuz** [comment]
Storing any particular format is not especially difficult, however, once you have such a database stored within your drive I imagine you will want to be able to do something with it, such as:

- edit it
- protect it with a dedicated primary password that is distinct from that of your cryptpad account
- allow other users to access and modify parts of it
- generate secure passwords and/or prompt you to store passwords for other web sites

...at which point this simple request starts to look more like _implement a full-featured password manager_, which is a larger job than our small team can reasonably handle :sweat_smile:

**Comment by CSDUMMI** [comment]
I understand. 

Are there any FOSS Web Apps that could be included in Cryptpad instead?

**Comment by CSDUMMI** [comment]
Otherwise an idea could be to add a PASSWORD field type to the Spreadsheets. 
(Which automatically generates a random string, which is hidden from view).

**Comment by ansuz** [comment]
I believe it would be simpler to just use such a web app as-is rather than trying to embed it into CryptPad. [This article](https://opensource.com/article/16/12/password-managers) lists several popular options.

**Comment by giraffekey** [comment]
You could use KeePassX and backup the password-encrypted database it creates to CryptPad.
