### ISSUE TITLE
Whiteboard doesn't recognise Huion graphic tablet byt Fabric.js demo does.

### ISSUE THREAD

**Issue by droyd5691** [xwiki-labs/cryptpad#819]
**Describe the bug**
I cannot draw on the whiteboard using my graphics tablet, yet I can draw on the Fabric.js drawing demo with my graphics tablet.

**Where did it happen?**
The issue occurs on CryptPad.fr

**To Reproduce**
1. Have a graphics tablet set up
2. Open a new whiteboard
3. Open the Fabric.js drawing demo at http://fabricjs.com/freedrawing
4. Try to draw on the whiteboard.
5. Try to draw on the Fabric.js demo

**Expected behavior**
As the whiteboard uses Fabric.js (according to the documentation) and I can draw with my graphic tablet on the Fabric.js drawing demo, I expect to be able to draw using my graphic tablet on a whiteboard document.

**Screenshots**
Link to short video showing tablet working on FabricJS drawing demo and not working on CryptPad whiteboard within same Brave browser: https://odysee.com/@issue-videos:1/cryptpad-whiteboard-fabricjs-issue:6?r=4iWEwUVwvessYLnXsXpUZgJUJcZWMjBD

**Browser (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave
   - variations: Chromium 95.0.4638.54 (official build) (64 bit)
 - Version: 1.3.87
 - Extensions installed: Crypto Wallets, Presearch
 - Browser tweaks: None

**Smartphone (please complete the following information):**

**Additional context**
Drawing with a graphic tablet on a whiteboard is preferable from a UX perspective.

**Comment by ansuz** [comment]
Hi,
I just deployed an updated version of Fabricjs to CryptPad.fr. Could you please test with your tablet and confirm whether it now works as expected?

**Comment by droyd5691** [comment]
![Whiteboard Smiley Face](https://user-images.githubusercontent.com/92029164/141982286-6327be04-6aa1-489a-a205-048cbf6506f5.PNG)

My tablet works perfectly with the whiteboard. Thank you very much.
