### ISSUE TITLE
Browser Firefox can’t establish a connection to the server at localhost:3004

### ISSUE THREAD

**Issue by francoisjacquet** [xwiki-labs/cryptpad#820]
**Describe the bug**
Since upgrade to version v4.12.0, when accessing the `drive/` or any other app, the browser (Firefox) "can’t establish a connection to the server at localhost:3004".
The request is initiated by `jquery.min.js` and requests the `inner.html` file.

**Where did it happen?**
Third-party instance

**To Reproduce**
0. Upgrade from v4.11.0 to v4.12.0
1. Go to [third-party instance]
2. Click on any app
3. Open dev tools, network tab

**Expected behavior**
Request the file at https://third-party-instance.com/ instead of localhost:3004

**Screenshots**
![image](https://user-images.githubusercontent.com/4723501/138565815-558bea3b-d5f0-40ed-9ced-e9ff51511c54.png)

**Browser (please complete the following information):**
 - OS: Debian
 - Browser Firefox ESR
 - Version 78.15
 - Extensions installed (UBlock Origin)
 - Browser tweaks "Enhanced Tracking Protection" custom mode

**Additional context**
Server: Apache
Config extract:
```js
var _domain = 'http://localhost:3003/';
    httpPort: 3003,

    // This is for allowing the cross-domain iframe to function when developing
    httpSafePort: 3004,
```
Apache conf extract:
```
        ProxyPass / http://localhost:3003/
        ProxyPassReverse / http://localhost:3003/
        ProxyRequests Off
        ProxyPreserveHost Off

        RewriteEngine on
        RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC]
        RewriteCond %{HTTP:CONNECTION} Upgrade$ [NC]
        RewriteRule .* ws://localhost:3003%{REQUEST_URI} [P]
```

This used to work properly until v4.11.0.

**Comment by francoisjacquet** [comment]
OK, got it to work thanks to the `checkup/` URL :)
I had `httpSafeOrigin` not set in the `config.js` file.

But now it complains the `httpSafeOrigin` and the `httpUnsafeOrigin` are the same.
If my safe origin is for example `https://my.domain.com`, what should be the unsafe origin?
If I create a `https://sandbox.domain.com` for that purpose, would that be OK?

**Comment by ansuz** [comment]
Details about the sandboxing system are [described in our documentation](https://docs.cryptpad.fr/en/admin_guide/installation.html#admin-domain-config), but yes, a second `https://sandbox.domain.com` subdomain is the right idea.

As the docs describe, this will only provide the intended security benefits if the relevant Content-Security-Policy headers are set by the server. We provide a working NGINX config, but we don't have the time to validate whether your Apache config implements the same behaviour. If possible I recommend using the provided NGINX config.

**Comment by francoisjacquet** [comment]
@ansuz thanks for your answer.

Simply adding the sandbox domain as a `ServerAlias` in Apache vhost seems enough.

Then, in the `config.js`:
```js
httpSafeOrigin: "https://sandbox.domain.com",
```
