### ISSUE TITLE
OnlyOffice Word Printing

### ISSUE THREAD

**Issue by msvp** [xwiki-labs/cryptpad#822]
**Describe the bug**
When using an OnlyOffice Word document, printing is hanging

**Where did it happen?**
cryptpad.msieursvp.fr

**Expected behavior**
No printing, just hanging !

**Screenshots**
![Capture d’écran 2021-10-30 165936](https://user-images.githubusercontent.com/5102015/139538499-ad5c8bd2-2f0a-4166-adc9-655bcf84f209.png)

**Browser (please complete the following information):**

 - OS: Windows 10
 - Browser chrome
   - variations [e.g. Firefox nightly, Firefox ESR, Chromium, Ungoogled chrome]
 - Version 94.0.4606.81 (Build officiel) (64 bits)
 - Extensions installed UBlock Origin

Thanks !

**Comment by ansuz** [comment]
The messages on [your instance's checkup page](https://cryptpad.msieursvp.fr/checkup/) might be helpful.

**Comment by mthld** [comment]
Hi,

Looks like your instance isn't available anymore, furthermore considering the absence of answer I'll be now closing this issue.
