### ISSUE TITLE
[Feature request] Possibility to have CalDAV for the Calendar

### ISSUE THREAD

**Issue by EdoSecco** [xwiki-labs/cryptpad#823]
It would be wonderful to have the possibility to use the Calendar with an external app via CalDAV.

**Comment by MrCyjaneK** [comment]
Agreed, I know that it is a huge security/privacy issue, as the content would need to be decrypted on server, but having it as an option would be awesome.

**Comment by ansuz** [comment]
@MrCyjaneK is correct that a server can only provide CalDAV updates if it has full access to the content. This is because the CalDAV protocol and clients have no concept of end-to-end encryption.

We currently have no plans to offer users the ability to reveal calendar data to the server in this manner, but if the CalDAV protocol ever evolves to include e2e encryption we'd be interested in supporting that.

**Comment by MrCyjaneK** [comment]
The only way in which that would be somewhat doable in a secure way is to have cryptpad desktop app that will serve CalDAV content over localhost.

**Comment by studied-sermon-gender** [comment]
What about using https://www.etesync.com ? It is [selfhostable](https://github.com/etesync/server), E2E encrypted and it generally seems like a good solution.

**Comment by mthld** [comment]
Hi,

> What about using https://www.etesync.com ? It is [selfhostable](https://github.com/etesync/server), E2E encrypted and it generally seems like a good solution.

As of today I don't believe we'll be embedding another external tool to CryptPad. Please understand the workload that integrating more & more dependancies creates.

I'll be closing this issue now, we'll keep an eye out for e2e encryption for CalDAV.

**Comment by Ezwen** [comment]
Actually this does not necessarily mean embedding an external tool. A possibility would be to implement the [EteBase protocol](https://www.etebase.com/) as an endpoint on the cryptpad side, which would make it possiblle EteSync-compatible calendar clients to connect to this endpoint — exactly the same as with the CalDAV protocol and CalDAV-compatible calendar clients. 

Implementing EteBase would still require significant work though.
