### ISSUE TITLE
Document Saving & Collaboration 

### ISSUE THREAD

**Issue by SimonLock94** [xwiki-labs/cryptpad#824]
Got the CryptPad subscription - having problems relating to saving & collaborating in a document. When I copy & past text in, then exit and return, the content has disappeared. Others who are also in the document can't see any of the content (just a blank screen). Note been an issue for the other formats (e.g. sheets, rich text etc) 

Also any new content that I write into the document will appear highlighted when I return. How can I resolve both of these issues?

S

**Comment by mthld** [comment]
Hello,

The issues you are describing can be caused by various web browser problems. Can you tell us more about your setup?

In the meantime I invite you to check our "Common issues" section in our documentation FAQ: https://docs.cryptpad.fr/en/FAQ.html#common-issues
