### ISSUE TITLE
form: multiple choice grids are not answerable correctly

### ISSUE THREAD

**Issue by ari-s** [xwiki-labs/cryptpad#827]
## Description

On a form with more than one choice grid, it's not possible to put answers on the first two questions of more than one choice grid - unless they're created specially (see below): when going through a form, the first choice grid seems working. The second choice grid also seems working, however, when on the first questions choices are selected, they disappear from the first choice grid. 
With additional choice grids similar things happen: it's only possible to select exactly one answer to **all** choice grids first and second row.

It's possible to create working forms with multiple choice grids: for this, on creation of the new choice grid delete the first two items which are there from the beginning. Every manually added item is not affected.

## Problem (my guess)

I guess when adding a choice grid, a prototype is copied (in contrast to a class being instantiated). With more than one choice grid the first two options items are references to the same set of radio buttons - and since only one radio button can be selected, the first two questions of all choice grids end up being mutually exclusive.

## Affected instances

these are links to forms that are basically MWEs, in author mode.

- ~~[cryptpad.fr](https://cryptpad.fr/form/#/2/form/edit/pDUsN4XgUjH+Mq+oNz6k6en4/)~~ does not reproduce, but I saw it earlier...
- [pads.c3w.at](https://pads.c3w.at/form/#/2/form/edit/gvGiQTuR01ldQLNidKnetI3m/) - cryptpad 4.11.0

## reproduce

1. create a new form
2. add the first choice grid
3. add a second or more choice grids
4. open the form as participant and choose options of all items. <br/>
    observe that your selection of the earlier choice grids disappear

## Expected behavior

It should be possible to choose options on all item of all choice grids, even if no special care has been taken on form creation.

## Browsers with reproduction

-  firefox 93
- chromium 93
- tor browser base on firefox 78

**Comment by mthld** [comment]
Hello,

Is this issue still occurring? As of today I can't reproduce this in any way.

**Comment by mthld** [comment]
Hello,

I can reproduce the issue on the instance hosted at https://pads.c3w.at.
However it's working as intended on https://cryptpad.fr:

![Screenshot 2022-08-08 at 15 14 19](https://user-images.githubusercontent.com/41020854/183426473-12d3814c-1818-42a3-8109-401e71313c5c.jpg)

Your best option is here to [reach out to your instance admins](https://pads.c3w.at/contact.html), there is nothing we can do on our end.
