### ISSUE TITLE
TypeError: can't convert undefined to object migrate-user-object.js:117:41

### ISSUE THREAD

**Issue by cremesk** [xwiki-labs/cryptpad#829]
hi,

i have a question.. a user on my cryptpad instance (pad.envs.net) send me this error:

https://envs.sh/Ehi.png

with the log:

`TypeError: can't convert undefined to object migrate-user-object.js:117:41`

does anyone have any idea what the problem is?

for me and other users everything is going well.

The user with the problem has already tried to clear his browser cache. without success. he always gets the same error.

my instance OS is Debian 11 and cryptpad is on the latest version.

**Comment by mthld** [comment]
Hello,

Is this error still occurring? If so, did you updated your instance to CryptPad latest version (5.0)?

**Comment by cremesk** [comment]
hi,
my instance is up-to-date. Unfortunately, I can't say whether the error still occurs because I don't get any feedback from the user. But I guess that it is fixed because nothing has happened to me anymore and I don't see anything in the logs either.
