### ISSUE TITLE
how would I control line height?

### ISSUE THREAD

**Issue by loganto** [xwiki-labs/cryptpad#83]
So it seems like when I type there is a quite a big space between lines.

yet I can see that text can by typed without so much space  -> i just cant figure out how it was done. 

http://i.imgur.com/XR4vqyu.png

**Comment by gustavohmsilva** [comment]
Isn't that the difference between Enter vs. Shift+Enter?

**Comment by loganto** [comment]
Ahh yes it is - thanks!

**Comment by gustavohmsilva** [comment]
You're welcome :D
