### ISSUE TITLE
Retaking Surveys

### ISSUE THREAD

**Issue by m-freitag** [xwiki-labs/cryptpad#832]
It appears not to be possibe for a user to retake a survey and to generate additional rows in the results backend. 

However, when using forms for small-scale manual data collection, this would be a nice feature.

**Comment by eloeffler-fhnw** [comment]
Currently the survey answered status is stored in LocalStorage as CP_formAnswered.

A quick solution to enable retaking a survey would be to add a button next to the "Edit my responses" button that deletes this value and reloads the page. It could say "Permanently store my responses and retake survey"

It would also be nice to be able to toggle if this option is available to participants or not.

As a workaround for now: It's always possible to retake surveys with a private tab.

**Comment by davidbenque** [comment]
Hello, we got this feedback before through our matrix chat and we are planning to implement this feature. Our time is taken by funded research projects at the moment but we hope to get to this in the next couple of months.

For now this is a rough mockup of what I have in mind. Essentially it would be an added option to the existing submission setting:

![image](https://user-images.githubusercontent.com/11028490/146348593-07742871-6ca3-4809-bef9-852f02beb59e.png)

Would this suit the use-cases you have in mind?

**Comment by eloeffler-fhnw** [comment]
That looks great!

Maybe the "Multiple times" entry would need clarification whether it is possible to edit afterwards.
If it says "Multiple times and edit" then the screen after taking the survey could look like this:
![Screenshot_20211216_110034](https://user-images.githubusercontent.com/75788737/146350671-6c487a55-2eb6-48fe-92d2-4060a7578bb7.png)
