### ISSUE TITLE
Icons look blurry

### ISSUE THREAD

**Issue by QazCetelic** [xwiki-labs/cryptpad#839]
**Describe the bug**
Icons look blurry

**Where did it happen?**
cryptopad.fr

**To Reproduce**
1. Go to Rich Text editor
2. View blurry icons

**Expected behavior**
Sharp, clear icons

**Screenshots**
![image](https://user-images.githubusercontent.com/51381523/146139997-a42f14b4-d530-4371-80ef-0df60c520220.png)

**Browser (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version Latest (95.0)
 - Extensions installed (UBlock Origin, ..]
 - Browser tweaks Firefox enhanced tracking protection

**Additional context**
I suggest replacing the icons with SVG's. I could help with that.

**Comment by mthld** [comment]
Hi,

Thanks for the report but there is nothing we can do about Firefox antialiasing issues on Microsoft Windows 10. I'll be closing this now.
