### ISSUE TITLE
Help option in the File menu blocked

### ISSUE THREAD

**Issue by meaz** [xwiki-labs/cryptpad#847]
When you click the Help option (that can be found in the File menu of any document) it tries to redirect to the docs.cryptpad.fr but fails. 

For example, I get this url: `https://sandbox.cryptpad.server.org/bounce/#https%3A%2F%2Fdocs.cryptpad.fr%2Fen%2Fuser_guide%2Fapps%2Frichtext.html` with a blank page.

I followed the nginx template in the documention.

**Comment by ansuz** [comment]
This could be related to an incorrectly configured sandbox domain on your instance. Can you check your instance's checkup page (`https://your.instance/checkup/`) to see if it is passing all of the automated diagnostics?

**Comment by meaz** [comment]
Yep, that was an issue with the nginx config. Thanks.
