### ISSUE TITLE
CryptPad stuck at "Loading..." screen

### ISSUE THREAD

**Issue by dewey** [xwiki-labs/cryptpad#85]
Hey,

I'm running the latest version in a setup like mentioned in issue #84. I'm running it behind a nginx reverse proxy on a https endpoint with the following config:

```
    location / {
        proxy_pass http://localhost:3010/;
        proxy_set_header    Host $host;
        proxy_set_header    X-Forwarded-Proto https;
        proxy_buffering off;
        autoindex  off;
    }
```

Something doesn't seem to work as I'm getting the following error messages.

<img width="815" alt="screen shot 2017-02-14 at 22 48 04" src="https://cloud.githubusercontent.com/assets/790262/22950986/cbd2f0a6-f307-11e6-857f-7e3d420c9286.png">

I tried it with the same nginx config as mentioned in this thread: https://github.com/xwiki-labs/cryptpad/issues/62#issuecomment-264664204 but that didn't change anything.

```
location / {
        proxy_pass http://localhost:3010/;
        proxy_set_header    Host $host;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection upgrade;
    }
```

Any idea what's wrong there?

**Comment by kpcyrd** [comment]
Please check your nginx config for X-Frame-Options headers and set it to `SAME`.

**Comment by dewey** [comment]
That did the trick, thanks a lot!

**Comment by fredhampton** [comment]
@dewey  Where did you add the below

add_header X-Frame-Options SAMEORIGIN


Thanks!

**Comment by dewey** [comment]
@fredhampton I added it to my nginx config like that:

```
server {
    listen      443;
    server_name paste.example.com;

    ssl_certificate     /etc/letsencrypt/live/paste.example.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/paste.example.com/privkey.pem;
    include /etc/nginx/ssl.conf;

    error_log   /var/log/nginx/paste.example.com.error.ssl.log;
    access_log  /var/log/nginx/paste.example.com.access.ssl.log;

    location / {
        proxy_pass http://localhost:3010/;
        add_header X-Frame-Options SAMEORIGIN;
        proxy_set_header    Host $host;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection upgrade;
    }
}
```

**Comment by fredhampton** [comment]
Thanks !!!
