### ISSUE TITLE
Open Discussion Panel

### ISSUE THREAD

**Issue by Yolakalemowa** [xwiki-labs/cryptpad#850]
Hi,

Noob here; and new to your project and to github. 

I was looking for the "discussion" panel where one can talk and ask questions about this interesting project but was told that discussion panels on github are also issues to be requested. So here we are.

Opening such a general discussion session would certainly make it more accessible to more people, so I highly recommend it. Otherwise if there are other channels you recommend your users seek to discuss and ask, please let me know.

Love the project btw. Keep it up.

**Comment by davidbenque** [comment]
Hello and welcome to CryptPad. The reason we haven't enabled discussions here is that it's difficult for our small team (3 people) to keep track of conversations and issues on multiple platforms. The current channels are already a lot, so adding one doesn't seem wise and would likely lead to frustration if we are not able to respond.

The best ways to get in touch are:
- GitHub issues for problems relating to the code and/or possible bugs
- Built in support tickets on cryptpad.fr or the instance you use for issues using CryptPad
- Our [Matrix channel](https://app.element.io/#/room/#cryptpad:matrix.xwiki.com) for all of the above and/or issues relating to administering instances
