### ISSUE TITLE
Cannot delete by right click

### ISSUE THREAD

**Issue by parisni** [xwiki-labs/cryptpad#851]
I cannot delete files / folders by right click > delete. No error in the js console, just nothing happens.

the only way is drag/trash. 

cryptpad `v4.12.0` on various chromium browser.

**Comment by ansuz** [comment]
I suspect this is related to a bug with the right-click menu that was introduced in `4.12.0` and fixed in `4.12.1`. Can you still reproduce the issue after updating?

**Comment by parisni** [comment]
@ansuz yeah good catch. this solves the issue
