### ISSUE TITLE
Czech translation is done now

### ISSUE THREAD

**Issue by matejdivecky** [xwiki-labs/cryptpad#852]
Happy new year, 
we have completed translation of Cryptpad for czech speaking users (https://weblate.cryptpad.fr/projects/cryptpad/app/cs/). We are preparing new instance on cryptpad.cz in our collective nolog.cz and we commit to keep the translation maintained. 

We are already testing the translation on our server, but I would like to know what are the next steps to include the translation in upstream repo. 
I can just create a pull request with the changes, but I guess there is some more integrated way with weblate to pull the changes automatically. 
Can you please give me a hint? 

Thanks a lot!

**Comment by ansuz** [comment]
Happy new year :)

Thanks for the contribution!

I've merged the most recent translations from Weblate into our `soon` branch and applied a small patch to include Czech in the list of languages available inn the platform's language selector. We'll merge this branch to `main` for our upcoming 4.13.0 release.

Can you confirm that [my use of _Čeština_](https://github.com/xwiki-labs/cryptpad/commit/0b3fdb0ef1a7043285294bd45a7af232eff53221#diff-0f97d1314c7a1e3407746f7c254392c4558916795f032e604f4d82b7a60d067eR5) as the localized label for the language is correct?

**Comment by matejdivecky** [comment]
Hi, thanks a lot! 
"Čeština" in `customize.dist/translations/messages.cs.js` is **correct**, looking forward for the 4.13.0 release.
