### ISSUE TITLE
Add password to excel table

### ISSUE THREAD

**Issue by MSGCZ** [xwiki-labs/cryptpad#856]
Hello everyone,

your project is awesome! Many thanks!

But I found the error.

I imported file (.xlsx) and evrerything is correct.

When I try to add password to document...

Step 1
![Screenshot_1](https://user-images.githubusercontent.com/80202249/149506755-3a75f54d-fc38-4615-8e6d-2bc88970908c.png)

Step 2
![Screenshot_2](https://user-images.githubusercontent.com/80202249/149506991-26adde7b-b246-4ef0-bc9d-739f6b9ac546.png)

Step 3
![Screenshot_3](https://user-images.githubusercontent.com/80202249/149507007-58769ae6-8624-40cd-889a-03b46e04c033.png)

**Comment by mthld** [comment]
Hello,

I can't reproduce this issue on my end, it can be related to your setup. Can you tell us more about it? In the meantime I invite you to check out the "Common issues" section of the FAQ in CryptPad official documentation: https://docs.cryptpad.fr/en/FAQ.html#common-issues
