### ISSUE TITLE
Survey : several conditional sections

### ISSUE THREAD

**Issue by PM2000-maker** [xwiki-labs/cryptpad#857]
When you add two sections, it creates a conflict between them.

I've an yunohost instance at: https://pads.lelabo.nohost.me 
I'm trying to create a form with two conditional sections and it's create several bugs

**To Reproduce**
In a form, create a question. Then create a conditional section about this question.
And add a third question and a conditional section about this third question. This is not possible, the conditional questions are shuffled.

**Screenshots**

**Browser (please complete the following information):**
 - Windows 10
 - Firefox
   - 
 - 96.0.1 (64 bits
 - UBlock Origin, facebook container, kepassXC-browser, GPDR Autofill, 
 - firefox "Enhanced Tracking Protection" standard

**Comment by davidbenque** [comment]
Hello, this issue was previously reported and has since been fixed. Please update your instance to the latest version to resolve it on your instance.
