### ISSUE TITLE
URLs ending with a hyphen cause problems in mails

### ISSUE THREAD

**Issue by nielsbohr** [xwiki-labs/cryptpad#86]
URLs like

> .../pad/#/1/edit/1BR ... LTb-

cause problems as the hyphen at the end is not interpreted as part of the URL by mail clients and someone clicking on the link will therefore be directed to a non-existant pad.

**Comment by ansuz** [comment]
If your client is sending emails as html, then the link ought to be formatted by the sending client, not the receiver. I'm fairly sure that trailing hyphens conform to the URL specification, which would make this a bug in their client.

If it's affecting you, though, it's probably affecting others, so we'll see what we can do about it anyway. Thanks for the report.
