### ISSUE TITLE
cryptpad file: how can I delete it and become a registrated user??

### ISSUE THREAD

**Issue by jj030** [xwiki-labs/cryptpad#861]
I got this message on my cryptpad file: "Dieses Dokument muss auf eine neuere Version aktualisiert werden. Für Gäste ist die Bearbeitung deaktiviert, bis das Dokument von einem registrierten Benutzer geöffnet wird." I created it myself (and other people added their contacts on it), we are like 14 people who have the link, but everyone who enters, is only a guest, although I created it myself. How can I delete it? Cheers.

**Comment by ansuz** [comment]
Any registered user account should be able to migrate the document to the newer format. Registration is free and does not require any personal information.

Assuming you are using CryptPad.fr, you can register at https://cryptpad.fr/register/

**Comment by jj030** [comment]
Thanks so much!!

Von meinem iPhone gesendet
