### ISSUE TITLE
Comments and chat on read-only documents

### ISSUE THREAD

**Issue by hermann-san** [xwiki-labs/cryptpad#866]
Sometimes I want to share a spreadsheet with a group of people in read-only mode. However, I still want them to be able to leave comments (anonymous or with username) and chat messages. That doesn't seem to be possible as of now, correct?

It would be great if that would be possible because I often times have this need.
Thanks.

**Comment by mthld** [comment]
Hello,

It's already possible to use the chat, as long as you have a registered account. See the documentation: https://docs.cryptpad.fr/en/user_guide/apps/general.html#users-and-chat

I believe the way comments are handled on documents is only possible when users have write access.
