### ISSUE TITLE
Teams - Document copy appears in root folder after opening the document

### ISSUE THREAD

**Issue by Hetti** [xwiki-labs/cryptpad#871]
**Describe the bug**
When creating documents (at least tested with code pad and rich text pad) in a Team and reopening them, they appear a second time in the root folder of the team.
This was reliable reproducible.

It also happened with other shared documents that already exist, but I couldn't reproduce it reliable!

**Where did it happen?**
This is happening on the C3W Crytpapd instance https://pads.c3w.at

**To Reproduce**
1. Go to your Team
2. Create a pad (tested with rich text pad and code pad)
3. Close the Pad
3. Open the Pad again
4. When pad is loaded the same Pad appears in the root folder of the team. Pads have the same ID.

**Expected behavior**
It shouldn't make another copy of the pad appear in the root folder

**Screenshots**

Single Pad
![grafik](https://user-images.githubusercontent.com/3261408/155022939-4359cf17-d67e-43f2-8470-258d6427ee83.png)

After opening the pad
![grafik](https://user-images.githubusercontent.com/3261408/155023009-3eb26b01-9130-41be-af9a-12161a202afd.png)

**Browser (please complete the following information):**
 - OS: Arch Linux
 - Browser: Firefox 
 - Version: 97.0.1 (64-Bit)

This bug could also be reproduced with Safari on MacOS too!

**Comment by ansuz** [comment]
We just merged a fix for this to our `soon` branch which will be included in the next release.
