### ISSUE TITLE
Sheets: Column resizing on touch devices

### ISSUE THREAD

**Issue by smaktacular** [xwiki-labs/cryptpad#879]
Hi,

how would I perform a resize of columns on a touch device where there is no pointer? Is there a button to initiate the resize?

Regards

**Comment by mthld** [comment]
Duplicate #928

**Comment by Akash26355** [comment]
GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼

**Comment by Akash26355** [comment]
GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼

**Comment by Akash26355** [comment]
GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼

**Comment by Akash26355** [comment]
GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼

**Comment by Akash26355** [comment]
GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼

**Comment by Akash26355** [comment]
GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼

**Comment by Akash26355** [comment]
GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼GOLD =Loan %customer= care℅ helpline℅ number 📞❻❷❾❺❶❻❶❸❽❼
