### ISSUE TITLE
SyntaxError when Super Agent addon is active

### ISSUE THREAD

**Issue by glocalglocal** [xwiki-labs/cryptpad#883]
When Super Agent is active on Firefox or Brave and I visit a Cryptpad rich text document I get the following error on the Cryptpad page every time: 

`SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

On a few occasions I got: `Script error.`

Whitelisting cryptpad or disabling the addon from within its settings doesn't make a difference. If I disable the addon from the browser settings, the website works fine. This is on a Win11 machine. Strangely, this doesn't happen on a Win10 machine with identical browsers/addons setup.

**Comment by sant-sh** [comment]
I am too facing this issue. If I remove super agent then Cryptpad works great.

I have tried Librewolf as well as Firefox on Macbook 

below are the console error 

```
Uncaught SyntaxError: JSON.parse: unexpected character at line 1 column 2 of the JSON data
    onReply https://example.com/common/sframe-boot.js?ver=1.7:27
    afterLoaded https://example.com/common/sframe-boot.js?ver=1.7:67
    load0 https://example.com/common/sframe-boot.js?ver=1.7:73
    <anonymous> https://example.com/common/sframe-boot.js?ver=1.7:79
    <anonymous> https://example.com/common/sframe-boot.js?ver=1.7:81
```

**Comment by mthld** [comment]
Hello,

Thanks for your reports, however we don't support specific web browser extensions. I invite you to check out our documentation to know more about this: https://docs.cryptpad.fr/en/FAQ.html#common-issues
