### ISSUE TITLE
nginx issues 

### ISSUE THREAD

**Issue by fredhampton** [xwiki-labs/cryptpad#89]
We have crytpad running with proxypass using nginx
When we try to load a pad the service hangs on the loading screen

nginx proxy pass settings are like this 

## Set the location routing.
location ~ / {

	proxy_set_header Host $host;
	proxy_set_header X-Real-IP $remote_addr;

	##Use the domain.tld here.
	proxy_pass http://150.82.45.137:3500;
}

**Comment by ansuz** [comment]
I'll see about writing up a guide with an example nginx config soon. In the meantime, it would help to have any errors from your browser console.

**Comment by ansuz** [comment]
We've recently split our production server across two machines, one to serve static assets, and another for the websocket and database. This is the relevant section from the nginx config which is proxying the websocket.

```
        location / {
                proxy_pass http://localhost:3000;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

                add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
                # WebSocket support (nginx 1.4)
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection upgrade;
        }
```

Note that the proxy pass directive points to a local address. I hope that helps.

**Comment by fredhampton** [comment]
Thanks so much ....It worked !!!!!!

**Comment by s3rvant** [comment]
I was having this issue as well and the additional lines worked for me. Here's my working nginx config:

```
server {
  server_name cryptpad.example.com;

  listen 443 ssl;
  # cerbot ssl lines here

  # Reverse proxy
  ssl on;
  ssl_session_cache builtin:1000 shared:SSL:10m;
  access_log /var/log/nginx/access.log;

  location / {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_pass http://192.168.0.42:3000;
    proxy_read_timeout 90;
    proxy_redirect http://192.168.0.42:3000 https://$host;

    # Additions for websockets
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection upgrade;
  }
}

server {
  if ($host = cryptpad.example.com) {
    return 301 https://$host$request_uri;
  }

  server_name cryptpad.example.com;
  listen 80;
  return 404;
}
```
Note that my reverse proxy is a separate machine from what I'm using to host CryptPad
