### ISSUE TITLE
Matrix Widget?

### ISSUE THREAD

**Issue by ptman** [xwiki-labs/cryptpad#890]
Matrix does have an EtherPad widget, but would it be possible to have a cryptpad widget as cryptpad has so many more useful features?

**Comment by cyb3rm00n** [comment]
It works for me with pads, but **when I try to embed a sheet it shows a black screen.**

### Screenshots

How I see the custom widget in Matrix:
![imagen](https://user-images.githubusercontent.com/50640867/164233763-9acf5e50-f9f9-4b84-ab8c-61f6b865474d.png)
How I get the link to embed the sheet (sorry it is partially in spanish), basically I just check the embeded option:
![imagen](https://user-images.githubusercontent.com/50640867/164233546-bb45b117-4942-4817-93a2-712d16f74a0f.png)
