### ISSUE TITLE
iFrame refused

### ISSUE THREAD

**Issue by Shuggaloaf** [xwiki-labs/cryptpad#897]
**Describe the bug**
When using the embed link the page does not load and I get the error below (this worked up until sometime within the last month)
`Refused to frame 'https://cryptpad.fr/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self' https: vector:".`

**Where did it happen?**
CryptPad.fr 

**To Reproduce**
Copy the iframe embed link from a document.
Add iframe to other website/app/etc.
Try to load.

**Expected behavior**
Load embedded iframe as 

**Browser (please complete the following information):**
 - OS: Win10
 - Browser: Chrome/Chromium
 - Extensions installed: UBlock Origin (disabled)

**Comment by Shuggaloaf** [comment]
I believe this warning may be related: `crbug/1173575, non-JS module files deprecated.`

**Comment by ansuz** [comment]
Our 4.14.0 update introduced new security measures. It's expected that CryptPad will refuse to load if the embedding page was not loaded via HTTPS. If you are still having issues over HTTPS and you can provide further details so we can reproduce we'll investigate further.
