### ISSUE TITLE
Restore functionality does not seem to work?

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [xwiki-labs/cryptpad#914]
**Describe the bug**
I accidentally screwed up one of the excel sheets and I need to restore the older version of it which does not seem to work

**Where did it happen?**
CryptPad.fr

**To Reproduce**
Steps to reproduce the behavior: (I have not investigated much, this is just what i did)
1. Open sheet
2. Sort it
3. Restore it
4. Opens already sorted sheet

**Expected behavior**
Document gets restored

**Browser (please complete the following information):**
Brave browser but i doubt that it is frontend related

**Comment by mthld** [comment]
Hello,

The history and restoring functionalities works as intended here. As CryptPad runs mostly on your browser it can pretty much be a Brave issue. See our official documentation on this matter: https://docs.cryptpad.fr/en/FAQ.html#common-issues

Please note that we don't test CryptPad against Brave. Can you try with another web browser? In a fresh private window, with all extensions disabled?
