### ISSUE TITLE
fatal error has occurred

### ISSUE THREAD

**Issue by iratymch** [xwiki-labs/cryptpad#915]
When I worked on the sheet, a fatal error occurred. Message: "A fatal error has occurred. Click OK to reboot". Problem is that after a reboot the data may not be saved.

**Comment by mthld** [comment]
Hello,

Thanks for your report, however this issue can be caused by a wide range of parameters. It would have been nice if you could have used the Bug Report issue template.

If you want help we need specific informations to help you. 🫤
