### ISSUE TITLE
Checkup page complains about Content-Security-Policy settings although they seem all right

### ISSUE THREAD

**Issue by jrselzer** [xwiki-labs/cryptpad#916]
Following the instructions at https://docs.cryptpad.fr/fr/admin_guide/installation.html#admin-cryptpad-config I copied the default Nginx configuration into my setup and adapted it to my setup. Cryptpad starts up fine and interacts well with Nginx, but I get an error when checking my configuration with https://cryptpad.mydomain/checkup/

```
This instance is running CryptPad v4.14.1.

Page content was served by "nginx/1.18.0".

You appear to be using a firefox/gecko browser on UNIX to view this page.

34 / 41 tests passed.

Details found below

https://cryptpad.mydomain/sheet/inner.html was served with incorrect Content-Security-Policy headers.

A value of "'self' blob: https://cryptpad.mydomain https://sandbox.mydomain wss://cryptpad.mydomain" was expected for the connect-src directive.
```
In the details section it says:

```
{
 "default-src": "'none'",
 "child-src": "https://cryptpad.mydomain",
 "worker-src": "'self'",
 "media-src": "blob:",
 "style-src": "'unsafe-inline' 'self' https://cryptpad.mydomain",
 "script-src": "'self' 'unsafe-eval' 'unsafe-inline' resource: https://cryptpad.mydomain",
 "connect-src": "'self' https://cryptpad.mydomain blob: wss://api.cryptpad.mydoman https://sandbox.mydomain",
 "font-src": "'self' data: https://cryptpad.mydomain",
 "img-src": "'self' data: blob: https://cryptpad.mydomain",
 "frame-src": "'self' https://sandbox.mydomain blob:",
 "frame-ancestors": "'self' https://cryptpad.mydomain"
}
```
I assume the related Nginx configuration entry is in line  102

`set $connectSrc "'self' https://${main_domain} blob: wss://${api_domain} https://${sandbox_domain}";`

Being an Nginx newbie I'm not sure, but it looks to me like this line looks very much like expected by the self-test. The order of the allowed domains is not the same, but this should not be an issue. Is it possible that the checkup tool is giving a false alert here? 

For testing purposes I changed the line to

`set $connectSrc "'self' blob: https://${api_domain} https://${sandbox_domain} wss://${api_domain}";`

but I'm still getting the same message.

**Comment by meaz** [comment]
I do have a similar problem, but with `frame-ancestors`
```
https://cryptpad.disroot.org/sheet/inner.html was served with incorrect Content-Security-Policy headers.

A value of "'self' https: vector:" was expected for the frame-ancestors directive. This rule determines which sites can embed content from this instance in an iframe.
```

but the test also tells me:
```
{
 "default-src": "'none'",
 "child-src": "https://server.org",
 "worker-src": "'self'",
 "media-src": "blob:",
 "style-src": "'unsafe-inline' 'self' https://server.org",
 "script-src": "'self' 'unsafe-eval' 'unsafe-inline' resource: https://server.org",
 "connect-src": "'self' https://cryptpad.disroot.org blob: wss://server.org https://sandbox.server.org",
 "font-src": "'self' data: https://server.org",
 "img-src": "'self' data: blob: https://server.org",
 "frame-src": "'self' https://sandbox.server.org blob:",
 "frame-ancestors": "'self' https://server.org"
}
```

**Comment by mthld** [comment]
Hello folks,

As these issues are clearly not a bug, but a configuration issue on our end I'll politely ask you to move this over [the forum](https://forum.cryptpad.org/t/configuration). Over here you'll find community support and insights from the CryptPad team. You can signup using a traditional email & password combination or use external authentication with GitHub or Twitter.

We are aiming to keep issues on GitHub tidy so we can better concentrate at fixing bugs.

Hope you'll understand and see you over the forum!

**Comment by mthld** [comment]
https://forum.cryptpad.org/d/30-checkup-page-complains-about-content-security-policy-settings/
