### ISSUE TITLE
Initial Mobile UI is unusable and confusing for new users

### ISSUE THREAD

**Issue by jahway603** [xwiki-labs/cryptpad#917]
**Describe the bug**
Initial Mobile UI is unusable and confusing

**Where did it happen?**
Did the issue occur on CryptPad.fr or an instance hosted by a third-party? On CryptPad.fr

**To Reproduce**
1. Go to any spreadsheet located on CryptPad.fr.
1. Enter password, since it's password protected. While doing so, this enlarges the password box and then user can hit submit.
1. Now the screen is zoomed in and a new user does not know what to do at this point. This is where new user complains to me as it's not clear how they enter information into the CryptPad.fr spreadsheet I've shared with them.
1. Since I'm not a new user, I zoom out with my fingers on the screen.
1. At this point, most of the spreadsheet is covered with another "overlay" which contains "Fill", "Borders Style", etc.
1. I then click on the first button all the way on the right hand-side of the screen to make the "overlay" disappear.
1. Now the spreadsheet is visible and a user would know be able to edit it.

**Expected behavior**
User should be presented with a Mobile UI that they can "easily" navigate in and around without confusion. I use this on a computer in a web browser, so was not aware of other user's issues they told me about until I tried it on my own phone to better understand what troubles they were experiencing.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: Android 12, but users experiencing issues on their iPhones and other Android versions
 - Browser: Bromite (Chromium fork), but other users have a variety of browsers that experienced the same issue
 - Version: 102.0.5005.92

**Additional context**
I would not have discovered this bug if most of the users editting my CryptPad.fr shared spreadsheet were using computers instead of phones.

**Comment by mthld** [comment]
Duplicate #928
