### ISSUE TITLE
Kanban: Editing is not allowed when the title of the task box is blank

### ISSUE THREAD

**Issue by emreavcia** [xwiki-labs/cryptpad#921]
**Describe the bug**
The title is not possible to be renamed through the main view (you can only rename it by clicking the edit button on the item)

**Where did it happen?**
The issue occurs on the Kanban on CryptPad.fr.  

**To Reproduce**
1. Go to Kanban
2. Click on the plus button in "to Do", "in Progress", or "Done sections"
3. Create a new item with a title.
4. Delete the title.
5. Attempt to rename the title.

**Expected behavior**
 To rename it without clicking the edit button.

**Screenshots**
![image](https://user-images.githubusercontent.com/84312074/173055589-22b5ea15-cfa6-4fe7-8ed1-a6526277a913.png)

**Browser (please complete the following information):**
 - windows 
 - Google Chrome [version 102.0.5005.63 (Official Build) (64-bit)]
 (Collaborators: raised by @canahm in the context of a testing lecture delivered by @1337tester)

**Comment by 1337tester** [comment]
Additional Info with recording
https://app.birdeatsbug.com/sessions/94vgcB7Q5p21PZ6E_ru7SPUvjp51R50W-nYUi09tlgGp?systemPane=active
