### ISSUE TITLE
After upgrading to version 5, still states 4.14.0

### ISSUE THREAD

**Issue by mailanetworks** [xwiki-labs/cryptpad#922]
**Describe the bug**
I upgraded to the latest version using the instructions on Github. But the about pages states that I'm still using 4.14.0

**Where did it happen?**
Private instance running the development version

**To Reproduce**
Not applicable

**Expected behavior**
Expected to flush the cache and restart services, to see new version.

**Screenshots**
Not applicable

**Browser (please complete the following information):**
Multiple OS and browsers

**Smartphone (please complete the following information):**
Not applicable

**Additional context**
Used the guide in https://docs.cryptpad.fr/en/admin_guide/maintenance.html

**Comment by ansuz** [comment]
It is very likely you are serving customized assets from `/customize/` rather than the default updated assets from `/customize.dist/`.

An outdated `./customize/pages.js` would explain this.
