### ISSUE TITLE
Shared calendar in Teams

### ISSUE THREAD

**Issue by thebigalwisi** [xwiki-labs/cryptpad#923]
Hello folks,
a shared calendar for a team would be great! Is something like this being discussed?

**Comment by mthld** [comment]
Hi,

Team calendars are already implemented, can you check our official documentation and try? https://docs.cryptpad.fr/en/user_guide/collaboration.html#calendar

**Comment by mthld** [comment]
@thebigalwisi did you had any chance to try it?

**Comment by mthld** [comment]
Well, closing!
