### ISSUE TITLE
Posting into multiple cells at the same time not possible in spreadsheets on some devices

### ISSUE THREAD

**Issue by aneverhopefulhelper** [xwiki-labs/cryptpad#927]
**Describe the bug**
From most sources (plaintext and websites), it used to be possible to just copy multiple lines and paste them at once into a sheet so that they filled multiple rows. Now, in most cases it's only possible to paste directly into one cell, making it harder to add larger groups of data at once - you have to copy and paste each into each cell, which was already possible before. This behaviour has been noticed from multiple different devices.

**Where did it happen?**
https://cryptpad.fr

**To Reproduce**
1. Copy or cut some text
2. Try to paste it into multiple spreadsheet cells/rows at the same time
3. Notice it only pastes into one cell

**Expected behavior**
It is expected to be able to paste into multiple cells/rows at the same time from multiple copied or cut text.

**Screenshots**

**Browser (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome and Edge
 - Version: Chrome 103.0.5060.66 and Edge 103.0.1264.37
 - Extensions: None.

**Additional context**

**Comment by DillFrescott** [comment]
None of these issues are being addressed it seems. Perhaps its time to start looking for an alternative. It won't even let me paste into a spreadsheet at all on version 5...

**Comment by mthld** [comment]
Hello,

Thanks for your report, I'm not sure OnlyOffice support this in the first time. However it would clearly be an issue from their side as we simply integrate their application into CryptPad.

I invite you to take this issue to their repository: https://github.com/ONLYOFFICE/DocumentServer, if they decide to implement this feature, release a new version we will surely update CryptPad.
