### ISSUE TITLE
mobile experience is unusable

### ISSUE THREAD

**Issue by woeisme** [xwiki-labs/cryptpad#928]
**Describe the bug**
excel documents cannot be viewed / interacted with on mobile platforms

**Where did it happen?**
on main site

**To Reproduce**
1. create excel document on computer
2. attempt to access document on mobile browser
3. no pinch zoom or other method to view / edit document / remove blocking UI 

**Expected behavior**
the document to be usable on mobile

**Screenshots**

**Browser (please complete the following information):**
 - Browser [e.g. firefox, tor browser, chrome, safari, brave, edge, ???]
   - variations [e.g. Firefox nightly, Firefox ESR, Chromium, Ungoogled chrome]
 - Extensions installed (UBlock Origin, Passbolt, LibreJS]
 - Browser tweaks [e.g. firefox "Enhanced Tracking Protection" strict/custom mode, tor browser "safer" security level, chrome incognito mode]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mthld** [comment]
Hello,

Thanks for your report, as our Spreadsheet app is a direct OnlyOffice integration, I invite you to take this issue to their bug report directly: https://github.com/ONLYOFFICE/DocumentServer

As of today there is sadly little we can do about this issue ourselves.
