### ISSUE TITLE
Link sharing with view only access not available as an option on Cryptpad

### ISSUE THREAD

**Issue by ashutoshsaboo** [xwiki-labs/cryptpad#930]
**Describe the bug**
I was referring to the docs here - https://docs.cryptpad.fr/en/user_guide/share_and_access.html#sharing-a-link - where it shows the option to share links to uploaded files on Cryptpad for view only access/edit/or view once and self-destruct modes. I'm registered on the official flagship instance - https://cryptpad.fr/drive - where I can't see these options anymore on Cryptpad. It seems like the file is by default shared in view only mode, but I'm not sure as there's no explicit messaging on the UI - as the explicit options as shown in the docs are not visible. 

This is a really important feature of Cryptpad to share links with specific access modes - view/edit/self-destruct view modes - analogous to Google docs. Needless to mention, but i'm sure there are abundant privacy related use-cases where setting these link sharing toggle access modes are very important before sharing with the intended recipients. Can this be please fixed? 

**Where did it happen?**

Did the issue occur on CryptPad.fr or an instance hosted by a third-party?  
If on another instance, please provide its full URL.

Official flagship cryptpad instance - https://cryptpad.fr/drive

**To Reproduce**
1. Go to https://cryptpad.fr/drive
2. Upload a PDF/excel/word file from desktop. Optionally either assign it as a password or not. Mark yourself as the owner and ensure file is stored in your cryptpad.
3. Right click on uploaded file -> click on Share -> Go to Link tab. 
4. There's no option to change link sharing modes as shown in the docs above.

**Expected behavior**
Separate Toggles for link sharing should have been visible as shown in the docs. https://docs.cryptpad.fr/en/user_guide/share_and_access.html#sharing-a-link . 

**Screenshots**
I can't share the entire link tab screenshot as it contains the actual shared link which is private. But here's the screenshot of the bottom part of the link tab, showing that the default access mode is not self destruct link mode: 

![Screenshot 2022-07-19 at 11 26 09 AM](https://user-images.githubusercontent.com/9900945/179676794-e6b1ec5d-14ff-4efa-bac9-247572f8e1e8.png)

**Browser (please complete the following information):**
 - OS: MacOS Big Sur 11.6.5
 - Browser: Brave browser [Version 1.38.109 Chromium: 101.0.4951.41 (Official Build) (x86_64)](https://brave.com/latest/)
 - Version: Latest web version hosted on https://cryptpad.fr/drive/
 - Extensions installed (UBlock Origin, Passbolt, LibreJS]: UBlock origin and standard brave browser protection
 - Browser tweaks: Standard Brave browser protection, which shouldn't be causing this toggle to disappear ideally. 

**Smartphone (please complete the following information):** 
Not tested on mobile

**Additional context**

**Comment by mthld** [comment]
Hi,

You can see below it's working as intended on our end:
![Screenshot 2022-08-05 at 11 26 46](https://user-images.githubusercontent.com/41020854/183047689-3f14da77-70e5-478d-8fc3-a65f899cf1bf.jpg)

Also I invite you to check out the "Common Issues" section from our documentation: https://docs.cryptpad.fr/en/FAQ.html#common-issues, please note that Brave support isn't tested.

Can you please check with another browser?

**Comment by theova** [comment]
I stumbled over this issue, so:
Uploaded files are considered to be static and can therefore not be changed.
Consequently, there is no `Edit` link that can be generated.

The share link that you generate from an uploaded file is therefore read-only.

**Comment by MrYnLA-02** [comment]
> I stumbled over this issue, so: Uploaded files are considered to be static and can therefore not be changed. Consequently, there is no `Edit` link that can be generated.
> 
> The share link that you generate from an uploaded file is therefore read-only.

This is documented for FILES (such as .pdf, etc?) However, if user is sharing a FOLDER, then the "expected (as stated in CryptPad's own user guide/info)" Access options are in fact present and available.  This sure seems like a silly BUG!
