### ISSUE TITLE
Missing rows in shared spreadsheet

### ISSUE THREAD

**Issue by CodeResearcher** [xwiki-labs/cryptpad#940]
**Describe the bug**
When sharing a spreedsheat (~2500 rows, 11 columns) by link, only about 300 rows are shown when the shared link is used

**Where did it happen?**
cryptpad.ffmuc.net

**To Reproduce**
1. create new password protected spreadsheet
2. paste content with about 2500 rows into the spreadsheet
3. share spreadsheet by link
4. open shared link in different browser session
5. only the first 300 rows are shown

**Expected behavior**
All rows from the document should be visible by shared link

**Browser (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome (104.0.5112.81), Firefox (103.0.1)
 - Extensions installed: none
 - Browser tweaks: none

**Comment by mthld** [comment]
Hello,

Thanks for reaching out about this issue, however I see that the instance you are using is outdated: `CryptPad v4.14.1`.
Can you try to reproduce this bug on https://cryptpad.fr, which is running the latest version?

**Comment by mthld** [comment]
We've had another issue, see #950 which looks the same, can you confirm it?

If so I'll be closing this issue on favor of the other one. 😊

**Comment by CodeResearcher** [comment]
Yes, seems to be the same behavior.

**Comment by mthld** [comment]
Thanks for the confirmation, I'll be closing this issue in favor of the other one.
