### ISSUE TITLE
Cloud sync

### ISSUE THREAD

**Issue by Raj2032** [xwiki-labs/cryptpad#953]
### Summary

Since we have mega cloud, Google Drive, OneDrive etc, I would be nice to have a cryptpad cloud syncing software as well where we can sync our stuff to the cryptpad cloud.

### Motivation

Instead of having to manually upload the files, I can just put all the files in the cloud folder on the computer and let it automatically sync.

**Comment by Raj2032** [comment]
@mthld Yes that is correct :)

**Comment by mthld** [comment]
It's a #939 duplicate, I'll be closing this issue in favor of the other one!
