### ISSUE TITLE
Navigation smartphone

### ISSUE THREAD

**Issue by Tyu44** [xwiki-labs/cryptpad#954]
### Summary

Bonjour, quand vous ouvrez un classeur avec cryptpad sur un smartphone, impossible de naviguer dessus avec les doigts. Il faut naviguer avec les bouton de défilement classiques qui sont très petits et pas pratique.
Est-ce possible de songer à une évolution dans ce domaine ?
Je vous remercie.

### Motivation

Ce serait très utiles pour tous les utilisateurs de smatphone.

**Comment by mthld** [comment]
Bonjour,

Merci pour votre intérêt envers CryptPad.

Les applications Spreadsheet, Document et Presentation sont basées sur [OnlyOffice](https://onlyoffice.com) et à ce jour nous dépendons de leur projet pour les fonctionnalités de ces trois applications. Nous avons conscience que l'expérience mobile n'est pas optimale, en cas d'améliorations publiées par OnlyOffice nous ferons bien sûr notre possible pour intégrer ces dernières dans CryptPad. D'ici là malheureusement il n'y a rien que nous puissions faire.
