### ISSUE TITLE
Nested Conditional Sections In Forms

### ISSUE THREAD

**Issue by RichardJActon** [xwiki-labs/cryptpad#956]
### Contribution guidelines

- [X] I've read the [code of conduct](https://github.com/xwiki-labs/cryptpad/blob/main/CODE_OF_CONDUCT.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I've read the [Common issues documentation section](https://docs.cryptpad.fr/en/FAQ.html#common-issues) and I also checked [previous issues](https://github.com/xwiki-labs/cryptpad/issues).

### Description

In the form creation UI clicking the add button within an existing conditional section presents the user with the option to add another conditional section. Clicking on conditional section within and existing conditional section however does not add a nested conditional section it appears to do nothing.

It would be nice to see support for nesting conditional sections however if this is complicated to implement it would be good to have the icon to add a conditional section hidden when within a conditional section until/if support for nesting is implemented.

### Steps to reproduce

1. Create a question suitable to be conditioned on
2. create a conditional section
3. create a question suitable to be conditioned on within the previous conditional section
4. attempt to add a conditional section within the previous conditional section

### Expected behavior

1. This creates a nested conditional section or 2. the icon to create conditional sections is not shown within conditional sections.

### System information

| Question | Answer |
| --- | --- |
| Operating system and version | Ubuntu 20.04 |
| Web browser and version| Brave [Version 1.42.97 Chromium: 104.0.5112.102 (Official Build) (64-bit)](https://brave.com/latest/) |
| Extensions installed | NA |
| Browser tweaks | NA |
| CryptPad version | v5.0.0 (cryptpad.fr at time of submission) |

**Comment by mthld** [comment]
https://user-images.githubusercontent.com/41020854/186415268-3e5b52b2-3209-42a3-95bb-1a221cdaadb1.mov
