### ISSUE TITLE
Form/Poll/Time wrong/different div height if axes are swapped 

### ISSUE THREAD

**Issue by devNan0** [xwiki-labs/cryptpad#975]
### Contribution guidelines

- [X] I've read the [code of conduct](https://github.com/xwiki-labs/cryptpad/blob/main/CODE_OF_CONDUCT.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I've read the [Common issues documentation section](https://docs.cryptpad.org/en/FAQ.html#common-issues) and I also checked [previous issues](https://github.com/xwiki-labs/cryptpad/issues).

### Description

If you swap axes the div height is to small (See [example poll](https://cryptpad.fr/form/#/2/form/view/qjmR3qND8D5NJhxTiB67mvAv4QgHXJ5RpvkoRBvmb6g/))
This results in an unaligned table/gird which makes it hard to match answers to the right/corresponding date/time
AFAIK this is only the case if the poll type is set to `Time`.

`.cp-poll-time-day` is 40px
The rest is 35px

### Steps to reproduce

1. Open my example poll https://cryptpad.fr/form/#/2/form/view/qjmR3qND8D5NJhxTiB67mvAv4QgHXJ5RpvkoRBvmb6g/
2. Click on `swap axes`

### Expected behavior

Options and answers to align in a table/grid

### System information

| Question | Answer |
| --- | --- |
| Operating system and version | Win 10 & 11, Debian 10 & 11, Android 11  |
| Web browser and version | Microsoft Edge 106.0.1370.47, Firefox 105.0.3 & 102.3.0esr & 105.2.0, Chromium 106.0.5249.119 |
| Extensions installed | None/Disabled |
| Browser tweaks | None |
| CryptPad version | v5.1.0 (https://cryptpad.fr/) |

**Comment by mthld** [comment]
![Screenshot 2022-10-17 at 11 22 29](https://user-images.githubusercontent.com/41020854/196140772-58bcc8c7-2583-46d7-b9ef-df93e0f48537.png)

Thanks @davidbenque for fixing this and @devNan0 for reporting! 🎉
