### ISSUE TITLE
Deletion of Teams Drive

### ISSUE THREAD

**Issue by aconite33** [xwiki-labs/cryptpad#977]
### Contribution guidelines

- [X] I've read the [code of conduct](https://github.com/xwiki-labs/cryptpad/blob/main/CODE_OF_CONDUCT.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I've read the [Common issues documentation section](https://docs.cryptpad.org/en/FAQ.html#common-issues) and I also checked [previous issues](https://github.com/xwiki-labs/cryptpad/issues).

### Description

When running a local instance of Cryptpad, unable to delete a Teams Drive after the creation.

On clicking the "DELETE" button, no request is sent to the server side (Attached to the Docker window looking for any new requests to the Nginx server).

I have tried leaving the window open after clicking Delete for 2+ Hours and no resolution.

I am running a custom size of my teams drive (1 GB).

### Steps to reproduce

1. Create a Teams Drive
2. Create documents in Teams Drive
3. Browse to Team
4. Click on Administration as the Owner of the Teams Drive
5. Click "DELETE"
6. Validate that the Teams Drive never deletes and only feedback is constant spinning wheel

### Expected behavior

Deleting the Teams Drive as the Owner of the Team should delete the Teams Drive

### System information

| Question | Answer |
| --- | --- |
| Operating system and version | Ubuntu 20.04  |
| Web browser and version| Latest Chrome |
| Extensions installed | None |
| Browser tweaks | None |
| CryptPad version | Latest Docker - https://github.com/xwiki-labs/cryptpad-docker |

**Comment by mthld** [comment]
Hello,

Thanks for your report. However, we aren't supporting the Docker install so we can't help you on this matter.
I encourage you to take this to [the community forum](https://forum.cryptpad.org).

Please also note that [the repository you linked](https://github.com/xwiki-labs/cryptpad-docker) has it's own issue tracker.

For now I'll be closing this issue. 😊
